### ISSUE TITLE
Errors when I open in VS

### ISSUE THREAD

**Issue by kielec** [UnamSanctam/SilentXMRMiner#10]
Could not find type  'SilentXMRMiner.MephTheme'. Please make sure that the assembly that contains  this type is referenced. If this type is a part of your development project,  make sure that the project has been successfully built using settings for your  current platform or Any CPU. 

Could not find type  'SilentXMRMiner.MephComboBox'. Please make sure that the assembly that contains  this type is referenced. If this type is a part of your development project,  make sure that the project has been successfully built using settings for your  current platform or Any CPU. 

etc...

**Comment by UnamSanctam** [comment]
Build the project once and then reopen the Form1.
