### ISSUE TITLE
Persisting issue

### ISSUE THREAD

**Issue by oneinam1llion** [UnamSanctam/SilentXMRMiner#102]
![image](https://user-images.githubusercontent.com/80195847/111051203-4ddb4380-841f-11eb-9bcc-b552ab90989e.png)

![image](https://user-images.githubusercontent.com/80195847/111051214-66e3f480-841f-11eb-9fa5-ab4d2e06f33f.png)

I've got downloads but no clients, I feel like I am doing something wrong. Does the stub have to be executed by a user click instead of a batch script? It's set to elevate permissions so I don't have any issues adding powershell and regedit into the .bat file & executes by itself. Is it because I have it set to not wait for 30 seconds but to start instantly? And then the program that started the executable closes? I'm stumped, really am. I've been making stubs for two weeks now and releasing them and have gotten next to no results.

**Comment by UnamSanctam** [comment]
Try running it without elevated permissions, it installs into the user profile to avoid permission issues so if it installs into the administrator profile due to the elevation but the user usually uses another profile then it won't start with the current user.

**Comment by oneinam1llion** [comment]
The thing is, it runs under elevated permissions and works when I test it, injecting itself into an invisible service (svchost).
I have stealth off because I made a watchdog that starts with the computer and pings a website 3 times and then kills taskmgr.exe
So I don't really have to worry about it being terminated, it simply only shows up half of the time. There is no way I can run it without elevated permissions because there are so many layers to my installer, by the time it gets to the executable payload it's gone through 3 different executables all with elevated permissions setting the next one elevated too, I would have to completely remake the batch executable, remove my windows host lines, netsh bypasses and another admin requiring feature I added and then test it, any other options? I wish you could compile it for me? Maybe it's the machines I am making the stub on, they're all fresh VM's, each time I need a new stub I make a new VM and then kill it when I am done, they're all running on 2015 windows 10. But each time I install .net 4.6.1 on them so I should have next to no issues??!?!

**Comment by UnamSanctam** [comment]
Yeah there shouldn't really be any issues which is the weird part. And even if there was a problem with the elevation it should at least run until the next restart but it seems like it doesn't for you.

So exactly everything works on your local test VM's but not when distributing? I could technically build it for you if you want to see if that works.

**Comment by oneinam1llion** [comment]
Yes, do you have telegram? I am about to head off to my 8 hour shift so I won't be able to recomp everything until tonight.
Everything works flawlessly on the test VM and on other local machines on my network. When distributed only half seem to show up and I am sure there is a very good explanation for this cause.

**Comment by UnamSanctam** [comment]
Well I don't have telegram, is there any messaging service you use? Preferably not requiring a phone number. I will test things out on my computer to see if I can get it to not work.

**Comment by UnamSanctam** [comment]
Well seems like there aren't even any issues with elevated permissions like I though there might be. Might be some other hidden issues, I'll try to run it on other computers to see if something stops working.

**Comment by oneinam1llion** [comment]
Just got home, no new clients. Would you like to get in contact via a private IRC room?
I was hoping the stub would work but it doesn't seem so.
![image](https://user-images.githubusercontent.com/80195847/111059743-f7452800-8465-11eb-83e9-b273598abb3a.png)

3 new downloads & no new clients. This could be because they never downloaded it, I've figured out mediafire counts link clicks as "downloads". Since there are so many possible issues here hindering my stub I am unsure.

**Comment by UnamSanctam** [comment]
Well, I can use whichever contact method that doesn't require a phone. Usually people contact me on Hackforums via the convo fuunction.

**Comment by oneinam1llion** [comment]
I cannot use hackforums unless I use a socks5 proxy I do not have any on hand right now, I would prefer discord or wickr.

**Comment by UnamSanctam** [comment]
I made a Discord, you can contact me on Unam Sanctam#3135.

**Comment by oneinam1llion** [comment]
![image](https://user-images.githubusercontent.com/80195847/111112857-4313d200-8537-11eb-9059-ddedbdba9acf.png)
Everything is as you left it, decided to test it on a real machine only using 3% but clearly working.

**Comment by oneinam1llion** [comment]
Do you know why it is only using 3% on a duo?

**Comment by UnamSanctam** [comment]
Can you take a screenshot of the command line options by hovering the process? Might also want to blur out the things like wallet address.

**Comment by oneinam1llion** [comment]
Everything is correct, not to mention still haven't gotten any clients since the last stub we made.
Could be the batch script?

**Comment by UnamSanctam** [comment]
Probably then yes.

**Comment by UnamSanctam** [comment]
It should be using CPU though if everything is correct. How many cores does that machine have?

**Comment by oneinam1llion** [comment]
Unam, I've contacted you under : 
![image](https://user-images.githubusercontent.com/80195847/111264316-a5370a80-85fd-11eb-9e18-3c19cb3b9ef5.png)

Get back as soon as possible, I have to make a new discord every so often most services don't like my public IP.
