### ISSUE TITLE
conhost

### ISSUE THREAD

**Issue by shainodev** [UnamSanctam/SilentXMRMiner#103]
why is it removed from the injection tab

**Comment by UnamSanctam** [comment]
Windows has now added protections against injecting into certain System processes without administrator access.

**Comment by shainodev** [comment]
also i use moneroocean and it seems to not work cuz i open it and it doesnt do anything

**Comment by UnamSanctam** [comment]
And the settings are correct?

**Comment by shainodev** [comment]
nvm it worked thanks for the help tho
