### ISSUE TITLE
How to use the .bat file to delete the 0.9 version of the miner

### ISSUE THREAD

**Issue by zoubaba1997** [UnamSanctam/SilentXMRMiner#105]
How to use the .bat file to delete the 0.9 version of the miner, I used del / a: h C:\Users\%USERNAME%\AppData\Local\Temp\Chrome.exe but it was unsuccessful, I now need to delete the old miner in the victim Add new miner

**Comment by UnamSanctam** [comment]
Does `del /a:h %TEMP%\Chrome.exe` work?

**Comment by zoubaba1997** [comment]
No job shows wrong instructions, and the 0.9 version of the miner is still running
![Uploading 无标题.png…]()

**Comment by zoubaba1997** [comment]
No job shows wrong instructions, and the 0.9 version of the miner is still running
![Uploading 无标题.png…]()

**Comment by zoubaba1997** [comment]
![无标题](https://user-images.githubusercontent.com/73113267/111147060-11e1e300-85c5-11eb-85c6-d1631e75f897.png)
This is my command. The miner's name is Chrome.exe

**Comment by UnamSanctam** [comment]
Copy paste this command `del /a:h %TEMP%\Chrome.exe` it is more compatible if the user does not run their OS on their C: drive.

Your command doesn't work because you you have spaces between /a:h

**Comment by zoubaba1997** [comment]
Thanks, there is still a question, does the 1.01 version cancel the hidden installation?

**Comment by UnamSanctam** [comment]
Version 1.0 and later removes the "Hide File" options since they cause the program to be un-overwritable, meaning that you cannot  update the miners simply by running the program.

Normally you should be able to update the program by just creating a miner with the same "Install" save path and file name and it will overwrite the existing miner but when it's hidden then Windows won't allow it to be overwritten.

**Comment by UnamSanctam** [comment]
If you are worried about users removing the miner then if you have the "Watchdog" enabled then if they remove the file while the Watchdog is running it will copy the file back and run it.

**Comment by zoubaba1997** [comment]
Thanks, I used this method to avoid anti-virus detection, I hope it helps you
![Uploading 无标题.png…]()

**Comment by zoubaba1997** [comment]
![无标题](https://user-images.githubusercontent.com/73113267/111149307-b1a07080-85c7-11eb-9093-94c9d3b7c065.png)

**Comment by UnamSanctam** [comment]
Yes, only problem is that it requires administrator permissions.
