### ISSUE TITLE
Is it possible to somehow sew a configuration file into the assembly so that the command line parameters are not visible through the process explorer ?

### ISSUE THREAD

**Issue by timboft** [UnamSanctam/SilentXMRMiner#106]
so that the name of the parameters, the name of the pool, the name of the wallet are not visible

**Comment by UnamSanctam** [comment]
No not really, you can just sniff the traffic anyways to get them so there isn't much reason too. If you mine directly to a pool and has never posted your wallet address anywhere it can't really be used in anyway.

**Comment by timboft** [comment]
but then it will be clear what kind of process is working and with what parameters

**Comment by timboft** [comment]
Is it possible to add other task managers to the assembly?

**Comment by timboft** [comment]
more precisely, so that the process cannot be seen through other task managers?

**Comment by UnamSanctam** [comment]
You mean to the "Stealth" option? I mean it's possible but I didn't since Windows didn't like all the API class.

But the process can be found out anyway. If you have "Watchdog" enabled it will just start it up again if closed down.

**Comment by timboft** [comment]
yes I meant it, well, thanks for the answers anyway

**Comment by UnamSanctam** [comment]
No problem, I might try to include some sort of method to encrypt the command line options but I'll have to make it work well.

**Comment by timboft** [comment]
it would be nice to have the data encrypted when viewed
