### ISSUE TITLE
Do you have an ETA of the silent eth miner release?

### ISSUE THREAD

**Issue by danielkp1234** [UnamSanctam/SilentXMRMiner#107]
@UnamSanctam Do you have any ETA on the release of the silent eth miner?
Are there other problems than the GPU VRAM allocation?

**Comment by UnamSanctam** [comment]
Well I'm currently trying to decrease the detection rate of the injector since Microsoft has been updating their Defender definitions a lot, then there is also the problem of: how often and long do people leave their computers idle? Since only like 10-20% of all computers can run the miner due to the VRAM requirement and it will only run when idle, how profitable is it really?

**Comment by danielkp1234** [comment]
Okay, Well I think if it ran on gaming pcs the majority of them would be able to run it with the VRAM requirement :). And in general eth mining would be way more profitable in my opinion. IMO I think that the current detection rate would be fine for a initial release :)

**Comment by danielkp1234** [comment]
@UnamSanctam But I mean you could release if now if the only thing missing is lowering detections rates.

**Comment by UnamSanctam** [comment]
I was about to create the new repo when I was doing my final tests and it seems like the memory reallocation crashes some AMD cards so I have to find out why it does that.

**Comment by danielkp1234** [comment]
@UnamSanctam lol that seems weird. You could always just not support those cards in the initial release :)

**Comment by UnamSanctam** [comment]
Seems like I've gotten everything working now, just have to make sure everything in the builder is correct and working.

**Comment by danielkp1234** [comment]
@UnamSanctam Awesome!, will the auto-removal/self-destruct feature that I suggested be included in the initial release?

**Comment by UnamSanctam** [comment]
I have now uploaded the Silent ETH Miner here: https://github.com/UnamSanctam/SilentETHMiner, there is no auto-removal as of yet since I have to modify the Theme and haven't had time since it isn't very urgent.
