### ISSUE TITLE
Is there any cryptor for xmrig bypass antivirus detection?

### ISSUE THREAD

**Issue by timboft** [UnamSanctam/SilentXMRMiner#108]

**Comment by oneinam1llion** [comment]
https://mkaring.github.io/ConfuserEx/
https://yck1509.github.io/ConfuserEx/

**Comment by timboft** [comment]
i mean to encrypt xmrig.exe

**Comment by timboft** [comment]
xmrig  it is written in C ++

**Comment by UnamSanctam** [comment]
Well, you can't really obfuscate C++ since it's already kind of "obfuscated", I mean it's C++. The injected XMRig doesn't really get detected anyways, I've never seen a detection of it anyways.
