### ISSUE TITLE
Hide file removed from install menu

### ISSUE THREAD

**Issue by Rafo124** [UnamSanctam/SilentXMRMiner#109]
Hi,
I noticed that the 'hide file' feature was removed from the install menu. Was this accidentally?

**Comment by UnamSanctam** [comment]
No, it got removed since overwriting hidden and/or system files by programs seems to usually require administrator permissions so it got removed since it makes it impossible to update the miner.

**Comment by shainodev** [comment]
isnt the WinCFG folder really hidden cause i cant seem to find it in appdata, but when i double hide it with my app it will show it and all other files

**Comment by Rafo124** [comment]
> No, it got removed since overwriting hidden and/or system files by programs seems to usually require administrator permissions so it got removed since it makes it impossible to update the miner.

That's unfortunate. Maybe you can add a button in the builder but with a warning saying it's impossible to update it?

**Comment by UnamSanctam** [comment]
>isnt the WinCFG folder really hidden cause i cant seem to find it in appdata, but when i double hide it with my app it will show it and all other files

Yes if you still have a WinCFG folder left hidden by a previous version it will still be hidden.

>That's unfortunate. Maybe you can add a button in the builder but with a warning saying it's impossible to update it?

Well maybe, but usually most people won't read or understand it and I'll get a ton of questions about it.
