### ISSUE TITLE
How does it work exactly?

### ISSUE THREAD

**Issue by Somaboy123** [UnamSanctam/SilentXMRMiner#11]
Hi, Ive tried it on some of my pc's for some time but I dont seem to get any income?

in pool I entered pool.minexmr.com:4444
in walled my wallet offcourse
and password nothing?

Am I doing something wrong?

**Comment by UnamSanctam** [comment]
Double-check all your settings, do you have Idle Mining on?

**Comment by Somaboy123** [comment]
no idle mining is not on, now I got it working for some time. but all pc's where the same? because they didn't have a name. so I set password to names like the help icon said but now it doesnt seem to work? any ideas what I'm doing wrong? for pool I'm using https://minexmr.com/

and I really need them to be separate names hopefully you can help me because I really like your version of it!

**Comment by Somaboy123** [comment]
And I tried to change the code but when I open the project I get only errors so that wasnt a option eighter

**Comment by UnamSanctam** [comment]
First of all leave the password empty, as stated in the help documents you should add a dot and then the worker name to mine as a worker i.e Wallet.WorkerName

The only way to make each miner have its own worker name is to build a new miner for each user to run which for most isn't very feasible, and is also not supported by most pools. Also, the minexmr.com pool only supports up to 100 miners without using something like xmrig-proxy.

**Comment by Somaboy123** [comment]
mmm okay, thanks for the info I will try these things out. maybe its better to start using SupportXMR then. but I like the dashboard from MineXMR so much and I miss that in SupportXMR

**Comment by Somaboy123** [comment]
hey, when I open the project I get a lot of errors? how can I fix them?
-Could not find type 'SilentXMRMiner.MephTheme'
-Could not find type 'SilentXMRMiner.MephTabcontrol'
-Could not find type 'SilentXMRMiner.MephComboBox'
-Variable 'txtInjection' is undeclared
-Could not find type 'SilentXMRMiner.MephTextBox'
-Variable 'txtPoolUsername' is undeclared
-Variable 'txtPoolURL' is undeclared
and so on...
in total there are 38 errors can you please help me out?

**Comment by Somaboy123** [comment]
because I want to make it so automatically sets username to pc name.
or can you help with that?
