### ISSUE TITLE
why conhost injection removed

### ISSUE THREAD

**Issue by corsair550** [UnamSanctam/SilentXMRMiner#110]
what is the reason you have removed conhost and svchost from inject into section i tried that settings on at least 10 different windows 10 builds like 1903, 1909, 2004, 20h1, 20h2, 21h1, even latest insider build(21318) and more, conhost was working great is this some kind of bug ?

**Comment by UnamSanctam** [comment]
Well I've tested it on 27 computers and now it only worked on 9 of them so I am not sure if Microsoft added something into Windows or if it's something added into Windows Defender.

**Comment by UnamSanctam** [comment]
It doesn't work on my main computer or my laptop anymore either.

**Comment by corsair550** [comment]
interesting i think i will keep using v1.0 thank you
