### ISSUE TITLE
1.0.1 Version issue

### ISSUE THREAD

**Issue by zoubaba1997** [UnamSanctam/SilentXMRMiner#112]
I want to ask if deleting the injection will affect the miners.Since I updated all the miners with the 1.0.1 version, the number of my miners has changed from 1000 to 300.

**Comment by oneinam1llion** [comment]
Can you elaborate, "deleting the injection"?

**Comment by zoubaba1997** [comment]
> 您能详细说明一下“删除注射”吗？

Removed injection options due to new Windows protections,When I updated my miners with version 1.0.1, my total number of miners became less. I thought they were not working, and I also added exclusions using powershell

**Comment by oneinam1llion** [comment]
There may be residual miners leftover, have you made sure all the miners where deleted and killed in task manager one way or another?
You can accomplish this with a batch script as long as you know the names of the executables and the locations.
As long as you're using something like cmd.exe you shouldn't have an issue. Do you have any troubleshooting reports you can share that would maybe help?

**Comment by oneinam1llion** [comment]
Also I know this is completely offtopic and unorthodox but, your claims of getting 5k in a week. I was hoping your could help me do the same.  Currently only have about 5 or so but have 600 views on youtube and over 100 downloads but only 5. I have a working version now thanks to unam but spreading is time consuming especially when I work a job.

**Comment by zoubaba1997** [comment]
> 我也知道这完全是题外话和非正统的，但是，您声称在一周内获得5k。我希望您能帮助我做同样的事情。目前在YouTube上只有大约5个左右，但在YouTube上有600次观看，超过100次下载，但只有5个。感谢unam，我现在有一个工作版本，但是传播非常耗时，特别是当我工作时。

Telegram contact me

**Comment by oneinam1llion** [comment]
> > 我也知道这完全是题外话和非正统的，但是，您声称在一周内获得5k。我希望您能帮助我做同样的事情。目前在YouTube上只有大约5个左右，但在YouTube上有600次观看，超过100次下载，但只有5个。感谢unam，我现在有一个工作版本，但是传播非常耗时，特别是当我工作时。
> 
> Telegram contact me

I have

**Comment by timboft** [comment]
Why does the menu with injections work in version 1.0.1 if you say that they have been removed?

**Comment by zoubaba1997** [comment]
> 如果您说注射菜单已被删除，为什么带有注射菜单在1.0.1版中有效？

Didn’t UnamSanctam say it was deleted?

**Comment by UnamSanctam** [comment]
Only the conhost.exe and svchost.exe options.

**Comment by zoubaba1997** [comment]
> 仅conhost.exe和svchost.exe选项。
That is my setting error, thank you UnamSanctam
