### ISSUE TITLE
How to remove all of the mining code?

### ISSUE THREAD

**Issue by ZakyanGrish** [UnamSanctam/SilentXMRMiner#113]
I did build and run the miner on my windows laptop with the 'WatchDog' feature enabled, but I'm having trouble removing it now. Could you please help me remove 100% of the miner? Thanks.

**Comment by UnamSanctam** [comment]
Stop the process called sihost64.exe and the miner and then remove the miners startup entry in regedit at "HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Run". If you want to you can then remove the miner file where you chose to install it and remove the WinCFG folder from %AppData%.

**Comment by ZakyanGrish** [comment]
Thanks!
