### ISSUE TITLE
Doesn't Work 

### ISSUE THREAD

**Issue by pepeonzima1337** [UnamSanctam/SilentXMRMiner#115]
I don't know what seems to be the problem I tried like every pool but you stated that use nanopool 
but they require atleast one share so I mined using xmrig but still it is not in the database and I then tried different pools doesn't work
I tried 2miners pool it doesn't work can you help me please :)

**Comment by UnamSanctam** [comment]
If you mined using XMRig how much H/s did it say you were mining at?

**Comment by pepeonzima1337** [comment]
It wasn't showing the speed but at some point it showed 10hashes to 20 then 80/s to 100 then max 800hashes 
it showed me this I tried mining using gui version winxmr but they stopped working on that project

**Comment by UnamSanctam** [comment]
When mining with XMRig press 'h' and it will say what hashrate the cores are mining at.

**Comment by pepeonzima1337** [comment]
is there any other miner with easy setup I know xmrig is pretty easy but if it doesn't work and also please suggest a pool as well

**Comment by UnamSanctam** [comment]
Just download XMRig to a folder and then create a .bat file in the same folder containing:
```
@echo off
xmrig.exe --coin=monero --url=xmr-eu1.nanopool.org:14433 --tls --user=WALLET_ADDRESS --cpu-max-threads-hint=50
pause
```
and replace WALLET_ADDRESS with your Monero wallet address. Then start it and press 'h' to see the hashrate.

**Comment by pepeonzima1337** [comment]
Thanks for the quickest response Bruh! <3  and Thank you so much for giving me your precious time

**Comment by pepeonzima1337** [comment]
I got my share in database of nanopool but still the worker doesn't showup even after the build and execution I set it to 20% useage and decrease the execuation delay to 2 seconds still nothing and please tell me which port should I use with ssl or without ssl I used port without ssl
xmr-eu1.nanopool.org:14444 
it is not working :(

**Comment by UnamSanctam** [comment]
Use xmr-eu1.nanopool.org:14433 and enable SSL/TLS since that is generally better. Does the miner use any CPU in the Task Manager (don't enable "Stealth" when testing since then the miner will pause if you open Task manager)?

**Comment by pepeonzima1337** [comment]
Tried it with this too doesn't show up in task manager stealth is disabled tried it with ssl/tls and the process is no where to be found defender is disable and firewall is too and there is no other antivirus plus it doesn't showup in process explorer and I also tried it with admin priviliages still nothing. I think it is not getting executed delay was 2 second

**Comment by pepeonzima1337** [comment]
Windows 10 Pro 64bit

**Comment by UnamSanctam** [comment]
Sorry some work came up. If you enabled the "Watchdog" can you see if sihost64.exe is running?

**Comment by UnamSanctam** [comment]
And you can send the .exe here by uploading it to something like anonfiles and linking it here. I can try and debug it to see if I see anything directly wrong with it.

**Comment by pepeonzima1337** [comment]
Here you go https://anonymousfiles.io/ovAEs5AV/

**Comment by pepeonzima1337** [comment]
and sorry for the late reply I'm checking the watch dog mode

**Comment by UnamSanctam** [comment]
The link gives a 404, try using https://anonfiles.com/

**Comment by pepeonzima1337** [comment]
https://anonfiles.com/I1wa33l0uc/mxr_zip pass 123

**Comment by UnamSanctam** [comment]
Upload your compiled miner, not the builder :)

**Comment by pepeonzima1337** [comment]
:) sorry for that bruh :0 my bad

**Comment by pepeonzima1337** [comment]
https://anonfiles.com/a9z032l7u5/laststand_zip here you go pass 123

**Comment by UnamSanctam** [comment]
The miner starts for me, if you download Process Hacker https://processhacker.sourceforge.io/ and search for explorer.exe can you see the miner?

**Comment by pepeonzima1337** [comment]
![Capture](https://user-images.githubusercontent.com/80935238/111864297-dc9d1280-8981-11eb-81d1-c1f84b7337ad.PNG)

**Comment by UnamSanctam** [comment]
Hover over the explorer.exe at the bottom, does it show a long string of commands?

**Comment by pepeonzima1337** [comment]
https://prnt.sc/10qol9g

**Comment by pepeonzima1337** [comment]
yes it is actually miner but why it is not working https://prnt.sc/10qolye

**Comment by UnamSanctam** [comment]
Either it cannot use any CPU or it cannot connect to the pool. Were you able to mine directly with the XMRig?

**Comment by pepeonzima1337** [comment]
Yes I did

**Comment by pepeonzima1337** [comment]
I used xmrig just like you asked me to and I got my share and account in database

**Comment by pepeonzima1337** [comment]
So I just tested it on rdp I thought maybe my Isp is blocking it somehow or my it is my cpu problem but it is not working on rdp :|

**Comment by UnamSanctam** [comment]
Try building a new miner and enable 'Advanced Parameters', then remove everything in the box below and enter this `--coin=monero`

**Comment by pepeonzima1337** [comment]
Still nothing :|

**Comment by pepeonzima1337** [comment]
https://prnt.sc/10qpjg2

**Comment by UnamSanctam** [comment]
I will compile a miner that's not hidden quickly so that it shows a console that will say what's wrong.

**Comment by pepeonzima1337** [comment]
:) thank you I will wait

**Comment by UnamSanctam** [comment]
Here, try using this https://anonfiles.com/obPf37lcua/Silent_XMR_Miner_Builder_zip

**Comment by pepeonzima1337** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/80935238/111865914-bb412400-898b-11eb-82d3-4a64a622d4ff.png)

**Comment by pepeonzima1337** [comment]
it is actually working but it not showing any woker online in nanopool

**Comment by UnamSanctam** [comment]
Looks like you don't have enough memory.

**Comment by pepeonzima1337** [comment]
so problem is with my cpu right let me check it on rdp

**Comment by UnamSanctam** [comment]
Well both the CPU and RAM are very low.

**Comment by pepeonzima1337** [comment]
in rdp console is not showing up

**Comment by pepeonzima1337** [comment]
so if I have to be sure it is working or not How can I actually see workers are online or not . Because nanopool doesn't show anything

**Comment by pepeonzima1337** [comment]
and what do you think about a panel which shows workers online and to update  miner or wallet address actually like a mining botnet

**Comment by UnamSanctam** [comment]
I'm not planning on implementing anything like that myself but technically XMRig already supports that if you use xmrig-proxy and the http-api but you'll have to host your own server and such.

For your first question, it shows hashrate when they're mining but it's possible to a worker name by adding .WorkerName after the wallet address in the builder but all the miners will use the same worker name then so you won't be able to see how many there are since that's not the intended use for it.

**Comment by pepeonzima1337** [comment]
and thanks for the help and the information you have provided <3 keep sharing your knowledge :D
