### ISSUE TITLE
Pls help

### ISSUE THREAD

**Issue by ckove** [UnamSanctam/SilentXMRMiner#116]
hello i used a nanopool and a mymonero wallet so i infected my computer to see if its working... How do i check if im mining it or not? Like on minergate u can see the hash rate while i cant find it here on nanopool. Im new to this and would love to figure stuff like this out. Thanks!!?

**Comment by UnamSanctam** [comment]
Depending on whether you enabled "Stealth" or not, if didn't enable it then you can check if it's using any CPU using the Task Manager. If you enabled "Stealth" then use something like Process Hacker to see if it's using any CPU. If it is using any then it has connected to the pool and is mining, nanopool has quite a high share difficulty (doesn't really affect profit) so mining a share can take a while depending on how fast you're mining. 

To get to your wallet dashboard just go to nanopool and enter your wallet address in the top left and press Search, you will have to mine at least one share before it registers though.

**Comment by ckove** [comment]
Thanks man! I was wondering if nanopool and mymonero are compatible with each other? and in the wallet bar on the setup menu do i have to put anything more than the code that i copied from mymonero wallet. Thanks for such a fast respond wish you the best!

**Comment by UnamSanctam** [comment]
Yes all Monero wallets generally work with all Monero pools since they all work through the Monero blockchain. You really only need to enter the wallet address you get from the wallet, you can technically add a worker name and/or email (used as a password to change the minimum withdrawal amount on nanopool) but it isn't needed.

**Comment by ckove** [comment]
Another thank you im gonna close this issue cya!

**Comment by UnamSanctam** [comment]
Good luck
