### ISSUE TITLE
Bypassing Eset AV

### ISSUE THREAD

**Issue by thebigjoe** [UnamSanctam/SilentXMRMiner#117]
Hey, i bypassed eset with confuser ex, but the miner gets detected because it gets dropped in %appdata% , this is a little suggestion from me is to avoid dropping the exe but still making it run on startup

**Comment by UnamSanctam** [comment]
Then the user could just remove the file.

**Comment by oneinam1llion** [comment]
There would be no way to avoid dropping a file, unless it was compiled launched, and dropped somewhere else along down the payload., with another application. It's simply just heuristics, not really a code detection. That being said, there is no way to avoid that unless the file is signed by a publisher and verified.  When any file is opened an AV watches it like a hawk, scanning it and learning its behavior, which is then sent to a review team to determine the state of that file (safe, or not). New registry entries, file droppage outside of the working directory. Is almost always cataloged as potentially malicious unless that working directory is a folder made by the program. - most things that are "FUD" have obscure bypassing methods, or simply work in its own working directory, which is not a favorable outcome. If you want more information let me know, if you think outside of the box there is always a way to make something good bad.
