### ISSUE TITLE
Not worked

### ISSUE THREAD

**Issue by Toxenskiy** [UnamSanctam/SilentXMRMiner#119]
Doesn't work at all.
![image](https://user-images.githubusercontent.com/55586522/111914072-a8108000-8a81-11eb-8c07-2166f301b67b.png)

**Comment by UnamSanctam** [comment]
Is your pool address and wallet correct?

**Comment by Toxenskiy** [comment]
yes, it runs the file for some reason.

**Comment by Toxenskiy** [comment]
it drops the file and doesn't run it.

**Comment by UnamSanctam** [comment]
Hmm is "Install" and "Watchdog" enabled or not?

**Comment by Toxenskiy** [comment]
intstall yes, Watchdog no.

**Comment by Toxenskiy** [comment]
![image](https://user-images.githubusercontent.com/55586522/111914270-63d1af80-8a82-11eb-9a9e-0be78dfce688.png)

**Comment by UnamSanctam** [comment]
Firstly, why not? Secondly, it doesn't auto-start it without the Watchdog anymore since Windows Defender instantly detects it if it does.

**Comment by Toxenskiy** [comment]
and after restarting the pc, will he start it?

**Comment by UnamSanctam** [comment]
Yeah if the miner entry exists in "HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Run" in the registry it will start with Windows, You can check with regedit.

Also, if you enable the Watchdog it will automatically start the miner if it's closed down and will copy it back if removed. And GPU mining Monero isn't very profitable anymore, [GPU mining Ethereum](https://github.com/UnamSanctam/SilentETHMiner) or something else is better (though it requires a good GPU).

**Comment by Toxenskiy** [comment]
you can just glue 2 miners xd

**Comment by Toxenskiy** [comment]
1 per processor, other per video card. this miner mines only on the CPU, if not then how to disable gpu mining

**Comment by UnamSanctam** [comment]
You enabled GPU mining in the Monero builder. But yes if you build both the Monero miner and the Ethereum miner I linked and bind them together it will mine on both CPU (Monero) and GPU (Ethereum).

**Comment by Toxenskiy** [comment]
but how to glue them together so that there are not many detections so?

**Comment by UnamSanctam** [comment]
Well some File Binders will be detected as droppers and others won't but generally it depends if you want to sacrifice some undetectability to be able to mine on both CPU and GPU. I have used https://bytecode77.com/pe-union before it can be a bit advanced.

**Comment by Toxenskiy** [comment]
I remember this application +12 detections

**Comment by UnamSanctam** [comment]
Yeah because people scan it with virustotal so it gets detected but you can use any .NET Obfuscator on it to decrease detections.

**Comment by Toxenskiy** [comment]
ну я так и делаю.

**Comment by UnamSanctam** [comment]
Yeah but trying different obfuscators and settings in the obfuscator can decrease it more but if you can't get it to decrease then just spreading the Monero miner by itself is fine.

**Comment by Toxenskiy** [comment]
File died after obfuscation

**Comment by Toxenskiy** [comment]
![image](https://user-images.githubusercontent.com/55586522/111919242-fa5d9b00-8a99-11eb-90d1-b3c1a2eee6bc.png)

**Comment by UnamSanctam** [comment]
Try turning off "Compress & Encrypt Resources" since they're already encrypted.

**Comment by Toxenskiy** [comment]
helped

**Comment by Toxenskiy** [comment]
bruh
![image](https://user-images.githubusercontent.com/55586522/111919569-c1262a80-8a9b-11eb-8671-17764fd81d6f.png)

**Comment by Toxenskiy** [comment]
all that remains is to find a normal eth-proxy for linux

**Comment by UnamSanctam** [comment]
https://github.com/Atrides/eth-proxy actually still works.

**Comment by UnamSanctam** [comment]
Set it up and use the 'http' scheme in the builder and it should all work.

**Comment by Toxenskiy** [comment]
and after installing the proxy, what should I specify here?
![image](https://user-images.githubusercontent.com/55586522/111937331-8db5c100-8ad8-11eb-824d-9d7225939876.png)

**Comment by Toxenskiy** [comment]
one more question, is there a way to make the file encrypt itself at startup and start itself? Or how to implement it differently.
It's just that obfuscation does not work more than 2-3 times, then defender already detects

**Comment by pepeonzima1337** [comment]
if it is defender that is causing issue why not disable it with nyan x cat script :)

**Comment by UnamSanctam** [comment]
You should usually select the 'http' scheme for proxies. The miner is unfortunately really already as encrypted as it can be. What does the antivirus detect the file as? It will usually say what it thinks it is. You could also try using other settings in the obfuscator since sometimes it detects the things like 'Anti ILDASM'.

**Comment by Toxenskiy** [comment]
By the way, I recently saw another watchdog from another miner, he wrote the program into a notepad via base64 and then recovered due to this (even if all processes are closed, it will still start)

**Comment by UnamSanctam** [comment]
Well I could but then I would have to add the Watchdog into the registry I guess. I would have to test it out.

**Comment by Toxenskiy** [comment]
4 lines on python and now my file cannot be scanned on scanners and you cannot run the miner more than once.

**Comment by Toxenskiy** [comment]
How is it going?

**Comment by Toxenskiy** [comment]
on YouTube, it seems like I saw such a code, the video was called "work custom malware"

**Comment by UnamSanctam** [comment]
Yeah it does make the miner easier to remove though since they can more easily find the watchdog.

**Comment by Toxenskiy** [comment]
I have 2 questions, 
1)How to remove the miner from watchdog !!!kdopskapdoas
2)Where in the source code can you add additional processes from which the miner will hide?

**Comment by UnamSanctam** [comment]
The watchdog reads the miners code into memory at the start. 

The programs which it "hides" from is coded into the XMRig, currently it's only Task Manager for the XMR miner since Windows doesn't seem to appreciate too many calls at a high frequenzy.

**Comment by Toxenskiy** [comment]
but how to remove it from memory?
![image](https://user-images.githubusercontent.com/55586522/112193200-b93fc500-8c18-11eb-9828-c090110e26a0.png)

**Comment by UnamSanctam** [comment]
End the process called "sihost64.exe"

**Comment by Toxenskiy** [comment]
And when will the function of random worker nicknames appear in the builder?

**Comment by Toxenskiy** [comment]
it's just that this function is only available in the ETHEREUM miner

**Comment by UnamSanctam** [comment]
No you can use {%RANDOM%} or {%COMPUTERNAME%} in both builders.

**Comment by Toxenskiy** [comment]
ok, fix it
![image](https://user-images.githubusercontent.com/55586522/112479417-11e0a080-8d86-11eb-8682-0fdfdc744fc1.png)

**Comment by UnamSanctam** [comment]
I know that it doesn't say it, technically I don't believe most pools support having too many worker names which is why I haven't added it. I would only recommend using either if you don't plan on having too many workers or are using xmrig-proxy.

**Comment by Toxenskiy** [comment]
i know what you mean and yes i use xmrig proxy

**Comment by Toxenskiy** [comment]
i use vds 23$/year

**Comment by UnamSanctam** [comment]
Yeah then using {%RANDOM%} or {%COMPUTERNAME%} will be fine as long as it isn't passed on to the pool. Might add it into the tooltip though I probably need to say that mining directly to a pool with many worker names might get you banned.

**Comment by Toxenskiy** [comment]
i know ;)))

**Comment by Toxenskiy** [comment]
it would be great to have a custom build so others don't kill it.

**Comment by Toxenskiy** [comment]
by the way, why every time the miner is restarted a different name, I thought it should be the same

**Comment by UnamSanctam** [comment]
No if you use {%RANDOM%} it will randomize a new name each startup since the miner never saves anything.

**Comment by Toxenskiy** [comment]
okay, why is the pc name not the one that the computer itself has.

**Comment by UnamSanctam** [comment]
I you use {%COMPUTERNAME%} it will use the computers name but remove all non A-Z/a-z/0-9 characters since pools usually only supports those, it also limits the length to 10 since pools usually also have a limit of that. You can find the code here: https://github.com/UnamSanctam/SilentXMRMiner/blob/master/SilentXMRMiner/Resources/Program.vb at line 191/192.

**Comment by Toxenskiy** [comment]
pc name - oreha
![image](https://user-images.githubusercontent.com/55586522/112511062-19fb0900-8da3-11eb-9f03-e3f6ea99c37b.png)

**Comment by Toxenskiy** [comment]
but you do not know how to delete inactive workers

**Comment by UnamSanctam** [comment]
It depends on the pool (or xmrig-proxy) settings but inactive workers get removed automatically after a few days.

**Comment by UnamSanctam** [comment]
And the  {%COMPUTERNAME%} works correctly, the computer you linked has a default Windows computer name.

**Comment by Toxenskiy** [comment]
but you could not make a measured load for the miner, that is, if the pc requires power, then the miner slows it down and so that the percentage is loaded by 90%.

**Comment by Toxenskiy** [comment]
if you give the user the right HUGE PAGES, then the hashrate will grow by 1.5

**Comment by Toxenskiy** [comment]
russian yt https://www.youtube.com/watch?v=kM3Hw3rC3Bw

**Comment by Toxenskiy** [comment]
I don't know for sure, but the miner is weak

**Comment by Toxenskiy** [comment]
possibly because of watchdog xd
but the miner that is being cut from the text editor has been keeping for me already in the region of 2 months all users

**Comment by Toxenskiy** [comment]
why such a big donation can be done there 1
![image](https://user-images.githubusercontent.com/55586522/112720072-4e8ad400-8f0d-11eb-9bdb-db4a11c2422f.png)

**Comment by Toxenskiy** [comment]
downloaded and launched 8 people left 0 is this a joke?

**Comment by UnamSanctam** [comment]
What do you mean the miner is weak? And the watchdog doesn't affect performance in the slightest. The donate-level is set to 5 by default out of support for the dev.

Have you checked that your pool and wallet settings are correct?
