### ISSUE TITLE
email

### ISSUE THREAD

**Issue by ckove** [UnamSanctam/SilentXMRMiner#120]
on nanopool it says that i need an email to withdraw but in your program there isnt any place to put email so how can i withdraw?

**Comment by UnamSanctam** [comment]
Well you don't need an email to withdraw, you can mine with an email to lower the minimum payout of XMR. If you read the nanopool guide on their website it says to input this `YOUR_XMR_ADDRESS.YOUR_WORKER/YOUR_EMAIL` as your wallet address.

**Comment by ckove** [comment]
so i have a couple of miners and everything working fine so when the withdraw day comes it wuld be fine? + I dont see any workers but i know that its mining

**Comment by UnamSanctam** [comment]
Yes when you reach the current minimum withdrawal (by default at 1 XMR) it will withdraw automatically to your wallet. Workers are meant to be used if you want to see the specific speed of all the miners using that worker name and thus aren't required.

It is possible to lower the minimum withdrawal (to 0.1 XMR) by mining just 10 shares on your own computer with an email, then use that email (as a password on nanopool) to change the withdrawal and then closing the miner.

**Comment by ckove** [comment]
yo second time u replied to my questions instantly thank you so much! :)
