### ISSUE TITLE
I signed up to githuba to give my thanks

### ISSUE THREAD

**Issue by agarmax** [UnamSanctam/SilentXMRMiner#122]
I'll probably get my first payment tomorrow
0.01 XMR  I will be happy to send you 10% of this and the amounts I will earn from now on.

**Comment by UnamSanctam** [comment]
No problem, I am glad that it works. Only send some if you feel like it's worth it :)

**Comment by agarmax** [comment]
It will mining be easier if not detected by Windows security center

**Comment by UnamSanctam** [comment]
Well each time I release it it is undetected but since people upload it to things like virustotal the code signatures get detected in a day or two. Usually .NET Obfuscators will decrease detections since they change the code signatures and other things.

**Comment by Toxenskiy** [comment]
4 lines on python and now my file cannot be scanned on scanners and you cannot run the miner more than once.
