### ISSUE TITLE
Can u get banned ?

### ISSUE THREAD

**Issue by ckove** [UnamSanctam/SilentXMRMiner#124]
![232](https://user-images.githubusercontent.com/80935559/112548746-ff358e00-8dbc-11eb-806d-7c91c799dc9c.jpg)
How come it suddenly stopped it was working all day ?

**Comment by UnamSanctam** [comment]
Check the computer that you're mining on?

**Comment by ckove** [comment]
in not mining with mine :D dont tell anyone :)

**Comment by ckove** [comment]
I never put anything for password and workername so i never see if they are online or not

**Comment by UnamSanctam** [comment]
They could've turned of their computers.

**Comment by ckove** [comment]
in the same time ? I had quite a traffic today on downloads so to happend in the same time is rare but oh well maby they did. Thank you for your help!
