### ISSUE TITLE
Last one i swear 

### ISSUE THREAD

**Issue by ckove** [UnamSanctam/SilentXMRMiner#125]
![232323](https://user-images.githubusercontent.com/80935559/112551723-bcc28000-8dc1-11eb-8a78-287023d77e7c.jpg)
Sorry for real! Maby u know why? But it suddenly showed that i have some unconfirmed balance before it was 0 and it says on the graph that it didnt mine anything so how come i get unconfirmed balance ? Thank you so much i wont bother you again!

**Comment by UnamSanctam** [comment]
Unconfirmed balance is any balance that hasn't gotten any blockchain confirmations yet. They are normal after mining since it can take a while for it to get confirmed.
