### ISSUE TITLE
read this guys!

### ISSUE THREAD

**Issue by ckove** [UnamSanctam/SilentXMRMiner#126]

**Comment by ckove** [comment]
Nanopool banned me so dont use nanopool

**Comment by UnamSanctam** [comment]
How many miners?

**Comment by ckove** [comment]
around 5 to 7 working more than 12h a day... sad. Maby its because i had no workers showing but thats just my guess

**Comment by UnamSanctam** [comment]
Well then you must've done something else since there are people with like 500-1000, in what way were you banned?

**Comment by ckove** [comment]
![Screenshot_20210327_004109_com huawei browser](https://user-images.githubusercontent.com/80935559/112702845-2790bb80-8e95-11eb-9be6-251b7d3e2326.jpg)
I srsly dont know what else could be the problem...

**Comment by ckove** [comment]
i just showed my ip plz dont attack me guys

**Comment by ckove** [comment]
I think its because I always left password in your program blank and it never showed miners i had 0 workers online and offline but i still had people mine in the meantime so i think thats why

**Comment by UnamSanctam** [comment]
No that won't matter, I never mine with a worker names and the password should always be left blank, but well that's just your IP that's banned , if you connect with a VPN does it still work? They usually only ban IPs that try to DDoS them. Are the miners running on a separate net?

**Comment by ckove** [comment]
My only guess is maby bcz i check like every 10mins on my phone than on my computer so like 100 times a day maby they taught i was a bot

**Comment by ckove** [comment]
and yes miners run on separate nets

**Comment by UnamSanctam** [comment]
Well 100 times shouldn't matter, does anyone else use the same net? If so they might have gotten the IP banned, but if the miners are on another net they should still be mining.

**Comment by ckove** [comment]
omg man sorry about wasting your time i used vpn and i got in... one more question how to spread i tryed to make fake tutorials on youtube but its too slow like 2 3 people per day?

**Comment by UnamSanctam** [comment]
No problem, glad that it was nothing serious. But well that's the most common spreading way, usually making more videos or using sites like view4view or like4like can work to increase the traffic. There are also lots of spreading tutorials online on forums although a lot try to make money off of you.

**Comment by ckove** [comment]
Thank you man. Never met a guy on internet more generous than you! You helped me like 5 times and you always reply to me within 5min. Really appreciate your help!
