### ISSUE TITLE
I don't know for sure, but the miner is weak (scam??)

### ISSUE THREAD

**Issue by Toxenskiy** [UnamSanctam/SilentXMRMiner#127]
possibly because of watchdog xd
but the miner that is being cut from the text editor has been keeping for me already in the region of 2 months all users
downloaded and launched 8 people left 0 is this a joke?
why such a big donation can be done there 1
![image](https://user-images.githubusercontent.com/55586522/112720392-1c7a7180-8f0f-11eb-9bf4-ffb3cc07a634.png)

**Comment by UnamSanctam** [comment]
I'll write the same reply here as in your other issue.

>What do you mean the miner is weak? And the watchdog doesn't affect performance in the slightest. The donate-level is set to 5 by default out of support for the dev.

>Have you checked that your pool and wallet settings are correct?

**Comment by Toxenskiy** [comment]
donate lvl can be changed up to 1, secondly the pool and wallet are correct

**Comment by UnamSanctam** [comment]
I know that it can be changed, I have set it to 5 to support the developer, you can change it to 1 and compile the code yourself it you want to. And if everything was correct then it would be mining so some settings is obviously wrong.

**Comment by Toxenskiy** [comment]
hmm watchdog is no longer relevant; ((
![image](https://user-images.githubusercontent.com/55586522/112721047-dfb07980-8f12-11eb-8788-d844b9c4aa56.png)

**Comment by UnamSanctam** [comment]
What? It haven't been detected in any of my tests yet, what antivirus do you have?

**Comment by Toxenskiy** [comment]
Windows Defender -_-

**Comment by UnamSanctam** [comment]
What is it getting detected as?

**Comment by Toxenskiy** [comment]
the path to sihost64 + performs the actions of the malefactor

**Comment by UnamSanctam** [comment]
Yes but what kind of virus does it say it is?

**Comment by Toxenskiy** [comment]
![image](https://user-images.githubusercontent.com/55586522/112721182-99a7e580-8f13-11eb-9b1e-d4cdc3dc63fc.png)

**Comment by UnamSanctam** [comment]
Hmm, I'll have to test it out but it's never been detected so far on any of my machines.

**Comment by UnamSanctam** [comment]
And what miner settings are you using for it not to work? You can copy paste the "Process Command Line" from your first image here.

**Comment by Toxenskiy** [comment]
now the whole miner detects even after obfuscation, etc.

**Comment by Toxenskiy** [comment]
![image](https://user-images.githubusercontent.com/55586522/112721440-ca3c4f00-8f14-11eb-8bc0-9a592b53e17c.png)
![image](https://user-images.githubusercontent.com/55586522/112721444-d1635d00-8f14-11eb-96cc-4ba6cbb3613b.png)
![image](https://user-images.githubusercontent.com/55586522/112721446-d6281100-8f14-11eb-967e-fcaeb8c598d2.png)
![image](https://user-images.githubusercontent.com/55586522/112721450-db855b80-8f14-11eb-96b0-d3fd07f9c348.png)

**Comment by UnamSanctam** [comment]
Well then the obfuscations most likely has been detected. what pool address are you using?

**Comment by Toxenskiy** [comment]
detect miner
![image](https://user-images.githubusercontent.com/55586522/112721470-fc4db100-8f14-11eb-9dd0-c591079ef318.png)

**Comment by Toxenskiy** [comment]
xmrig proxy

**Comment by UnamSanctam** [comment]
If you use xmrig-proxy then you must enable "Nicehash Mining" as it says on the page: https://github.com/xmrig/xmrig-proxy

**Comment by Toxenskiy** [comment]
wow not know

**Comment by Toxenskiy** [comment]
but how to put your lvl donation

**Comment by UnamSanctam** [comment]
You would have to download the project and open it with Visual Studio 2019, change the donate-level in Form1.vb on line 88 and then build the miner.

**Comment by Toxenskiy** [comment]
How would you recommend an obfuscator?

**Comment by UnamSanctam** [comment]
Well usually I recommend ConfuserEx but so many people have been using it that it's been mostly detected, I don't really have any other current recommendations but you can find a list of other Obfuscators here https://github.com/NotPrab/.NET-Obfuscator

**Comment by Toxenskiy** [comment]
is it for ready-made exe?

**Comment by UnamSanctam** [comment]
Which one, the ConfuserEx?

**Comment by Toxenskiy** [comment]
use it after build

**Comment by UnamSanctam** [comment]
Yes.

**Comment by Toxenskiy** [comment]
and how to use it for .exe

**Comment by UnamSanctam** [comment]
How to use what, the obfuscator?

**Comment by Toxenskiy** [comment]
already understood

**Comment by Toxenskiy** [comment]
you want to say that miners did not work due to the fact that I did not enable nicehash

**Comment by UnamSanctam** [comment]
Yes since on xmrig-proxys page it says
>⚠️ ⚠️ ⚠️ Nicehash support must be enabled on miner side, it mandatory. ⚠️ ⚠️ ⚠️

**Comment by Toxenskiy** [comment]
hmm it's strange, when I ran without a nice hash on a virtual machine everything was fine

**Comment by bengalm** [comment]
@UnamSanctam I want to know how to bypass the startup of C++ program, 360av always intercepts my registry operation, do you have a way?

**Comment by Toxenskiy** [comment]
what's the best way to distribute the miner?

**Comment by velial31** [comment]
i have same issue, windows defender detect my file. How to avoid this?

**Comment by UnamSanctam** [comment]
The problem with it detecting the registry key being added is kind of unavoidable from what I've seen since it seems to detect any unsigned program being added into the registry and such I believe it would remove and program and not just possibly unwanted or malicious ones. I have tried adding it into the startup folder instead but for me WD detected it instantly when I did that.

Well to decrease detections you can either use an obfuscator or crypter.
