### ISSUE TITLE
nicehash question

### ISSUE THREAD

**Issue by ckove** [UnamSanctam/SilentXMRMiner#128]
do i need to use nicehash on nanopool ?

**Comment by UnamSanctam** [comment]
No only enable Nicehash if you mine on the nicehash pool you use xmrig-proxy.

**Comment by ckove** [comment]
another fast respond damn man u on fire love yaaaa!!!!!!!!!!

**Comment by golxd** [comment]
> No only enable Nicehash if you mine on the nicehash pool or if you use xmrig-proxy.

Hello, Tell me pls where is the best place to mine now, I tried it on minergate, but it often crashes. Which is better to use? nicehash?

**Comment by UnamSanctam** [comment]
I use nanopool but other pools like ethermine work as well.

**Comment by golxd** [comment]
> I use nanopool but other pools like ethermine work as well.

Okay, thanks for answering, I'll try nanopool, don't tell me there are no problems with the output? and do you need a passport, etc.?

**Comment by golxd** [comment]
![image](https://user-images.githubusercontent.com/81568432/112845840-fccd7f80-90ad-11eb-90de-e4c64f070b00.png)
is everything right? i dont know need to "SSL Stratum Port" or "Stratum Port"

**Comment by UnamSanctam** [comment]
Use the SSL Stratum Port and then enable "SSL/TLS" in the "Mining" tab. Also leave the password completely blank otherwise it won't work on nanopool.

**Comment by golxd** [comment]
Got it. Thank you very much. The last question, there are statistics on how many devices are connected to the miner?

**Comment by UnamSanctam** [comment]
No, to do that you would need to run your own xmrig-proxy which is quite complicated. It is possible to use the computer name as the worker name but usually pools don't like when you have too many workers.

**Comment by golxd** [comment]
I've been trying to mine test for more than an hour, the site writes **account not found**. tried to change pools (usa eu), changed port. Nothing helps. on the site in search I write my xmr wallet, writes **account not found** What could be the problem? 
![image](https://user-images.githubusercontent.com/81568432/112867433-98b5b600-90c3-11eb-8a69-8d221650ff24.png)
![image](https://user-images.githubusercontent.com/81568432/112867455-9eab9700-90c3-11eb-8cb5-4ef0f33396c3.png)
![image](https://user-images.githubusercontent.com/81568432/112867468-a3704b00-90c3-11eb-931e-9c0916a5e7c6.png)
![image](https://user-images.githubusercontent.com/81568432/112867482-a66b3b80-90c3-11eb-8b1d-499fe7e4b340.png)
![image](https://user-images.githubusercontent.com/81568432/112867514-b1be6700-90c3-11eb-8883-a4c966ee7550.png)
![image](https://user-images.githubusercontent.com/81568432/112867537-b84cde80-90c3-11eb-805c-e659da24deb7.png)

**Comment by UnamSanctam** [comment]
Is the miner using any CPU?

**Comment by golxd** [comment]
in the device manager, the explorer loading is 50%, I don't understand what the problem is

**Comment by UnamSanctam** [comment]
Then it's working and mining, nanopool has quite a high share difficulty so it can take a while for a share to be accepted depending on the CPU.

**Comment by golxd** [comment]
well thanks, I will try further. <3

**Comment by golxd** [comment]
Appeared, thank you for your help <3
