### ISSUE TITLE
It doesnt work

### ISSUE THREAD

**Issue by Dovahkiin1234** [UnamSanctam/SilentXMRMiner#131]
I've been using this software for a quite a long time but after update 1.0.2 mining doesnt starts. Program and watchdog (sihost64) opens but mining doesnt start. My antivirus software isnt even open. Why is it like this?

**Comment by UnamSanctam** [comment]
Well the actual miner hasn't been changed since update 1.0 and the subsequent updates don't contain that much, does it work before 1.0.2 (1.0 or 1.0.1)?

**Comment by Dovahkiin1234** [comment]
It was working I can check it right now

**Comment by UnamSanctam** [comment]
1.0 didn't work?

**Comment by Dovahkiin1234** [comment]
yes it didn't

**Comment by UnamSanctam** [comment]
Well I only really added anti-sleep in that version, try downloading https://github.com/xmrig/xmrig/releases and create a .bat file in the same folder containing:
`xmrig.exe --coin=monero --url=xmr-eu1.nanopool.org:14444 --user=8BbApiMBHsPVKkLEP4rVbST6CnSb3LW2gXygngCi5MGiBuwAFh6bFEzT3UTufiCehFK7fNvAjs5Tv6BKYa6w8hwaSjnsg2N --pass= --cpu-max-threads-hint=20`
And see if that runs.

**Comment by UnamSanctam** [comment]
The latest version?

**Comment by Dovahkiin1234** [comment]
yes checking the pool on the site rn

**Comment by UnamSanctam** [comment]
Well if it just stopped working then the only real possibility is that your IP is banned from the pool server or another miner is a already mining on your system so it won't start.

**Comment by Dovahkiin1234** [comment]
going to use their miner if doesnt start then probably ip banned

**Comment by Dovahkiin1234** [comment]
I checked it Im pretty sure its not mining neither the pool Im using probably ip banned do you know any good pools?

**Comment by UnamSanctam** [comment]
Well I only really use nanopool, also check if it's running with something like Process Hacker if you aren't already.

**Comment by Dovahkiin1234** [comment]
I did check it with process hacker too bad that I got banned from it at least I got my cash

**Comment by UnamSanctam** [comment]
Well, then either your wallet address is banned or just your current IP. You can try the xmrig I sent before and change the pool and wallet address to your own and then run it to see if it starts to mine or not.

**Comment by Dovahkiin1234** [comment]
alright man gonna try it out thank you

**Comment by UnamSanctam** [comment]
I said this in your other issue as well but in my new release I've fixed a critical bug on some Windows systems so it's recommended to build a new miner with that version.
