### ISSUE TITLE
New more hidden method of persistence!

### ISSUE THREAD

**Issue by Footsiefat** [UnamSanctam/SilentXMRMiner#132]
[https://youtu.be/-hz0PTVa0k4](https://youtu.be/-hz0PTVa0k4)

have a watch of this, but basically you can add a reg key which runs our program with the original program as an arugment. so if you so it right you can make this program run every time explorer.exe runs which could be a easier and more inivisble form of persistence on boot. If you do add this though make sure it adds runs the original exe aswell otherwise youll crash windows because explorer wont run. also youll have to deal with this running multiple times since users will use explorer multiple times on boot

**Comment by UnamSanctam** [comment]
That method requires administrator privileges though.

**Comment by Footsiefat** [comment]
True that. You want me to do you my UAC bypass program then?

**Comment by shainodev** [comment]
> That method requires administrator privileges though.

its easy to impliment a uac bypass its just like 10 lines bro

**Comment by UnamSanctam** [comment]
> its easy to impliment a uac bypass its just like 10 lines bro

No, Microsoft isn't stupid, although there are UAC bypasses with things like event viewer, disk cleanup and others they are neither short, easy, undetected nor very reliable. The two last reasons are the primary reason why I've not added any.
