### ISSUE TITLE
injection does not occur without admin rights, how to disable injections completely? will such a function be in new updates?

### ISSUE THREAD

**Issue by timboft** [UnamSanctam/SilentXMRMiner#133]
injection does not occur without admin rights, how to disable injections completely? will such a function be in new updates?

make it possible to disable injections

**Comment by UnamSanctam** [comment]
Injection does work without administrator permissions. The whole program is built upon injecting the miner and running it that way, it would technically be possible to instead move the miner from memory to a folder but that would get detected by the antivirus immediately.
