### ISSUE TITLE
Mobile

### ISSUE THREAD

**Issue by ckove** [UnamSanctam/SilentXMRMiner#134]
Hi! Can phones mine monero? If so do you plan on making a program for that purpose? Thanks!

**Comment by UnamSanctam** [comment]
Well it's technically possible to mine on phones but it will have both a low hashrate and the heat will be unbearable. But even then you would implement it into your own APK or something so I don't plan on in of course.

**Comment by ckove** [comment]
Thanks for the quick reply. I read an article on phone viruses so i was just curious.

**Comment by UnamSanctam** [comment]
Yeah most phone viruses are usually "keyloggers", data stealers/crypto stealers since they are usually the most profitable and flexible.
