### ISSUE TITLE
detected wd

### ISSUE THREAD

**Issue by Toxenskiy** [UnamSanctam/SilentXMRMiner#137]
Protected version
![image](https://user-images.githubusercontent.com/55586522/113282181-42c55600-92ef-11eb-9fb7-b98192347b35.png)

![image](https://user-images.githubusercontent.com/55586522/113282154-3b9e4800-92ef-11eb-8caa-68e22047bf4c.png)

no watchdog version:
![image](https://user-images.githubusercontent.com/55586522/113282744-07775700-92f0-11eb-8f4d-dc25e738cde6.png)

![image](https://user-images.githubusercontent.com/55586522/113282716-faf2fe80-92ef-11eb-9985-93c847a5af24.png)

**Comment by Toxenskiy** [comment]
sihost64 detected
![image](https://user-images.githubusercontent.com/55586522/113283441-fe3aba00-92f0-11eb-9a25-0e6f820b4108.png)

**Comment by UnamSanctam** [comment]
Hmm haven't seen the watchdog detected before, it probably isn't detected but gets detected because your main miner is detected. Also build the miner as release and not debug, are you building the latest version as well?

**Comment by Toxenskiy** [comment]
build 1.1 debug version

**Comment by UnamSanctam** [comment]
If you use the pre-compiled builder does it get detected as well?

**Comment by Toxenskiy** [comment]
did not check

**Comment by Toxenskiy** [comment]
be able to give me your build

**Comment by Toxenskiy** [comment]
after all the tests, I found out that it was a watchdog that was detecting

**Comment by Toxenskiy** [comment]
That is, everything works fine and the antivirus does not detect it. The watchdog is detected and removed. And this is how everything works

**Comment by UnamSanctam** [comment]
Hmm interesting, haven't seen that happening before. I will try and change the code a bit on the next release.
