### ISSUE TITLE
AP

### ISSUE THREAD

**Issue by Toxenskiy** [UnamSanctam/SilentXMRMiner#138]
Have you thought about the admin panel, for example, taking AsyncRat as the source?
P.S. and yes you have a good stealth. to bypass it, it is not enough to rename the program itself

**Comment by UnamSanctam** [comment]
The miner is made in C++ and AsyncRat is made in C# so the code is not even close to compatible, I don't have nearly enough time to make an admin panel myself but you can technically use the built-in XMRig HTTP API if you want an admin panel.

And well if I understand you correctly then I have to say that it's not renamed, it's injected through process hollowing and injecting the program is nearly as good as it can get, that's the reason nearly all crypters do it as well.

**Comment by Toxenskiy** [comment]
what complexity of encryption are you using in ConfuserEx

**Comment by UnamSanctam** [comment]
I usually set my own options but Normal or Minimum usually work.

**Comment by Toxenskiy** [comment]
use precompiled build
![image](https://user-images.githubusercontent.com/55586522/113433306-a03cce00-93e7-11eb-885f-787467509a79.png)

**Comment by Toxenskiy** [comment]
![image](https://user-images.githubusercontent.com/55586522/113433429-dd08c500-93e7-11eb-9510-6529893362cb.png)
![image](https://user-images.githubusercontent.com/55586522/113433438-e09c4c00-93e7-11eb-8278-bb2e2c71da96.png)
![image](https://user-images.githubusercontent.com/55586522/113433449-ea25b400-93e7-11eb-93fa-7e85bd292f98.png)

**Comment by UnamSanctam** [comment]
Hmm weird, the normal miner usually gets detected since the program is public so many use it irresponsibly but the watchdog usually won't get detected and I haven't been able to get it detected myself. Try running it on another computer to see if it gets detected.

Also try setting the 'Save Path' to Temp or something since Windows Defender can be a bit sensitive about the UserProfile sometimes.

**Comment by Toxenskiy** [comment]
after the start of the detect program, that is, the drop was successful

**Comment by UnamSanctam** [comment]
Well yeah but that could be because it got started in the UserProfile which WD sometimes won't like. And what 'Start Delay' did you use?

**Comment by Toxenskiy** [comment]
15 seconds and I changed the install path to "temp"

**Comment by UnamSanctam** [comment]
And if you try running it on another computer it gets detected as well?

**Comment by Toxenskiy** [comment]
do not have 1 more computer for the test
