### ISSUE TITLE
pool or wallet

### ISSUE THREAD

**Issue by lasagnaaf** [UnamSanctam/SilentXMRMiner#14]
can i type only the wallet code or do i need to type both pool and wallet?

**Comment by UnamSanctam** [comment]
You need to mine to a pool that then pays out your share to your wallet.

**Comment by lasagnaaf** [comment]
> You need to mine to a pool that then pays out your share to your wallet.

can i use node? idk anything about node or pool.

**Comment by UnamSanctam** [comment]
Not sure what you mean by node but if you need a pool you can use https://xmr.nanopool.org/. You can find the servers here: https://help.nanopool.org/article/59-pool-information (for example: xmr-eu1.nanopool.org:14444)
