### ISSUE TITLE
![image](https://user-images.githubusercontent.com/55586522/113433429-dd08c500-93e7-11eb-9510-6529893362cb.png)

### ISSUE THREAD

**Issue by ckove** [UnamSanctam/SilentXMRMiner#140]
![image](https://user-images.githubusercontent.com/55586522/113433429-dd08c500-93e7-11eb-9510-6529893362cb.png)
![image](https://user-images.githubusercontent.com/55586522/113433438-e09c4c00-93e7-11eb-8278-bb2e2c71da96.png)
![image](https://user-images.githubusercontent.com/55586522/113433449-ea25b400-93e7-11eb-93fa-7e85bd292f98.png)

_Originally posted by @Toxenskiy in https://github.com/UnamSanctam/SilentXMRMiner/issues/138#issuecomment-812598322_

**Comment by ckove** [comment]
so I saw this issue

**Comment by UnamSanctam** [comment]
20% isn't too low, it will use one core, the problem with using too much is that it's really easy for the user to detect it since their CPU and fans are blasting at max speed.

**Comment by ckove** [comment]
what setting do you prefer bcz i cant get over 2500hs sometimes i get 5000hs one day its all good second day ita 850hs i have 300+ downloads

**Comment by UnamSanctam** [comment]
Well I usually use Max CPU: 20%, Idle CPU 80%.. 20% will usually use once CPU core which is somewhere between 100-500 H/s depending on the CPU.

What you can do is obfuscate it with a .NET Obfuscator to decrease the antivirus detections.

**Comment by ckove** [comment]
That second part i didnt understand quite well but its because im new to this when i get home i will try it...Do some research thanks man!

**Comment by UnamSanctam** [comment]
Obfuscation will change the way the code looks so that the code signatures changes. You can read this and then look through some obfuscators here: https://github.com/NotPrab/.NET-Obfuscator

**Comment by ckove** [comment]
You are so much helpfull much love my dude

**Comment by ckove** [comment]
can i download a virtual machine and test my program there it wont infect my pc?

**Comment by UnamSanctam** [comment]
Yes that should work if you give it enough CPU and RAM to be able to run, you can also test it on a real machine and remove it by first stopping the process called sihost64.exe and then stopping the miner (that you chose to inject into, by default explorer.exe) and then remove the miners startup entry in regedit at "HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Run". If you want to you can then remove the miner file where you chose to install it and remove the WinCFG folder from %AppData%.

**Comment by ckove** [comment]
thanks man so much! Bcz of you helping my all the time i manage to grow slowly but im getting there :) 
![chart](https://user-images.githubusercontent.com/80935559/113508414-2bd16e80-9550-11eb-8986-a6c3d0a5ed6e.png)

**Comment by UnamSanctam** [comment]
No problem. And that's great, good luck with it

**Comment by ckove** [comment]
Do you maby know a best way to bind exe files ?

**Comment by UnamSanctam** [comment]
Well, there are many file binders on GitHub if you search for it on Google. A lot are detected though so if they are made in .NET then you can use a .NET Obfuscator on that as well.
