### ISSUE TITLE
Decreasing the miner getting caught

### ISSUE THREAD

**Issue by Dovahkiin1234** [UnamSanctam/SilentXMRMiner#141]
I have a problem about miner getting caught too easily 
I spread it pretty nice and people opens it for 20 minutes any advices?
![Screenshot_4](https://user-images.githubusercontent.com/46829185/113491784-e3786900-94db-11eb-9c8f-19aceac550db.png)

**Comment by UnamSanctam** [comment]
Well if it gets detected it won't mine anything since it will get removed right away, is there something supposed to be wrong with your graph? If you want to decrease detections you should use a .NET Obfuscator.

**Comment by Dovahkiin1234** [comment]
People disable their antivirus and open the miner but they open their antivirus after 20 minutes I think you can add something so the cpu usage increase overtime? Is that possible?

**Comment by UnamSanctam** [comment]
No problem and thank you. But the miner won't really get detected while it's running and won't get detected by CPU usage, if it stops it's caused by something else. And CPU usage is bound by the amount of cores it uses so it can't really be changed slightly but only in big amounts.

**Comment by Dovahkiin1234** [comment]
What makes it stops?

**Comment by UnamSanctam** [comment]
Does it stop? Where do you see that it stops?

**Comment by Dovahkiin1234** [comment]
![Screenshot_6](https://user-images.githubusercontent.com/46829185/113520998-58f93d80-959f-11eb-97fa-aeac6f4167df.png)
On here the hash rate drops

**Comment by UnamSanctam** [comment]
Well that doesn't really say anything, that's just how mining works, it's luck based so it will go up and down all the time depending on your luck in finishing jobs. https://help.nanopool.org/article/62-faq#6.-hashrate

**Comment by Dovahkiin1234** [comment]
Oh alright then actually my overall hashrate is increasing so nothing to worry about

**Comment by UnamSanctam** [comment]
In my new release I've fixed a critical bug on some Windows systems so it's recommended to build a new miner with that version since it can be spread to more computers.
