### ISSUE TITLE
help me setup binance pool its not working

### ISSUE THREAD

**Issue by vishalkadam472** [UnamSanctam/SilentXMRMiner#142]
I have been trying to do this but it's not working for me, it's still showing 0
have done the right way please check the below once 

pool : stratum+tcp://ethash.poolbinance.com:1800
wallet address  : 0x62347eaa2537abd742c2dcf83e46fbe3f7bdb8e1

**Comment by UnamSanctam** [comment]
Pool is: ethash.poolbinance.com:1800

**Comment by vishalkadam472** [comment]
I have tested with this one too but still it's zero

**Comment by UnamSanctam** [comment]
First of all use the pool: ethash.poolbinance.com:1800
Second of all, have you created a miner account? It says you haven't https://www.binance.com/en/support/faq/360040943132

**Comment by vishalkadam472** [comment]
Yes I have created an account, ![image](https://user-images.githubusercontent.com/63178414/113503026-00995000-954d-11eb-9199-4e6030ba70d3.png)

**Comment by UnamSanctam** [comment]
Yes then you should enter:
Pool: ethash.poolbinance.com:1800
Worker: nitrous.001
Password: 123456

**Comment by vishalkadam472** [comment]
Thanks for your help,
now I understand why it was not working
Now it's working perfectly fine

**Comment by vishalkadam472** [comment]
And one more thing I have observed, if I disable the application from startup program it's getting disabled even if I restart my system.

Can we hide from startup program too,
So that silent mining can run fully in background mode

**Comment by UnamSanctam** [comment]
No, it uses the Windows startup function to startup, there aren't really any other viable ways to do it since we can only really do what Windows allows us to do, the other ways to do it is to either add it into the Startup folder but that gets detected almost instantly or to add it into the task scheduler but that requires administrator permissions.

**Comment by vishalkadam472** [comment]
Yes I have added in task schedule and it's working thank you

**Comment by UnamSanctam** [comment]
Hey, in my new release I've firstly fixed a critical bug on some Windows systems but I've also added Task Scheduler into the startup. It will now use the Task Scheduler if the program is run with administrator permissions.
