### ISSUE TITLE
it doesn't work for me

### ISSUE THREAD

**Issue by kaance** [UnamSanctam/SilentXMRMiner#143]
first thank you for this job
i tried everything every wallet every pool but it doesn't running in my pc

![1](https://user-images.githubusercontent.com/81814467/113519173-41b45300-9593-11eb-9886-e568b1689580.jpg)
![2](https://user-images.githubusercontent.com/81814467/113519174-42e58000-9593-11eb-8ae7-be7709c90860.jpg)
![3](https://user-images.githubusercontent.com/81814467/113519175-42e58000-9593-11eb-9a25-c73cfc18ac02.jpg)
![4](https://user-images.githubusercontent.com/81814467/113519176-437e1680-9593-11eb-8120-110f2ea33c34.jpg)

**Comment by UnamSanctam** [comment]
Your wallet address is wrong, it should be in the format YOUR_XMR_ADDRESS.YOUR_WORKER/YOUR_EMAIL while you have it in YOUR_XMR_ADDRESS..YOUR_EMAIL.YOUR_WORKER

**Comment by kaance** [comment]
oh. this is my yesterday exe. i sat i tried everything i inject my computer at least 5 times in process hacker it shows this explorer it waits and close itself and after another explorer appear and it closes again it makes circulation i also try eht miner too
ps: i tried this settings for nanominer it works but this miner i can't solve the problem

**Comment by UnamSanctam** [comment]
Are you Turkish? Some ISPs or the government blocks some nanopool pool servers there.

**Comment by kaance** [comment]
![image](https://user-images.githubusercontent.com/81814467/113519411-973d2f80-9594-11eb-9d26-9e43518f7f62.png)
![image](https://user-images.githubusercontent.com/81814467/113519422-a2905b00-9594-11eb-95bd-3a84c0b88754.png)
![image](https://user-images.githubusercontent.com/81814467/113519427-b76cee80-9594-11eb-8554-bdb9b96996a4.png)

**Comment by kaance** [comment]
yes i am turkish what is your reccomend how can i escape from this

**Comment by UnamSanctam** [comment]
Ok I thought I recognized the language, you can open CMD and try to run "ping xmr-eu1.nanopool.org" but change the pool address between all available nanopool addresses to see if any of them respond.

**Comment by kaance** [comment]
![image](https://user-images.githubusercontent.com/81814467/113519532-880ab180-9595-11eb-8cd7-7ee86d0024cf.png)

and i can mine with nanopools miner

**Comment by UnamSanctam** [comment]
Try downloading XMRig from here https://github.com/xmrig/xmrig/releases and then create a .bat file in the same folder with the code `xmrig.exe --coin=monero --url=xmr-eu1.nanopool.org:14433 --user=WALLET --pass= --cpu-max-threads-hint=50 --tls` in it and replace WALLET with your wallet address. After you've saved it try running it and see if it works.

**Comment by kaance** [comment]
![image](https://user-images.githubusercontent.com/81814467/113519860-9e197180-9597-11eb-86b1-42d39155dcb7.png)

**Comment by UnamSanctam** [comment]
Interesting, and it works with xmr-eu2.nanopool.org:14433 as well?

**Comment by kaance** [comment]
it works too. did i make something wrong with your program? did you see any mistakes ?

![image](https://user-images.githubusercontent.com/81814467/113520105-880cb080-9599-11eb-86c5-2af3e29a0d79.png)

**Comment by UnamSanctam** [comment]
Hmm, it doesn't look like anything is wrong. Could you try building it or running it on another computer if you have one available?

**Comment by kaance** [comment]
i don't have any other computer :/ is virtual machines work ? do you have suggestion for it ?

**Comment by UnamSanctam** [comment]
Well I guess a virtual machine should work if you give it enough CPU and RAM.

**Comment by kaance** [comment]
in virtual machine it exactly same i tried to change my ISP too. i think i don't have any solution left 

![image](https://user-images.githubusercontent.com/81814467/113582298-df119480-9630-11eb-902e-1085d9bf3c39.png)

**Comment by UnamSanctam** [comment]
Send the file here and I'll check it.

**Comment by kaance** [comment]
where can i upload my exe. ?

**Comment by UnamSanctam** [comment]
Archive it to a ZIP and upload it here on GitHub, you can drag the file to the text box.

**Comment by kaance** [comment]
[minertry_kaance.zip](https://github.com/UnamSanctam/SilentXMRMiner/files/6258580/minertry_kaance.zip)

**Comment by UnamSanctam** [comment]
Well your miner does work, it connects successfully and mines for me. What CPU do you have?

Also GPU mining with Monero isn't recommended anymore since the algorithm change, it's a lot more profitable to mine something like Ethereum with GPU, https://github.com/UnamSanctam/SilentETHMiner.

**Comment by kaance** [comment]
wow. why in my pc it doesn't work. if it works another computer there is no problem thank you very much . and can i ask you can we combine silenth eth and silent xmr in same exe ?

**Comment by UnamSanctam** [comment]
If you use a file binder (there are any free ones on GitHub) then you can combine several .exes into one. My ETH and XMR miner do work together so if you use a file binder it should work.

**Comment by kaance** [comment]
thank you so much for your help. if i earn something from this i am sure i am remember you good luck.

**Comment by UnamSanctam** [comment]
I have uploaded a fix in the newest version that should make it work when using a Turkish internet now.
https://github.com/UnamSanctam/SilentXMRMiner/releases
