### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by Easy27** [UnamSanctam/SilentXMRMiner#147]
Hello,

First, I would like to say what you did, is great.
I'm new in this world and I need a bit of help..

I think I do everything right:
Disable the antivirus.
address: xmr.pool.minergate.com:45700my user and my user

In install I enable the flag and leave everything as it is, (enabling the idle in  mining)
After I lounch itI find in the regedit the services.exe running.
Now, I should have it running in the background but my CPU usage is 1%..
Do I have to download anything else or I'm ok with the miner builder?
Thanks for your help

**Comment by UnamSanctam** [comment]
So your pool is: xmr.pool.minergate.com:45700 and your wallet address/user is your MinerGate email address?

And how long is the 'Start Delay'? Services.exe is the injector that injects the miner into the process you chose (by default explorer.exe) after the chosen 'Start Delay'. And do you have 'Stealth' enabled? If you do it will pause if you have Task Manager, Process Explorer or Process Hacker open.

**Comment by Easy27** [comment]
Hello,

Yes, pool correct and email address.
delay is 30sec.
So, I build the miner and launch it, I see the services.exe in regedit.

**Comment by UnamSanctam** [comment]
If you use Process Hacker can you find the miners explorer.exe process? And do you have 'Stealth' enabled or not?

**Comment by Easy27** [comment]
![image](https://user-images.githubusercontent.com/81977767/113600736-babdb400-9640-11eb-8dfd-248b27210b0f.png)

yes, I can see it, in red, but the cpu still 1%, no, stealth is not enabled

**Comment by UnamSanctam** [comment]
Can you take a screenshot of the string that appears when you hover it?

**Comment by Easy27** [comment]
sure
![image](https://user-images.githubusercontent.com/81977767/113601047-24d65900-9641-11eb-97d7-651afdb52f0d.png)

**Comment by UnamSanctam** [comment]
Hmm weird, it looks alright but I can't really test it since MinerGate doesn't work for me. The issue before you had a similar problem but his file still worked for me, do you have access to another computer you can try it on or alternatively could you try another pool?

**Comment by Easy27** [comment]
it's working like below but not on minergate
![image](https://user-images.githubusercontent.com/81977767/113603511-56045880-9644-11eb-8773-2a8e68e2fba9.png)
What do I have to do to delete it?
Is enough to terminate the process and delete services in regedit?

**Comment by UnamSanctam** [comment]
Ok good, I've had many problems with MinerGate myself. To remove it first kill 'sihost64.exe' and then kill the miner process (explorer.exe) and then remove the regedit 'Services.exe' entry and it won't be able to start up again.

**Comment by Easy27** [comment]
ok thanks. Let me know if there's another way to use minergate, please

**Comment by UnamSanctam** [comment]
No problem, and well unfortunately the error is on their end so they'll have to do something about it. For me I cannot mine to MinerGate no matter what I use so I mainly stay away from it.
