### ISSUE TITLE
Not work. What wrong with it?

### ISSUE THREAD

**Issue by PXCorp** [UnamSanctam/SilentXMRMiner#150]
Can you open it on virtual machine and say what wrong with it please? https://drive.google.com/file/d/1zCc8mMy4jMiQd23ZkVifis37yfQHq1IU/view?usp=drivesdk

**Comment by UnamSanctam** [comment]
The file has been removed, ZIP it and drag it onto the reply box and it will be attached to your reply.

**Comment by PXCorp** [comment]
I cant ;(

**Comment by PXCorp** [comment]
> The file has been removed, ZIP it and drag it onto the reply box and it will be attached to your reply.

Im doing this on my phone bc computer is busy

**Comment by UnamSanctam** [comment]
Upload it to anonfiles.com or something then, alternatively just say the pool address, wallet address, password and SSL/TLS settings you used so I can see if anything is wrong.

**Comment by PXCorp** [comment]
It is momentally deleting when im trying to send it

**Comment by PXCorp** [comment]
[test.zip](https://github.com/UnamSanctam/SilentXMRMiner/files/6267108/test.zip)
....... Ok, im stupid you say ZIP im trying to send Rar.
Password 1234

**Comment by UnamSanctam** [comment]
The miner works fine, what is it that isn't supposed to be working?

**Comment by PXCorp** [comment]
> The miner works fine, what is it that isn't supposed to be working?

Because, google delete this file from google disc ;(
Sry
