### ISSUE TITLE
threats detected

### ISSUE THREAD

**Issue by twofacednine380** [UnamSanctam/SilentXMRMiner#151]
![CATTURA1](https://user-images.githubusercontent.com/68342746/113776078-cb962480-9729-11eb-9a55-4582ca7ecdfb.png)
![Cattura2](https://user-images.githubusercontent.com/68342746/113776093-cfc24200-9729-11eb-9f31-cb62438edeea.PNG)

Any advice? I tried also with a .NET Obf (Skater) but still detected (even on other devices).

**Comment by UnamSanctam** [comment]
Well the .NET Obfuscator didn't change enough of the code it seems.

**Comment by twofacednine380** [comment]
Could you tell me any .NET Obfuscator? I tried with ConfuserEX too, but same story

Thanks in advance for any further answer

**Comment by UnamSanctam** [comment]
Well here is a list of different .NET Obfuscators https://github.com/NotPrab/.NET-Obfuscator

What settings did you use in ConfuserEx?

**Comment by twofacednine380** [comment]
Preset "Maximum";
And i added any protection manually too;
If i send the file this is still detected.

And again, thanks for your time.

**Comment by UnamSanctam** [comment]
Yeah the obfuscator usually gets detected after a while, you can try any on that list, I'm usually not into that market so I don't know which ones are usually best (except things like .NET Reactor and those of course but those are hard to come by, at least for the latest versions)

**Comment by twofacednine380** [comment]
Ok, thanks;
Appreciated your help, I hope I'll figure it out with something.
