### ISSUE TITLE
Help For Crypte

### ISSUE THREAD

**Issue by DogusCyk** [UnamSanctam/SilentXMRMiner#152]
![image](https://user-images.githubusercontent.com/81167210/113854584-b1029080-97a7-11eb-87c2-157bca817bd2.png)
What Should I Open For Crypte

**Comment by PXCorp** [comment]
![Screenshot_2021-04-04-22-09-47-596_com android chrome](https://user-images.githubusercontent.com/81931207/113925483-bbe31280-97f3-11eb-9cf4-e1121fdb7621.png)
