### ISSUE TITLE
Not work

### ISSUE THREAD

**Issue by PXCorp** [UnamSanctam/SilentXMRMiner#153]
Working like 10-20 sec and then 1% of CPU. 3 hours of idle no shares idk why.
[.svchost.zip](https://github.com/UnamSanctam/SilentXMRMiner/files/6273777/default.svchost.zip)

**Comment by UnamSanctam** [comment]
Yeah, you have 'Stealth' enabled so opening Task Manager, Process Explorer or Process Hacker will pause the miner until you close it down.

**Comment by PXCorp** [comment]
> Yeah, you have 'Stealth' enabled so opening Task Manager, Process Explorer or Process Hacker will pause the miner until you close it down.
 
All of this are closed ;(

**Comment by UnamSanctam** [comment]
Build one without 'Stealth' so you can check if it uses any CPU.

**Comment by PXCorp** [comment]
> Build one without 'Stealth' so you can check if it uses any CPU.

Ok ill try, how to delete it btw?)

**Comment by UnamSanctam** [comment]
First stop the process called sihost64.exe and then the miner (by default explorer.exe) and then remove the miners startup entry in regedit at "HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Run".

**Comment by PXCorp** [comment]
> First stop the process called sihost64.exe and then the miner (by default explorer.exe) and then remove the miners startup entry in regedit at "HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Run".

K thx

**Comment by PXCorp** [comment]
Yeeeeessssssssssssssssssss it workkss thx
