### ISSUE TITLE
Workers

### ISSUE THREAD

**Issue by PXCorp** [UnamSanctam/SilentXMRMiner#155]
![IMG_20210409_143358](https://user-images.githubusercontent.com/81931207/114174152-e5f61b00-9940-11eb-91f6-05830ce90b8f.jpg)
So, i need to put my email in password(in miner)?
And then fill in in this(photo) blank?

Sry for my English ;) I hope you would be able to read and understand that.)

**Comment by PXCorp** [comment]
Its nanopool

**Comment by UnamSanctam** [comment]
To use an email on nanopool, enter it into the wallet address like this: YOUR_XMR_ADDRESS.YOUR_WORKER/YOUR_EMAIL for example 8BbApiMBHsPVKkLEP4rVbST6CnSb3LW2gXygngCi5MGiBuwAFh6bFEzT3UTufiCehFK7fNvAjs5Tv6BKYa6w8hwaSjnsg2N.Worker/fake@email.com

**Comment by PXCorp** [comment]
ohhh okkk Worker name or email yes? ok ill try

**Comment by UnamSanctam** [comment]
Yes you should use a worker name and email if you want to change the minimum payout. Although you do not need to to so on every miner, as long as the miner with the email and worker only gains 10 rating (mining 10 shares) you will be to change the payout so it's possible to mine 10 shares on only your own computer with the email and then use that as the password after mining 10 shares.

**Comment by PXCorp** [comment]
so i  need to do this:
483GxAuP24oaQUa4SvoxbDEJ2Nw21qmsvY7FdSpGxiQjVFwJrWsKbEnALRdNeMqJxCZkoHSggUzXzVPvd4SbdHaFEe9UHGF.pcworker/example@gmail.com
yes?

**Comment by PXCorp** [comment]
[test.zip](https://github.com/UnamSanctam/SilentXMRMiner/files/6286940/test.zip)

**Comment by UnamSanctam** [comment]
Yes that should be correct

**Comment by PXCorp** [comment]
ok thx
