### ISSUE TITLE
Off Topic

### ISSUE THREAD

**Issue by pepeonzima1337** [UnamSanctam/SilentXMRMiner#156]
Hi would you develop bitcoin silent CPU + GPU miner
I know using bitcoin silent miner wouldn't be a great Idea since it can be tracked.
But it is more profitable and interesting thing is I can't seem to find any good repos on Silent Bitcoin CPU+Gpu miner.
and If you are not going to make a miner
then How can I make one.

**Comment by UnamSanctam** [comment]
Well, Bitcoin mining isn't profitable at all, the only thing which is profitable to mine Bitcoin with is ASIC miners. That's probably why you aren't able to find any.
