### ISSUE TITLE
Don't working

### ISSUE THREAD

**Issue by paar2rnax** [UnamSanctam/SilentXMRMiner#158]
I create not silent and not installed build and start it and it doesn't work

**Comment by paar2rnax** [comment]
I use this settings
![image](https://user-images.githubusercontent.com/82118480/114216908-f75f1780-9980-11eb-93ae-fa18145d3775.png)
![image](https://user-images.githubusercontent.com/82118480/114216930-fded8f00-9980-11eb-87d0-13b636de704a.png)
![image](https://user-images.githubusercontent.com/82118480/114216947-0219ac80-9981-11eb-9c06-08faf0148355.png)
![image](https://user-images.githubusercontent.com/82118480/114216955-05149d00-9981-11eb-8e70-aa4f82f80755.png)
![image](https://user-images.githubusercontent.com/82118480/114216972-09d95100-9981-11eb-8688-50ba48e833ee.png)
![image](https://user-images.githubusercontent.com/82118480/114216983-0d6cd800-9981-11eb-9894-26bb7a87d5f8.png)

**Comment by paar2rnax** [comment]
and I don't have any task active

**Comment by UnamSanctam** [comment]
And the explorer.exe process it injects into is using no CPU?

**Comment by paar2rnax** [comment]
No it doesn't use CPU

**Comment by UnamSanctam** [comment]
Try another pool, firstly MinerGate is quite bad and if it's the same thing as before then the problem is on their side and they also steal your hashrate.

**Comment by paar2rnax** [comment]
what pool can you recommend?

**Comment by UnamSanctam** [comment]
Nanopool, MoneroOcean or Hashvault are usually good. Though nanopool is the only one I'm certain doesn't ban you for having over 100 miners without using something like xmrig-proxy.

**Comment by paar2rnax** [comment]
Bro I try to use nanopool but miner doesn't work
![image](https://user-images.githubusercontent.com/82118480/114219647-5eca9680-9984-11eb-82cb-e819f5e99c59.png)

**Comment by UnamSanctam** [comment]
Well, firstly try looking at the explorer.exe with Process Hacker instead, secondly it can take a while for a share to be submitted to the pool since they have quite a high share difficulty (but the profit will be the same), they can also take a while to update the page.

**Comment by paar2rnax** [comment]
Why your silent ETH miner work so good but monero doesn't work? What I'm doing wrong

**Comment by paar2rnax** [comment]
Ok I'm waiting 30 min and see the result

**Comment by paar2rnax** [comment]
![image](https://user-images.githubusercontent.com/82118480/114219999-de586580-9984-11eb-85e3-197d8b93afef.png)

**Comment by UnamSanctam** [comment]
Can you hover over the miners explorer.exe and it should show a long string and then screenshot that?

**Comment by paar2rnax** [comment]
![image](https://user-images.githubusercontent.com/82118480/114220560-9554e100-9985-11eb-8baf-ef404b960894.png)

**Comment by paar2rnax** [comment]
uhmmm I think I need to close this why it use minergate pool when I use nanopool

**Comment by UnamSanctam** [comment]
Yes you need to close it, it's probably left since you opened the last one.

**Comment by paar2rnax** [comment]
![image](https://user-images.githubusercontent.com/82118480/114220812-e6fd6b80-9985-11eb-98eb-7a7e742848be.png)
Okay I start it. Let's wait 10 minutes

**Comment by paar2rnax** [comment]
What is donate level 5?

**Comment by paar2rnax** [comment]
Yeah I think it work now cuz it use CPU
![image](https://user-images.githubusercontent.com/82118480/114220982-1ad89100-9986-11eb-8873-d66fc4c581aa.png)

**Comment by UnamSanctam** [comment]
That's the donate-level of the XMRig, it's set to 5% (5 minutes every 100 minutes) by default. And yes exactly since it's using CPU it's working and it should show up on nanopool after it's mined a bit and their site has updated.

**Comment by golxd** [comment]
don't know if nanopool has a limit on the number of miners? 200?  500? 1000?

**Comment by UnamSanctam** [comment]
> don't know if nanopool has a limit on the number of miners? 200? 500? 1000?

Not that I've seen or heard of, there is someone using my miner which has around 2200 miners from last time I heard from him and I believe he is mining directly to nanopool.

**Comment by golxd** [comment]
> Not that I've seen or heard of, there is someone using my miner which has around 2200 miners from last time I heard from him and I believe he is mining directly to nanopool.
understood, thanks, we will test) I just would not like to recruit a lot of miners and get banned)

**Comment by paar2rnax** [comment]
Thank you. Miner work great!!!
