### ISSUE TITLE
watchdog getected

### ISSUE THREAD

**Issue by Toxenskiy** [UnamSanctam/SilentXMRMiner#159]
Again the watchdog detects

**Comment by Toxenskiy** [comment]
even with crypt

**Comment by UnamSanctam** [comment]
You can crypt the watchdog now by enabling Custom Watchdog in the 'Advanced Options'.

**Comment by Toxenskiy** [comment]
So I mean it's still a detection

**Comment by Toxenskiy** [comment]
![image](https://user-images.githubusercontent.com/55586522/114265040-392aa500-99f7-11eb-972e-530f99a904d1.png)

**Comment by Toxenskiy** [comment]
![image](https://user-images.githubusercontent.com/55586522/114265271-88bda080-99f8-11eb-9c59-5d82735bbfd3.png)

**Comment by Toxenskiy** [comment]
The problem has been resolved. It turned out that you need to encrypt in different ways
