### ISSUE TITLE
If it will be deleted, will it reproduce itself?

### ISSUE THREAD

**Issue by switchy7** [UnamSanctam/SilentXMRMiner#16]
hello, if the miner will be deleted from the folder where it was installed, will it be auto-installed automatically or it will be deleted permenatly? and if it will not be deleted how to complete uninstall the miner?

**Comment by UnamSanctam** [comment]
Yes if you remove it from the installed folder it will be permanently removed.

**Comment by switchy7** [comment]
will it be seen in processor manager?  or when it will be injected in process like for example explorer.exe the Miners exe file will not be in the process manager? thank you

**Comment by UnamSanctam** [comment]
The original program can not be seen in any processor manager because it injects the miner code into for example explorer.exe and then closes down so it remains completely hidden.

**Comment by switchy7** [comment]
oh ok thanks for fast answer
