### ISSUE TITLE
smart screen detected

### ISSUE THREAD

**Issue by Toxenskiy** [UnamSanctam/SilentXMRMiner#161]
what to do?

**Comment by UnamSanctam** [comment]
That's how windows works, unless you register a company at Microsoft and get a certificate and then also increase the programs reputation it will always show that. All programs without Microsoft certificates do. https://docs.microsoft.com/da-dk/windows/win32/win_cert/windows-certification-portal?redirectedfrom=MSDN

**Comment by UnamSanctam** [comment]
SmartScreen is just a popup that warns users that the file hasn't been certified and can't be blindly trusted.
