### ISSUE TITLE
Crypt advice

### ISSUE THREAD

**Issue by Zile9** [UnamSanctam/SilentXMRMiner#166]
With what program should i crypt the miner and watchdog?

**Comment by UnamSanctam** [comment]
Try to use any .NET Obfuscator, either try https://github.com/mkaring/ConfuserEx or any from here https://github.com/NotPrab/.NET-Obfuscator

**Comment by Zile9** [comment]
What Crypter would you recommend if i dont want instalation through builder but rather through persistence and startup in crypter

**Comment by UnamSanctam** [comment]
Well, I don't know, I don't deal much with crypters so I don't know which ones are actual at the moment.
