### ISSUE TITLE
 did you mondark crypto through confuserex?

### ISSUE THREAD

**Issue by Toxenskiy** [UnamSanctam/SilentXMRMiner#167]

**Comment by Toxenskiy** [comment]
sihost64.exe detected new detect
![image](https://user-images.githubusercontent.com/55586522/114297105-72c2e500-9ab7-11eb-981b-e064e9cd1d0c.png)

**Comment by UnamSanctam** [comment]
Yes I obfuscated Mandark although not through ConfuserEx

**Comment by UnamSanctam** [comment]
And you can obfuscate the Watchdog as I said before if you want to decrease the detection

**Comment by Toxenskiy** [comment]
This is the obfuscated version. 
You can throw off the original Mondark, I myself want it crypting

**Comment by UnamSanctam** [comment]
This is the unobfuscated Mandark but the detection you sent don't have anything to do with that.
[Mandark.zip](https://github.com/UnamSanctam/SilentXMRMiner/files/6291882/Mandark.zip)

**Comment by Toxenskiy** [comment]
i know

**Comment by Toxenskiy** [comment]
obfuscated miner 
![image](https://user-images.githubusercontent.com/55586522/114306309-3c4f8f00-9ae4-11eb-9459-899e6600c384.png)

**Comment by UnamSanctam** [comment]
Is that from Windows Defender when you run the miner?

**Comment by Toxenskiy** [comment]
+

**Comment by Toxenskiy** [comment]
yea

**Comment by UnamSanctam** [comment]
Interesting

**Comment by Toxenskiy** [comment]
I think obfuscation is not enough, we still need to impose something

**Comment by UnamSanctam** [comment]
Can you try building a miner with this version (it's using the old injector) and see if you get the same detection?
[Silent XMR Miner Builder.zip](https://github.com/UnamSanctam/SilentXMRMiner/files/6291904/Silent.XMR.Miner.Builder.zip)

**Comment by Toxenskiy** [comment]
try. 
but first I want to try to impose a different defense

**Comment by UnamSanctam** [comment]
What kind of defense?

**Comment by Toxenskiy** [comment]
helped
![image](https://user-images.githubusercontent.com/55586522/114307228-69517100-9ae7-11eb-962f-97ec044219ff.png)

**Comment by UnamSanctam** [comment]
Did you do that on the Mandark?

**Comment by Toxenskiy** [comment]
not on the whole miner, Mondark I encrypted in order to make it unique, otherwise it’s not a fact that yours will not be killed

**Comment by UnamSanctam** [comment]
Yes obfuscating the miner should always be done but if you try building a miner with the latest file I sent does it still get detected as CoinMiner when you start it? Or when did it detect it as CoinMiner?

**Comment by Toxenskiy** [comment]
obfuscation works for 10 minutes, after 10 minutes it writes detection

**Comment by Toxenskiy** [comment]
the only thing that smartscreen complains about every launch

**Comment by UnamSanctam** [comment]
Yes that will always happen unless you get it certified from Microsoft which you can't really do https://docs.microsoft.com/en-us/windows/win32/win_cert/windows-certification-portal?redirectedfrom=MSDN

**Comment by Toxenskiy** [comment]
But it never happened before

**Comment by UnamSanctam** [comment]
That only happens on computers that have it on, I don't get any messages like that and most others don't either

**Comment by UnamSanctam** [comment]
Do you get the same message if you use [Silent XMR Miner Builder.zip](https://github.com/UnamSanctam/SilentXMRMiner/files/6291904/Silent.XMR.Miner.Builder.zip)?

**Comment by Toxenskiy** [comment]
ok try

**Comment by Toxenskiy** [comment]
to impose obfuscation? If so, at what level

**Comment by UnamSanctam** [comment]
Use any, I just want to see if you experience any difference when using the old injector (that builder has the old one).

**Comment by Toxenskiy** [comment]
well, it seems like there are no complaints from the antivirus, but this is only after launch

**Comment by Toxenskiy** [comment]
and how do injectors differ?

**Comment by UnamSanctam** [comment]
The code is a bit different, I wanted to upgrade it since I was worried that the injector was a bit unstable but maybe it works fine with the old one. So now I have to decide whether to use the old one or revert to the old one.

**Comment by Toxenskiy** [comment]
It would be cool if you did 2 versions, one uploaded in telegram and the other here.

**Comment by Toxenskiy** [comment]
So that there are not many detections straight.

**Comment by UnamSanctam** [comment]
Well the code will still be the same so the detections wouldn't differ too much since I don't have the time to change the entire code signature.

**Comment by Toxenskiy** [comment]
old injector detected

**Comment by Toxenskiy** [comment]
sihost64 detected last version obfuscated maximum
![image](https://user-images.githubusercontent.com/55586522/114309713-cf8ec180-9af0-11eb-843d-eb03920660cd.png)

**Comment by UnamSanctam** [comment]
Yeah, that's not the sihost64 getting detected but the obfuscator being detected

**Comment by UnamSanctam** [comment]
Some protections do get detected sometimes

**Comment by Toxenskiy** [comment]
I can't find a normal obfuscator in any way

**Comment by Toxenskiy** [comment]
Eziriz detected, confuserex detected

**Comment by UnamSanctam** [comment]
Yeah, obfuscators get detected after a while, sometimes it works by using less protections

**Comment by Toxenskiy** [comment]
you thought to make a config, just every time it takes a very long time to enter everything

**Comment by UnamSanctam** [comment]
Yeah, it's just that making a config will be a lot of code so I haven't had time yet.
