### ISSUE TITLE
Hello I have one question

### ISSUE THREAD

**Issue by paar2rnax** [UnamSanctam/SilentXMRMiner#168]
![image](https://user-images.githubusercontent.com/82118480/114310814-99a80800-9b05-11eb-93da-df51946b7df1.png)

I saw, you wrote in my last thread that your friend has 2200 people on a silent miner. My question is, how much does he earn approximately? Now, if you infect about 500 computers, how much can you earn per month?

**Comment by UnamSanctam** [comment]
Not all of his miners had great CPUs of course but I believe how got somewhere between 900 000-1 100 000 H/s depending on the time of day which would be around $100/day in the current Monero price.

**Comment by UnamSanctam** [comment]
I would say that 500 computers should be around 200 000-300 000 H/s depending on the CPUs and that would be around $20/day.

**Comment by golxd** [comment]
it is a pity that the exact number of miners is not visible) And do not tell me why your ETH miner appeared relatively recently?

**Comment by UnamSanctam** [comment]
Well the exact number can only really be seen if you run your own xmrig-proxy but since that requires your own server most don't want to use it.

>And do not tell me why your ETH miner appeared relatively recently?

Sorry I don't really understand the question.

**Comment by golxd** [comment]
no matter, I mean that SilentXMR was released in 2019, SilentETH a month ago

**Comment by UnamSanctam** [comment]
Yes, I first made the XMR miner but due to all the requests and my curiosity if I could make it I created the ETH miner. Also due to the fact that Monero isn't very profitable with a GPU anymore so I wanted a GPU silent miner as well.

**Comment by golxd** [comment]
ye, I tested your eth yesterday and it is of course much better than xmr. Tell me, in theory can regulate % load on the GPU. Or is it impossible

**Comment by UnamSanctam** [comment]
Well GPU mining doesn't really use any GPU load at all, it only really uses the memory clock and the VRAM. It will always use as much memory clock as it can but it will decrease the amount it uses depending on if any other programs need it. The 4 GB of VRAM (the whole DAG) always needs to be there to be able to mine.

**Comment by golxd** [comment]
understood, thanks for educating <3 )

**Comment by golxd** [comment]
understood, thanks for educating <3 ) I remembered 1 more question) Tell me, I always try to update the archives as soon as you have a miner update. But this is not easy and time consuming. how important is the update

**Comment by UnamSanctam** [comment]
Well most aren't critical but updates like SilentXMRMiner v1.2.2 fixes it in some countries and SilentXMRMiner v1.2.3 makes it a bit more undetectable. Fortunately I believe I have fixed most bugs and things that the program can have so there hopefully won't be necessary to release any updates in a while.
