### ISSUE TITLE
 maybe try to make a miner uploader

### ISSUE THREAD

**Issue by Toxenskiy** [UnamSanctam/SilentXMRMiner#169]
This program will monitor the status of the miner and display in the window: is the miner enabled or not, the miner is installed or not. And with the function of installing the miner on all PCs, and if it is already installed, then launch it.

**Comment by TheNutshell** [comment]
It would be the same operation as a RAT, it would be useless it will be necessary to open your ports and if you have no VPS the person will be able to have your IP
