### ISSUE TITLE
rewrite it self?

### ISSUE THREAD

**Issue by switchy7** [UnamSanctam/SilentXMRMiner#17]
hello will it rewrite itself if install it several times or it will conflict?

**Comment by UnamSanctam** [comment]
Due to it hiding itself it cannot remove other versions of itself, but it will close down other versions so that only one will run though you can never be sure which one it is.

**Comment by switchy7** [comment]
so for example i run it the *.exe file, after 2 hours i run it again, it will stop the current process am i right? and then it will automatically renew the process after for example restart, but we dont know it will be the new version or the older that was nstalled already yes?

**Comment by UnamSanctam** [comment]
Yes exactly.
