### ISSUE TITLE
So using confuser ex any recommended ways to spread anything helps thanks. 

### ISSUE THREAD

**Issue by woahdood** [UnamSanctam/SilentXMRMiner#170]

**Comment by woahdood** [comment]
??

**Comment by UnamSanctam** [comment]
Well I'm not a social engineer so my proficiency in it isn't that good but most people spread it using YouTube videos, mostly game cheats, program cracks or something similar.

**Comment by PXCorp** [comment]
> Well I'm not a social engineer so my proficiency in it isn't that good but most people spread it using YouTube videos, mostly game cheats, program cracks or something similar.

Or sending as a homework using email parser
