### ISSUE TITLE
After I restarted xmrig-proxy, I lost all my miners

### ISSUE THREAD

**Issue by zoubaba1997** [UnamSanctam/SilentXMRMiner#174]
Hello UnamSanctam, I haven't contacted you for a long time. I have a question. Yesterday I had about 3000 miners, but after I restarted xmrig-proxy this morning, it became 75. You can see the picture below, this is what happened
![c776b4e53fe7f08547860286ee6f556](https://user-images.githubusercontent.com/73113267/115014083-7524a500-9ee4-11eb-8264-1b20fba0a6b9.png)

**Comment by zoubaba1997** [comment]
I sent my miner to my server, and then gave the victim a downloader I wrote. It worked very well. Just this morning, after I restarted xmrig-proxy, all the miners disappeared. Did the watchdog appear problem

**Comment by UnamSanctam** [comment]
Hmm, there shouldn't be any problem. When exactly did the miners disappear, exactly after restarting xmrig-proxy? Since the miner will try to reconnect automatically for some time it should reconnect after a restart.

**Comment by ZephyrGT** [comment]
@zoubaba1997 hello which pool are you using?

**Comment by zoubaba1997** [comment]
> @ zoubaba1997你好，您正在使用哪个游泳池？

chinese pool,Not suitable for you

**Comment by ZephyrGT** [comment]
Why not suitable :)?
