### ISSUE TITLE
Is it possible to use it for mining doge?

### ISSUE THREAD

**Issue by near710** [UnamSanctam/SilentXMRMiner#175]
Hi! I wanna to know if it was possible to use it to mine dogecoin by modifying something, thanks ;)

**Comment by UnamSanctam** [comment]
No, mining Dogecoin won't even be very profitable just like Bitcoin due to it being mined by ASIC so mining it with a normal computer wouldn't earn you much.

**Comment by near710** [comment]
ok but if i want to do it anyway i can't use your program, correct?

**Comment by UnamSanctam** [comment]
No, Dogecoin uses the scrypt algorithm.
