### ISSUE TITLE
Works perfectly with nicehash?

### ISSUE THREAD

**Issue by LYZEN77** [UnamSanctam/SilentXMRMiner#176]
so I just started mining 3 days ago so i am TOTALLY new to this shi, mining bitcoin with nicehash right now, wanting a quick tutorial on how to configure this software and make it nicely functional with the nice framework, nicehash. since many of us out there are using nicehash, this is a MUST have.

**Comment by UnamSanctam** [comment]
I will answer this issue with the same answer. 
Well I don't think you're mining bitcoin but something else. Nicehash only converts for example Monero by selling your RandomX hashing power and they pay you in bitcoin.

Just use the RandomX nicehash pool and then enable 'Nicehash mining' in the options tab.

**Comment by LYZEN77** [comment]
that's exactly what i am doing. Tests on a win7 vm result in nothing but no cpu usage nor gpu and ofc i have the stealth option off so i can see if it actually works.

![image](https://user-images.githubusercontent.com/51676266/115094319-c5702700-9f25-11eb-98fe-b52b0204e3dc.png)

**Comment by LYZEN77** [comment]
@UnamSanctam it would be amazing if we can actually get the miner up and running with gpu mining too

**Comment by UnamSanctam** [comment]
Don't include the scheme like you're doing remove everything before daggerhashimoto. And that's the wrong pool for Monero (RandomX), that's the Ethereum pool.

**Comment by UnamSanctam** [comment]
You can see the pools here https://www.nicehash.com/algorithm, use randomxmonero.LOCATION.nicehash.com:3380 and replace LOCATION with the server location.

**Comment by LYZEN77** [comment]
dude it was js the wrong pic, was meant for the eth miner lol, ya sure it can work on win7? waited even more than 30 secs cuz of the start delay parameter set to 30, no avail. 
![image](https://user-images.githubusercontent.com/51676266/115094726-411ea380-9f27-11eb-8d87-d11e7d21a8ee.png)

**Comment by UnamSanctam** [comment]
Yes it works on Windows 7, which miner are you trying the XMR or the ETH? If the ETH what GPU do you have?

**Comment by LYZEN77** [comment]
no just the xmr miner with gpu mining off, just testing now so only enabling the cpu mining

**Comment by UnamSanctam** [comment]
What pool and wallet address did you enter?

**Comment by LYZEN77** [comment]
![image](https://user-images.githubusercontent.com/51676266/115094972-39abca00-9f28-11eb-92ff-83917f38f3a8.png)
and i got the address from the nicehash dashbord

**Comment by LYZEN77** [comment]
this is my discord if ya don't want this issue to turn into a newspaper
lyzen#2012

**Comment by UnamSanctam** [comment]
I think these are the locations servers and not 'eu':

- eu-north
- eu-west
- usa-west
- usa-east

**Comment by LYZEN77** [comment]
i ve seen the eu one working fine and it's way faster in terms of connectivity, it's working fine!

**Comment by UnamSanctam** [comment]
And you have enabled 'Nicehash Mining' in the 'Mining' tab?

**Comment by LYZEN77** [comment]
ima hand ya with details, a new rig has appeared in the dashboard, i can only see 33% cpu usage, it doesn't start at windows startup so after a reboot i have to run the executable again (how to get around this) and yes i have enabled that for sure

**Comment by UnamSanctam** [comment]
Did you enable 'Install'? That's how to make it start with Windows. How many cores does your CPU have? How much Max CPU did you set it to?

**Comment by LYZEN77** [comment]
the install one got me confused, ya should rename it to something more relatable to starting with windows startup, fixed the cpu thing by tweakin a vm setting, and ya the startup entry is there in the CurrentVersion\Run

**Comment by UnamSanctam** [comment]
Well I still have the names back from Lime-Miner so that's why it's called Install, you can hover the '?' next to options to see what they do and can also check the wiki https://github.com/UnamSanctam/SilentXMRMiner/wiki.

If it's there in the registry it should start with Windows.

**Comment by LYZEN77** [comment]
yea i know about the ? thing, this is goin to be a good start for my trip because of you! keep it up fam and i will be in touch in case anything happened or if any bugs showed.
