### ISSUE TITLE
remove the boundries!

### ISSUE THREAD

**Issue by LYZEN77** [UnamSanctam/SilentXMRMiner#179]
how can i get it to work with linux? so instead of compiling a windows exe it would do a bash one. Might need to rewrite it with python for example instead of vb, if it's really a long process, tell me if there is any shortcuts we can take out there

**Comment by UnamSanctam** [comment]
You would have to remake the entire injector and everything in sometime else. The injector uses Windows libraries to do everything: Copy Files, Add to Startup, Inject into process, Check permissions, Check running processes and more. You would have to in some way recreate https://github.com/UnamSanctam/SilentXMRMiner/blob/master/SilentXMRMiner/Resources/Program.cs (the injector) with Linux solutions for everything.

**Comment by UnamSanctam** [comment]
Also remember that things like startup with boot differs depending on the Linux distro (unless you try something with systemd maybe) and other things like that so you would have to do things with that in mind.

**Comment by LYZEN77** [comment]
since there is obviously no csharp->bash converter short answer is, **doing it is pain**
