### ISSUE TITLE
add config file with export/import function

### ISSUE THREAD

**Issue by LYZEN77** [UnamSanctam/SilentXMRMiner#180]

**Comment by UnamSanctam** [comment]
This has been an intended feature to add for quite a while but there is a lot of code to add to make it take save/load all the options which is why it hasn't been prioritized.

**Comment by shainodev** [comment]
> This has been an intended feature to add for quite a while but there is a lot of code to add to make it take save/load all the options which is why it hasn't been prioritized.

they have the source, why dont they just make it enabled from there? they can edit stuff and it will always stay the same.
u can also make the bools for it so its easier for them to change default settings.

**Comment by LYZEN77** [comment]
@UnamSanctam on a side not, i tested it on 
![Screenshot 2021-04-19 033318](https://user-images.githubusercontent.com/51676266/115236478-164d6e80-a124-11eb-8d15-44fc4624c3cf.jpg)
with only the crappy windows security enabled, the process got instantly terminated as soon as the executable starts, no matter if you run it as an admin or nah

**Comment by UnamSanctam** [comment]
Do you mean that the antivirus removed it? Windows Defender is actually one of the best antiviruses at the moment so you will have to obfuscate the miner to make it undetected since a lot of people use the miner and thus the code signatures get detected.

**Comment by LYZEN77** [comment]
the debugging feature is a godsent, some missing .net component, but the nicehash dashboard only reports mining, no speed whatever, it's destroying the cpu but wonder if it's actually working and how to make sure 
![image](https://user-images.githubusercontent.com/51676266/115237731-90322780-a125-11eb-8ddf-7a118f76bc6c.png)

**Comment by UnamSanctam** [comment]
Where should the hashrate be seen?

**Comment by LYZEN77** [comment]
all i see is 0 but you should click on the rig and it will hand you the details

**Comment by UnamSanctam** [comment]
How long have you been mining, and what CPU are you using?

**Comment by LYZEN77** [comment]
i love how sneaky, notice the curves when i open the tskmgr 
![image](https://user-images.githubusercontent.com/51676266/115239139-1602a280-a127-11eb-8120-cfe6659ac9d4.png)
15 mins or so

**Comment by UnamSanctam** [comment]
Haha yeah, since nicehash has quite a high difficulty (between 200 000-400 000) it can take a while to mine a share, especially with that CPU, I'm not sure what hashrate you get but lets say you have 200 H/s then mining a share with the average difficulty of 300 000 it would take around 300 000/200/60=25 minutes for a single share.
