### ISSUE TITLE
This is a question more than a issue

### ISSUE THREAD

**Issue by b3astxd** [UnamSanctam/SilentXMRMiner#181]
Since xmr miner uses cpu,and eth uses gpu,is it possible to use both of the silentminers in one PC?
and can you help me about how can I use a rat for using this miner.I don't want you to teach me one by one or something.It would
help me if you gave me a link about how to use this or the eth miner with a rat.

**Comment by UnamSanctam** [comment]
Yes you can use both of them at the same time. If you want to use them with a RAT depending on the RAT most of them have a file upload & execution function where you can select a file to upload and run on their computer and that is the function you should use.

**Comment by b3astxd** [comment]
thank you so much and I really appreciate how fast u replied.If I start earning someday,I'll definitely send u some xmr
