### ISSUE TITLE
rootkit question

### ISSUE THREAD

**Issue by LelouchViBri** [UnamSanctam/SilentXMRMiner#182]
hey, not really an issue, i'm just wondering if it's any good using r77 rootkit along with the miner, it makes no big different at the moment since it's injecting into a process and the process is still visible even with the rootkit

**Comment by UnamSanctam** [comment]
Well you could still hide the watchdog, all the files and registry entries in which case finding the injected process wouldn't matter since the watchdog would just start it again when closed down.

**Comment by Toxenskiy** [comment]
so there is a suggestion from oneinam1llion. And what is your priority at the moment.

**Comment by LelouchViBri** [comment]
> 
> 
> Well you could still hide the watchdog, all the files and registry entries in which case finding the injected process wouldn't matter since the watchdog would just start it again when closed down.

okay makes sense, thank you!
