### ISSUE TITLE
Well hello

### ISSUE THREAD

**Issue by ZephyrGT** [UnamSanctam/SilentXMRMiner#184]
This is my 2nd issue :D 
bro what is password for xmr-eu1.nanopool.org:14444 or nano pool do you know because its mining i open the debug no errors but cant see the hash rate

**Comment by UnamSanctam** [comment]
There is no password for nanopool, does it use any CPU?

**Comment by ZephyrGT** [comment]
Yes it's using 25% but i cant modify my min payout :D

**Comment by UnamSanctam** [comment]
Ahh, you can start a miner on your own computer (without 'Install' and everything like that) that has the wallet address as `YOUR_XMR_ADDRESS.YOUR_WORKER/YOUR_EMAIL` for example `8BbApiMBHsPVKkLEP4rVbST6CnSb3LW2gXygngCi5MGiBuwAFh6bFEzT3UTufiCehFK7fNvAjs5Tv6BKYa6w8hwaSjnsg2N.TestWorker/fake@email.com`. Then after you've mined 10 shares on your computer you can use fake@email.com as the password to change the minimum payout.

**Comment by ZephyrGT** [comment]
How to mke like that xd sorry i don't know much :(

**Comment by UnamSanctam** [comment]
Create a new miner build that has the pool xmr-eu1.nanopool.org:14444 and the wallet as `YOUR_WALLET.TestWorker/fake@email.com`. If you mine with this on your computer until it has mined 10 shares then you can use fake@email.com as the password to change the minimum payout.

**Comment by ZephyrGT** [comment]
Thanks :3
