### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Milk8** [UnamSanctam/SilentXMRMiner#187]
I build and run the file on my own pc, with none of the settings selected other than cpu mining, looking in task manager I 100% do not see the file running, im sure its a user error but I cant figure out why it simply will not work.

**Comment by UnamSanctam** [comment]
What settings in the 'Main' tab did you use? Keep in mind that the miner gets injected into the process you select in the main tab as well so you should look for that file (by default explorer.exe).

**Comment by Milk8** [comment]
Yea I injected into the default explorer.exe, I figured I could see the random thing taking a shit ton of my cpu in task manager never the less?

**Comment by UnamSanctam** [comment]
Yes, but are your connection settings correct?

**Comment by Milk8** [comment]
What do you mean by connection settings? My pool? or?

**Comment by UnamSanctam** [comment]
Yes are your pool, wallet and password settings correct for the pool you're trying to connect to?

**Comment by Milk8** [comment]
Yea its all correct, I pasted my pool and username from minergate, wouldnt I be able to see the process in task manager taking a ton of cpu usage anyways or no? Its also not saying there is a bot connected on minergate

**Comment by UnamSanctam** [comment]
Yes it should, keep in mind that MinerGate is quite tricky and doesn't always work. I can't really test it since MinerGate doesn't work for me no matter which miner or configuration I use though it does work for some people. From what I can see there seems to be something wrong with their severs or something like it. MinerGate does also steal your hashrate it you care about that.

**Comment by Milk8** [comment]
Alright then xD, what miner should I use them? Preferably one thats easy to use obviously

**Comment by UnamSanctam** [comment]
Well, no miner I've tried has worked with MinerGate but I usually use other pools like Nanopool, MoneroOcean or Hashvault. Keep in mind that of all pools it's only Nanopool that I'm sure of doesn't ban you for having a lot of miners unless you host your own xmrig-proxy. On my wiki: https://github.com/UnamSanctam/SilentXMRMiner/wiki all examples are with Nanopool if you want to try that.

**Comment by Milk8** [comment]
Is MineXMR.com reliable?

**Comment by Milk8** [comment]
Alright ill try that

**Comment by Milk8** [comment]
Its saying my address is invalid bc ive never mined before and all the tutorials online are for if your planning to mine on your own pc so its already mining to that wallet with the default nanopool miner, do you know how I can get my pool port without using the default miner they provide to use on ur own pc

**Comment by UnamSanctam** [comment]
The wallet will become 'valid' (if you mean that it says the account wasn't found) after you've mined a bit with the miner since then it will 'create' your account. Just use pool xmr-eu1.nanopool.org:14444 and your XMR wallet address as the wallet address and leave the password blank and it should work.

**Comment by Milk8** [comment]
I did that and built the file with the same default things and still see nothing happening in task manager, could it be an issue that im currently on a macbook with windows installed on it currently using windows? Pretty sure it uses the same parts as a normal default windows pc would

**Comment by Milk8** [comment]
No clue what I did, but made it as cmd.exe instead and now cmd is using all my cpu in task manager and in process hacker i sww it aswell, so I assume that its working for whatever reason now

**Comment by Milk8** [comment]
Would I need to crypt the file to stay safe if people get the file?

**Comment by Milk8** [comment]
Oh and is there anything I need to do on nanopool other than just wait till I have enough to withdraw money? I see theres a settings thing with email but it dosent work and idk if I need that or not? Also explorer does not work for me, only cmd does

**Comment by UnamSanctam** [comment]
Using an obfuscator would be preferable yes, you can read more here: https://github.com/UnamSanctam/SilentXMRMiner/wiki#how-can-i-decrease-detections

To change the minimum payout you can read the wallet address section of the wiki as well since I have given an example there.

Explorer should work, don't torget to kill any old miners that might be running as explorer.exe already. To do this you can use something like Process Hacker and search for --url in the top-right and all miners should show up.

**Comment by Milk8** [comment]
The explorer still does not work for whatever reason, is monero or ethereum generally better for mining? If they had a solid gpu would ethereum be far better than monero mining from a good cpu or no? Considering all pcs dont have gpus

**Comment by UnamSanctam** [comment]
Hmm weird, and you're sure that all miners are closed down? 

It's optimal to mine XMR with CPU and ETH with GPU at the same time since they are both designed to work together.

**Comment by Milk8** [comment]
Is it possible to bind both files together into one?

**Comment by UnamSanctam** [comment]
Yes you can use a file binder.

**Comment by Milk8** [comment]
And if the person does not have a gpu it would just only run the xmr one? Is it fine using the same process for both?

**Comment by UnamSanctam** [comment]
Yes, if no GPU is found the ETH miner will just close down while the XMR one keeps running. 

You can use the same process but using seperate ones can make it harder to find both.

**Comment by Milk8** [comment]
Alright ill do that, you know of any good binders?

**Comment by Milk8** [comment]
I used lime binder and it worked, you know if theres any way to make this us on windows ud? with any paid crypter or?

**Comment by UnamSanctam** [comment]
Well you can search 'file binder github' on Google for quite a lot of results but one user used 'Dream AIO' but I think you need to build the program from source yourself since it's an educational project.

**Comment by Milk8** [comment]
alright

**Comment by UnamSanctam** [comment]
You can use the same obfuscator in the link that I linked before to make it more undetected. https://github.com/UnamSanctam/SilentXMRMiner/wiki#how-can-i-decrease-detections

**Comment by Milk8** [comment]
I used that one and it only brought it down by like 1 on vt, I used confuser which I assume you know what that it brought it down by like 12 and only had 8 detections, I binded them and now that file gets 37 detections which is pretty bad, so binders increase the detection by a bunch I take it?

**Comment by Milk8** [comment]
Oh and this is fine for mining on a shit ton of pcs as it is with just one?

**Comment by UnamSanctam** [comment]
Well antiviruses consider binders as malware which is why detections go up, you can use ConfuserEx or .NET Reactor on the binded file as well to decrease it. If the pool and everything is correct then it will work on as many conputers as you want it to.

**Comment by Milk8** [comment]
If I try to do it with confuser it just says failed(With the binded file) before it worked with the single file though

**Comment by UnamSanctam** [comment]
Is the binded file a .NET file? If it is then it should work, try with other settings if it doesn't.
