### ISSUE TITLE
How much percent to silent?

### ISSUE THREAD

**Issue by paar2rnax** [UnamSanctam/SilentXMRMiner#190]
Hello, how much processor power needs to be set to really be silent? I think it need to set 40% and then 80% at idle 1 minute

**Comment by UnamSanctam** [comment]
Yes that should be fine, it's a bit less silent than 20% on higher end CPUs but is more profitable of course.

**Comment by paar2rnax** [comment]
And I have last question. I know that many guys can download your miner to many computers for money. 1000 installs cost about $ 100. If you make a paid crypt miner, will it pay off a lot? There are not exactly 1000 installations, but about 600-800.

**Comment by UnamSanctam** [comment]
Well, I'd say that 600-800 miners should be around 300 000-600 000 H/s depending on the computers (unless they're really really bad) which would be around $35-$75/day in the current Monero price. If I understand "make a paid crypt miner" correctly then to make it undetected I personally tried .NET Reactor which made it undetected to most antiviruses, either use some sort of obfuscator or like you said a paid crypter or something, I wrote more about it here: https://github.com/UnamSanctam/SilentETHMiner/wiki#how-can-i-decrease-detections

**Comment by paar2rnax** [comment]
Okay thank you!
