### ISSUE TITLE
How to crypt file with .net reactor?

### ISSUE THREAD

**Issue by paar2rnax** [UnamSanctam/SilentXMRMiner#191]
![image](https://user-images.githubusercontent.com/82118480/115618436-19a34e80-a30c-11eb-844c-cc3a81f68685.png)

**Comment by paar2rnax** [comment]
I can't find guide in youtube

**Comment by UnamSanctam** [comment]
Select the settings in the bottom box and then press 'Protect' on the left side. It will then create a folder in the same folder as the miner file with the name of the miner + _protected containing the obfuscated miner.

The default settings you can try initially are:
![.NET Reactor Settings](https://i.imgur.com/WzVTID8.png)
If it still gets detected then enable/disable some settings to see what works for you.
