### ISSUE TITLE
 donate does not work

### ISSUE THREAD

**Issue by Toxenskiy** [UnamSanctam/SilentXMRMiner#194]
why did I put donate at 99% but I don't care about mining

**Comment by UnamSanctam** [comment]
What? If I understand you correctly then donate-level can be set to a maximum of 5 (5%).

**Comment by Toxenskiy** [comment]
xmrig has no limits on this

**Comment by Toxenskiy** [comment]
default = 1
minimum = 1

**Comment by UnamSanctam** [comment]
Oh really? I haven't changed it, wierd...

**Comment by Toxenskiy** [comment]
well, in the original xmrig so

**Comment by Toxenskiy** [comment]
I don't have your sources

**Comment by UnamSanctam** [comment]
Ahhh, wait you're correct. I don't know if you used my older miner versions but back in the day I used the donate-level option to enable/disable other options in the miner, for example: donate-level=5 was how it enabled 'Idle Mining' and anything below that would disable 'Idle Mining' so I set the upper limit to 5 incase I was going to add more options but I didn't want to actually increase the donate to over 5% if you understand what I mean.

**Comment by UnamSanctam** [comment]
I didn't think anyone ever wanted to increase it over 5 so I forgot to change it back to the original.

**Comment by Toxenskiy** [comment]
I have a question why you ignore me when I ask for a suggestion

**Comment by UnamSanctam** [comment]
Which one?

**Comment by Toxenskiy** [comment]
it is unique in your repository

**Comment by UnamSanctam** [comment]
Ahh the one that is similar to oneinam1llion? I get so many messages that sometimes I forget if I've responded or not after reading if I have to think about it. That feature is intended to be added but I have to figure out a good solution for it, it also requires a lot of tests to see if it works.

**Comment by Toxenskiy** [comment]
is this a professional shutdown of virustotal for users who started the builder?
![image](https://user-images.githubusercontent.com/55586522/115660738-22644680-a345-11eb-9fa5-ce04b89c537e.png)

**Comment by UnamSanctam** [comment]
Yes, NYAN-CAT added it back in Lime-Miner project and it has stayed in the code since.

**Comment by Toxenskiy** [comment]
and it is not more logical to add it to build

**Comment by UnamSanctam** [comment]
Well, the antiviruses don't like it when you add things into the hosts file via code which is why it isn't in the miner, it also requires administrator permissions.

**Comment by Toxenskiy** [comment]
I'll try to do something similar to yours and start rewriting xmrig from scratch. your sources are not present, you can wish me luck;)

And as far as I remember, the miner itself is written in c ++

**Comment by UnamSanctam** [comment]
Yes you're correct, it's written in C++, good luck with the project

**Comment by Toxenskiy** [comment]
thanks

**Comment by Toxenskiy** [comment]
Can you tell me how to build xmrig

**Comment by UnamSanctam** [comment]
Here is the official guide for Windows: https://xmrig.com/docs/miner/build/windows

**Comment by Toxenskiy** [comment]
thanks

**Comment by PXCorp** [comment]
> thanks

Can i ask you? What's your hashrate?)

**Comment by LYZEN77** [comment]
> > thanks
> 
> Can i ask you? What's your hashrate?)

dontasktoask.com
