### ISSUE TITLE
Invalid Shares

### ISSUE THREAD

**Issue by TheNutshell** [UnamSanctam/SilentXMRMiner#196]
Hello i have a problem but i think i'm not only to have this. with the miner a get some invalid shares and the IP of miner is banned 30 hours on the pool, how i can solve that ?

**Comment by UnamSanctam** [comment]
How many invalid shares and which pool?

**Comment by TheNutshell** [comment]
24 it block my acc ( Minergate )

**Comment by TheNutshell** [comment]
then ?

**Comment by UnamSanctam** [comment]
Oh, well I've never had any good experiences with MinerGate but usually invalid shares have to do with a high ping or something like it.

**Comment by TheNutshell** [comment]
k i move to nanopool

**Comment by UnamSanctam** [comment]
Yeah try something else and see if something similar happens in case the problem has to do with MinerGate.
