### ISSUE TITLE
Stops working after a while

### ISSUE THREAD

**Issue by AndreiZdrali** [UnamSanctam/SilentXMRMiner#198]
I can infect them, but after a while (usually 2 days) they stop mining and appear offline. I have installer and stealth mode on. I know they didn't delete the miner.

**Comment by UnamSanctam** [comment]
Which pool? And how do you check whether they are online or not, XMRig-proxy?

**Comment by AndreiZdrali** [comment]
First I used MineXMR, but I now changed to nanopool and I still have the same problem. Each user has his own worker name so I can track them.

**Comment by UnamSanctam** [comment]
And you're sure that the miner is still on their computer? I have a few miners that have been running for a few months now so there shouldn't be any problem with the miner itself unless there is some kind of bug.

**Comment by AndreiZdrali** [comment]
Yes, it is still on their computers. After running the virus the original .exe can be deleted, right?

**Comment by UnamSanctam** [comment]
Yes

**Comment by AndreiZdrali** [comment]
Ok, thanks. I'll just try taking the steps from the documentation again and see if it works.
