### ISSUE TITLE
 what information is stored in WinRing

### ISSUE THREAD

**Issue by Toxenskiy** [UnamSanctam/SilentXMRMiner#199]

**Comment by UnamSanctam** [comment]
WinRing is XMRigs driver to access the MSR registers. https://xmrig.com/docs/miner/randomx-optimization-guide/msr

**Comment by Toxenskiy** [comment]
I checked the connections right now and noticed one on pastebin, what is it for?

**Comment by UnamSanctam** [comment]
It's partly for the dev fee and partly to test whether it works since I was planning on adding that to the miner (that you can choose a pastebin link instead of pool/wallet/etcetera and make it so that it gets all the connection settings from the pastebin instead every time the miner starts.).

**Comment by Toxenskiy** [comment]
and in what format should I specify? host: wallet?

**Comment by UnamSanctam** [comment]
Yeah `host:port;wallet` but it isn't fully functional yet

**Comment by Toxenskiy** [comment]
I will not hide, I was on your pastebin and you indicated two paths there, that is, stratum | ssl?

**Comment by UnamSanctam** [comment]
Yes exactly, I was experimenting how it would work since I'm not sure everyone can use SSL.

**Comment by Toxenskiy** [comment]
if I'm not mistaken | is this value or

**Comment by UnamSanctam** [comment]
Yes that is the value and I chose that to separate them since it's not used very often and thus won't cause any problems.
