### ISSUE TITLE
After restart users stop mining

### ISSUE THREAD

**Issue by SilviuZLDX** [UnamSanctam/SilentXMRMiner#200]
Hello! Thank you for your project! It is very good, however i have a bug or something that seems to happen to me i don t know why. When i infect someone the program works well, the user mines until he restarts his computer. I have install mode ON. Maybe because the save path is in temp ? Should i change it to AppData? Thanks again :)

**Comment by UnamSanctam** [comment]
Hmm, well it should work with temp just fine, you can try AppData if you want to but the miner uses the normal Windows startup mechanism to work so there shouldn't be much difference, though it does seem like on some computer when something is added to startup it is disabled by default. If you run the miner as administrator (if you can) then it will use the Task Scheduler instead which is more reliable.

**Comment by SilviuZLDX** [comment]
good to know, will try that. Also, how can i convert the builder to give me an kawpow miner? Do i just need to change parameters ?

**Comment by UnamSanctam** [comment]
In the 'Advanced Options' inside the 'Mining' tab you can activate 'Advanced Parameters' and add --algo=kawpow

**Comment by UnamSanctam** [comment]
Yep

**Comment by SilviuZLDX** [comment]
i will close the issue, again, thanks !!!!
