### ISSUE TITLE
How to change to kawpow

### ISSUE THREAD

**Issue by SilviuZLDX** [UnamSanctam/SilentXMRMiner#201]
Hello! It is me again sorry, tried to change to kawpow and seems to not work. 
Parameters : --algo=kawpow --asm=auto --cpu-memory-pool=1 --randomx-mode=auto --randomx-no-rdmsr  --cuda-bfactor-hint=12 --cuda-bsleep-hint=100

**Comment by UnamSanctam** [comment]
Is "GPU Mining" enabled?

**Comment by SilviuZLDX** [comment]
Yes sir

**Comment by UnamSanctam** [comment]
How are you checking whether it works or not?

**Comment by SilviuZLDX** [comment]
nanopool doesn t even create me an address

**Comment by UnamSanctam** [comment]
If you download and start Process Hacker and then find the miner process by searching for --url in the top right search bar and then double-clicking the process you should be able to see the GPU memory usage in the GPU tab.

**Comment by SilviuZLDX** [comment]
yeah you are right, it consumes 10MB

**Comment by UnamSanctam** [comment]
Hmm it should take a lot more, could you try running this I just compiled quickly that works for me to see if it just has something to do with the settings?
[TEST2.zip](https://github.com/UnamSanctam/SilentXMRMiner/files/6368117/TEST2.zip)

**Comment by SilviuZLDX** [comment]
yes sure

**Comment by SilviuZLDX** [comment]
i think it works, what settings did you use ?

**Comment by UnamSanctam** [comment]
Is it using any GPU memory?

I used these settings:
Pool: rvn-eu1.nanopool.org:12433
Wallet: Ravencoin wallet address

'CPU Mining': Off
'GPU Mining': On
'SSL/TLS': On

'Advanced Parameters': `--algo=kawpow --asm=auto --cpu-memory-pool=1 --randomx-mode=auto --randomx-no-rdmsr  --cuda-bfactor-hint=12 --cuda-bsleep-hint=100`

**Comment by SilviuZLDX** [comment]
i can continue monday if it is okay to you. Should i close the issue ?

**Comment by UnamSanctam** [comment]
Sure go ahead, see you then if needed

**Comment by SilviuZLDX** [comment]
good night
