### ISSUE TITLE
mondark detected

### ISSUE THREAD

**Issue by Toxenskiy** [UnamSanctam/SilentXMRMiner#202]

**Comment by Toxenskiy** [comment]
![image](https://user-images.githubusercontent.com/55586522/115927034-7ded1c00-a48c-11eb-8efc-cc454d705666.png)

**Comment by UnamSanctam** [comment]
When does it detect it? When running the miner?

**Comment by Toxenskiy** [comment]
when downloading sources

**Comment by UnamSanctam** [comment]
Oh, that doesn't matter, it won't affect the actual miner then.

**Comment by Toxenskiy** [comment]
why do you need necrobit

**Comment by UnamSanctam** [comment]
Oh, you don't, I meant that you only need the red options initially

**Comment by UnamSanctam** [comment]
You can also try to load the Example.nrproj project to get some example options I set before.

**Comment by Toxenskiy** [comment]
ahh ok
