### ISSUE TITLE
Not work!!!

### ISSUE THREAD

**Issue by alix1011** [UnamSanctam/SilentXMRMiner#203]
Hi, I have the same problem, I used different ports and turned off stealth, but after running Miner, it does not use the cpu.

Supportxmr.com:3333

Pls help me

**Comment by UnamSanctam** [comment]
Take a screenshot of your 'Main' tab settings.

**Comment by alix1011** [comment]
![Screenshot_20210424-100521_Microsoft Remote Desktop](https://user-images.githubusercontent.com/53878062/115948657-9db02e80-a4e4-11eb-81d1-bd4a885ebdf9.jpg)

**Comment by UnamSanctam** [comment]
Ahh you should use the pool: `pool.supportxmr.com:3333`

**Comment by alix1011** [comment]
Tnx bro❤

**Comment by alix1011** [comment]
My friend, I have a suggestion for the development of Miner, did you use Telegram Messenger?  If we can connect the miner to the Telegram bot in the next updates, it will be very good and we can control the minor and the system from the Telegram bot. Can you do this?

**Comment by UnamSanctam** [comment]
No I'm not really planning on creating a control panel at the moment. Most just use a RAT and then control the miner from there. The miner does have a built-in HTTP API that can technically be used but it's quite advanced to use and set up.

**Comment by alix1011** [comment]
![IMG_20210424_114218_773](https://user-images.githubusercontent.com/53878062/115950767-706a7d00-a4f2-11eb-8088-4d026fae3f89.jpg)

**Comment by alix1011** [comment]
My friend, if you can make the appearance and use of the miner like this miner in future updates, it will be very good because it is easier to configure and has a much better environment.

**Comment by alix1011** [comment]
My friend, if you can make the appearance and use of the miner like this miner in future updates, it will be very good because it is easier to configure and has a much better environment.

**Comment by UnamSanctam** [comment]
Well that miner has a lot less options than mine does so if I did it like that it would become very bloated and hard to differentiate between all the options on the screen.

**Comment by alix1011** [comment]
The miner environment is very tidy and beautiful, the applications of both are similar, and it was a suggestion.
