### ISSUE TITLE
Hello Freemine

### ISSUE THREAD

**Issue by Toxenskiy** [UnamSanctam/SilentXMRMiner#204]
This is also a way to store a pool / wallet

**Comment by UnamSanctam** [comment]
Are you having problems with a pool/wallet?

**Comment by Toxenskiy** [comment]
no, you just implemented one of my old ideas.

**Comment by UnamSanctam** [comment]
Ah, you mean the things we discussed in https://github.com/UnamSanctam/SilentXMRMiner/issues/199?

**Comment by Toxenskiy** [comment]
yea

**Comment by Toxenskiy** [comment]
188.120.xxx.239:xxxxx;RIG-2092|188.120.xxx.xxx:xxxxx;RIG-2093 true?

**Comment by UnamSanctam** [comment]
Yeah exactly, those are the dev addresses in the format we discussed in the other issue to test whether it works or not.

**Comment by Toxenskiy** [comment]
how did you crypto mondark

**Comment by Toxenskiy** [comment]
and could you throw off the original

**Comment by UnamSanctam** [comment]
With ConfuserEx or something but it doesn't matter if Mandark is detected or not since it's never directly exposed by the miner and thus the antiviruses don't really see it.
