### ISSUE TITLE
Crypt miner

### ISSUE THREAD

**Issue by alix1011** [UnamSanctam/SilentXMRMiner#205]
Hi my friend, I need a crypter for Miner because most AV know him, if you can think of a way.

**Comment by UnamSanctam** [comment]
You can find some on my wiki here: https://github.com/UnamSanctam/SilentXMRMiner/wiki#how-can-i-decrease-detections. .NET Reactor is usually really good.

**Comment by Toxenskiy** [comment]
on the contrary, confuserex works better for me

**Comment by Toxenskiy** [comment]
if I use the .net reactor there are a lot of detections and it’s not clear where and why

**Comment by UnamSanctam** [comment]
Yeah it depends on the settings you use, if you download the new version I replaced the old link on the wiki it should have an example project you can load for some settings that worked for me before.
