### ISSUE TITLE
Miner random name

### ISSUE THREAD

**Issue by som07338** [UnamSanctam/SilentXMRMiner#208]
Hello, I have a request to you or a proposal to implement the function of the random name of the miner so that each computer would have a random name on the pool when running.

**Comment by UnamSanctam** [comment]
Already exists, check here: https://github.com/UnamSanctam/SilentXMRMiner/wiki#wallet-addressuser. Keep in mind that most pools have a limit on the amount of workers that can exists (usually somewhere between 50-100 workers max).

**Comment by som07338** [comment]
Yes, I would like to know how to enable the random name of the miner, I will be very grateful for the details.

**Comment by UnamSanctam** [comment]
In that link I've written:
>The miner also supports dynamic worker names by using either {%RANDOM%} to generate a new random worker name every run or {%COMPUTERNAME%} to use the computers name as the worker name. Keep in mind though that most pools usually have a limit of between 50-100 worker names so do not use this feature if you plan to mine directly to a pool and have many miners.

So if you enter {%RANDOM%} as the worker name it will randomize the name on each run or if you use {%COMPUTERNAME%} as the worker name it will use the computer name.

**Comment by som07338** [comment]
Thanks for the clarification, can I donate somewhere for your work?

**Comment by UnamSanctam** [comment]
Sure, if you feel like it and have any crypto I have my addresses here https://github.com/UnamSanctam/SilentXMRMiner#donate

**Comment by alix1011** [comment]
One miner for all systems. Choose a worker name randomly.

Hi my friend, I have a suggestion, for each system separately to create a miner with a different worker name, it is difficult to build a miner with a different worker name each time, if in the new update, Miner can for each system that  It runs a name randomly or uses the IP system.  We compile a miner for all the targets that randomly select the worker name.  This is much better, please add this option as soon as possible. Thanks.

**Comment by UnamSanctam** [comment]
Read the replies over yours, that feature already exists.

**Comment by alix1011** [comment]
That is, if we leave the password blank, the miner randomly chooses the worker's name?

**Comment by UnamSanctam** [comment]
No if you enter {%RANDOM%} as the worker name it will randomize the name on each run or if you use {%COMPUTERNAME%} as the worker name it will use the computers name (which is usually different for each computer).

**Comment by alix1011** [comment]
Thanks for everything.  Should this be exact ??

{%RANDOM%}   ???

**Comment by UnamSanctam** [comment]
Yes
