### ISSUE TITLE
Miner run to all user !!!

### ISSUE THREAD

**Issue by alix1011** [UnamSanctam/SilentXMRMiner#209]
My friend, I checked the miner, and with the administrator's access, I ran it and realized that there was a problem, that if the user blocks the miner, the miner will no longer run on other users.  Please fix this problem quickly.

**Comment by UnamSanctam** [comment]
Blocks in what way? You mean disable it in the Task Scheduler?

**Comment by alix1011** [comment]
If one of the users singout to us from within the Task Manager, Miner or User, Miner will no longer run on other users.

**Comment by alix1011** [comment]
When we run the miner, if the user we ran the miner on is deleted, the miner should automatically run on the other user.

**Comment by alix1011** [comment]
Do you understand what I mean?

**Comment by UnamSanctam** [comment]
Well kind of I think. But if the user is removed the miner file would disappear as well since it's saved in the user profile.

**Comment by alix1011** [comment]
That means it can not be hidden from other users ??  Automatically run on another user when one user is deleted?

**Comment by UnamSanctam** [comment]
Well it won't be able to run on another user if the user where the miner was 'Installed' is removed since all the files for the user would also be removed.

**Comment by alix1011** [comment]
Hello my friend, is it possible to mine other currencies in different pools with this miner ???

**Comment by UnamSanctam** [comment]
Yes, you can mine all currencies that use any of these algorithms: https://xmrig.com/docs/algorithms, to change the algorithm open 'Advanced Options' and enable 'Advanced Parameters' there you can replace `--coin=monero` with `--algo=THEALGOYOUWANT`

**Comment by alix1011** [comment]
Are algorithms auto-tuning?  Or should they be adjusted ??

**Comment by UnamSanctam** [comment]
Select the algorithm that the coin you want to mine uses, sometimes the pool tells the miner which one to use but it's always better to select it yourself.

**Comment by alix1011** [comment]
That is, can it be set from the "advance option"?  What do you think is the best currency to extract?

**Comment by UnamSanctam** [comment]
Personally I think Monero since it's the most stable one, but Ravencoin comes second but it's a GPU only coin so mining Ethereum is still the most profitable at the moment.

**Comment by alix1011** [comment]
thanks bro.  What is the best algorithm for extraction?

**Comment by UnamSanctam** [comment]
For Monero? Monero only uses the RandomX algorithm and nothing else and it's set to use that in the miner by default. There are technically things like algorithm switching that MoneroOcean does where it mines different coins depending on the profitability and then pays you in Monero but I haven't added support for it since for me it freezes my computer for a couple of seconds.

**Comment by alix1011** [comment]
Thank you for all the help you have given me, I will thank you.

**Comment by alix1011** [comment]
Hi brother, how can I encrypt the program so that it is not decomposed and they do not have access to the source ??

**Comment by UnamSanctam** [comment]
https://github.com/UnamSanctam/SilentXMRMiner/wiki#how-can-i-decrease-detections

**Comment by alix1011** [comment]
How can the source code of the program be kept secret ??.  I want to use the output I got but I do not want others to be able to access its source.

**Comment by UnamSanctam** [comment]
Use one of the obfuscators in the link I sent: https://github.com/UnamSanctam/SilentXMRMiner/wiki#how-can-i-decrease-detections, obfuscating the source to make it harder to read is what obfuscators do. Though keep in mind that if done by a professional the source can always eventually be understood no matter what.

**Comment by alix1011** [comment]
That is, in no way can decompile be resisted?

**Comment by UnamSanctam** [comment]
Anyone proficient enough can reverse engineer any program, obfuscators make it harder and more time consuming to do so though.

**Comment by alix1011** [comment]
Thanks, I will try my best anyway.

**Comment by alix1011** [comment]
Hi my friend, I want to mine another digital currency, but how do I change the 'advanced option', for example for Tron or Turtlcoin?

**Comment by alix1011** [comment]
If you can send me the "advanced option" configuration of these two digital currencies (Tron and Turtle), thank you

**Comment by UnamSanctam** [comment]
First check what algorithm they use, for example I believe TurtleCoin uses the "argon2/chukwav2" algorithm so to make it mine TurtleCoin just replace `--coin=monero` so that it becomes `--algo=argon2/chukwav2`. So this would be `--algo=argon2/chukwav2 --asm=auto --cpu-memory-pool=1 --randomx-mode=auto --randomx-no-rdmsr  --cuda-bfactor-hint=12 --cuda-bsleep-hint=100` in the Advanced Options.

**Comment by alix1011** [comment]
Thanks, I mean put this config?

**Comment by UnamSanctam** [comment]
Yes, enter `--algo=argon2/chukwav2 --asm=auto --cpu-memory-pool=1 --randomx-mode=auto --randomx-no-rdmsr --cuda-bfactor-hint=12 --cuda-bsleep-hint=100` into the 'Advanced Parameters' field and it should mine the `argon2/chukwav2` algorithm which I believe TurtleCoin uses.

**Comment by alix1011** [comment]
Thanks, is it good for mine (Turtle or Tron)?

**Comment by UnamSanctam** [comment]
I don't know which algorithm TRONIX uses and couldn't really find it anywhere reliable, you would have to find which one it uses and see if it's supported here: https://xmrig.com/docs/algorithms and the change the `--algo=` to the correct one.

**Comment by alix1011** [comment]
Thanks bro, does that mean for every digital currency I just have to put its algorithm in the "advanced option" and do not need to make any general changes?

**Comment by UnamSanctam** [comment]
Yes that should be all that's needed (also don't forget to mine to a pool that supports that cryptocurrency).

**Comment by alix1011** [comment]
My friend, is the update for Miner close ??  When do you update ??  What new options does it have ???

**Comment by UnamSanctam** [comment]
Well there seems to be a new issue, seems like Windows Defender has started just flatly detecting the code piece `Assembly.Load` as malware and that is what is used to load the injector DLL so I have to find some workaround now.

**Comment by alix1011** [comment]
Ohh what a bad problem !!!  Can you encrypt the source and program so that it is not detected?

**Comment by UnamSanctam** [comment]
No not on the newer Windows Defender it seems like from what I've tested since `Assembly.Load` is a function that it can just detect on a lower level (since C# uses the .NET Framework which is a sort of API for lower level languages). I have been trying a few different things which have been differently successful but I'm still trying to find a way.

**Comment by alix1011** [comment]
My friend, I need your guidance, which of the low-cost digital currencies (turtle, Tron, bittorent, etc.) has the best profit for mine ???

**Comment by UnamSanctam** [comment]
Well, it depends on which coin you think is going to do best in the future incase you intend to save them.

**Comment by alix1011** [comment]
What do you suggest?

**Comment by alix1011** [comment]
My friend, what currency do you suggest ?????

**Comment by UnamSanctam** [comment]
Well I don't keep up with any of those projects, I just mine Monero.

**Comment by alix1011** [comment]
Hi my friend, the advance option configuration for turtlecoin did not work properly, it has a problem, it does not mine,

**Comment by UnamSanctam** [comment]
It works properly for me, are your pool and wallet settings correct?

**Comment by alix1011** [comment]
![Uploading Screenshot_20210505-120255_Microsoft Remote Desktop.jpg…]()

**Comment by alix1011** [comment]
![Screenshot_20210505-120255_Microsoft Remote Desktop](https://user-images.githubusercontent.com/53878062/117109490-ff508280-ad99-11eb-8fcc-38f5a3d93dfa.jpg)

**Comment by alix1011** [comment]
is it correct?

**Comment by alix1011** [comment]
and advanced option 
--algo=argon2/chukwav2 --asm=auto --cpu-memory-pool=1 --randomx-mode=auto --randomx-no-rdmsr --cuda-bfactor-hint=12 --cuda-bsleep-hint=100

**Comment by UnamSanctam** [comment]
That looks correct and just tried with those settings and it works for me. Does it not use any CPU?

**Comment by alix1011** [comment]
No, it does not use any CPU!

**Comment by UnamSanctam** [comment]
Send the miner here and I'll check the the one you built.

**Comment by alix1011** [comment]
My friend, I understand the problem!  , Miner Turtle can not be activated at the same time as Miner Monroe !!  , The only problem now is that I can not remove Miner Monroe, please prepare the Miner cleaner program sooner, both miners can not be enabled at the same time.

**Comment by UnamSanctam** [comment]
Yes, if they're injected into the same process then the miner won't open since it's not supposed to since only one miner should be open at once. Even when the miner remover option comes in the next version it can't remove old versions of course since all miner builds are different so it won't know what the miner name of your old miners are and thus it can't remove them.

**Comment by alix1011** [comment]
My friend, the new update is an amazing update !!  , I am waiting for a new update with new options and more power and better quality.  I hope you are successful and I want a great update from Miner in the near future.

**Comment by alix1011** [comment]
My friend, the new update is an amazing update !!  , I am waiting for a new update with new options and more power and better quality.  I hope you are successful and I want a great update from Miner in the near future.

**Comment by UnamSanctam** [comment]
A new update has now been released with quite a few improvements and additions: https://github.com/UnamSanctam/SilentXMRMiner/releases
