### ISSUE TITLE
Is this hiddin in task manager?

### ISSUE THREAD

**Issue by 1Legend11** [UnamSanctam/SilentXMRMiner#21]
If this is running will it show up in task manager?

**Comment by UnamSanctam** [comment]
It will show up as the program you chose to inject it into, default explorer.exe. It will not show the original file.

**Comment by 1Legend11** [comment]
ok. also it autostarts when pc turns on right?

**Comment by UnamSanctam** [comment]
If you enable "Install" when creating the miner.
