### ISSUE TITLE
Worker name》 IP System

### ISSUE THREAD

**Issue by alix1011** [UnamSanctam/SilentXMRMiner#210]
Hello my friend, in the new Miner update, the worker name is automatically the IP of the operating system.

**Comment by UnamSanctam** [comment]
Well the problem with using the IP as a worker name is that many pools don't accept dots (.) so the IP addresses would be combined into one number (like 1237813872) so it wouldn't be much different from the random or computer name options but I can add it if you feel like it's better.

**Comment by alix1011** [comment]
Not the same name is better, thanks for your explanation
