### ISSUE TITLE
Hello i got questions about proxy

### ISSUE THREAD

**Issue by ZephyrGT** [UnamSanctam/SilentXMRMiner#214]
1-How to setup it.
2-A mining pool better or proxy?
3-How can we connect hidden miner to proxy
4-Can you suggest best rdp? (Cheap)

**Comment by UnamSanctam** [comment]
1. Just download xmrig-proxy and edit the config.json, there isn't much you have to change to make it work. Just change the "bind" part to the port you want and change the "pools" to the pool you want to connect to.

2. A proxy is generally better.
 
3. Yes just connect to it like a normal pool but use the proxyip and port (proxyip:port) as the pool address.

4. I don't really keep up with that market so I don't know which ones are legit and who's best.

**Comment by ZephyrGT** [comment]
1-How much users can Nanopool hold? Till ban
2-Is there any other pool like nanopool? Not bans user when have 10k+ users :D

**Comment by ZephyrGT** [comment]
And is there is any chance to lose miners on proxy? Bc i saw someone that lose 3k+ on proxy in issues

**Comment by ZephyrGT** [comment]
Btw new update coming :)?

**Comment by UnamSanctam** [comment]
1. I have never heard of or seen a limit.

2. Not that I'm sure of.

3. No, his just got disconnected temporarily I guess, they should be back since he's still making other issues.

4. New update is coming along but there's a lot of code to change and I also update the ETH miner at the same time and I have a lot of real life work so that makes it take a while.

**Comment by ZephyrGT** [comment]
Nice how old are you xd?

**Comment by UnamSanctam** [comment]
I'm 22 now.

**Comment by ZephyrGT** [comment]
Wew...

**Comment by ZephyrGT** [comment]
Btw i was about to format my pc and i send u xmr did u recieve

**Comment by ZephyrGT** [comment]
I was about to lose them but its better to send someone that deserves it ;)

**Comment by ZephyrGT** [comment]
Its like ? 15.8$ i think 🤔 i just mined it and can't extract to my btc because so small xd

**Comment by UnamSanctam** [comment]
Yeah I got them, thank you very much friend I appreciate it

**Comment by ZephyrGT** [comment]
Np :)👌
