### ISSUE TITLE
Issue with Nanopool

### ISSUE THREAD

**Issue by gamethrower** [UnamSanctam/SilentXMRMiner#216]
So I'm testing miner on my PC. Mining Monero RandomX algo on Nanopool. The thing is statistics show up with a huge delay like a few hours and it shows i mined only 16 shares (After several hours of mining). I tried it multiple times and it always show me 16 shares with a huge delay and nothing more.

When I tried using Minergate cryptonight Monero my miner showed up in a minute and instantly got a few shares. After five minutes on Minergate I have over 30 good shares. Yeah I have a crappy CPU but why is it always stuck on 16 shares?

Edit. Now I notice that Minergate sends RandomX jobs even tho I used **-a cryptonight**.

**Comment by gamethrower** [comment]
Also the payout method I'm using on Minergate is PPS and Nanopool is PPLNS. Is this the problem?

**Comment by UnamSanctam** [comment]
Yeah Nanopool has quite a delay but the amount of shares don't directly correlate with hashrate or mining speed. The amount a share is worth depends on the share difficulty of the jobs sent by the pool. Nanopool has a fixed 400 000 share difficulty while MinerGate has a dynamic difficulty that starts with 1000 meaning that one Nanopool share is worth the same amount as 400 starter MinerGate shares. It should be using RandomX since that is the only algorithm used by Monero but I believe MinerGate just hasn't updated anything since the algorithm change in the beginning 2020.

**Comment by gamethrower** [comment]
> 
> 
> Yeah Nanopool has quite a delay but the amount of shares don't directly correlate with hashrate or mining speed. The amount a share is worth depends on the share difficulty of the jobs sent by the pool. Nanopool has a fixed 480 000 share difficulty while MinerGate has a dynamic difficulty that starts with 1000 meaning that one Nanopool share is worth the same amount as 480 starter MinerGate shares. It should be using RandomX since that is the only algorithm used by Monero but I believe MinerGate just hasn't updated anything since the algorithm change in the beginning 2020.

But why do I only get 16 shares?

**Comment by UnamSanctam** [comment]
Look at the hashrate and not the shares, since Nanopool has a fixed difficulty of 480 000 then mining one share with 1000 H/s would take 480000/1000/60=8 minutes on average but it would be worth more than a share with lower difficulty.

**Comment by gamethrower** [comment]
> 
> 
> Look at the hashrate and not the shares, since Nanopool has a fixed difficulty of 480 000 then mining one share with 1000 H/s would take 480000/1000/60=8 minutes on average but it would be worth more than a share with lower difficulty.

Hashrate that it show is wrong. It claim that my hashrate is ~800H/s when in reality its ~60H/s.

**Comment by UnamSanctam** [comment]
You should check the average hashrate over 6 hours on both of them to be able to see the difference clearly due to the luck based nature of mining.

**Comment by gamethrower** [comment]
> 
> 
> You should check the average hashrate over 1/2/3/6 hours on both of them to be able to see the difference clearly due to the luck based nature of mining.

Aight, thank you for response. 
Also is it true that Minergate shaves the hashrate or is it the effect of lags. What is your opinion?

**Comment by UnamSanctam** [comment]
There has been enough tests in my opinion to ascertain that they do steal hashrate. The XMRig devs also warn you to not use MinerGate for that reason.

**Comment by gamethrower** [comment]
> 
> 
> There has been enough tests in my opinion to ascertain that they do steal hashrate. The XMRig devs also warn you to not use MinerGate for that reason.

I thought everyone warns not to use Minergate due to decentralization purposes.
Another question. I made some modifications in XMRIG and compiled it. Some **.lib** file popped up in the release directory.
![Снимок](https://user-images.githubusercontent.com/46888050/116122513-8d59a880-a6ca-11eb-9fc6-4756cd1b9913.PNG)
Why is it here and is it necessary like WinRing?

**Comment by UnamSanctam** [comment]
That is also one reason, and no it's not necessary, those are just libraries that get built together with XMRig.
