### ISSUE TITLE
[SUGGESTION] Smart CPU Usage

### ISSUE THREAD

**Issue by Rafo124** [UnamSanctam/SilentXMRMiner#217]
Is there a possibility for a Smart CPU Usage feature? This would basically use all idle cores of the CPU instead of a fixed amount

Edit: or maybe you can set a fixed amount that will be used as a minimum amount and if there are more cores idle it will also use those extra

**Comment by UnamSanctam** [comment]
If you put it at 100% it will use all idle cores.

**Comment by Rafo124** [comment]
> If you put it at 100% it will use all idle cores.

Thanks for replying. I have an off topic question: I created a miner in v1.2.3 and enabled watchdog but after a few seconds it created 4-5 explorer.exe processes which all mine and make the computer very slow and not responsive

**Comment by UnamSanctam** [comment]
Well maybe, the miner shouldn't start another one if there is already another miner started. Try removing all the old ones by killing their processes and removing their files and try starting it again.

**Comment by Rafo124** [comment]
Thanks I will try that and hopefully it works
