### ISSUE TITLE
Not works

### ISSUE THREAD

**Issue by 0x069** [UnamSanctam/SilentXMRMiner#218]
i dont why that dont works

https://banned.host/uploads/66baf3d5-1e2e-440b-a8b0-3fd901f8fe41/PIRh85te.gif

**Comment by 0x069** [comment]
https://banned.host/uploads/66baf3d5-1e2e-440b-a8b0-3fd901f8fe41/C0Kp87vy.png

**Comment by UnamSanctam** [comment]
Try setting a password (worker name), I'm pretty sure SupportXMR requires one.

**Comment by 0x069** [comment]
thanks it works!!!
