### ISSUE TITLE
Hello bro i got a issue with nanopool

### ISSUE THREAD

**Issue by ZephyrGT** [UnamSanctam/SilentXMRMiner#219]
I got 16 hash each miner and 840 h/s is it a display problem ? thanks :)

**Comment by UnamSanctam** [comment]
What do you mean by "16 hash"?

**Comment by ZephyrGT** [comment]
16 shares sorry

**Comment by UnamSanctam** [comment]
Well, do you mean that it should be higher or lower? Hashrate on pools are just the amount of shares over time, if you have 16 shares and 840 H/s then that means that each share is calculated as 52,5 H/s  so if you would have 32 shares it would be 1680 H/s total. You can also read an issue I had yesterday here: https://github.com/UnamSanctam/SilentXMRMiner/issues/216

**Comment by ZephyrGT** [comment]
this is what i dont understand its same for every miner

**Comment by UnamSanctam** [comment]
Yeah, what's the problem?

**Comment by ZephyrGT** [comment]
lol the power of the miners are same for all computers isnt it problem xd

**Comment by UnamSanctam** [comment]
Well you should check the average over 1/2/3/6 hours to get the real hashrate.

**Comment by ZephyrGT** [comment]
okay :d
