### ISSUE TITLE
Xmrig-proxy 

### ISSUE THREAD

**Issue by codexprime** [UnamSanctam/SilentXMRMiner#22]
Hello, how to properly configure to use xmrig-proxy ?

**Comment by UnamSanctam** [comment]
There are many tutorials on YouTube on how to set it up, then only enable Nicehash mining in the miner and it'll work.

**Comment by codexprime** [comment]
Sorry, I didn't put the question correctly
it's all about the translator)

when I try to specify a dns proxy instead of a pool, I get an error message

how to set up a miner to work on a proxy? if the miner asks to enter the address directly into the pool

**Comment by codexprime** [comment]
Sorry, I didn't put the question correctly
it's all about the translator)

when I try to specify a dns proxy instead of a pool, I get an error message

how to set up a miner to work on a proxy? if the miner asks to enter the address directly into the pool

**Comment by UnamSanctam** [comment]
Just input the DNS proxy and port instead of the pool and it should work, what error do you get?

**Comment by codexprime** [comment]
in the pool field I enter data from the proxy in the format dns:port
I leave the wallet address and password field blank

when trying to build a build, it displays: Please enter valid pool settings

**Comment by UnamSanctam** [comment]
Enter your wallet address as well.

**Comment by codexprime** [comment]
if you change the wallet address in the proxy settings
will this affect the miner's performance?
in the build of which, let's say the old address is specified

**Comment by codexprime** [comment]
please add iplogger in the new assembly
it will be very good

thanks for the advice
after specifying dns and address
build was created

**Comment by UnamSanctam** [comment]
Great that it works.

If you have set the --user=WALLET_ADDRESS in your xmrig-proxy then it will use that address instead of the one you entered into the miner so it won't affect old builds.

Adding an IP logger wouldn't make much sense since normally the miner only ever connects to the pool and nothing else but if you use xmrig-proxy I believe you can use the --access-log-file=N parameter to log all access to the proxy.

**Comment by codexprime** [comment]
Thank you so much!
