### ISSUE TITLE
Can You Add File Binder

### ISSUE THREAD

**Issue by DogusCyk** [UnamSanctam/SilentXMRMiner#221]
Can You Add File Binder On Latest Version

**Comment by DogusCyk** [comment]
rip english 🤣

**Comment by DogusCyk** [comment]
When You Update Can Add File Binder Too ?

**Comment by UnamSanctam** [comment]
Well I was thinking of making a separate file binder program since then it would be possible to run a Windows Defender "killer" before the miner.

**Comment by DogusCyk** [comment]
Okey Thanks

**Comment by Toxenskiy** [comment]
and how do you plan to make a killer like the devil, everything has already been fixed
