### ISSUE TITLE
Watchdog Question

### ISSUE THREAD

**Issue by SilviuZLDX** [UnamSanctam/SilentXMRMiner#223]
Hello! If i keep the watchdog off will it help me to better bypass AV? Thanks

**Comment by UnamSanctam** [comment]
No not really, the watchdog won't really have any impact on the detections and if the watchdog gets detected and removed the miner would still stay. You can obfuscate the watchdog as well if you want to by enabling 'Custom Watchdog' in the 'Advanced Options' window. More info here: https://github.com/UnamSanctam/SilentXMRMiner/wiki#custom-watchdog https://github.com/UnamSanctam/SilentXMRMiner/wiki#how-can-i-decrease-detections

**Comment by SilviuZLDX** [comment]
Thank you
