### ISSUE TITLE
 Hi. Make a copy of the repository on another website(https://notabug.org/).

### ISSUE THREAD

**Issue by bakaba277** [UnamSanctam/SilentXMRMiner#224]

**Comment by bakaba277** [comment]
This website(github) doesn't like projects.

**Comment by bakaba277** [comment]
When the github closes this repository, you can go there completely. now it is too early to go there completely, because there is no blocking yet

**Comment by UnamSanctam** [comment]
Ah, yeah sure I'll go to other sites if this repository ever gets taken down.

**Comment by bakaba277** [comment]
there just has to be some kind of exit plan, right?:)

**Comment by bakaba277** [comment]
Another reason to do this now is to take your name so that no one assigns it to themselves and does not impersonate you.
