### ISSUE TITLE
Does Stealth Mode increase detection?

### ISSUE THREAD

**Issue by SilviuZLDX** [UnamSanctam/SilentXMRMiner#225]
Hello! I made my way through broswers and microsoft defender. The only time it detects the miner is only when i open the task manager. Does deactivating stealth mode helps ? Defenders says something about Persistence

**Comment by UnamSanctam** [comment]
No, persistence is usually detected when it sees the file get copied to another folder (like AppData) or when the registry key is added. Does it also detect it if you start it with administrator privileges instead?

**Comment by SilviuZLDX** [comment]
seems good it doesn t detect and i can spread it like this but the problem is that it doesn t appear on nanopool, been waitin for like 30 minutes

**Comment by SilviuZLDX** [comment]
yea 50%

**Comment by UnamSanctam** [comment]
Ok then it's working but just taking a while (unless you input the wrong wallet address or something). Nanopool has quite a high share difficulty so submitting a share can take a while and then Nanopool generally also has quite a delay as well.

**Comment by SilviuZLDX** [comment]
ok i will wait a bit more
