### ISSUE TITLE
xmr eth

### ISSUE THREAD

**Issue by golxd** [UnamSanctam/SilentXMRMiner#226]
if use the miner ETH and XMR at the same time, do you need different settings for "Inject into" and filename "Services.exe" Or you can make the same)

**Comment by UnamSanctam** [comment]
The filenames should be different but you can use the same 'Inject Into' for both although if you use different ones then if they find one miner then they won't necessarily find the other.

**Comment by golxd** [comment]
thx

**Comment by golxd** [comment]
interesting) What happen if a filenames will be same, miners dont work?

**Comment by UnamSanctam** [comment]
They will just overwrite each other.

**Comment by golxd** [comment]
then only the second miner will work, which overwrite the first
