### ISSUE TITLE
XMRig Proxy

### ISSUE THREAD

**Issue by PXCorp** [UnamSanctam/SilentXMRMiner#228]
Can you recommend me any FULL guide about XMRig-proxy(VDS server + host)?
Bc nonopool supports only 100 workers but i have 900+ donwloads(((

**Comment by UnamSanctam** [comment]
Well if you don't need to know how many miners you have you can just mine to nanopool with a single worker name directly but if you really need to then setting up xmrig-proxy shouldn't really require much of a guide. Just download xmrig-proxy and edit the "bind" and "pools" section in the config and port forward the port in the "bind" section and you're pretty much done. I'm not aware of any full guides for xmrig-proxy.

**Comment by PXCorp** [comment]
So i need a proxy htpps/socks5? And what i need to put in miners' pool?

**Comment by UnamSanctam** [comment]
Well, if you're planning to use some sort of external proxy then that proxy would have to allow port forwarding. The xmrig-proxy is run on a machine and then connected to by using the IP and port of the machine or a proxy/VPN on the machine if they allow port forwarding.

For the pool just enter the normal pool settings, here is an example config of my xmrig-proxy (uses port 3333 for SSL/TLS and 4444 for normal stratum):
```
{
    "access-log-file": null,
    "access-password": null,
    "algo-ext": true,
    "api": {
        "id": null,
        "worker-id": null
    },
    "http": {
        "enabled": false,
        "host": "127.0.0.1",
        "port": 0,
        "access-token": null,
        "restricted": true
    },
    "background": false,
    "bind": [
        {
            "host": "0.0.0.0",
            "port": 3333,
            "tls": true
        },
        {
            "host": "::",
            "port": 3333,
            "tls": true
        },
		{
            "host": "0.0.0.0",
            "port": 4444,
            "tls": false
        },
        {
            "host": "::",
            "port": 4444,
            "tls": false
        }
    ],
    "colors": true,
    "title": true,
    "custom-diff": 0,
    "custom-diff-stats": false,
    "donate-level": 0,
    "log-file": null,
    "mode": "nicehash",
    "pools": [
		{
			"algo": "rx/0",
			"coin": null,
			"url": "pool.hashvault.pro:8888",
			"user": "WALLET",
			"pass": "WorkerName",
			"rig-id": null,
			"keepalive": true,
			"enabled": true,
			"tls": true,
			"daemon": false
		},
		{
			"algo": null,
			"coin": "monero",
			"url": "xmr-eu2.nanopool.org:14433",
			"user": "WALLET",
			"pass": "x",
			"rig-id": null,
			"keepalive": true,
			"enabled": true,
			"tls": true,
			"tls-fingerprint": null,
			"daemon": false
        }
    ],
    "retries": 2,
    "retry-pause": 1,
    "reuse-timeout": 0,
    "tls": {
        "enabled": true,
        "protocols": null,
        "cert": null,
        "cert_key": null,
        "ciphers": null,
        "ciphersuites": null,
        "dhparam": null
    },
    "user-agent": null,
    "syslog": false,
    "verbose": true,
    "watch": true,
    "workers": true
}
```

**Comment by PXCorp** [comment]
![test](https://user-images.githubusercontent.com/81931207/116793058-1e66c000-aacd-11eb-9a73-17629fbae945.png)
what i need to put in first line?

**Comment by UnamSanctam** [comment]
The IP and port of the xmrig-proxy machine or the proxy/VPN it's connected with, 123.123.123.123:3333 or whatever it would be. Could also use a domain or No-IP or something incase the IP is dynamic.
