### ISSUE TITLE
persistance issue 

### ISSUE THREAD

**Issue by spiderloger** [UnamSanctam/SilentXMRMiner#229]
hello devz created an registry entry editor to run on system start up (windows) but  the problem is i cant see the file 
theprogram shows file name and that its saved in temp directory bu i cant find it 
any leads on persistance and file location and name navigation will be helpful thank u

**Comment by spiderloger** [comment]
or if any chznce is the feature there in the tool by deafault

**Comment by UnamSanctam** [comment]
What exactly are you asking for? If you enable 'Install' then it will add it into the registry and copy it to the filepath chosen.

**Comment by UnamSanctam** [comment]
And if it's saved in 'Temp' just go to %Temp% and it should be there.

**Comment by Toxenskiy** [comment]
the only thing that many users often clean at the pace

**Comment by spiderloger** [comment]
okay great is there any way of making the diskless feature persitance

**Comment by UnamSanctam** [comment]
What do you mean? A file has to exist to be able to run.

**Comment by spiderloger** [comment]
okay thanks a lot just thought the might be a way to run persistance with the diskless option since it is less detected by AV
programs like to mantain the injectd process even on sytem restart

**Comment by spiderloger** [comment]
or any obfusticator tool u use to make this undetactable please help the idea is just make  this persistance and undetactable
if there is any crypter or obfusticater which is good for .net files or for this tool specific generated file type please help have been trying diffrent methods for so long only the disklesss option is working for me 
please help if any

**Comment by UnamSanctam** [comment]
Well, I have some obfuscators on my wiki: https://github.com/UnamSanctam/SilentXMRMiner/wiki#how-can-i-decrease-detections.
