### ISSUE TITLE
I have no idea if this is working or not 

### ISSUE THREAD

**Issue by vitalisc** [UnamSanctam/SilentXMRMiner#232]
@UnamSanctam After watching a YouTube video i set it up  and run the build on my vps 
i didn't see any result here is the screenshot https://prnt.sc/12hdrn5
please can you drop me your discord  or message me through discord  with the id bravo123am#8377

**Comment by UnamSanctam** [comment]
Can you send a screenshot of the 'Main' settings tab? Also how long have you been mining?

**Comment by vitalisc** [comment]
i will record my procedure and send you the youtube video

**Comment by vitalisc** [comment]
@UnamSanctam  here is the video link please help me on this thanks https://youtu.be/yPvqOnudTdM

**Comment by UnamSanctam** [comment]
SupportXMR requires a password to mine (they use it as the worker name), since you also use the SSL/TLS port you should enable that in the "Mining" tab. Also keep in mind that SupportXMR is known for banning people for mining on botnets or having a lot of miners.

**Comment by vitalisc** [comment]
thanks for the response let me try that  also please can you message me here for some private conversation https://t.me/vitalisc

**Comment by UnamSanctam** [comment]
Unfortunately I don't have Telegram.

**Comment by vitalisc** [comment]
so please how do i reach you privately

**Comment by UnamSanctam** [comment]
You can add me on Discord: Unam Sanctam#3135 but keep in mind that I don't check it very often.
