### ISSUE TITLE
infection

### ISSUE THREAD

**Issue by XD-ThotHunter** [UnamSanctam/SilentXMRMiner#233]
may have infected myself on accident how do i remove this

**Comment by UnamSanctam** [comment]
https://github.com/UnamSanctam/SilentXMRMiner/wiki#how-do-i-remove-the-miner

**Comment by XD-ThotHunter** [comment]
> https://github.com/UnamSanctam/SilentXMRMiner/wiki#how-do-i-remove-the-miner

ty
