### ISSUE TITLE
No Distribute Virus Scanner

### ISSUE THREAD

**Issue by Vortexys** [UnamSanctam/SilentXMRMiner#239]
Someone have an Free No Distribute Virus Scanner? I just found paid ones

Unam, keep going with this amazing repository!

**Comment by Sh4r3cat** [comment]
antiscan.me or Kleenscan.com are very good. For Kleenscan you must create a new acc after 3 scans

**Comment by Toxenskiy** [comment]
both scanners merge the virus to antivirus

**Comment by Toxenskiy** [comment]
honestly, I say for the most part, if windowsdefender or esetnod32 do not complain, then you can redistribute

**Comment by Vortexys** [comment]
> honestly, I say for the most part, if windowsdefender and esetnod32 do not complain, then you can use it

I would say to try with Avast too, the most comum AV
