### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by zoubaba1997** [UnamSanctam/SilentXMRMiner#24]

**Comment by UnamSanctam** [comment]
Care to elaborate?

**Comment by codexprime** [comment]
does not mine, does not see the ball

there are workers in the logs

that the profit is not visible

or so it seems to me

**Comment by codexprime** [comment]
although apparently I'm wrong

at http://proxy.xmrig.info/

it is clear that there is a result

the truth is there all as one

only wallet address and several connections are visible

**Comment by UnamSanctam** [comment]
Sorry, your English is quite difficult to understand but what is working and what isn't?

**Comment by codexprime** [comment]
in the proxy logs you can see that there are new connections
all workers are signed with the wallet address
only one worker with multiple connections is visible in the panel

at first I thought that there was no profit, but it turns out that the miner finds tasks


in my case, the lack of a randomly generated unique worker name when working with a proxy + something will distinguish your miner from the rest

sorry it's all translator

**Comment by UnamSanctam** [comment]
Ah, ok I understand what you mean.

**Comment by UnamSanctam** [comment]
Test the newest version for now.

**Comment by codexprime** [comment]
after starting the build, a console window appears
set up the build directly to the pool
specifying the pool, wallet address, worker name

tested on windows server 2019
there is no profit on the pool, the worker does not appear
just the load on the processor

**Comment by UnamSanctam** [comment]
If your CPU goes up it means that it has connected to the pool and is mining. What pool are you using? Make sure to enter everything correctly so it mines to the right address.

**Comment by codexprime** [comment]
maybe you should try to configure the miner through TOR
maybe the connection is blocked

I expected about over an hour
but the worker is still not visible = (
https://www.supportxmr.com/

pool.supportxmr.com:3333
wallet address
worker name

**Comment by UnamSanctam** [comment]
I have had problems with supportxmr.com before, try using pool.supportxmr.com:443 and enabling SSL/TLS in the mining options.

Also keep in mind that if you have too many miners on supportxmr.com they ban you since botnets aren't allowed.

**Comment by codexprime** [comment]
in the proxy settings as I understand it
need to write
dns
wallet address
and configure on port 443?

**Comment by UnamSanctam** [comment]
Yes insert:
Pool: pool.supportxmr.com:443
Wallet Address: wallet address
Password: worker name

And then enable SSL/TLS in the "Mining" tab.

**Comment by codexprime** [comment]
how to set up the miner for a xmrig-proxy?
specify instead of the pool in the builder just the dns address and the wallet address?

and in the proxy settings already specify port 443?

**Comment by UnamSanctam** [comment]
Yes exactly, in the miner instead of the pool address enter the DNS of the server and then start the xmrig-proxy with --url=pool.supportxmr.com:443 instead.

**Comment by UnamSanctam** [comment]
Also don't forget to enable Nicehash mining in the "Mining" options if you are going to use xmrig-proxy.

**Comment by codexprime** [comment]
Thank you so much

**Comment by codexprime** [comment]
I officially confirm
miner is working

**Comment by UnamSanctam** [comment]
Ok, very good. I will leave this issue open for a while incase you need any more help.

**Comment by zoubaba1997** [comment]
After installation, it no longer starts automatically and is automatically banned by the system
![image](https://user-images.githubusercontent.com/73113267/103987017-bbbc8200-51c6-11eb-8a8a-1d1f0afc0e59.png)

**Comment by UnamSanctam** [comment]
What antivirus do you have?

And if the antivirus detects the virus it will remove it and therefore won't show it in the startup list and definitely wont deactivate it so that seems weird.

**Comment by zoubaba1997** [comment]
windows defender,and I still use it when closed

**Comment by UnamSanctam** [comment]
Did the antivirus detect and remove the virus? If it did, do you have a log activity in Windows Defender that shows it?

**Comment by zoubaba1997** [comment]
No virus detected

**Comment by UnamSanctam** [comment]
Then I am not sure why the startup gets disabled, that can only happen by either you disabling it manually or if you have some software that disable startup programs automatically.

**Comment by zoubaba1997** [comment]
The previous version can also start automatically, but the new version can't.

**Comment by UnamSanctam** [comment]
There hasn't been any changes to the code that installs and automatically starts the miner.

I have removed some code that kills all other miners if multiple are started so make sure that no other miners are installed at the same time.

**Comment by codexprime** [comment]
does this mean the elimination of other people's miners?
that is, unfortunately, expansion cannot be carried out on already captured machines?)

from the test I will say that:
30% of the miner's power on the server in 2 cores and 8 RAM gives from 200 to 700 H/s

**Comment by UnamSanctam** [comment]
No, the code I removed was code that checked if any other of my silent XMR miners where running and if they were it killed them, this code had been detected by antiviruses as being Coinminer code and as such I removed it.

 It wasn't really necessary in the first place since it was still random which installed miner ran last and killed the other ones. If you are going to install a miner on a machine that already has an older version on it then the old version should be removed first beforehand or you could let two or more miners run at the same time which is also possible.

And that hashrate looks accurate depending on the CPU, you can also find some benchmarks of different CPU speeds here: https://xmrig.com/benchmark

**Comment by Sh4r3catyt** [comment]
then i run the miner its crashing the pc so the desktop freez is that normal?

**Comment by UnamSanctam** [comment]
If you use 100% CPU, then yes.

**Comment by Sh4r3catyt** [comment]
Thanks for your fast answer but i try your newest version of the miner and my vps and virtual box freezing on 50cpu

**Comment by UnamSanctam** [comment]
Might be because they don't have enough cores so 50% becomes 100%, you can enable "Advanced Parameters" in the "Mining" tab and remove "--cpu-priority=5 --cpu-no-yield" from the string. Doing that will decrease performance but will make it so that the miner won't cause much instability at high CPU.

**Comment by Sh4r3catyt** [comment]
Thanks you!

**Comment by Sh4r3catyt** [comment]
Now my next problem the miner does not work on arabic pcs what can i do?

**Comment by UnamSanctam** [comment]
As in the system language is in Arabic? Is it a VM where the miner works when it's in English but not when it's in Arabic or something else?

**Comment by Sh4r3catyt** [comment]
the system language is Arabic

**Comment by Sh4r3catyt** [comment]
an error comes application cant run correctly

**Comment by UnamSanctam** [comment]
What exactly does the error message say?

**Comment by Sh4r3catyt** [comment]
Its not popping up again :/ but why is the miner not closing it self then it gets started again? in 0.7.1 its closing it self.

**Comment by UnamSanctam** [comment]
Sorry I don't really understand what you mean, closing and starting again in what way?

**Comment by Sh4r3catyt** [comment]
So then i start the miner its normal mining. Then i re-open the miner there are 2 cmd consoles that are mining and in the 0.7.1 the miner closed the other miner

**Comment by UnamSanctam** [comment]
Yes that code was removed due to it being detected by antiviruses as being a Coinminer.

Either way, you shouldn't run two miners at the same time anyways.

**Comment by Sh4r3catyt** [comment]
Thank you! <3

**Comment by Sh4r3catyt** [comment]
How is gpu mining works? i added pool.supportxmr.com:7777 and gpu only but it does nothing

**Comment by UnamSanctam** [comment]
How did you check whether it is working? It often won't show in Task Manager.

**Comment by Sh4r3catyt** [comment]
its running on 5.8 % on gpu says the taskmgr and also supportxmr didnt shows my name up

**Comment by UnamSanctam** [comment]
What GPU do you have and have you updated the graphics drivers the last few years? Also, you can't mine with GPU on most VMs since they don't expose the CUDA driver to the miner.

**Comment by Sh4r3catyt** [comment]
I use the miner at my main PC i have a GTX 970M

**Comment by Sh4r3catyt** [comment]
![Unbenannt](https://user-images.githubusercontent.com/77161107/104103408-3908f500-52a2-11eb-8ab0-a462a8ef1dac.PNG)

**Comment by UnamSanctam** [comment]
Yes, that seems correct. GPU mining is not the same as CPU mining, the percentage doesn't fully represent what the actual GPU load is. Also I have the miners GPU settings set to the minimum otherwise it can cause crashes for lower-end GPUs and higher-end ones during high load. You can change this if you want in the advanced parameters but they are quite hard to finetune.

**Comment by Sh4r3catyt** [comment]
Okay thanks, but can you re-add that feature that the miner close his self then its already running.

**Comment by UnamSanctam** [comment]
Well, sure but I have to find another way to do it, and it shouldn't be needed in the first place.

**Comment by Sh4r3catyt** [comment]
Would be nice

**Comment by Sh4r3catyt** [comment]
Then im mining with my gpu its not showing me up on supportxmr
What i can do?

**Comment by Mastersey** [comment]
Thank you so much for this miner project, i'm trying to come back in coding trying to undesrtanding projects like this so.. Thanks :D
I just have a question about using a xmr-proxy: I assume this is only recommended when miners are installed on privates computers only right ? Without that, the proxy address is obviously exposed to attacks ?
Thank you.

**Comment by UnamSanctam** [comment]
Yes that is correct unless you get some throwaway server or something that can't be tracked back to you.

**Comment by Mastersey** [comment]
> Yes that is correct unless you get some throwaway server or something that can't be tracked back to you.

Thanks for confirmation, so fast :p (If you decide to create a BAT wallet (Brave Browser), you will have some BATs awaiting for you as tips :)

**Comment by UnamSanctam** [comment]
No problem, I use Brave but have totally forgotten to connect my GitHub so many thanks for reminding me.
