### ISSUE TITLE
XMR Miner Not Working?

### ISSUE THREAD

**Issue by Crit19** [UnamSanctam/SilentXMRMiner#241]
I Build a miner, start it, it does what it is supposed to do for about 30 seconds, then crashes or something, just disappears from list of working programs, any solutions?

**Comment by UnamSanctam** [comment]
The injected program disappears? If you chose to 'Inject Into' explorer.exe it should show up as explorer.exe

**Comment by Crit19** [comment]
It did show up as explorer.exe, and it used 30% like I put there, but after 30 seconds it went back to 0.3%

**Comment by UnamSanctam** [comment]
Do you have 'Stealth' enabled?

**Comment by golxd** [comment]
**UnamSanctam**, tell me when will the update? I'm thinking of updating the archives, wait or not

**Comment by Crit19** [comment]
> Do you have 'Stealth' enabled?

I had it on first time, then tried with it off, I'll try some more stuff I find on some forums, thank you for trying, appreciate your help!
