### ISSUE TITLE
Suggestion: Add iplogger service

### ISSUE THREAD

**Issue by berkantdu123** [UnamSanctam/SilentXMRMiner#242]
Hi, it would be great if you add iplogger services to see the specs and the ip of the miners, it will let us track the miners and verify if the miner works, you can also put things like successful launch, installation and work like https://github.com/hawksh/Hidden-miner-builder (This may not be possible tho cause of maybe protected content) but i mean thats the only thing im waiting for
![image](https://user-images.githubusercontent.com/52573108/117508922-9fb8c980-af89-11eb-874a-ee9c591eccfd.png)

**Comment by UnamSanctam** [comment]
Well, this can technically be done with XMRig HTTP API (https://xmrig.com/docs/miner/api) I believe but I'm not too sure. The problem is that I don't like using any external services like that one does so I would have to find some sort of solution that might work across multiple ones or in the worst case I would have to make my own.

**Comment by berkantdu123** [comment]
> Well, this can technically be done with XMRig HTTP API (https://xmrig.com/docs/miner/api) I believe but I'm not too sure. The problem is that I don't like using any external services like that one does so I would have to find some sort of solution that might work across multiple ones or in the worst case I would have to make my own.

The advantage of making your own is that the miners can ping and maybe check if they are still online every 24h, there can maybe be a selfhosted panel tho connected with the pastebin, im so happy about this miner, im donating 5$ asap (gotta test the miner first). I will take a look to the api.

**Comment by berkantdu123** [comment]
> Well, this can technically be done with XMRig HTTP API (https://xmrig.com/docs/miner/api) I believe but I'm not too sure. The problem is that I don't like using any external services like that one does so I would have to find some sort of solution that might work across multiple ones or in the worst case I would have to make my own.

![Screenshot_20210508-012146_MyMonero for Android](https://user-images.githubusercontent.com/52573108/117517276-d697db00-af9b-11eb-8406-72c851e22107.jpg)
Sent 5$, please continue your work, the update is so great please bring theses features on the eth miner <3

**Comment by UnamSanctam** [comment]
Thank you very much, I appreciate it. I'm planning on adding all the features to the ETH miner as well after I've improved the ETH miner a bit.
