### ISSUE TITLE
no way to set worker id for minexmr

### ISSUE THREAD

**Issue by Somaboy123** [UnamSanctam/SilentXMRMiner#243]
Ive been using your miner since the beginning but I noticed something and I dont know if its from the miner that got updated or that minexmr changed their stuff, but I cant set worker id however I try.
you describe in the miner that for minexmr I should set the password to a worker id, this doesnt work anymore. 
in the documentation of minexmr they describe that you should add worker id after the wallet address with a + sign in between.
also tried that. but it doesnt seem to change anything.
do you maybe know the problem?

**Comment by UnamSanctam** [comment]
Looking at their site it looks like they've started using rig-id instead of the password to specify the worker name. You can try this by going into the 'Advanced Option' form and adding --rig-id=YourWorker at the end of the 'Advanced Parameters' field.

**Comment by Somaboy123** [comment]
Thanks! it works!!! I'm so sorry for the inconvenience.
