### ISSUE TITLE
Tnx for update miner

### ISSUE THREAD

**Issue by alix1011** [UnamSanctam/SilentXMRMiner#245]
my friend thank you for paying attention to the comments and suggestions for new options and improving Miner, and making it better day by day. Thank you very much.

**Comment by alix1011** [comment]
I have a problem in update miner

**Comment by alix1011** [comment]
![Screenshot_20210508-164441_Microsoft Remote Desktop](https://user-images.githubusercontent.com/53878062/117538873-00ddad00-b01d-11eb-9390-bdd2e7bec918.jpg)

**Comment by alix1011** [comment]
This is my config, but don't work miner

**Comment by alix1011** [comment]
Why ?

**Comment by alix1011** [comment]
Is there a problem with the settings?

**Comment by UnamSanctam** [comment]
Could you copy paste your whole 'Advanced Parameters' here? And is the wallet address a correct Turtlecoin wallet address?

**Comment by UnamSanctam** [comment]
Wait, you have 'Stealth' on. How do you check if it works then?

**Comment by alix1011** [comment]
There may be a problem with the system

**Comment by UnamSanctam** [comment]
Why? Keep in mind that when you have 'Stealth' on it will pause the miner if you open Task Manager or anything like it.

**Comment by alix1011** [comment]
Hello, my friend, I have a suggestion, can Miner be connected to the Telegram bot?  Can I control systems and minors using Telegram?

**Comment by alix1011** [comment]
Hello, my friend, I have a suggestion, can Miner be connected to the Telegram bot?  Can I control systems and miners using Telegram?

**Comment by UnamSanctam** [comment]
No, that would be very complicated and probably not worth it due to it being very inflexible. Even more so than to create a separate miner panel. It would also require you to in some capacity expose the bot API key.

**Comment by alix1011** [comment]
My friend, can you update this rat?  This rat has many options but for each system a separate robot must be set up, I mean it is not multi system.

https://github.com/LimerBoy/ToxicEye

**Comment by UnamSanctam** [comment]
Well I don't have the time at the moment.

**Comment by alix1011** [comment]
Do you understand what I mean?  I mean, you have to set up a separate output for each system, that is, you have to set up a separate API TOKEN BOT for each system. Is it possible to control multiple systems with one bot?

**Comment by alix1011** [comment]
Does that mean it takes a long time to update?

**Comment by alix1011** [comment]
Thanks if you have time to update it

**Comment by alix1011** [comment]
Thanks if you have time to update it
