### ISSUE TITLE
translation

### ISSUE THREAD

**Issue by bakaba277** [UnamSanctam/SilentXMRMiner#247]
as i said earlier, made a translation of the text
some points I decided not to translate, since some words are "names of their own" and do not require translation to understand them

I don't think that for my modest and inaccurate translation you need to write a function for changing the language, the reasonable solution I think is just to be able to download an alternative version in releases
so easier

https://github.com/bakaba277/translation/blob/main/translation

**Comment by UnamSanctam** [comment]
Ah, thank you very much, I'll think about how to best implement it. I really appreciate it!

**Comment by bakaba277** [comment]
glad to help you 

>I'll think about how to best implement it

the easiest will be replacing phrases in the specified places and compiling. at this stage of work on translation, this does not matter at all. simpler -- better :)
as I said the translation not exactly accurate, some moments may have been missed because of my inattention, in any case I need to have an idea how it will look to improve the translation in the future

**Comment by Khizhniak** [comment]
> 
> 
> Ah, thank you very much, I'll think about how to best implement it. I really appreciate it!

Would be nice, I could translate on some languages.

**Comment by Khizhniak** [comment]
> 
> 
> > Ah, thank you very much, I'll think about how to best implement it. I really appreciate it!
> 
> Would be nice, I could translate builder and wiki on some languages.

**Comment by UnamSanctam** [comment]
This feature is implemented in the new miner https://github.com/UnamSanctam/SilentCryptoMiner, just have to add the translations.
