### ISSUE TITLE
Considered a virus

### ISSUE THREAD

**Issue by zoubaba1997** [UnamSanctam/SilentXMRMiner#25]

**Comment by UnamSanctam** [comment]
Of course it is, it contains a crypto miner and nearly all antiviruses considers miners as protentional malware.

**Comment by zoubaba1997** [comment]
Can you avoid detection of antivirus software in one way?

**Comment by zoubaba1997** [comment]
Can I add your telegram?

**Comment by UnamSanctam** [comment]
It does avoid detection after you create the miner. It avoids things like Windows Defender but if you want to avoid everything you would have to get a crypter and crypt the miner.

**Comment by zoubaba1997** [comment]
> 创建矿工后，它确实避免了检测。它避免了诸如Windows Defender之类的事情，但是如果您想避免一切，则必须拥有一个加密器并对矿机进行加密。

Thank you very much
