### ISSUE TITLE
Blank Name in Task Manager 'Processes' Tab

### ISSUE THREAD

**Issue by longlivefrodo** [UnamSanctam/SilentXMRMiner#250]
![Capture](https://user-images.githubusercontent.com/83916978/117578791-f6d4b080-b0e7-11eb-88be-b92367d1871b.PNG)

Hello,

This is a great tool, well done to all involved in creating it! In the attached screenshot you can see that the icon representing the mining software doesn't have any text accosicated to it in the 'Processes' tab of Task Manager. I've filled out all the sections within the Silent Miner Builder (1.3) so I'm wondering if this is an issue or if there's a fix for this?

Many Thanks

**Comment by UnamSanctam** [comment]
That's how Task Managers svchost works, it will display as nothing since it's not hosting anything and there's not really anything you can do about it since it's not hosting a service.

**Comment by longlivefrodo** [comment]
Interesting, that makes sense! Thanks for the reply.

Would using a different injection file make any difference? e.g. cmd.exe, explorer.exe etc.

Thanks again, great work!

**Comment by UnamSanctam** [comment]
If you use explorer.exe or cmd.exe it will just say 'Explorer' or 'Windows Command Processor' (depends on the language of the computer) like any other open 'Explorer'.

**Comment by longlivefrodo** [comment]
Legend, thank you!
