### ISSUE TITLE
Binance

### ISSUE THREAD

**Issue by Ganns1** [UnamSanctam/SilentXMRMiner#251]
I use binance wallet as xmr mining. nanopool made a statement 6 days ago "#CFX miners warning: DO NOT mine directly to #Binance CFX addresses. Binance supports only BSC network deposits (CFX tokens), not Conflux network (real coins).", is this only valid for cfx? no problem right ?

**Comment by UnamSanctam** [comment]
Technically not a problem no but why do you even use Binance as a wallet and not a real wallet?

**Comment by Ganns1** [comment]
how so. I'm just mining the xmr to binance, I don't understand much of these things. What should I do ?

**Comment by UnamSanctam** [comment]
Yes but Binance is an exchange wallet and not a "real" wallet. You don't use a stock trading account as your bank account in real life do you? You can mine to Binance mostly fine but the fees to withdraw or transfer are usually very high. The most common wallet is the official Monero GUI wallet https://www.getmonero.org/downloads/

**Comment by UnamSanctam** [comment]
Yes you would have to build a new miner with the new wallet address depending on which pool you use. Not sure what fee they take for Monero but usually Binance takes a fee of between $1 to $15 per withdrawal.

**Comment by dyachenkomark** [comment]
Hi, UnamSanctam, thank you for your program! I have already started it on "minergate" but desided to move on nanopool, becouse i thing that more professional, is it better then "minergate"? So i have tried to start with "nanominer" and it started to work. I added my email, started to see my first worker and i understud that made everything right. When I tried to start with "silentXMRminer" i put this information:
 Pool: xmr-eu1.nanopool.org:14444
 Wallet address: 88ZMLmQmRL8WgaGjemiLNnhnGtQY4ow5wKhTrdRVLtoT3BsUgwFDYUAb1npJVHrhAfKsWuzoF4RDNG3fpLmAG8PX8LEQxaJ
 Password: - 
 In result i dont see my worker. I see that it is mining in "Current Calculated Hashrate", but I am not shure is it mining for me, becouse there is only one work(which is red and doesnt work)? 
 I tried to add my email in "Wallet address"(88ZMLmQmRL8WgaGjemiLNnhnGtQY4ow5wKhTrdRVLtoT3BsUgwFDYUAb1npJVHrhAfKsWuzoF4RDNG3fpLmAG8PX8LEQxaJ.myemail@gmail.com) but it doesnt work. Can you help me, where am i making mistake? Sorry for my english.
 Thank you!

**Comment by dyachenkomark** [comment]
Also I would like to know, if i had more then 10 computers, would "Minimum payout" become 1 XMR again?

**Comment by UnamSanctam** [comment]
You can change the minimum payout by mining with an email address, when you change it then it will stay that way no matter how many miners you have.

**Comment by dyachenkomark** [comment]
thank you for your very fast answer :) Yes, password is blank. 
Where can i get my "worker", what is it?

**Comment by dyachenkomark** [comment]
what will give it to me, if i add email in silentxmrminer?

**Comment by UnamSanctam** [comment]
A worker is just any name that the miners using that worker name will be grouped under when you check the statistics. Neither a worker name nor an email is actually required. What you explained earlier with the "Current Calculated Hashrate" going up means that everything is working correctly.

You don't need to enter a real email, you can frankly just use `password` as the email since it's only used as a password for changing the minimum payout.

**Comment by dyachenkomark** [comment]
UnamSactram, thank you very much!
