### ISSUE TITLE
Hashes 

### ISSUE THREAD

**Issue by gamethrower** [UnamSanctam/SilentXMRMiner#253]
If miner stops working before getting a share, will hashes be lost?

**Comment by UnamSanctam** [comment]
Mining is luck based so incorrect hashes don't matter, only the correct one does. You wouldn't lose anything since they were all wrong.

**Comment by gamethrower** [comment]
For example I get on average 1 share per 10 minute, if I stop 9 minutes after last share, will those minutes go to waste? 
So pool paying for shares, not total hashes submit?

**Comment by UnamSanctam** [comment]
Yes that's right. The formula is the shareDifficulity/hashesPerSecond so if the share difficulty is 400 000 (like Nanopool) and you mine at 500 H/s the average share time per share would be 400000/500=800 seconds on average so the average shares per minute would be 60/800≈0,075 shares per minute.

**Comment by gamethrower** [comment]
Thanks
