### ISSUE TITLE
No new workers in pool

### ISSUE THREAD

**Issue by Berkyb** [UnamSanctam/SilentXMRMiner#254]
Hi I've set up a decent number of miners with a few different ports, with TLS both on and off (no proxy). I've used different regional domains, admin access on all miners, but I'm not seeing any new workers on my pool dashboard. Firewalls and antivirus are all disabled.

**Comment by UnamSanctam** [comment]
Do you mean workers or miners? Does the miners use different worker names or do they use the same one? If they use the same one they will all show a combined hashrate under one worker name.
