### ISSUE TITLE
Stealth doesn't work

### ISSUE THREAD

**Issue by gamethrower** [UnamSanctam/SilentXMRMiner#256]
Still working after I open Task Manager even tho Stealth is on. CPU load of infected process is dropping to 0% and goes back every 10 seconds or so.

**Comment by UnamSanctam** [comment]
No it can't really do anything to the actual miner. If you use Process Hacker and double click the mining process could you screenshot the same sort of image I sent?

**Comment by gamethrower** [comment]
CPU drops to 0% when I open Process Hacker. Something wrong with Task Manager detection.

**Comment by gamethrower** [comment]
I checked using cmd CPU still jumps from 0% to 33% even with Task Manager closed.

**Comment by UnamSanctam** [comment]
Try and rebuild the miner, ensure that all the settings are correct as well.

**Comment by gamethrower** [comment]
Same

**Comment by UnamSanctam** [comment]
If you run it without 'Stealth' what does it show?

**Comment by gamethrower** [comment]
![image](https://user-images.githubusercontent.com/46888050/117850786-55d42a00-b28e-11eb-9e39-bba9cabf3d08.png)

**Comment by UnamSanctam** [comment]
Hmm, do you have 'Idle' enabled?

**Comment by gamethrower** [comment]
Maybe, but why does CPU load jump like this?

**Comment by gamethrower** [comment]
![image](https://user-images.githubusercontent.com/46888050/117851576-1eb24880-b28f-11eb-923f-2d772de9fa96.png)

**Comment by gamethrower** [comment]
No, I don't have one. Windows 7 is in wide use still you know. It's bad if it's not compatible.

**Comment by UnamSanctam** [comment]
Yes a few uses it but in my Windows 7 VM it works, I don't know if you have updated it any or not. Still, most people don't use the default Task Manager for Windows 7 but I guess I could search for the Window Name but that means it would still only work on English versions, blame Microsoft for not creating a window class for their Task Manager.

**Comment by gamethrower** [comment]
Why not look for process? 
Also I don't think this CPU jumps is related to Win 7.

**Comment by UnamSanctam** [comment]
I will try to recreate it with different Windows 7 service packs incase that happens on older ones.

**Comment by UnamSanctam** [comment]
Stealth will now also search for window titles so it will at least hide from the Task Manager when the window title is in English, the CPU fluctuation might have been fixed as well.

**Comment by UnamSanctam** [comment]
Seems like this problem has to do with the keepalive option for some pools in the 'Remote Configuration', try disabling keepalive.

**Comment by gamethrower** [comment]
Yeah nanopool doesn't support keepalive. Everything works now.

I suggest adding a fake error option. It seems like using file joiner to add simple program with error messagebox does increase detection rate.

**Comment by UnamSanctam** [comment]
I might be able to do the fake error efficiently now since I've reworked the program flow, just have to find somewhere in the builder to put it and what options it should have.

**Comment by dyachenkomark** [comment]
I also have the second computer with win7 1 SP and the program doesnt want to start. I have tried it on 2 different computers with Win10 and its work, but it doesnt work on win7. Maybe there is some secret?

**Comment by UnamSanctam** [comment]
No it should work as long as they have at least .NET Framewoek 4.5

**Comment by gamethrower** [comment]
Since someone opened the issue again here's another question.
What is the purpose of `WinRing0x64.sys` file? Can it be removed?

**Comment by dyachenkomark** [comment]
It has already worked when i tested it with Minergate, but when i change it to nanopool, it doesnt start. I will try  to do it again.

**Comment by UnamSanctam** [comment]
It's a driver that increases the hashrate by configuring MSR registers, though on most computers this requires administrator permisisons, you can read more here:https://xmrig.com/docs/miner/randomx-optimization-guide/msr

**Comment by dyachenkomark** [comment]
As i understood, i cant know amount and information of computers in nanopool with using silentXMRminer?

**Comment by UnamSanctam** [comment]
Yes you won't really be able to know that from any pool no matter which miner.

**Comment by dyachenkomark** [comment]
I have tried to change filename, try to restart computer but it doesnt want to start on Win7 1SP. i also dont use stealth mod, jusy try to test. What does whatdog mean? maybe i should turn it off.

**Comment by UnamSanctam** [comment]
No that won't really do anything. Check that the computer is both 64-bit and has at least .NET Framework 4.5, you can also use Process Hacker and search for `--cinit` in the top right search bar to see if any miners are running.

**Comment by dyachenkomark** [comment]
Yes, i have found it, it works, i have waited some time and it started to work. Thank you! what does "donate level" mean? are we giving a percent for you or what?

**Comment by UnamSanctam** [comment]
XMRig has a standard donation and that sets the level, that string used to be there so that the miner could see if any miners were running so it didn't start twice (it checked if any processes contained 'donate-level' and that's how it knew if any miners were running), it also used to be used as a configuration option back when I didn't want to make my own, so --donate-level=4 disabled Idle Mining and --donate-level=5 enabled it. Though that string isn't used anymore so it can technically be removed.
