### ISSUE TITLE
Successful Compilation - No Actual Mining

### ISSUE THREAD

**Issue by elityy** [UnamSanctam/SilentXMRMiner#259]
Hi, thanks for your effort for this project! I have read all the wiki and followed all the instruction. I disabled the Antivirus, and successfully built the executable. However, I cannot see the injected program (Explorer) to be actively using CPU. Moreover, when I tried to run complilled executables (uninstaller, too) there is no feedback - am I doing something wrong?
I would be very gratefull for your help.
I am also interested in how can I run this program without admin priveliges and ability to turn off antivirus.

**Comment by elityy** [comment]
Here are the screenshor of the 'main' and 'mining' tabs. I am using a MyMonero wallet and on of the European Nano pools.

<img width="402" alt="main xmr miner" src="https://user-images.githubusercontent.com/65614525/117970320-33471d00-b331-11eb-9e93-7934d71a4680.png">
<img width="402" alt="minining xmr miner" src="https://user-images.githubusercontent.com/65614525/117970323-34784a00-b331-11eb-8c10-98071ae3e3e9.png">

**Comment by UnamSanctam** [comment]
And when you start the miner (and wait the amount of time you chose in 'Start Delay') it uses no CPU? Can you download Process Hacker and search for `--cinit` in the top right search box, this should find the miner process (explorer.exe).

**Comment by elityy** [comment]
So I downloaded the Process Hacker, and when I enter `--cinit`, it finds nothing. Maybe I should try injecting into a different process?

**Comment by UnamSanctam** [comment]
You could try but it should work. If you start the miner while you have Process Hacker open does it appear in the list?

**Comment by elityy** [comment]
Nope, nothing happens. I mean I don't see any change in how much CPU explorer.exe is taking. For that matter, I don't see any change in CPU performance at all. I don't know anything what else I can do in this case. Maybe try on a different PC?

**Comment by UnamSanctam** [comment]
But it appears when you search for `--cinit`?

**Comment by elityy** [comment]
No, nothing appears. Should I maybe delete everything from the previous installations for the clearness of the experiment, and try it over?

**Comment by UnamSanctam** [comment]
Hmm, yes you can try to do that. You can also enable DEBUG in the 'Advanced Option' form to see if you get any errors when you run it.

**Comment by elityy** [comment]
Where can I see the errors from the debugger?

**Comment by UnamSanctam** [comment]
If there are any they should pop up on the screen as message boxes.

**Comment by elityy** [comment]
There are no messages.
So just to be clear, as I might be doing something intrinsically incorrect. Here is what I do:

1. Turn off the antivirus
2. Donwload the zip archive
3. With antivirus turn off, unzip the builder in some folder
4. Run the builder
5. **One the main page** Fill the pool info from the nano pool and put my monero wallet adress
6. **One the install page** Enable installation, keep the path, name and programm to be injected into as default
7. **One the miner page** Enable SSL, enable idle mining, don't touch the advanced options
8. **One the build page** Click build; in the console I got a message about successful build.
And if I clearly understand, after the specified amount of time the miner should be running and taking up some CPU, which should be evident from the task manager (no stealth).

So what am I doing wrong?

**Comment by UnamSanctam** [comment]
Well, that should work. test this and see if it works incase there is something wrong with your build process/computer or just the fact that you can't run it
[TEST2.zip](https://github.com/UnamSanctam/SilentXMRMiner/files/6468811/TEST2.zip)

**Comment by elityy** [comment]
So I have run the executable that you sent, it kind seems to be working - when I open the task manager, it shows for a few seconds that the explorer is taking up 30% of CPU. So probably it is woeking now.
So, first of all how I disable it now, and what did you input in there?
I have also tried your ETH miner, and I have the same situation there, so its probably something with data I input.
Maybe I would be possible to get in touch with on discord or telegram?

**Comment by UnamSanctam** [comment]
You can just kill it in the Task Manager or Process Hacker. I just input the nanopool pool address and a wallet address, nothing more, if you open CMD and run `ping xmr-eu2.nanopool.org` what response do you get?

**Comment by elityy** [comment]
This is what it looks like:

<img width="960" alt="ping cmd" src="https://user-images.githubusercontent.com/65614525/118407052-8ac5ef80-b687-11eb-9c07-2b0bee4fcbaf.png">

**Comment by UnamSanctam** [comment]
Ok the pool isn't blocked or something then, compile a miner and then if it doesn't work for you then send it here.

**Comment by elityy** [comment]
You mean the exe file that we create in install tab?

**Comment by UnamSanctam** [comment]
No just send the miner that you compile here if it doesn't work for your and I'll check it.

**Comment by elityy** [comment]
Here it is

[miner_test.zip](https://github.com/UnamSanctam/SilentXMRMiner/files/6489730/miner_test.zip)

**Comment by UnamSanctam** [comment]
Your miner is working correctly.
<img alt="6dabb24f93495107cd38" src="https://user-images.githubusercontent.com/10323655/118407802-a2e74000-b682-11eb-9b7b-3094d2a868b4.png">

**Comment by elityy** [comment]
Ok, i figured it - I did not run the compiled executable xD.
 So if I understand correctly, I can compile it on my machine and run the compiled file on other machines?

**Comment by UnamSanctam** [comment]
Yes exactly.

**Comment by elityy** [comment]
Thanks a lot for you support! I haven't ever somebody responding so quickly and to the point!

**Comment by UnamSanctam** [comment]
No problem, good luck with the mining.
