### ISSUE TITLE
How to delete ?

### ISSUE THREAD

**Issue by codexprime** [UnamSanctam/SilentXMRMiner#26]
How to delete ? accidentally infected a virtual machine, looked for a file in the folder in which I installed it, I cannot find

I will be glad if you add a batch file to remove the miner from the system =)

and please add an iplogger after all)

**Comment by UnamSanctam** [comment]
If you did not enable the "Install" option then you can just end the process in Task Manager but if you did enable "Install" you have to remove the miner key with Regedit in the path: "HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run".

**Comment by UnamSanctam** [comment]
And adding an IP logger wouldn't matter much since the miner never contacts any external servers and is not designed to ever do so.

**Comment by codexprime** [comment]
thank you very much, you saved me time =)

**Comment by codexprime** [comment]
otherwise the whole system would have to be demolished
