### ISSUE TITLE
Help me pl!

### ISSUE THREAD

**Issue by ValentinoLmao** [UnamSanctam/SilentXMRMiner#260]
Hello, I am not from America so I will use a translator, I hope it will translate correctly. I had a problem after compiling the miner, and after I started it, it works for the first couple of seconds ( I want to replace h/s does not count) and then just the load on the CPU drops, while I do not use the function to hide from the task manager because I check it for performance. The pool I use is MINERGATE.

**Comment by UnamSanctam** [comment]
Could you try another pool like https://xmr.nanopool.org/ to see if MinerGate is the problem?

**Comment by ValentinoLmao** [comment]
One second, am try next Pool, Rushen.

**Comment by ValentinoLmao** [comment]
Yes, MInerGate don't give mining bootnet. Thank you owner!

**Comment by ValentinoLmao** [comment]
> Не могли бы вы попробовать другой бассейн, как https://xmr.nanopool.org/ чтобы увидеть, является ли MinerGate проблемой?

It's Pool don't work! Am use xmr-eu1.nanopool.org:14444, and my wallet address, in point password i'am don't put text!

**Comment by ValentinoLmao** [comment]
Yes my start delay = 5 seconds, (testing). Everything is like in the story with MinerGate!

**Comment by UnamSanctam** [comment]
Could you send the .exe you built here and I'll test it?

**Comment by ValentinoLmao** [comment]
https://anonfiles.com/r1kaL7veuc/13_exe

**Comment by ValentinoLmao** [comment]
https://prnt.sc/12uio0o settings pool and wallet

**Comment by ValentinoLmao** [comment]
https://prnt.sc/12uiowx mining settings

**Comment by ValentinoLmao** [comment]
I'am paste pool from eu, because I'm from Ukraine

**Comment by UnamSanctam** [comment]
Your miner works correctly, could you try and open CMD and enter `ping xmr-eu1.nanopool.org` and see what response you get?
<img  alt="ca6959810f89d4a9ce1a" src="https://user-images.githubusercontent.com/10323655/117999458-27fdec80-b345-11eb-985d-2a69b6c7cca1.png">

**Comment by ValentinoLmao** [comment]
> Your miner works correctly, could you try and open CMD and enter `ping xmr-eu1.nanopool.org` and see what response you get?
wait

**Comment by ValentinoLmao** [comment]
Ответ от 51.255.34.118: число байт=32 время=56мс TTL=53
ENG: Response from 51.255.34.118: number of bytes=32 time=56ms TTL=53

**Comment by ValentinoLmao** [comment]
It's normal?

**Comment by UnamSanctam** [comment]
Hmm, okay so you can connect to the pool correctly, what CPU and what amount of RAM do you have?

**Comment by ValentinoLmao** [comment]
CPU Intel i3=6006U (3Ghz) RAM 4

**Comment by UnamSanctam** [comment]
Hmm, those are quite bad specs but could you try and download Process Hacker and then search for `--cinit` in the top right search bar? The miner should appear there in the list if you do.

**Comment by ValentinoLmao** [comment]
browsermine.com/ it's site and pool worked and don't have problems!

**Comment by UnamSanctam** [comment]
Ah I see, then the pool might've been blocked or something like it.

**Comment by ValentinoLmao** [comment]
Blocked from my Internernet ?

**Comment by UnamSanctam** [comment]
Maybe, could you download Process Hacker like I said above and see if the miner is running?

**Comment by ValentinoLmao** [comment]
Okey, mb pl give me link to save ph?

**Comment by UnamSanctam** [comment]
https://processhacker.sourceforge.io/

**Comment by ValentinoLmao** [comment]
https://prnt.sc/12uj9su

**Comment by ValentinoLmao** [comment]
CPU 0% for start 30%

**Comment by ValentinoLmao** [comment]
It's problems in pools maybe :( hhhh....

**Comment by ValentinoLmao** [comment]
https://prnt.sc/12ujl9v

**Comment by UnamSanctam** [comment]
Yeah that is correct. I would guess that either your CPU is too "bad" (either not supported or none of your CPU cores are idle) or that you cannot connect to the pool, although you could ping it so I would guess it's the first one.

**Comment by ValentinoLmao** [comment]
I will be glad to meet you, I come from Ukraine and plan to travel around the countries in the future, now I am studying English but I can't do it without an interpreter:(

**Comment by UnamSanctam** [comment]
Good luck, your miner does work though although it probably just doesn't work on your computer.

**Comment by ValentinoLmao** [comment]
mb
