### ISSUE TITLE
CPU usage spikes problems. 

### ISSUE THREAD

**Issue by boff64** [UnamSanctam/SilentXMRMiner#261]
I've tested it with cpu usage meter and it is not working right, I get cpu spikes every 10-20 seconds, it goes to 0 then to 40%. Mining hashrate is also affected.

**Comment by UnamSanctam** [comment]
Hmm, someone else also reported this but I can't reproduce it on any of my own systems. What OS are you using and what settings?

**Comment by UnamSanctam** [comment]
Could you try with the latest version and see if it happens with that one as well?

**Comment by boff64** [comment]
Problem still present

**Comment by boff64** [comment]
Windows 10 VM and Windows 10 on Ryzen 3 3200G, 16 GB ram. On both it does that, when I've tried regular xmrig, it is stable

**Comment by boff64** [comment]
v1.2.3 does not do this

**Comment by boff64** [comment]
Tested it now on older pc with AMD x2 cpu and 4GB of ram on another network and also try running it via VPN but still spikes

**Comment by UnamSanctam** [comment]
Hmm so the issue might have to do with AMD CPUs? That is kind of weird though since I haven't really touched any code pertaining to any of that.

**Comment by boff64** [comment]
I will try to run it on i7 5th gen now

**Comment by boff64** [comment]
<img width="630" alt="Screenshot 2021-05-14 at 11 35 25" src="https://user-images.githubusercontent.com/28629110/118252051-a1622000-b4a8-11eb-98ed-f20537b162f9.png">
Still same

**Comment by boff64** [comment]
This is 1 minute graph, it does that every 30 sec aprox

**Comment by boff64** [comment]
It does submit shares as before the update

**Comment by UnamSanctam** [comment]
Hmm, I'm not too sure what the problem is since I*m not able to reproduce it.

**Comment by boff64** [comment]
If you want, I can give you anydesk to my pc so you can test it

**Comment by boff64** [comment]
I can send you my miner so you can try to run that, I've tried my own compiled version and precompiled, both have a same problem.

**Comment by UnamSanctam** [comment]
Sure, send me the .exe.

**Comment by boff64** [comment]
Friend, I found a problem. Now when I've compiled a version for you without assembly and online config file it works like it should

**Comment by boff64** [comment]
I think online config file is a problem, I'll try it now again

**Comment by boff64** [comment]
Tested 100% problem with online config file, when I turn it on it starts to bug

**Comment by UnamSanctam** [comment]
What settings are you using in the 'Remote Configuration' file?

**Comment by boff64** [comment]
It gets data right, I've tried different .name/email and it gets that from url. 
[main]
algo=rx/0
pool=xmr-eu1.nanopool.org
port=14433
wallet=4ADX.....dsda.w2/explorer
password=
keepalive=true
nicehash=false
ssltls=true

**Comment by boff64** [comment]
File is uploaded to VPS as config.txt

**Comment by UnamSanctam** [comment]
If you disable keepalive doe sit still happen?

**Comment by boff64** [comment]
I'll try it now

**Comment by boff64** [comment]
Yea, that was a problem

**Comment by UnamSanctam** [comment]
Ah ok, some pools have a problem with keepalive, although I believed that it worked fine with nanopool but it seems like it doesn't.
