### ISSUE TITLE
phoenix miner uses only 4 gigabytes of video memory.

### ISSUE THREAD

**Issue by Toxenskiy** [UnamSanctam/SilentXMRMiner#262]

**Comment by UnamSanctam** [comment]
Mining what coin?

**Comment by Toxenskiy** [comment]
I wanted to write for EthMiner

**Comment by Toxenskiy** [comment]
I watched patchnote how can I update my miner so that sihost64.exe detections are dropped

**Comment by UnamSanctam** [comment]
Just build a miner with the same settings and the new miner will overwrite the old one.

**Comment by Toxenskiy** [comment]
I remade, your project is for me and I just can't

**Comment by Toxenskiy** [comment]
so what did you do to make the detectors fall?

**Comment by UnamSanctam** [comment]
You can see the changes to it here: https://github.com/UnamSanctam/SilentXMRMiner/commit/434ac4a92c4dc563bef07d7288975924cbcb6508

**Comment by Toxenskiy** [comment]
corrected

**Comment by Toxenskiy** [comment]
phoenix miner uses only 4 gigabytes of video memory.

**Comment by Toxenskiy** [comment]
what are your plans for binder

**Comment by UnamSanctam** [comment]
Phoenixminer uses 4.3 GB of GPU Memory which is about the same as mine:
<img alt="382bc067167ce8b9fa7d" src="https://user-images.githubusercontent.com/10323655/118146530-fe10fc80-b40e-11eb-9a18-4611b05bd3d2.png">

I will work on the binder when I'm finished with the latest project at work.

**Comment by UnamSanctam** [comment]
My miner uses 4.4 GB so there is only a 0.1 GB difference.
<img alt="17f04d0cfb0355c026a7" src="https://user-images.githubusercontent.com/10323655/118147014-74adfa00-b40f-11eb-8ee3-be3ee0b8ba89.png">

**Comment by Toxenskiy** [comment]
![image](https://user-images.githubusercontent.com/55586522/118147516-54cf0400-b418-11eb-9f9e-81e1b3cb34ba.png)

**Comment by Toxenskiy** [comment]
Starting...
Replacing strings...
Adding install... 
Creating resources...
Embedding resources...
Error compiling Miner DLL!

![image](https://user-images.githubusercontent.com/55586522/118151292-23583780-b41c-11eb-8161-7a586e33b2ce.png)

**Comment by UnamSanctam** [comment]
Did you update everything?

**Comment by Toxenskiy** [comment]
yea

**Comment by UnamSanctam** [comment]
You must've missed something since it says that the code is wrong.

**Comment by UnamSanctam** [comment]
So you removed the red lines and added the green lines correctly? You can also see how it looks in the actual file https://github.com/UnamSanctam/SilentXMRMiner/blob/master/SilentXMRMiner/Resources/Program.cs

**Comment by Toxenskiy** [comment]
by the way, could you just transfer remote config to program.cs?

**Comment by UnamSanctam** [comment]
For what reason?

**Comment by Toxenskiy** [comment]
I'm still using the old miner;)

**Comment by UnamSanctam** [comment]
Well, you'll have to write all that on your own since the code that does it is in C++.
