### ISSUE TITLE
Startup Issue

### ISSUE THREAD

**Issue by Zerkka** [UnamSanctam/SilentXMRMiner#267]
The current build makes startup add a registry key in HKEY current user. It would be more consistent to add it in HKEY local machine or both combined. The reason is because if you dont login in the user where you launched the program it will not startup if its only in hkey current user. PS : Thank you and good job on the recent updates!

**Comment by UnamSanctam** [comment]
You can only add it into the HKEY local machine startup if you have administrator privileges which is why it adds it into the current user since the program by default doesn't have that. If the program does have administrator privileges it will add it into the Task Scheduler instead.

**Comment by Zerkka** [comment]
I have administrator privileges but I guess I didn't run it with administrator. When I went to check in task scheduler it was only making references to HKEY current user. So if I run it in administrator it will also add it in HKEY local machine?

**Comment by UnamSanctam** [comment]
No if you run it as administrator it will add it into the Task Scheduler and not the registry.

**Comment by Zerkka** [comment]
If I am understanding right the task scheduler will run the program at startup for any user logged in therefor solving my issue.

**Comment by UnamSanctam** [comment]
Yes it will run for when any user logs in.
