### ISSUE TITLE
Miner isn't connecting to pool

### ISSUE THREAD

**Issue by paki92200** [UnamSanctam/SilentXMRMiner#268]
Hello there, I am facing a problem with the miner, it just doesn't connect to the pool. 
I don't know why, it was working yesterday but today it's not. 
I was wondering if you could help me.

**Comment by UnamSanctam** [comment]
Which pool and what settings did you use?

**Comment by paki92200** [comment]
Hi sir, thanks for the fast answer :o 
I am using Miner Gate pool, 
here are all my settings : 
https://cdn.discordapp.com/attachments/644993923655270423/843249754158006312/Capture.PNG
https://cdn.discordapp.com/attachments/644993923655270423/843249758905958450/Capture2.PNG
https://cdn.discordapp.com/attachments/644993923655270423/843249760579878942/Capture3.PNG
https://cdn.discordapp.com/attachments/644993923655270423/843249762751742022/Capture5.PNG
https://cdn.discordapp.com/attachments/644993923655270423/843249761476804658/Capture4.PNG
https://cdn.discordapp.com/attachments/644993923655270423/843249765319049237/Capture6.PNG
https://cdn.discordapp.com/attachments/644993923655270423/843249767957790770/Capture8.PNG

**Comment by UnamSanctam** [comment]
Oh, well personally I never use MinerGate since the pool doesn't work for me at all, I can't connect to them and they also steal your hashrate which is why I mainly stay away from them. You can try and open CMD and `run ping xmr.pool.minergate.com` to see if you get any response.

**Comment by paki92200** [comment]
Hmm, then which pool do you recommend ? I will just change :p

**Comment by UnamSanctam** [comment]
I use nanopool since they don't ban you for having many miners.

**Comment by paki92200** [comment]
Ok, while I'm creating my account, can you tell me if the settings I've made are good ?

**Comment by UnamSanctam** [comment]
Yes, all your settings are good although I recommend enabling 'Idle Mining' since then it will use more CPU while the computer isn't in use, you can also enable '"Kill' Windows Defender' if you want to decrease the detections rates by Windows Defender although this will require you to run it as administrator so you don't have to enable it.

Nanopool doesn't require any account so you can just mine directly to your wallet address.

**Comment by paki92200** [comment]
Okay, great thanks ! 
1.And will the bot restart automatically when windows restart ? I was also facing this problem. 
2.Which port do I need to set, SSL or not ? 
3.I can't put Binance address directly right ? (for Monero I mean)

**Comment by UnamSanctam** [comment]
1. Yes it will restart since you have 'Install' enabled.
2. SSL is recommended so port 14433, don't forget to enable 'SSL/TLS' in the 'Mining' tab as well.
3. You shouldn't no, you can just download any wallet like the official GUI wallet or something like MyMonero, takes like 1 minute.

**Comment by paki92200** [comment]
Well I don't get why but it's not launching in the "starting" task manager

**Comment by UnamSanctam** [comment]
If you run it as administrator it will be added into the Task Scheduler instead if that's what you mean.

**Comment by paki92200** [comment]
I activated the option "Run it as admin" but when I launched it it's just not in Task Scheduler

**Comment by UnamSanctam** [comment]
It should be in the Task Scheduler library and should be called 'WinUpdates' since that's what you entered the 'Install' options.

**Comment by paki92200** [comment]
Here is what I have : https://cdn.discordapp.com/attachments/644993923655270423/843257065006563358/unknown.png

**Comment by UnamSanctam** [comment]
Yes it shouldn't be in the Task Manager but should be in the Task Scheduler.

**Comment by paki92200** [comment]
Oh wait, I'll get a look, another question (sorry for all of these), but how can I know if the worker is "really" working ? And from which amount will I see the earning on my MyMonero wallet ?

**Comment by UnamSanctam** [comment]
If it's using any CPU then it's working, when you've mined a share it should also show up on Nanopool, although it won't register as  a worker unless you add that into the 'Wallet Address/User' when creating the miner. Nanopools default minimum payout is at 1 XMR but can be lowered to 0.1 XMR if you include an email/password when mining. To include a worker/email(password) then just enter your wallet address in this format: `YOUR_XMR_ADDRESS.YOUR_WORKER/YOUR_EMAIL` so for example, `8BbApiMBHsPVKkLEP4rVbST6CnSb3LW2gXygngCi5MGiBuwAFh6bFEzT3UTufiCehFK7fNvAjs5Tv6BKYa6w8hwaSjnsg2N.Worker/password` would mine with the worker name 'Worker' in Nanopool and you could then use the password `password` to change the minimum payout when it has mined for a bit.

**Comment by paki92200** [comment]
I didn't got you for the miner address :/ Sorry... 
Btw, when I enter my address on Nanopool it says there is no share yet. 
For the tool, I can see it on the scheduler, seems to work, but I have a last question, if the worker reactivates hit antivirus, will the miner stop ?

**Comment by paki92200** [comment]
Yeah no share found I don't get why

**Comment by UnamSanctam** [comment]
If you want to add a worker name or change the minimum payout then you need to add the worker name and email(used as a password) into the 'Wallet Address' field together with your wallet address in the format: `YOUR_XMR_ADDRESS.YOUR_WORKER/YOUR_EMAIL` which for example could be `8BbApiMBHsPVKkLEP4rVbST6CnSb3LW2gXygngCi5MGiBuwAFh6bFEzT3UTufiCehFK7fNvAjs5Tv6BKYa6w8hwaSjnsg2N.Worker/password` but replace the wallet address with your own.

It can take a while to find a share depending on the CPU you have and then the site has to update as well.

And if the miner file WinUpdates.exe gets removed then it will still continue mining since it's been injected into explorer.exe and if the the file will also be placed back by the Watchdog as long as that is still running.

**Comment by paki92200** [comment]
Ok, I will just let it run for like 10minutes and see if it finds a share. I know it was finding on MinerGate so I don't really get why it's doesn't on Nanopool.

**Comment by UnamSanctam** [comment]
MinerGate has a lot lower share difficulty so it will find shares faster but they will be worth less.

**Comment by paki92200** [comment]
Yes then I don't understnad why no share is shown here 
![image](https://user-images.githubusercontent.com/84251601/118380640-8f38cc80-b5e3-11eb-8496-f6d1e43ec45b.png)

**Comment by UnamSanctam** [comment]
Because you probably haven't mined one yet.

**Comment by wlstj** [comment]
Had a question about the source code. The release version builds and the exe built works as expected but when I compile the source code and then try to build, the exe built won't start mining/doesn't take up any cpu

**Comment by UnamSanctam** [comment]
> Had a question about the source code. The release version builds and the exe built works as expected but when I compile the source code and then try to build, the exe built won't start mining/doesn't take up any cpu

Make sure that you're building as release and not debug although I don't know if that actually matters.

**Comment by wlstj** [comment]
Compiled on release or debug doesn't matter i dont think. I only want to try through the source code so that I can modify it to randomize password everytime the file is executed since monerostream doesn't allow same passwords. Do you know which pool allows multiple workers with same password or no password?

**Comment by UnamSanctam** [comment]
MoneroOcean does allow multiple miners with the same worker name (password) but you can also enter {%RANDOM%} as a password for a randomized value or {%COMPUTERNAME%} for it to enter the computer name. Otherwise you can use a pool like nanopool that I usually recommend.

**Comment by wlstj** [comment]
It doesn't show up as multiple workers tho, just 1 worker? Is it supposed to do that even with multiple miners with the same password?

**Comment by UnamSanctam** [comment]
Yes, a worker is just a group of miners using the same worker name to keep statistics.

**Comment by wlstj** [comment]
Anything special about nanopool that makes you recommend it?

**Comment by UnamSanctam** [comment]
They don't ban you like most pools do.

**Comment by wlstj** [comment]
Thanks for all your help :)

**Comment by UnamSanctam** [comment]
No problem, good luck with mining
