### ISSUE TITLE
DOGECOIN

### ISSUE THREAD

**Issue by 0x069** [UnamSanctam/SilentXMRMiner#269]
Hello, Can you make a silent DOGECOIN Miner ?

**Comment by UnamSanctam** [comment]
You don't mine Dogecoin with normal computers, just like Bitcoin. Dogecoin and Bitcoin are mined with specialized ASIC miners and mining them with a normal computer would get you like $0.00001/day.

**Comment by j0er00t** [comment]
> You don't mine Dogecoin with normal computers, just like Bitcoin. Dogecoin and Bitcoin are mined with specialized ASIC miners and mining them with a normal computer would get you like $0.00001/day.

this site is working for dogecoin https://unmineable.com/coins/XRP

**Comment by UnamSanctam** [comment]
I should mention that on unminable you just mine coins like Ethereum and then they pay your for the Ethereum in currencies like Dogecoin.

**Comment by j0er00t** [comment]
> I should mention that on unminable you just mine coins like Ethereum and then they pay your for the Ethereum in currencies like Dogecoin.

damn yes i understand mate rep+
