### ISSUE TITLE
My interface is like this

### ISSUE THREAD

**Issue by zoubaba1997** [UnamSanctam/SilentXMRMiner#27]
![image](https://user-images.githubusercontent.com/73113267/103858410-3b791c80-50f3-11eb-98ef-3719ee995387.png)

**Comment by zoubaba1997** [comment]
After I configured it, he didn't work
![image](https://user-images.githubusercontent.com/73113267/103858569-8eeb6a80-50f3-11eb-8e84-9a717b192056.png)

**Comment by UnamSanctam** [comment]
That's weird, maybe the interface becomes like that due to Chinese character scaling or something, I will try to fix it in the next version. 

Also, what pool address and password did you enter? It won't connect if they're wrong.

**Comment by zoubaba1997** [comment]
> 这很奇怪，也许由于汉字缩放等原因，界面变得像这样，我将尝试在下一版本中对其进行修复。
> 
> 另外，您输入了什么池地址和密码？如果他们错了，它将无法连接。

think you

**Comment by UnamSanctam** [comment]
Test the newest version, I have fixed a lot of things.

**Comment by zoubaba1997** [comment]
> 测试最新版本，我已经修复了很多问题。

Okay, thank you very much.
