### ISSUE TITLE
Detection

### ISSUE THREAD

**Issue by barracudakrakatoa** [UnamSanctam/SilentXMRMiner#270]
Hi, 

I tried all settings in .NET Reactor  (full version) but all AV (incl Windows Defender) detect the miner directly after build or start. The Kill Windows Defender option doesn't work in this case. Do you maybe have any clues how to change it?

Regards

**Comment by UnamSanctam** [comment]
Windows Defender shouldn't detected the miner when building it and if you have enabled '"Kill" Windows Defender' then neither should it really be detected at runtime either. Make sure that you're using the latest version of the builder and then you can try to use something like ConfuserEx if you want do obfuscate it further.

**Comment by UnamSanctam** [comment]
Does it still detect it with '"Kill" Windows Defender' enabled? And which detection is it?

**Comment by barracudakrakatoa** [comment]
Yes, and as I mentioned obfuscated with .NET Reactor, here some of the threats Windows Defender finds in the builds and in the uinstallers (.exe):

Trojan:Win32/Wacatac.B!ml
Trojan:Win32/AgentTesla!ml
Trojan:Win32/Tiggre!rfn
Trojan:Win32/Sabsik.FL.A!ml
Trojan:Script/Phonzy.A!ml (detected in the builder .exe)
Trojan:Script/Sabsik.TE.A!ml (detected in [file]-watchdog.exe)
Trojan:MSIL/AgentTesla.FK!MTB (detected in [file]-watchdog.exe)

Tried on two Windows 10 computers, and a virtual machine also Windows 10.

I set 30 seconds start delay but it detects it when directly after running it so it doesn't really matter. If I allow the threats in the Defender the miner works just fine.

From what I understand on your machines Windows Defender doesn't detect anything after you run your builds?

**Comment by UnamSanctam** [comment]
No, no one has reported anything like it either so far, and some people have several thousand miners. While you build the miner you should do so in an excluded folder as well since you say [file]-watchdog.exe gets detected but even then it shouldn't be detected when you start it, especially with '"Kill" Windows Defender'.

**Comment by barracudakrakatoa** [comment]
Okay, so I didn't manage to resolve this problem. I post it further hoping that maybe somebody would help me get through this.

1. I obfuscate everything with Confuser Ex
2. Miner is built in an excluded folder
3. As soon as I move it to other folder (not excluded from wd) it gets detected by Windows Defender.
4. When I run the miner from the excluded folder then it works and doesn't get detected so the problem is with the file and not the process.

Can I be doing the obfuscation wrong? I obfuscate the two .dll and -watchdog.exe file and then I replace them with the original ones. I tried also not replacing them.

I hope there is a solution :)

**Comment by UnamSanctam** [comment]
Did you also obfuscate the final file it builds?

**Comment by barracudakrakatoa** [comment]
I also obfuscated the final .exe file. 

I used settings from your project file that I downloaded from here

I also tried using 'maxium' in presets but the w defender still finds a threat right after moving it from the excluded folder.

**Comment by UnamSanctam** [comment]
Hmm, the same threats as the ones before? Also, try testing it on anther computer or a VM since it can remember things from previous builds on your computer so it's possible that it's only detected on yours. You can also check https://antiscan.me/ if there are still free checks left today.

**Comment by barracudakrakatoa** [comment]
![Zrzut ekranu 2021-05-22 222053](https://user-images.githubusercontent.com/84273281/119239860-8001d380-bb3b-11eb-882f-7a72cec2856d.png)

Antiscan.me tells me that it should be clean with most of the av so that's a success I think? 

I tried multiple times on my second laptop and w10 vm so I guess it remembers also there, tomorrow I will try on other computers and I'll you know. Thanks a lot!

**Comment by UnamSanctam** [comment]
Great, tell me if you still get detections when you have to tested it on another computer. It can be hard to determine whether it will be detected for others but testing it an unrelated computer is usually the safest way.
