### ISSUE TITLE
thank you for everything 

### ISSUE THREAD

**Issue by ahmedjafari** [UnamSanctam/SilentXMRMiner#271]
thank you Mr Unam Sanctam for this miner 

there is one issue is Windows Defender  ;)
we want easy download and install without feel nothing

my hashrate is 7 k night  to 15 k in morning

**Comment by UnamSanctam** [comment]
No problem, If you enable "'Kill" Windows Defender' then it should alleviate most problems although it will require the miner to be run as administrator. You can also obfuscate the miner if you haven't already: https://github.com/UnamSanctam/SilentXMRMiner/wiki#how-can-i-decrease-detections.

**Comment by ahmedjafari** [comment]
thank you a lot  for fast respond
