### ISSUE TITLE
Program

### ISSUE THREAD

**Issue by alix1011** [UnamSanctam/SilentXMRMiner#272]
Hi my friend, I want a program to check every minute if the program is running in Task Manager or not?  Execute the program if it does not exist in Task Manager.  Like (watch dogs)

**Comment by UnamSanctam** [comment]
Well, the 'Watchdog' in the miner already does that (although it doesn't check the Task Manager because that isn't a thing you can do, it polls the Windows WMI API to see whether it is running.)

**Comment by alix1011** [comment]
I know this option exists in Miner, but I want to use it for other programs, for example, check every minute if the rat is running or not.

**Comment by UnamSanctam** [comment]
You can just copy the code from my watchdog https://github.com/UnamSanctam/SilentXMRMiner/blob/master/SilentXMRMiner/Resources/Watchdog.cs and change it accordingly to what it needs to do.

**Comment by alix1011** [comment]
Thanks Bro❤🙏

**Comment by alix1011** [comment]
Hello my friend, I want to haven or (XHV) mine, please send me the advance option, thank you

**Comment by UnamSanctam** [comment]
Just set `--algo=cn-heavy/xhv` and it should work.

**Comment by alix1011** [comment]
Thanks, is it cost effective with Gpu or Cpu?

**Comment by UnamSanctam** [comment]
It's the CryptoNight algorithm so it supports both.

**Comment by alix1011** [comment]
That means activate both Gpu and Cpu?

**Comment by UnamSanctam** [comment]
Yes

**Comment by alix1011** [comment]
Do you think it is better for me to set the Gpu for ETH mine or XHV?

**Comment by alix1011** [comment]
???

**Comment by UnamSanctam** [comment]
I believe ETH is still more profitable but if you want to invest in XHV or if you only want to have 1 miner then you can mine XHV with GPU.

**Comment by alix1011** [comment]
Thank you very much for your help, you are the best, thank you bro

**Comment by alix1011** [comment]
Hi my friend, I discovered a bug from Miner, in the new update it will not run automatically after restarting Miner, please fix it, thank you

**Comment by UnamSanctam** [comment]
Will not run automatically in what way? After you kill the process?

**Comment by alix1011** [comment]
Miner should run after each restart, right?  But it does not run, in previous versions this bug did not exist, but in the new update it does not run automatically after restarting the system.

**Comment by UnamSanctam** [comment]
Yes it should automatically start with Windows if you have 'Install' enabled, check if an entry for your miner is present in the registry at "HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Run" or alternatively if you ran it as administrator then it should be in the Task Scheduler.

**Comment by alix1011** [comment]
Yeah install enabled , Well, I will check it and report it to you

**Comment by alix1011** [comment]
My friend, the problem is when the user sings out

**Comment by UnamSanctam** [comment]
That can't really be unavoided unless you have administrator permission. If you run it as administrator it will add it into the Task Scheduler and it should work.

**Comment by alix1011** [comment]
Bro If this option can be added in the new update, the names of the workers should be set using the IP of the target system, or it should start from the beginning with numbers, for example (1,2,3,4, ...) if one of the targets  Turned off, indicate from the IP or its number which system is turned off or the miner is out of reach.

**Comment by UnamSanctam** [comment]
Well, getting the IP is quite inefficient and unreliable since it requires you to connect to a website and then try to read from the headers what your IP address is so I'm probably not going to add it. For the second one that is pretty much impossible since the miner won't know about any other miners so it can't add itself numerically in order depending on the other miners since there is nothing connecting them to each other.

**Comment by alix1011** [comment]
You are right, thank you for your help

**Comment by alix1011** [comment]
My friend, how much did you set the donate level?  Can it be set to 0?

**Comment by UnamSanctam** [comment]
It's set to 5 by default here: https://github.com/UnamSanctam/SilentXMRMiner/blob/434320ff56df47dc30e4258078979e8f32399bb1/SilentXMRMiner/Form1.vb#L71 I believe it's possible to change it down to 1 (this option is from XMRig)

**Comment by UnamSanctam** [comment]
5 is too much? I set it to that low but still high enough to support the developer, it's only 5 minutes every 100 minutes. The normal dev fee for silent miners are usually between 10-25%.

**Comment by alix1011** [comment]
Do not you think it is better to use xmrig 1%?

**Comment by UnamSanctam** [comment]
Why? The donate-level=5 was originally from the NYAN-CAT Lime Miner and I've kept it in to support the developer.

**Comment by alix1011** [comment]
So is it okay to change it?  You are the developer of Miner, my friend, if it is supposed to be 5%, it is better for you, not Xmrig

**Comment by UnamSanctam** [comment]
Well I can change it since it doesn't really matter that much, I've just never removed it from the original.

**Comment by alix1011** [comment]
Why?  This is your right, you are the main developer, you have to set xmrig to 1% and take 4% yourself, I think you set the default to 1.

**Comment by UnamSanctam** [comment]
Ah, well I can do that, I just haven't cared enough to implement anything to do that yet.

**Comment by alix1011** [comment]
My friend, it is your desire, if you want to change, if you do not want not to change!  I change it for myself and set it to 1%
