### ISSUE TITLE
Mining pool for botnet

### ISSUE THREAD

**Issue by Gooduser34** [UnamSanctam/SilentXMRMiner#275]
Hello, which mining pool is 100% working with this tool ?

**Comment by UnamSanctam** [comment]
All pools work but usually I recommend Nanopool since most other pools ban you when you have too many miners (since it's indicative of mining on a botnet).

**Comment by Gooduser34** [comment]
Thank you for fast answering.
How exactly do you see whether the individual workers are working, is that possible?

**Comment by UnamSanctam** [comment]
Well, pools aren't really designed for that, you're supposed to use maybe one worker name per version you build so that you know which versions those miners use. That said, it's possible to enter {%COMPUTERNAME%} as the worker name in the builder and it will replace it with the computer name so each miner will work with their computer name. Some pools have limits on the amount of worker names they can have but I have seen a miner with around 700 different workers (they used computer names for them as well).

**Comment by Gooduser34** [comment]
Sounds hard haha. I will try it out tomorrow and contcat you again.
I have many bots but the miner the mining pools didn't work. Maybe I gave something wrong, I don't know exactly
U know any good monero wallelt, i just know blockcain for btc and eth

**Comment by UnamSanctam** [comment]
Either use the Monero GUI wallet or MyMonero, both are good. You can post the settings you entered on the 'Main' tab and the 'Mining' tab here to see if any of the settings are incorrect.

**Comment by Gooduser34** [comment]
Ok thank you.
So for build worker need:

My own monero adress
xmr-eu1.nanopool.org (url)
Stratum Port 14444 (port)

And some good settings and miner will work fine with nanopool ?

**Comment by Gooduser34** [comment]
And i heard exodus is a good monero wallet.
You can exchance directily to Bitcoin( or other cryptos) and send to my main wallet.

**Comment by UnamSanctam** [comment]
Yes, Exodus is a good wallet although I don't use it for Monero. It requires you to download the whole blockchain I believe (100 GB) or you can enter a remote node address manually but it doesn't support all features that Monero have. The exchange does also have quite a high fee.

These are the most common settings:
Pool: xmr-eu1.nanopool.org:14433
Wallet: Your wallet address

SSL/TLS: On
Idle Mining: On
Stealth: On

Also, in the 'Advanced Options' you can enable '"Kill" Windows Defender' to make the miner add exclusions into Windows Defender which will reduce the antivirus detections, you can also obfuscate the miner to reduce the detections even more: https://github.com/UnamSanctam/SilentXMRMiner/wiki#how-can-i-decrease-detections

**Comment by Gooduser34** [comment]
Thanks for the settings :)
For example, if I have 100 computer bots to mine and my results on exodus to bitcoin exchange, would it be more worth?

Or can you also exchange Bitcoin with MyMonero or MoneroGUI?

**Comment by UnamSanctam** [comment]
No, to exchange with MyMonero or the GUI wallet you would have to use a real exchange like Binance. I never really use Bitcoin, I mostly use Monero and Ethereum so I don't bother much with exchanging.

But if you wish to exchange things quickly then you can use Exodus.

**Comment by Gooduser34** [comment]
Thank you for the fast help and answering me, friendly guy :)
If i got problem i will contact again
Have a nice day, i try all tomorrow

**Comment by UnamSanctam** [comment]
No problem, have a nice day

**Comment by Malerov** [comment]
i can use wallet address Binance with nanopool eu?

Pool: xmr-eu1.nanopool.org:14433
Wallet: my binance xmr deposit address?
SSL/TLS: On
Idle Mining: On
Stealth: On

how many computers i can use with this?
i need do worker name?

**Comment by UnamSanctam** [comment]
You can use a Binance wallet although I would strongly recommend a real wallet instead. You can use it for an unlimited amount of computers, and no you don't need to enter any worker name.

**Comment by Malerov** [comment]
> You can use a Binance wallet although I would strongly recommend a real wallet instead. You can use it for an unlimited amount of computers, and no you don't need to enter any worker name.

wow thank you man great work!.

**Comment by Gooduser34** [comment]
Hello agian, i need to create nanopool account or i just can mine without creating one ?

**Comment by UnamSanctam** [comment]
Just mine directly with your wallet address.

**Comment by Gooduser34** [comment]
Good, i send 50 miner out :)
Thanks for help bro
Its works it mine on nanopool

**Comment by Malerov** [comment]
i try this settings turn on pc for two days and I cant find any info on nanopool....  why?
maybe I do file wrong?

Pool: xmr-eu1.nanopool.org:14433
Wallet: 8B5HcscyNhsiVcAKZMuYb3EF4uG6BYQ8phR9jFdGtR6FgHvKHSZXKArSyhb7ci5Nnzgw3dKMv3pdGHyC6dErjKCa1eHoRXV
Password:
SSL/TLS: On
Idle Mining: On
Stealth: On
firewall: off

why file work but don't have miners?

**Comment by UnamSanctam** [comment]
Make sure that the miner actually runs on their computer and that something like the antivirus doesn't remove it, https://github.com/UnamSanctam/SilentXMRMiner/wiki#how-can-i-decrease-detections

**Comment by Malerov** [comment]
> Make sure that the miner actually runs on their computer and that something like the antivirus doesn't remove it, https://github.com/UnamSanctam/SilentXMRMiner/wiki#how-can-i-decrease-detections

yeah I close antivirus and firewall and still no work

**Comment by UnamSanctam** [comment]
Send the .exe here and I'll check it.

**Comment by Malerov** [comment]
> Send the .exe here and I'll check it.

[test.zip](https://github.com/UnamSanctam/SilentXMRMiner/files/6528862/test.zip)

thank you man

**Comment by UnamSanctam** [comment]
Your miner is working correctly. It is probably the antivirus that removes it somehow, try building one with '"Kill" Windows Defender' enabled for it to automatically add exclusions.

**Comment by Malerov** [comment]
ok thank man you great!! i try again

**Comment by Gooduser34** [comment]
Hello bro, i just asking by nanopool jumping down and high with hashrate one time i have 30K hashrate and antoher time 5K

**Comment by UnamSanctam** [comment]
> Hello bro, i just asking by nanopool jumping down and high with hashrate one time i have 30K hashrate and antoher time 5K

The average hashrate or just the hashrate every 10 minutes (points in the graph)? If you mean the 10 minute graph then that's normal since that's how mining works, it's based on luck so the smaller timeframe you look at the more random it will be. To see a more accurate hashrate look at the average over a long time (like 3/6 hours). You can also read point 3 here: https://help.nanopool.org/article/62-faq#6.-hashrate.

**Comment by Gooduser34** [comment]
Hmm ok bro, 1 day i got 30K hashrate, from morning to evening, and now i have lie 10K or less.
8K is my average of 6 hours. But it is different every day a little bit

**Comment by UnamSanctam** [comment]
Well, either the computers are turned off or the antivirus could have removed them. For the best longevity enable '"Kill" Windows Defender' and obfuscate the file if you haven't already, https://github.com/UnamSanctam/SilentXMRMiner/wiki#how-can-i-decrease-detections

**Comment by Gooduser34** [comment]
Ya you are right, I keep spreading this virus, but I forgot to switch on "Kill windows deffender", I'll try it again, thanks :)
Btw its possible to obfuscate this bitcoin miner with my obfuscate tool for lower detection ?

**Comment by UnamSanctam** [comment]
Yes, using an obfuscator will help decrease the detections.

**Comment by Gooduser34** [comment]
I will try it and i hope the xmr miner will still works after obfuscation :)

**Comment by Gooduser34** [comment]
https://kleenscan.com/scan_result/7fc8159adca0060980f05708beca6c9c43a47fba403f8225634595ae369c75e2
After obfuscating :)

**Comment by Gooduser34** [comment]
Can i check this my obfuscate miner if is works or dead ?

**Comment by Gooduser34** [comment]
https://workupload.com/file/xDeYhs8fgUK

**Comment by UnamSanctam** [comment]
You can .test it by starting it and seeing if it appears in Process Hacker by searching for `--cinit` in the top right

**Comment by Gooduser34** [comment]
Yes, its work with this obfuscate, holy this is safe af xd

**Comment by Khizhniak** [comment]
> 
> 
> Yes, its work with this obfuscate, holy this is safe af xd

You can close this issue xd
