### ISSUE TITLE
Best port to use for supportxmr?

### ISSUE THREAD

**Issue by unkfc** [UnamSanctam/SilentXMRMiner#278]
What would be the most profitable port to use for supportxmr?

Pool Address
The miner will want a pool URL and a port: pool.supportxmr.com:3333
Port descriptions:

3333 Low starting diff
5555 Medium starting diff
7777 High starting diff
9000 SSL/TLS

If you can't get through firewall, try these:

8080 Firewall bypass
80 Firewall bypass
443 Firewall bypass w/SSL/TLS

thats what it says. Which one should I choose?

Is it also profitable to enable the GPU option for the miner?

**Comment by UnamSanctam** [comment]
You can use any since it's just the starting difficulty but I would either recommend 3333 or 9000. Keep in mind though that SupportXMR is known for banning users they believe are mining with a botnet.

**Comment by unkfc** [comment]
![image](https://user-images.githubusercontent.com/76722171/119157793-644ae000-ba0a-11eb-96fa-eca413e316e9.png)
also i selected notepad option but it shows an error.
And does defender disabler work with other antiviruses?

**Comment by UnamSanctam** [comment]
That error means that the Watchdog was built incorrectly, try rebuilding the miner. The '"Kill" Windows Defender' option runs commands that Microsoft has added to enable control of WD through the command line so no it won't work on others.
