### ISSUE TITLE
Android(apk miner)

### ISSUE THREAD

**Issue by Gooduser34** [UnamSanctam/SilentXMRMiner#279]
It is possible to make a android(apk) miner for you ?
Crazy if its possible and working haha :)

**Comment by UnamSanctam** [comment]
Well, you'd earn like $0.03/day per phone and the phones would become very hot and the battery time would be abysmal. Most non-rooted phones would probably just close the program since it's using too much battery depending on the phone.

**Comment by Hackedbyu** [comment]
Apk miner youtube 11minerP01aa

**Comment by Gooduser34** [comment]
U right bro :)
