### ISSUE TITLE
Idle mining

### ISSUE THREAD

**Issue by misterbister8123** [UnamSanctam/SilentXMRMiner#28]
is there any way to set the idle mining to 10 seconds or 1 minute?
also could u add conhost.exe to the injection thing

**Comment by misterbister8123** [comment]
also in install add hide the file

**Comment by misterbister8123** [comment]
like file attributes

**Comment by misterbister8123** [comment]
or another idea i got, when hes on the pc it does 10% cpu and when hes idle for 1 minute it goes to 50%

**Comment by UnamSanctam** [comment]
Firstly, I'll look into adding the option to hide the "Install" file in the next version and likewise I can add conhost.exe as an option.

Secondly, I have not added a way to change the Idle Mining time because that would require me to modify the XMRig code more than I would like to (because it would make updating it to newer versions a lot harder). I might have figured out a way to do it with the least amount if impact that I will try out in the next version though. And also, due to the same aforementioned reason I have not opted into adding a way of changing the amount of CPU it uses when Idle instead of pausing as it currently does.

**Comment by misterbister8123** [comment]
you have the code for the idling thing, i could make one myself if there was like a miner stopper inside the stub

**Comment by misterbister8123** [comment]
yo also, isnt the idle miner only 1 line of code?

**Comment by UnamSanctam** [comment]
The Idle code is not 1 line and is directly inside the XMRig binary so you would have to add it into the XMRig code and then compile it yourself to make any changes.

**Comment by misterbister8123** [comment]
i have got a idling thing way but its a whole different app in c#, it wouldnt be that hard if there was like a process.kill way in ur stub already built in, i think its possible but im not sure thats why im asking u

**Comment by UnamSanctam** [comment]
My miner injects the XMRig binary into a process and then closes down completely to hide itself so it cannot run any other code after it has injected the actual miner.

**Comment by misterbister8123** [comment]
owh, alright i havent got any other stealth ways to make it more hidden, cuz thats all of what u actually can do to hide it, but do u know how much idle mining effects the monero u earn? cuz idk

**Comment by UnamSanctam** [comment]
Depends entirely on how often the client leaves their computer running while they aren't actively using it. So if you want to use Idle it depends if you want to maximize profit or stealth, the most common settings are either Max CPU at 20-40% without Idle or 60-80% with Idle for maximum profit to stealth ratio.

I might look into allowing to change the Max CPU during Idle and while not Idle in the next version but it would require quite a myriad of code changes to add new config options so I still have to think about it.

**Comment by misterbister8123** [comment]
yeah, ill put 10% cpu with no idle, and like 50 when idle, so they wont notice it

**Comment by misterbister8123** [comment]
also when u enable install does it install into AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup, and registry? or doesnt it change shit if u put it to AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup

**Comment by UnamSanctam** [comment]
It copies the file to the path chosen in the "Install" tab, which by default is the Temp folder and then adds the miner to "HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Run" in the registry.

**Comment by misterbister8123** [comment]
owh i see, one last thing u can do to make it more look like a real app is obfuscation, when i put the application to dnspy i could get my wallet address and password in like 2 seconds, but when i put the application to themidia it says its already packed why?

**Comment by UnamSanctam** [comment]
Obfuscation should be done by the user after the miner is built since programs specifically built for obfuscation are almost always better and not everyone wants obfuscation in case they are going to modify it in some other way.

**Comment by misterbister8123** [comment]
but why does it say the app is already obfuscated?

**Comment by misterbister8123** [comment]
also the app breaks when i use phoenix protector

**Comment by UnamSanctam** [comment]
They might think it's already obfuscated since it contains encrypted programs (the miner and DLLs) so use another obfuscator that is better made and it should work.

**Comment by misterbister8123** [comment]
im using peuniun features alphabetic obfuscation string encryption and string literal encryption and hidden, that also decreases the detection rate from i think it was 12 to 7

**Comment by misterbister8123** [comment]
but when do u think u will make the max cpu update, so i know is it worth waiting rn or i should be doing something else

**Comment by misterbister8123** [comment]
aaaaaaaaaaaaaaaaaaalso last feature that can be good and easily added fake error and open delay

**Comment by UnamSanctam** [comment]
I guess those could be added, I just have to be careful not to add too much since people tend to not understand what they do. But I am not sure when I'll release the new version since I have some other work to do and it depends on when that will be finished.

**Comment by misterbister8123** [comment]
ight ight, cuz fake error is a thing i need, cuz the app doesnt open anything anyway and a fake error doesnt make the victim scared. open delay like 1 min so they will look at task manager for like 23 seconds and see nothing and be like oh okay

**Comment by misterbister8123** [comment]
yo theres a problem with the max cpu, im putting it to 10% and its taking 30%, also the idle mining one mines like 50% cpu until i click then it goes to 0 and starts counting

**Comment by UnamSanctam** [comment]
These feature have now been added in the latest version.

**Comment by shainodev** [comment]
> These feature have now been added in the latest version.

this is me in another acc, thanks

**Comment by shainodev** [comment]
another suggestion, is it possible to add more startup ways not just windows folder startup, like registry startup, userinit startup, or would it raise detection?

**Comment by UnamSanctam** [comment]
Haven't tested enough so right now it only has registry startup but might add others if they are reliable enough,
