### ISSUE TITLE
Is the miner mining for the developer too?

### ISSUE THREAD

**Issue by DigitalGiorgiAptsiauri** [UnamSanctam/SilentXMRMiner#280]
Hi, just want to clarify this point. Does this miner also mine for the developer's address for some portion of the time? 

In other words, should I consider donating when I make something, or is it already being donated/payed?

**Comment by UnamSanctam** [comment]
The XMR miner does a dev donation although I personally do not currently get anything from that one.

**Comment by DigitalGiorgiAptsiauri** [comment]
`I personally do not currently get anything from that one`
Can you clarify that? I mean, say my miner runs for 1000 hours, for what portion of the time is it mining for you?

**Comment by UnamSanctam** [comment]
If you mine for 1000 hours then it's by default set to mine 45 hours to the XMRig dev and 5 hours to me.
