### ISSUE TITLE
What If I Set Its Level To 0

### ISSUE THREAD

**Issue by pinak77** [UnamSanctam/SilentXMRMiner#281]
Hey I found this when I was monitoring the process in which the miner was injected i.e. explorer.exe, when I watched its command line I found this donate-level=5 and I found the same in the source so, what if I set it to 0? will it stop mining or what? 
![Annotation 2021-05-23 152659](https://user-images.githubusercontent.com/76965106/119255916-c9a1fb00-bbdb-11eb-9000-721de3f5ea87.png)

**Comment by UnamSanctam** [comment]
It's from XMRig, you should be able to set it to 1 to reduce the donation amount or set it higher to increase it.

**Comment by pinak77** [comment]
will it work If I set it to 0?

**Comment by pinak77** [comment]
> It's from XMRig, you should be able to set it to 1 to reduce the donation amount or set it higher to increase it.

will it work If I set it to 0?

**Comment by UnamSanctam** [comment]
I think 1 is the lowest amount in XMRig.

**Comment by pinak77** [comment]
> I think 1 is the lowest amount in XMRig.

btw why the source is not compiling in visual studio? It says Invalid Resx file

**Comment by UnamSanctam** [comment]
Check that the file it asks for is there.

**Comment by pinak77** [comment]
> Check that the file it asks for is there.

its not there bro it shows me this error

 Invalid Resx file. Could not find file 'C:\Users\user\Desktop\SilentXMRMiner-master\SilentXMRMiner\Resources\Mandark.dll'. Line 123, position 5.

**Comment by UnamSanctam** [comment]
Check that your antivirus didn't remove it.

**Comment by pinak77** [comment]
its already turned off bro since I downloaded the source

**Comment by pinak77** [comment]
yes bro I got it

**Comment by pinak77** [comment]
I think it was deleted so let me redownload the source. Thank You for your help
