### ISSUE TITLE
mining behind a firewall

### ISSUE THREAD

**Issue by meyerlor** [UnamSanctam/SilentXMRMiner#282]
Hello,
maybe this is beyond the scope of this particular miner, but i hope you can point me in the right direction :) how is it possible to mine behind a firewall? I think not only the usual port(s) are blocked, but the firewall also uses a blacklist with the common mining pool adresses. Is it somehow possible to get through using a proxy or something?

**Comment by UnamSanctam** [comment]
In that case you would probably have to host your own xmrig-proxy and then maybe use some port like 443 (or just any random port) if possible.
