### ISSUE TITLE
Sometimes miners go off on Minergate

### ISSUE THREAD

**Issue by paki92200** [UnamSanctam/SilentXMRMiner#284]
Hello there, I don't know why but sometimes the miner cuts and it's offline on Minergate. 
Could you tell me why ? 
yesterday I had like 10+ workers, and today nothing.

**Comment by j0er00t** [comment]
dont use minergate, use https://xmr.nanopool.org/

**Comment by paki92200** [comment]
Too late for that.. workers already work on Minergate :/

**Comment by dyachenkomark** [comment]
Minergate is stealing your hashrate, it is better to use nanopool.
