### ISSUE TITLE
binder?

### ISSUE THREAD

**Issue by j0er00t** [UnamSanctam/SilentXMRMiner#285]
hello world

i try many method and binders to bind my server file with other tools and spread it and many many many peoples download it,
but there is no connection nothing works.

so is binding good or we just use direct files without binder??

and i use nanopool

**Comment by UnamSanctam** [comment]
Can you send your mining settings here?

**Comment by j0er00t** [comment]
@UnamSanctam here mate all my settings

https://i.imgur.com/RLq6cTJ.png
https://i.imgur.com/KX6I2mz.png
https://i.imgur.com/WND6kfz.png

**Comment by UnamSanctam** [comment]
Those settings are correct as far as I can see, if it doesn't work then their antiviruses could be removing the miner, try enabling '"Kill" Windows Defender' (since you already run it as administrator anyways) and see if that makes any difference.

**Comment by j0er00t** [comment]
> Those settings are correct as far as I can see, if it doesn't work then their antiviruses could be removing the miner, try enabling '"Kill" Windows Defender' (since you already run it as administrator anyways) and see if that makes any difference.

yes sure my friend thanks for you :)

**Comment by Gooduser34** [comment]
Woks fine with binder
