### ISSUE TITLE
Variable Error

### ISSUE THREAD

**Issue by RyloB** [UnamSanctam/SilentXMRMiner#286]
![image](https://user-images.githubusercontent.com/84995385/120042395-fbe69a80-bfd7-11eb-941c-8e9e7feb7db2.png)
I'm having this error, I have no idea why. I opened the app like usual, entered my pool information and other things but it just keeps responding with this error message.

**Comment by UnamSanctam** [comment]
Will appear if something entered is really wrong (meaning it can't compile), what does it stop at in the build log? And could you screenshot the settings you've entered?

**Comment by RyloB** [comment]
> Will appear if something entered is really wrong (so it can't compile), what does it stop at in the build log? And could you screenshot the settings you've entered?

Hey! Thanks for the fast response, I managed to fix it. Anyone else who runs into this problem the fix is not enough storage on the drive, I thought it must've been wrong but I forgot I've recorded like 400gb of footage in the past few days. Good luck!
