### ISSUE TITLE
Name on worker

### ISSUE THREAD

**Issue by Fleettelematicssystem** [UnamSanctam/SilentXMRMiner#287]
How do I name the worker?

**Comment by UnamSanctam** [comment]
All pools do it differently, check your pools documentation for how to do it.

**Comment by Fleettelematicssystem** [comment]
I'm using nanopool, to put the name so I put the wallet.nome?

in main in the builder?

**Comment by Fleettelematicssystem** [comment]
I'm using nanopool, to put the name so I put the wallet.nome?

in main in the builder?

**Comment by UnamSanctam** [comment]
Yes, for nanopool put the worker name in the wallet address like so: `WALLET_ADDRESS.WORKER`
