### ISSUE TITLE
How to compile xmrig-proxy on windows?

### ISSUE THREAD

**Issue by Toxenskiy** [UnamSanctam/SilentXMRMiner#288]
How to compile xmrig-proxy on windows according to the guide from xmrig-proxy does not work.

**Comment by UnamSanctam** [comment]
Following https://xmrig.com/docs/miner/build/windows works, otherwise you can just use the pre-compiled proxy.

**Comment by Toxenskiy** [comment]
xmrig-proxy
![image](https://user-images.githubusercontent.com/55586522/120095545-4169ab80-c12f-11eb-85ad-f00b8aab35d0.png)

**Comment by UnamSanctam** [comment]
Well, I think you need something like gcc to built it for Unix. I build it for Visual Studio personally.

**Comment by Toxenskiy** [comment]
in visualstudio I get some errors

**Comment by Toxenskiy** [comment]
![image](https://user-images.githubusercontent.com/55586522/120104842-33338380-c15f-11eb-8ee0-8b3ff1ea7a37.png)

**Comment by UnamSanctam** [comment]
Ah yeah I remember some error like that I think, if you go to the file listed (Job.cpp) you should be able to fix it.

**Comment by Toxenskiy** [comment]
how to use mandark?
Mandark.Mandark.Load("C:\\Windows\\System32\\calc.exe",rawData,"beta"); // not worked

**Comment by UnamSanctam** [comment]
Should be `Mandark.Mandark.Load(rawData, "C:\Windows\System32\calc.exe","beta");`

**Comment by Toxenskiy** [comment]
![image](https://user-images.githubusercontent.com/55586522/120108067-33864b80-c16c-11eb-9f00-cc7c69348504.png)

**Comment by UnamSanctam** [comment]
Where are you loading the Mandark from?

**Comment by Toxenskiy** [comment]
I added it through dependencies

**Comment by UnamSanctam** [comment]
And you have the .DLL in the same folder as the program you're running?

**Comment by Toxenskiy** [comment]
yes

**Comment by Toxenskiy** [comment]
is there any xmrig-proxy for ether? if yes, then give a link

**Comment by Toxenskiy** [comment]
?

**Comment by UnamSanctam** [comment]
No there aren't any good functioning ones.
