### ISSUE TITLE
Detection issues

### ISSUE THREAD

**Issue by Fleettelematicssystem** [UnamSanctam/SilentXMRMiner#289]
Hi,
I performed the obfuscation in the dll files and also in the watchdog exe and also the main file, it is already practically undetectable by the most common avs, however, how to make the avs not detect after the file is executed? Is there a tool or a term I can look for to find out more about it? Even free av services detect and delete the file after its execution.

**Comment by UnamSanctam** [comment]
Well, usually it gets detected because the obfuscations for the Miner DLL isn't thorough enough to remove all code signatures and can sometimes work if using a private obfuscator. But if you enable '"Kll" Windows Defender' then it will be pretty undetectable for Windows Defender.

**Comment by Fleettelematicssystem** [comment]
I used ConfuserEx to perform the obfuscation, if I use a more sophisticated obfuscation tool it would also have an effect after executing the file? I thought this kind of obfuscation would only benefit the file until it runs.

**Comment by UnamSanctam** [comment]
No, obfuscation affects the whole file, the reason it doesn't detect it until it's run is because I encrypt the whole miner DLL and load it at runtime with a loader and the loader isn't detected but the miner DLL code can get detected after it's decrypted and loaded.

**Comment by Fleettelematicssystem** [comment]
I see, thanks for the information. Do you have any recommendations for a more sophisticated private tool? Or, somewhere I can look for them?

**Comment by Fleettelematicssystem** [comment]
can you update the stub to make Fud again?
