### ISSUE TITLE
Fee %

### ISSUE THREAD

**Issue by lorenzocc** [UnamSanctam/SilentXMRMiner#29]
Creator do you take a % fee  of the mining or you base everything on donations? I will use it anyways i was just curious

**Comment by UnamSanctam** [comment]
The XMRig miner fee is there which should be 4%/5% normally, I personally do not take a free.

**Comment by lorenzocc** [comment]
oh thanks for the reply, so I can't mine ethereum with this?

**Comment by UnamSanctam** [comment]
No since it's an XMR miner but I'm pretty sure mining Ethereum with a silent miner isn't really profitable anymore.

**Comment by lorenzocc** [comment]
Do you know where I could find pretty much the same miner but for eth?
sorry for the trouble

**Comment by UnamSanctam** [comment]
No sorry I'm not aware of any and I'm not sure if any exist since they aren't very profitable at mining with CPU which is the main way to silent mine since it is the most compatible.
