### ISSUE TITLE
Resource Monitor

### ISSUE THREAD

**Issue by Khizhniak** [UnamSanctam/SilentXMRMiner#293]
Hey!
I read your code and found that your miner does not stop if it is not "Task Manager, Process Hacker or Process Explorer", but what about "Resource Monitor"(https://en.wikipedia.org/wiki/Resource_Monitor), it is just a lite version of "task manager" but it can still track the miner. (Probably, not tested, but apparently yes).

**Comment by UnamSanctam** [comment]
Yes currently it does not stop for the Resource Monitor since it uses the window class "WdcWindow" and when I tested adding that then it stopped for other Windows programs as well since it seemed like other programs also used the "WdcWindow" as their window class.

**Comment by Khizhniak** [comment]
Ah, that is sadly.
