### ISSUE TITLE
do i need to put a recieving address for the miner

### ISSUE THREAD

**Issue by dsfdsdwcdsfsdf** [UnamSanctam/SilentXMRMiner#295]
do i put my main address from the "account" tab in the wallet gui, or do i need to make a recieving address, because im not getting any crypto

**Comment by UnamSanctam** [comment]
You can use either, check on the pool how much you've mined.

**Comment by dsfdsdwcdsfsdf** [comment]
> 
> 
> You can use either, check on the pool how much you've mined.

i cant   im using nanopool  so ii cant check

**Comment by UnamSanctam** [comment]
Of course you can, just enter your wallet address in the top right box.

**Comment by dsfdsdwcdsfsdf** [comment]
> 
> 
> Of course you can, just enter your wallet address in the top right box.

just did and nothing comes up

**Comment by UnamSanctam** [comment]
What does it say?

**Comment by dsfdsdwcdsfsdf** [comment]
> 
> 
> What does it say?

Remember: to add your account to the database you should find at least one share

**Comment by dsfdsdwcdsfsdf** [comment]
im mining on a vm, so it should work

**Comment by UnamSanctam** [comment]
Then that means that it hasn't mined at least 1 share yet. Mining on a VM is usually very slow since it usually doesn't have much access to any CPU caches like the L3 cache from my experience. It might also not have enough RAM depending on how much you've assigned to the VM.

**Comment by dsfdsdwcdsfsdf** [comment]
> 
> 
> Then that means that it hasn't mined at least 1 share yet. Mining on a VM is usually very slow since it usually doesn't have much access to any CPU caches like the L3 cache from my experience. It might also not have enough RAM to do full mining so it does light mining instead depending on how much you've assigned to the VM.

i left it running overnight so id assume id get atleast a tiny bit

**Comment by UnamSanctam** [comment]
Well, even it if you're mining really slowly then it should probably have found at least one. Can you send your setting that you used here (the 'Main' and 'Mining' tab)?

**Comment by dsfdsdwcdsfsdf** [comment]
> 
> 
> Well, even it if you're mining really slowly then it should probably have found at least one. Can you send your setting that you used here (the 'Main' and 'Mining' tab)?

https://anonfiles.com/5cA6m0zeuf/Screenshot_20_png
https://anonfiles.com/3eAam7z4u7/Screenshot_18_png
https://anonfiles.com/j4A0m5z5u0/Screenshot_19_png

**Comment by UnamSanctam** [comment]
Those setting look correct although I wouldn't recommend putting it at 0% because then it won't mine unless Idle of course. Also, make sure that Task Manager or something similar isn't started since you have 'Stealth' enabled and thus it will pause the miner while it's open.

**Comment by dsfdsdwcdsfsdf** [comment]
> 
> 
> Those setting look correct although I wouldn't recommend putting it at 0% because then it won't mine unless Idle of course. Also, make sure that Task Manager or something similar isn't started since you have 'Stealth' enabled and thus it will pause the miner while it's open.

even with task manager it is still running even though it has stealth on
and i want it to mine only when idle so its less noticable

**Comment by UnamSanctam** [comment]
Show me a screenshot of the Task Manager. Also, it won't be noticeable with Max CPU at 20% either since that's not a lot the only reason it's using more for you is because you're using a VM that you haven't given much CPU to, for any normal computer it won't use as much since they can utilize their whole CPU.

**Comment by dsfdsdwcdsfsdf** [comment]
> 
> 
> Show me a screenshot of the Task Manager. Also, it won't be noticeable with Max CPU at 20% either since that's not a lot of usage. The only reason it's using more for you is because you're using a VM that you haven't given much CPU to, for any normal computer it won't use as much since they can utilize their whole CPU.

i deleted the vm bc it was not working
the vm had 2 cores and was set to 20% non idle and injected into svchost
in task manager it was using 50% of cpu while task manager was open
i just made a new miner and vm, i just put the miner with the settings i gave you into the vm, and the miner is inactive rn while in task manager and the new vm has 3 cores

**Comment by UnamSanctam** [comment]
Yes then it seems like there was something wrong with the VM. If it has 3 cores now then it should be using around 33% CPU if you have it set to 20% Max CPU (since 100%/3 cores=33%, so 33% CPU is the minimum available).

**Comment by UnamSanctam** [comment]
And I just tested it on my main computer and it works.

**Comment by dsfdsdwcdsfsdf** [comment]
> 
> 
> Yes then it seems like there was something wrong with the VM. If it has 3 cores now then it should be using around 33% CPU if you have it set to 20% Max CPU (since 100%/3 cores=33%, so 33% CPU is the minimum available).

i set the miner to 10% and 80% idle  thanks
