### ISSUE TITLE
Detection

### ISSUE THREAD

**Issue by Khizhniak** [UnamSanctam/SilentXMRMiner#296]
Well, i build .exe with Stealth on, Kill "Windows Defender" then encrypted with confused exe-watchdog.dll, exe-watchdog.exe, exe-miner.dll But Windows defender deleted file before even i run it and was saying smth like ~Trojan.LALALA.Blablabla~ Hacker can have acess to your pc.
What i did wrong?

To confuse i was drag dll/exe on filearea, then opened "Protect!" and just pressed "Protect!" button. Maybe cuz of it.

**Comment by UnamSanctam** [comment]
Did you use my project for ConfuserEx as well?

**Comment by Khizhniak** [comment]
> 
> 
> Did you use my project for ConfuserEx as well?

Yes, https://github.com/mkaring/ConfuserEx

**Comment by UnamSanctam** [comment]
I mean, did you load the project with the ConfuserEx obfuscation settings: https://anonfiles.com/BdZ605y4uf/SilentXMRMiner7_crproj or made your own?

**Comment by Khizhniak** [comment]
> I mean, did you load the project with the ConfuserEx obfuscation settings: https://anonfiles.com/BdZ605y4uf/SilentXMRMiner7_crproj or made your own?

own, and I didnt load my setting, all was by default.

**Comment by Khizhniak** [comment]
> 
> 
> > I mean, did you load the project with the ConfuserEx obfuscation settings: https://anonfiles.com/BdZ605y4uf/SilentXMRMiner7_crproj or made your own?
> 
> own, and I didnt load my setting, all was by default.

**Comment by Khizhniak** [comment]
Maybe i should load your setting and then try again.

**Comment by UnamSanctam** [comment]
ConfuserEx uses no settings by default so running it without setting any won't do anything.

**Comment by Khizhniak** [comment]
OH my.. okay, i will load https://anonfiles.com/BdZ605y4uf/SilentXMRMiner7_crproj this. Thank you so much dude
