### ISSUE TITLE
miner using alot of memory

### ISSUE THREAD

**Issue by dsfdsdwcdsfsdf** [UnamSanctam/SilentXMRMiner#297]
im still not getting any crypto even after setting the miner to use 80% of cpu, my settings are fine
the miners working other than that except for its using like 30% of my memory in a 4 core vm
mainly im not getting any crypto

**Comment by UnamSanctam** [comment]
It says account not found on nanopool?

**Comment by dsfdsdwcdsfsdf** [comment]
> 
> 
> It says account not found on nanopool?

yes

**Comment by UnamSanctam** [comment]
Can you send the new .exe here?

**Comment by dsfdsdwcdsfsdf** [comment]
> 
> 
> Can you send the new .exe here?

https://tmpfiles.org/46764/miner.exe

**Comment by UnamSanctam** [comment]
Do you have an unobfuscated version?

**Comment by dsfdsdwcdsfsdf** [comment]
> 
> 
> Do you have an unobfuscated version?

https://tmpfiles.org/46768/miner4u.exe

**Comment by dsfdsdwcdsfsdf** [comment]
https://anonfiles.com/Hfj8t5z3ua/Screenshot_24_png
this was how much memory the obfuscated one was using

**Comment by UnamSanctam** [comment]
That's how svchost works in the Task Manager, since it doesn't host any service (naturally) it won't display any name since it's made to display the name of the service it's hosting. Also, the miner you sent has an incorrect 'Install' name, meaning it's missing the .exe at the end.

**Comment by dsfdsdwcdsfsdf** [comment]
> 
> 
> That's how svchost works in the Task Manager, since it doesn't host any service (naturally) it won't display any name since it's made to display the name of the service it's hosting. Also, the miner you sent has an incorrect 'Install' name, meaning it's missing the .exe at the end.

my bad https://tmpfiles.org/46771/miner4u.exe   the others though i did not make that mistake, it happened to that one bc i was renaming it

**Comment by UnamSanctam** [comment]
The miner works correctly, only reason I can think of that it hasn't mined for you is if maybe you have had the Task Manager, Process Explorer or Process Hacker open so that it hasn't mined anything due to you having 'Stealth' enabled.

**Comment by dsfdsdwcdsfsdf** [comment]
> 
> 
> The miner works correctly, only reason I can think of that it hasn't mined for you is if maybe you have had the Task Manager, Process Explorer or Process Hacker open so that it hasn't mined anything due to you having 'Stealth' enabled.

i left it overnight running with no task manager open
how long do you think it will take with my settings of 80%

**Comment by UnamSanctam** [comment]
Shouldn't be very long, maybe 10-30 minutes.

**Comment by dsfdsdwcdsfsdf** [comment]
> 
> 
> Shouldn't be very long, maybe 10-30 minutes.

if it still wont work do you think i should try a different port?

**Comment by UnamSanctam** [comment]
Sure but that shouldn't really be a problem. Only things I can think of is if you live in a country which has blocked the nanopool server or if you only have like 1 GB RAM or something.
