### ISSUE TITLE
Help kawpow

### ISSUE THREAD

**Issue by Demon4u** [UnamSanctam/SilentXMRMiner#298]
I don't understand what's going on. Does not work. Tested on the nvidia tesla v100. Original XMRig good work

**Comment by Demon4u** [comment]
[r.zip](https://github.com/UnamSanctam/SilentXMRMiner/files/6594808/r.zip)

**Comment by UnamSanctam** [comment]
First of all, if you're planning to mine on several computers then you shouldn't really use NiceHash since they block a lot of IPs (like mine, so I can't connect to their pool server). Does it work if you use another pool?
