### ISSUE TITLE
Remote configuration of xmr

### ISSUE THREAD

**Issue by illegaler** [UnamSanctam/SilentXMRMiner#301]
Sorry for the very simple question, but the format used in pastebin is

```
[main]
algo=rx/0
pool=xmr-us-east1.nanopool.org
port=14433
wallet=~~~~~2CMXjjQnu4Pbc
password=
keepalive=false
nicehash=false
ssltls=true
```

If I want to set the worker name and password in nanopool, can I do it like this?

```
[main]
algo=rx/0
pool=xmr-us-east1.nanopool.org
port=14433
wallet=~~~~~2CMXjjQnu4Pbc.{%COMPUTERNAME%}/testpassword
password=
keepalive=false
nicehash=false
ssltls=true
```

Or do I need to do this?

```
[main]
algo=rx/0
pool=xmr-us-east1.nanopool.org
port=14433
wallet=~~~~~2CMXjjQnu4Pbc.{%COMPUTERNAME%}
password=testpassword
keepalive=false
nicehash=false
ssltls=true
```

**Comment by UnamSanctam** [comment]
The first one is correct but also `{%COMPUTERNAME%}` does not work for 'Remote Configuration' in the current version since the 'Remote Configuration' is directly inside the miner.

**Comment by illegaler** [comment]
Does that mean I can just have `{%COMPUTERNAME%}` in the main settings and not in the remote settings and the name will be random?
Also, which one should I put the password in?

**Comment by illegaler** [comment]
Oh, I'm sorry. By first one, I assume you mean the second configuration.
In other words.
```
[main]
algo=rx/0
pool=xmr-us-east1.nanopool.org
port=14433
wallet=~~~~~2CMXjjQnu4Pbc/testpassword
password=
keepalive=false
nicehash=false
ssltls=true
```
Is this the correct setting?

**Comment by UnamSanctam** [comment]
The 'Main' settings will only be used if the 'Remote Configuration' settings do not work so having it in the 'Main' settings won't matter for it. In the new version it will replace `{%COMPUTERNAME%}` and such inside the miner itself so it will work but I'm currently doing a major, major rework of everything so it's been taking quite a while.

So the only thing that works with the 'Remote Configuration' is a static worker name like:
```
[main]
algo=rx/0
pool=xmr-us-east1.nanopool.org
port=14433
wallet=~~~~~2CMXjjQnu4Pbc.Worker/testpassword
password=
keepalive=false
nicehash=false
ssltls=true
```

**Comment by illegaler** [comment]
In other words, until the new version is released, random names will not work with remotes, and all workers in the pool will have the same name when using the current remote, is that correct?

**Comment by UnamSanctam** [comment]
Yes exactly. When I implemented the 'Remote Configuration' I didn't think about it since I only ever use static worker names.

**Comment by illegaler** [comment]
I see. Then I'll set up the remote configuration after the new version is released.
Thanks for developing and sharing your awesome tool :)
