### ISSUE TITLE
CPU load while gaming / Obfuscation question

### ISSUE THREAD

**Issue by Khizhniak** [UnamSanctam/SilentXMRMiner#302]
What if a guy have bad CPU like i5-4xxx and he open game and cpu runs on 100%, because miner also wants 20% of? Is it possible to stop run miner while gaming or smth?

**Comment by UnamSanctam** [comment]
The mining process runs at a lower priority than processes like games usually do so that shouldn't really be a problem. I've run it on an old i3 while having CS:GO open and didn't experience much difference in lag (from when running it without the miner).

**Comment by Khizhniak** [comment]
Thank you! And i dont want to open new issue, so. 

When I obfuscate the file, can I use 2 or more obfuscators, for example, I will obfuscate the explorer-watchdog.exe file first with ConfuserEx, and then I will glue it with another exe file and encrypt it with the built-in obfuscator in https://github.com/bytecode77/pe-union

**Comment by UnamSanctam** [comment]
Sure I guess, though if you intend to bind it with the watchdog keep in mind that it will start the other program as well every time the watchdog starts.

**Comment by Khizhniak** [comment]
Do you mean that if the build has a watchdog enabled and the final exe I merge with another file, then the dog will also check and run it?

**Comment by UnamSanctam** [comment]
No, only if you merge it with the watchdog. If you merge the final miner file with another file using pe-union it should work.

**Comment by Khizhniak** [comment]
Okay, thank you men. You're the best!
