### ISSUE TITLE
Suspicious activity

### ISSUE THREAD

**Issue by gamethrower** [UnamSanctam/SilentXMRMiner#303]
Why does builder from releases behave differently from one I compiled myself? Your release contacts some IPs and domains. For some reason it launches Firefox.

**Comment by UnamSanctam** [comment]
No it doesn't.

**Comment by gamethrower** [comment]
![image](https://user-images.githubusercontent.com/46888050/121064946-e0963f00-c7d0-11eb-9e4e-a8c7df3d9282.png)
![image](https://user-images.githubusercontent.com/46888050/121065004-f3a90f00-c7d0-11eb-9982-7b6bbdc7e266.png)

**Comment by UnamSanctam** [comment]
You can decompile the program with something like ILSpy and look at the code yourself. I don't know what you're checking it with but it might be clicking these or something:
```
	private void labelGitHub_LinkClicked(object sender, LinkLabelLinkClickedEventArgs e)
	{
		Process.Start("https://github.com/UnamSanctam/SilentXMRMiner");
	}

	private void labelHackforums_LinkClicked(object sender, LinkLabelLinkClickedEventArgs e)
	{
		Process.Start("https://hackforums.net/showthread.php?tid=5995773");
	}

	private void labelWiki_LinkClicked(object sender, LinkLabelLinkClickedEventArgs e)
	{
		Process.Start("https://github.com/UnamSanctam/SilentXMRMiner/wiki");
	}
```

**Comment by gamethrower** [comment]
It's VirusTotal Behavior check. When I upload builder that I compiled myself it doesn't do anything like this.

**Comment by UnamSanctam** [comment]
You would have to ask VirusTotal, you can check the code in with ILSpy and you'll see that it's an exact copy of when you compile it.

**Comment by UnamSanctam** [comment]
Maybe our compile settings are different or something, like in the folder .vs

**Comment by UnamSanctam** [comment]
I've reuploaded a build after I cleared the Visual Studio settings, you can test that one.

**Comment by Khizhniak** [comment]
👀

**Comment by gamethrower** [comment]
> 
> 
> I've reuploaded a build after I cleared the Visual Studio settings, you can test that one.

Where? You didn't upload anything.

**Comment by UnamSanctam** [comment]
I replaced the current version.

**Comment by gamethrower** [comment]
It says last update was 26 days ago.

**Comment by UnamSanctam** [comment]
Yes but I replaced the .zip file of that release. Try it and see.

**Comment by UnamSanctam** [comment]
Since it's not a new release but just a compile of the current one without the Visual Studio settings that contacted those servers which I would guess is something like Microsofts telemetry.

**Comment by gamethrower** [comment]
Now it's identical to my version. I hope it wasn't stealer or something.

**Comment by UnamSanctam** [comment]
You can check the code of the .exe like I said earlier with something like ILSpy, it's not obfuscated. And the miner is 2 years old now without anything like it.

**Comment by Khizhniak** [comment]
🎉I knew UnamSanctam is great guy!

**Comment by Khizhniak** [comment]
@gamethrower You already can close this issue.
