### ISSUE TITLE
windows virtual box 

### ISSUE THREAD

**Issue by silentminer22** [UnamSanctam/SilentXMRMiner#304]
i configured the tool very well with all the instructions but its taking computational power with a file explorer.exe but its not mining 
what could possibly cause that
liike its taking the usual power it takes for mining but nothing is mined what can cause that please help

**Comment by UnamSanctam** [comment]
If it's using CPU then that means it's mining correctly. How do you check whether it's mining or not?

**Comment by silentminer22** [comment]
![Capture](https://user-images.githubusercontent.com/83955445/121277905-70e28b80-c886-11eb-832b-8ffa05c56f9c.PNG)
or this have anything to do with the pool coz have been running but no change in the hasrate

**Comment by silentminer22** [comment]
using minexmr pool.minexmr.com:4444
and other pools like xmrfast.com cpu taken no hashrate change or is the anywere the program crushed iam confused

**Comment by UnamSanctam** [comment]
Because you have so little CPU and RAM it mines in light mode which is really slow so the reason it probably doesn't show up is because it mines at such a slow speed that it will take quite a while for it to find a share.
