### ISSUE TITLE
Im new and bad been trying to get this on my computers  for days 

### ISSUE THREAD

**Issue by xwildcard** [UnamSanctam/SilentXMRMiner#305]
Idk but everytime I downloaded the app i dont even have to unzip and i get a virus also wtf is that paypal amazon bs script running in the back ground is that included or are some of use not suppose to see that, idk ive spent 2 days fucking around had to reset my computer   3 times im getting worried idk how this is suppose to be a silent miner it literally acts like the computers  alive almost like it learn’s how to fuck you more you try and delete it. Not mad just #sweating like a beach 

any advice would helpful im in the process of getting  v4.5.2  but some of my setting were locked and im like yup here we go again on a smoke break rn but gotta go back and delete that shit

**Comment by xwildcard** [comment]
Ow its trying to open my wallet

**Comment by xwildcard** [comment]
v1.3.4 (14/05/2021)

Made the Windows Defender Killer less intrusive, ironically to reduce detections


Lmfao dude it literally took over windows defender and started locking me out of shit and deleting my files wtf is this
Again not hating cause idc really just what the fuck 😂

**Comment by UnamSanctam** [comment]
This is the only real download link https://github.com/UnamSanctam/SilentXMRMiner/releases any other is not legitimate, if you've downloaded it anywhere else then you've probably downloaded a virus.

**Comment by xwildcard** [comment]
Ok thank that is the only one i havent tried

**Comment by Khizhniak** [comment]
😂 ngl its funny.
PRO TIP: Before download any software you can try search in google original link to source file. Example: Google "XMR miner github / Silent xmr miner github / site:github.com PROGRAMM'S_NAME". 

Sorry for my exellent english.

**Comment by xwildcard** [comment]
Ay don’t make fun of my typing skills texting is dumb. my hands are to big

**Comment by Khizhniak** [comment]
kk, close this
