### ISSUE TITLE
How to set worker name for nicehash.com?

### ISSUE THREAD

**Issue by EvilSlesh** [UnamSanctam/SilentXMRMiner#306]
How to set worker name for nicehash.com?
stratum+tcp://randomxmonero.eu-west.nicehash.com:3380.TestPC 
not work

**Comment by UnamSanctam** [comment]
Enter pool: randomxmonero.eu-west.nicehash.com:3380 and wallet address: YOUR_NICEHASH_ADDRESS.TestPC
