### ISSUE TITLE
more profitable crypto?

### ISSUE THREAD

**Issue by LelouchViBri** [UnamSanctam/SilentXMRMiner#307]
hello, is there any other crypto more profitable than xmr that i can mine with the specific program? and is there any advantage/disadvantage?

**Comment by UnamSanctam** [comment]
Not really, most CPU coins are equally profitable to mine. They also fluctuates all the time so there's no definite answer.

**Comment by LelouchViBri** [comment]
i see, thanks for the fast answer!
