### ISSUE TITLE
Something annoying

### ISSUE THREAD

**Issue by Smurfboi007** [UnamSanctam/SilentXMRMiner#308]
So I got everything is working and I got around/i think around 30 workers.

Why I said "I think" is because I can't see the workers name, or anything really, except how much I have earned. 

This is on Nanopool, but on Minergate you can see the exact number of workers. I know it's bad from other perspectives but it's just so annoying not knowing how many actually works and is mining. 

This probably doesn't have anything to do with the miner, but on the ETH miner there's an option to set a workers name, but not on this one. I obviously don't know how these miners work but, why is that?

**Comment by UnamSanctam** [comment]
The ETH miner and the XMR miner uses different URL schemes so the XMR one doesn't have an "automatic" one that tries to figure out how to send the worker name. All pools enter worker names differently so you should always check the pool on how to enter one. For nanopool the way to enter a worker name is to include it inside the wallet address like so `XMR_WALLET_ADDRESS.Worker`

**Comment by Smurfboi007** [comment]
Ah, aight.

Thanks!

**Comment by Smurfboi007** [comment]
So I just gotta build a new miner with `XMR_WALLET_ADDRESS.Worker` as the wallet address

**Comment by UnamSanctam** [comment]
Yes
