### ISSUE TITLE
Now I'm not saying he is....but i mean :/

### ISSUE THREAD

**Issue by xxwild** [UnamSanctam/SilentXMRMiner#309]
So i still have the virus only it completely locked me out of  my pc no admin, safe mode, internet downloads or am i able to view files and use setting also completely took over windows defender, also i am lead to believe i am connected to another pc but I’m not sure on that also can not access 32 or  any way to restore my pc all denied or cant access permissions, well that’s cool but what does that have to do with the script...you might ask. Ah well let me see here............ “breath”......... it’s literally the first 2 download option’s  provided under the code  tab and immediately after choosing to keep files “the download warning” you get infected and the “virus” starts taking over crucial programs/setting’s/files to fix your pc not only that but try and boot up cmd in safe mode run a icacls cmd command to remove all permission it uses windows defender to block you from using icacls again not just that it can be anything literally anything spent 3 days  trying  to fix my pc and shes toast now, i refuse to believe the user UnamSanctam has no idea of this unfortunate overlook 
Latest commit
@UnamSanctam
UnamSanctam
…
29 days ago
Git stats
Files
Type
Name
Commit time
SilentXMRMiner
29 days ago
SilentXMRMiner
LICENSE
2 years ago
LICENSE
README.md
29 days ago
README.md
SilentXMRMiner.png
5 months ago
SilentXMRMiner.png
SilentXMRMiner.sln
2 years ago
SilentXMRMiner.sln
This is were the green button to download would be not the best but you can match it up with what it says on the code page but ill add photos 

Downloads

Pre-Compiled: https://github.com/UnamSanctam/SilentXMRMiner/releases

This one finished first and immediately proceeded to ram it’s huge shlong down my throat 

My Other Miners

Silent ETH (Ethereum) Miner
So you built this one, maybe i wrong but i recall you saying silentxmr wasn’t  build by you or you just used xmr miner and built on it “unsure exactly what the case is but I digress”. Fair enough  but how do you place the link to one that you don’t know gives a virus, and one that you built haven’t downloaded silent ETH but lets be real it definitely gives a virus to 

You told me  “if i got it anywhere’s else it’s probably  a virus” so.... wtf does that mean and were is my post from before and why did you email me at all, wait can u get a person’s email from github, ill have to check on that or maybe it was a pm usnure because i can no longer access the acount ☺️, 

but anyways point is something isn’t adding up here ill wait for a good response because maybe i have been using github completely wrong this whole time and this is how silent miners work completely break your f****** pc. pictures will be provided if i can upload them  if not pm and i will show you the email’s and what i was describing on the code section 

I’m eagerly awaiting your response thank you

“If this gets deleted without response i am re uploading”

**Comment by xxwild** [comment]
Never mind old one wasn’t closed my apologies and it was email from github just checked

**Comment by UnamSanctam** [comment]
I have coded both the Silent XMR Miner and the Silent ETH Miner from scratch (though it was first based on Lime-Miner but I have rewritten everything) and I'm sure there is no malware anywhere. This https://github.com/UnamSanctam/SilentXMRMiner/releases is the only legitimate pre-built download link for the miner. If you've downloaded anywhere else you have probably downloaded a virus from there. None of the behavior you experience has nothing to do with the miner and is easily provable by checking the code.

**Comment by xxwild** [comment]
Dude idk what to tell you i legit download of your links and preceded to fight my computer for days..... 

If you are interested hope in a discord call or anything along those lines i will gladly show you

**Comment by xwildcard** [comment]
![Uploading E51F98E5-0AB3-4593-9072-756A7E8CFC17.png…]()

**Comment by xwildcard** [comment]
![739D93E8-B8C6-46D2-905C-93AB4D31749D](https://user-images.githubusercontent.com/85602802/121769856-f3dc3e00-cb33-11eb-8c9a-314f60da8d03.png)
![359E0573-6691-42E8-9EF3-8EC393617FA1](https://user-images.githubusercontent.com/85602802/121769858-f3dc3e00-cb33-11eb-8879-4ccf55bfa822.png)
![4BFE0DA9-B407-409F-8DED-2A9BD65C664F](https://user-images.githubusercontent.com/85602802/121769859-f474d480-cb33-11eb-8039-578ed9f79a11.png)

**Comment by UnamSanctam** [comment]
I'm currently not at home, but the only two possible scenarios are that either you've downloaded a virus or you're lying. The other issue you linked has nothing to do with this and is already resolved.

**Comment by Smurfboi007** [comment]
Can vouch for UnamSanctam...

I'm certain this is not him. His support is amazing so is the product.

**Comment by xwildcard** [comment]
Ok but how come windows detected a risk  after download then after i unzipped the file it killed my pc and the amazon file that i happened to be there which try’s to steal info im not lying and yeah I’m downright positive one of those link specifically the second one caused the death of my pc not to mention half the files are xmrminer or named something along those lines and its s botnet malware it didn’t bother showing itself until i tried removing it. proceeded to force kill programs and locks out settings

**Comment by UnamSanctam** [comment]
The 'code' button is made by GitHub and I have no control over it. All that button does is downloads the code from the repository (that you can see in cleartext on the code page) which can't be executed so there is a 0% chance that that is what you did.

**Comment by xwildcard** [comment]
This one its not called builder but master or something like that cant remember

**Comment by xwildcard** [comment]
#
![E93873F2-5B3F-4B8C-9FF0-36FF7AE5CC26](https://user-images.githubusercontent.com/85602802/121770353-d492e000-cb36-11eb-802d-b058a1945c82.png)
That one

**Comment by UnamSanctam** [comment]
The master is the code which doesn't have sny immediate files to execute. You also can't get a virus without running something so you can't get a virus just by unzipping something.

**Comment by xxwild** [comment]
Maybe I accidentally ran the program on myself im unsure i don’t remember clicking on it at all but its a possibility all i know is it happened immediately after downloading  the  files and when i pressed keep half way through the download was when all the programs poped up under window’s defender notifications, if that is the case how do i kill the script

**Comment by UnamSanctam** [comment]
A windows defender notification is normal since the code contains an unencrypted crypto miner until you compile the miner but there are no direct executables in the code except in the Resouces folder. What you download isn't a script but a builder that builds a miner, the builder itself doesn't do anything.

**Comment by xxwild** [comment]
It was not the builder it was the other one and i cant for the life of me remember it was master or something similar in  meaning

**Comment by UnamSanctam** [comment]
There is no other one. The master one is the download made by GitHub which contains the source code of the program, you can't run the source code so what you're experiencing must come from something else you've run.

**Comment by xxwild** [comment]
![image](https://user-images.githubusercontent.com/85781677/121770929-4a4c7b00-cb3a-11eb-9eda-e8aa1f23f4f3.jpg)
Im legit not making this up idk what else to say i mean i get nothing out of blaming you for something you didnt do?, but the case is a little extra something  was in that download, that pic is what happens every time  i try and fix a file or restore the computer it learns to lock me out of it, am i wrong or does it look like im connected to someone else’s network/ botnet

**Comment by xxwild** [comment]
But there is nothing else this happened twice from your download one time and i managed to restore before the option to restore was blocked. When i set driver, windows etc backup your file was the only thing I downloaded

**Comment by UnamSanctam** [comment]
There is nothing extra in it, you can see all the commits to the code here: https://github.com/UnamSanctam/SilentXMRMiner/commits/master, the project is open source so anyone can see what the code does. Are you sure that you were on the real GitHub site?

**Comment by xwildcard** [comment]
I mean do you know anyone who would impersonate you and make a whole page just to give  malware disguised as your program lmfao. Its whatever im over this spent way to long trying to fix this computer been awake almost well its been 3days 9 hours now since ive last slept “thx adderal” l  I’m still lost as what to do if you can point me in the right direction idk I’ve tried absolutely everything last resort is buy a windows cd and reinstall off that, but i will close this post after your next reply just incase you have any ideas as to what might work

I apologize for kinda attacking you but if you were in my shoes rn you would think the same thing this is something ive never seen before its mind boggling

**Comment by xwildcard** [comment]
![image](https://user-images.githubusercontent.com/85602802/121771472-8fbe7780-cb3d-11eb-873f-22bee41ba486.jpg)
.....

**Comment by UnamSanctam** [comment]
It's no problem. There are quite a few reposts on forums since it's quite a big miner but I haven't heard of any fake GitHub websites. I would probably reinstall Windows on another harddrive and then move all the files from the current drive there. What that looks like from your screenshot shouldn't really be done by any virus except maybe a scuffed ransomware or something. Most viruses like RATs are pretty undetectable and doesn'rät really

**Comment by xwildcard** [comment]
Yeah it acts like its alive idk how to explain  it almost like “human ai” because how else does it knoe to block me out of stuff you know like what?????  It almost learns never in my life have I experienced this before

**Comment by xwildcard** [comment]
Shot how do i close this??

**Comment by UnamSanctam** [comment]
You probably can't since you don't seem to have privleges to do anything. Reinstalling Windows is the only quick solution I can think of.

**Comment by UnamSanctam** [comment]
What you're describing sounds like some sort of RAT where they were remote controlling your screen but with RATs you can get files and things silently so I'm not sure why anyone would use tge real screen.

**Comment by xwildcard** [comment]
Yeah sadly i don't own a disk or can use a back up 
And dont have another pc or usb so im a in a pickle lol

**Comment by xwildcard** [comment]
And exactly I thought you set this whole thing up to steal my paypal info with that amazon file 😂😂😂, but theres no way someone would be on exactly when i am to block those programs, ill try my best to explain. So once it, they or alien realize’s im close to deleting/destroying it freezes everything except for  what it needs to stop me and block’s that method of trying to delete it, if that makes sense yeah no clue very strange its almost trying its hardest to live so i am now getting more convinced that aliens might be living  in my pc 🤔

**Comment by Khizhniak** [comment]
woto fuck? you just downloaded a virus somewhere and crying to Unam? You can just reinstall windows and do not open .exe files from not trusted sources.

**Comment by xwildcard** [comment]
Did you not read anything i explained exactly why i can not “just restore windows” it gotten so far i get the blue screen of death and cannot access anything forgive me for accusing him when that had been the only thing download since previous restore

**Comment by Gooduser34** [comment]
> So i still have the virus only it completely locked me out of my pc no admin, safe mode, internet downloads or am i able to view files and use setting also completely took over windows defender, also i am lead to believe i am connected to another pc but I’m not sure on that also can not access 32 or any way to restore my pc all denied or cant access permissions, well that’s cool but what does that have to do with the script...you might ask. Ah well let me see here............ “breath”......... it’s literally the first 2 download option’s provided under the code tab and immediately after choosing to keep files “the download warning” you get infected and the “virus” starts taking over crucial programs/setting’s/files to fix your pc not only that but try and boot up cmd in safe mode run a icacls cmd command to remove all permission it uses windows defender to block you from using icacls again not just that it can be anything literally anything spent 3 days trying to fix my pc and shes toast now, i refuse to believe the user UnamSanctam has no idea of this unfortunate overlook
> Latest commit

Add me on discord i try to help you jew#3289

**Comment by LelouchViBri** [comment]
what you're describing has nothing to do with the specific program, you downloaded a virus somewhere else, probably a cracked program or something. only run stuff in a virtual machine.

**Comment by xwildcard** [comment]
Idk if its a virus either, only thing it hasnt done is hacked other devices from my network

**Comment by Khizhniak** [comment]
bro just go to computer master, let him format your HDD and just install new windows
Whats problem?

**Comment by boff64** [comment]
Unam is trusted 100%, this man is lying. "Blue screen of death", Showing sharing of System32 witch is by default restricted by system to share... He is just a liar who is jealous! As you can see, those are all fake problems. He does not even know what he talks about and he doesn't have a Hard disk/USB or reinstall windows, if he is not smart enough to reinstall windows then he can pay 10usd to a technician to reinstall his PC hahahahahh Just go away scammer.

**Comment by xxwild** [comment]
Oh jesus, cause i got the bluescreen after that
You are rushing to the defense of someone who doesn’t need it and. I
provided a aggressive stance to a question i believed was true at the time
thinking to have my stance a argumentative one would show  with my
question’s if he was truthful in his answers which i believe he was.it
concludes to more or less just another thread in a sea of information  that
we call the Internet.   Unam had no problem challenging and providing good
evidence as to why i was wrong im still unsure what happened myself but yes
i do not blame him  nor do i think that he gave me a malware download,
thank you have a nice day mr boff64 😚🙃

**Comment by aquestionpls** [comment]
take the help from Gooduser34 or visit a computer doctor to reinstall windows

don't waste any more time fighting a virus programmed by aliens impersonating Unam 📦 
good luck

**Comment by xxwild** [comment]
That was a joke 😂 and i did many replies ago

**Comment by xwildcard** [comment]
> > So i still have the virus only it completely locked me out of my pc no admin, safe mode, internet downloads or am i able to view files and use setting also completely took over windows defender, also i am lead to believe i am connected to another pc but I’m not sure on that also can not access 32 or any way to restore my pc all denied or cant access permissions, well that’s cool but what does that have to do with the script...you might ask. Ah well let me see here............ “breath”......... it’s literally the first 2 download option’s provided under the code tab and immediately after choosing to keep files “the download warning” you get infected and the “virus” starts taking over crucial programs/setting’s/files to fix your pc not only that but try and boot up cmd in safe mode run a icacls cmd command to remove all permission it uses windows defender to block you from using icacls again not just that it can be anything literally anything spent 3 days trying to fix my pc and shes toast now, i refuse to believe the user UnamSanctam has no idea of this unfortunate overlook
> > Latest commit
> 
> Add me on discord i try to help you jew#3289

Im going to add you didn’t before because i had a apple bill, couldn't download it
