### ISSUE TITLE
No restart after internet drop out

### ISSUE THREAD

**Issue by southernpitbull** [UnamSanctam/SilentXMRMiner#31]
The miners don't seem to reconnect to the pool after an internet blackout. On win 7 they keep running but don't reconnect, and on windows 10 they seem to just shut down. Is there a way you can add a check to see if they're connected to the pool every 15 min or so?

**Comment by southernpitbull** [comment]
Also on the 2miners pool they all show up as a single worker. Is it possible to generate random worker named to help spot slow miners and help differentiate a bit?

**Comment by UnamSanctam** [comment]
The miner does reconnect automatically after the Internet comes back, the miner uses XMRig and I've reconnected plenty of times. And if you enter {%RANDOM%} in the builder as the Worker name it will randomize it every time the miner is started, you can also enter {%COMPUTERNAME%} as the Worker and it will use the computer name as the Worker name (though you should add 1 letter before computer name like this C{%COMPUTERNAME%} to ensure that computer names with Unicode characters don't become blank).
