### ISSUE TITLE
XMR_WALLET_ADRESS.WORKER

### ISSUE THREAD

**Issue by Smurfboi007** [UnamSanctam/SilentXMRMiner#310]
So if you write the workers name to be "name" If I use the same one on another computer will it be something like "Name1". Or will it mine under the same name?

**Comment by UnamSanctam** [comment]
It will use the same name but you can enter `{℅COMPUTERNAME%}` for it to use the computer name.

**Comment by Smurfboi007** [comment]
Alright, thanks!

**Comment by Khizhniak** [comment]
Let's say I have a botnet, can I combine all my workers into one? Using a proxy or other thing?

**Comment by UnamSanctam** [comment]
> Let's say I have a botnet, can I combine all my workers into one? Using a proxy or other thing?

You mean so that it only shows 1 worker for the pool? Then yes xmrig-proxy is what you use, it will divide jobs from the pool into 256 sub jobs so 256 miners will only show as 1 miner for the pool.
