### ISSUE TITLE
Injecting Optional

### ISSUE THREAD

**Issue by pasxalisk** [UnamSanctam/SilentXMRMiner#311]
Can you please add an option for not injecting into other process?

**Comment by UnamSanctam** [comment]
No, it would then have to extract xmrig.exe to somewhere and start that but any antivirus would immediately remove that.

**Comment by pasxalisk** [comment]
The reason i am asking for this is because Windows Defender triggers when the miner is injected into eg explorer.exe

**Comment by pasxalisk** [comment]
Even if you add an exclusion for the file, in the next (daily) update of Windows Defender, it "resets" this exclusion

**Comment by UnamSanctam** [comment]
And if it didn't do that it would get detected immediately anyways since all miners are considered PUP or malware. Just use '"Kill" Windows Defender' when it's reset it will just add it the next time the miner is started.

**Comment by pasxalisk** [comment]
I tried using the "Kill Windows Defender" feature but it doesn't seem to work

**Comment by UnamSanctam** [comment]
It does, did you also enable 'Run as Administrator'?

**Comment by pasxalisk** [comment]
Even tried using a 3rd party Antivirus and adding it to exlusions. Still, when the injection takes place, windows defenders complains again

**Comment by pasxalisk** [comment]
> 
> 
> It does, did you also enable 'Run as Administrator'?

I did. I will try once again. Maybe i did something wrong

**Comment by pasxalisk** [comment]
Also, it seems that the {%COMPUTERNAME%} and {%RANDOM%} do not work when pulling them from a remote configuration file

**Comment by UnamSanctam** [comment]
Correct, they do not in the current version since those are replaced in the injector while the 'Remote Configuration' is retrieved in the miner itself.
