### ISSUE TITLE
Crypt

### ISSUE THREAD

**Issue by Khizhniak** [UnamSanctam/SilentXMRMiner#312]
I'm confused, if i will share a encrypted miner which only detects 2 antiviruses, WHAT gonna happen if people will active upload it on VT?

Will I be able to re-encrypt it later with other parameters and it will again be invisible to antiviruses, or is it in the code?

**Comment by UnamSanctam** [comment]
When it gets uploaded to VT then they will send code signatures to all the AVs so that they can detect the program. You will be able to obfuscate it if those code signatures gets changed when obfuscating it.

**Comment by Khizhniak** [comment]
What does mean "code signatures gets changed when obfuscating it" or maybe how is it possible to do with ConfuserEx?

**Comment by UnamSanctam** [comment]
Obfuscators will change around the code and add/remove things in it and when it does that the code signatures (usually) gets changed. Only problems can be if it detects a code signature or something that the obfuscator didn't change or if it detects some obfuscation method done by the obfuscator.

**Comment by Khizhniak** [comment]
Oh, okay. Thank you!

**Comment by Khizhniak** [comment]
If someone will look for a project for ConfuserEx, then i can offer this one: https://anonfiles.com/3eefs716ue/agressiveprod_crproj

Cuz of 
![изображение](https://user-images.githubusercontent.com/57261690/121939277-87d92000-cd55-11eb-8687-ec5db074952b.png)
