### ISSUE TITLE
Startup not working

### ISSUE THREAD

**Issue by Barenchi** [UnamSanctam/SilentXMRMiner#313]
Hello,

I installed the miner with install function and watchdog both administrator privileges and without and the miner won't start automatically on startup.
 It works with manual input though.

**Comment by UnamSanctam** [comment]
Can you find the registry key in "HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Run" or see it in the Task Scheduler library? Can you also send a screenshot of your 'Install' settings? Although nothing should probably be wrong there.
