### ISSUE TITLE
Settings for supportxmr?

### ISSUE THREAD

**Issue by hadfdushantha** [UnamSanctam/SilentXMRMiner#314]
Hi, I have been trying to add supportxmr but non of my builds show on the pool even I run on 10 pcs for 1 hour. Can you tell me the best settings to use for supportxmr pool?

Thank you.

**Comment by UnamSanctam** [comment]
Don't forget to use a password (Worker name) as it is required by the pool.

**Comment by hadfdushantha** [comment]
That was quick! :) Ok, I will try. Thank you

**Comment by Khizhniak** [comment]
Just a question. How many working hashes / second should be in order for them to start being displayed on the nanopool website

**Comment by UnamSanctam** [comment]
> Just a question. How many working hashes / second should be in order for them to start being displayed on the nanopool website

Any amount, it just needs to submit shares which can take a while with a very low hashrate.
