### ISSUE TITLE
bro nanopool setup

### ISSUE THREAD

**Issue by tonyvettori** [UnamSanctam/SilentXMRMiner#316]
Bro i think my configuration is either wrong or my laptop is just too outdated to produce the required hash rate for nanopool to discover my first share. Ive been mining for about 16hrs and my account has yet to be discovered by nanopool. Could you give any suggestions on the configurations, devices and overall tips to making this work. Id like nanopool to discover my share 1st before i start doing the leg work of spreading. Its either my configuration or my device because I see the miner is working for everyone else or should I use a different pool. Thanks bro...

**Comment by UnamSanctam** [comment]
What CPU and how much RAM do you have? Can you also post your settings here?

**Comment by tonyvettori** [comment]
RAM INSTALLED: 2.00gb
CPU: Celeron (R) Dual-Core CPU T3500 @ 2.10GHZ

Configuration: 
POOL: xmr-us-west1.nanopool.org:14433  (I STAY IN AFRICA , BUT THERES NO AFRICAN BASED SERVER FOR NANOPOOL)

Wallet Address/User: *monero address*
Password: not required

**Comment by UnamSanctam** [comment]
Yeah your CPU and RAM are very bad so you probably have a really really low hashrate. Don't forget to also enable 'SSL/TLS' since you use that port. You can send your miner here and I'll try running it on my computer.

**Comment by tonyvettori** [comment]
nah i can't let you do that bro. So all i need is computers with better RAM and CPU ? got it. 
Thanks my brother Ill update you , if things are still not working out

**Comment by tonyvettori** [comment]
bro have you thought about changing the miner signature so you dont need admin priv to bypass windows defender? or will the code be dysfunctional?

**Comment by UnamSanctam** [comment]
The commands to "bypass" Windows Defender requires administrator privileges to run. If you want to change the code signatures to decrease signature detections then you should use an obfuscator, https://github.com/UnamSanctam/SilentXMRMiner/wiki#how-can-i-decrease-detections. The signatures obviously gets changed on each release since I update the code but since so many use it it gets detected fast.
