### ISSUE TITLE
I'm a complete noob, xmrig.exe not opening, after permissions allowed

### ISSUE THREAD

**Issue by nouratowel** [UnamSanctam/SilentXMRMiner#317]
Hi, so firstly thanks for creating such a great code for all of us to use. Secondly, I'm brand new to github and am expecting a GUI to be opened upon trying to open xmrig.exe (is this an error?), I'm very excited to start using this product, if possible, a beginner friendly guide would be very beneficial considering I can't seem to even get the program open and running. 
Thanks again

**Comment by UnamSanctam** [comment]
You can find pre-built releases here: https://github.com/UnamSanctam/SilentXMRMiner/releases, download the top most "Silent.XMR.Miner.Builder.zip". Most fields in the builder have '?' that you can hover over to get some information, you can also read the wiki: https://github.com/UnamSanctam/SilentXMRMiner/wiki which is a bit more extensive.

**Comment by nouratowel** [comment]
Thanks for the quick reply, I've managed to get the GUI opened! Thank you
