### ISSUE TITLE
Doesn't start mining

### ISSUE THREAD

**Issue by muser20000** [UnamSanctam/SilentXMRMiner#318]
Hey, so I downloaded the pre-compiled version onto a Windows 10 VM. I wanted to test the miner and basically just went with the "standard" options, didn't configure anything special. Windows Defender is turned off as well. The .exe does run, but doesn't seem to start mining at all. All help greatly appreciated.

**My VM settings:**
![image](https://user-images.githubusercontent.com/86350839/123074019-3dbc0280-d417-11eb-8c31-bb9375fe0f80.png)

**Windows Defender:**
![image](https://user-images.githubusercontent.com/86350839/123074230-693eed00-d417-11eb-9133-3d84a1fd546a.png)

**The builder settings:**
Only using minergate to test.
![image](https://user-images.githubusercontent.com/86350839/123074466-9c817c00-d417-11eb-97c1-a78bfbeae97b.png)

![image](https://user-images.githubusercontent.com/86350839/123074584-bae77780-d417-11eb-9039-c89bc7ba4065.png)

![image](https://user-images.githubusercontent.com/86350839/123074619-c2a71c00-d417-11eb-8246-319fe0814729.png)

![image](https://user-images.githubusercontent.com/86350839/123074654-c9ce2a00-d417-11eb-9e0f-ca225dbccdbd.png)

![image](https://user-images.githubusercontent.com/86350839/123074679-d18dce80-d417-11eb-8c90-b4eebbc0901c.png)

![image](https://user-images.githubusercontent.com/86350839/123074732-dce0fa00-d417-11eb-841c-3f4ae20bf7d3.png)

![image](https://user-images.githubusercontent.com/86350839/123074782-ea967f80-d417-11eb-95c2-a61da55d0f64.png)

The .exe starts up and is running, but as you can see in the taste manager it's not mining. (Stealth is turned off)
![image](https://user-images.githubusercontent.com/86350839/123075019-1d407800-d418-11eb-8e8d-2ed2e45022c0.png)

Also tested it with different settings before, but just doesn't seem to work for me. Any idea why? Probably it's something stupid and I'm just not seeing it.. thanks.

**Comment by UnamSanctam** [comment]
Try something other than MinerGate, their servers are usually quite bad and they also steal hashrate. Best is to use something like nanopool or some other pool which won't ban you (most pools ban you if you have "malicious"/"botnet" miners usually meaning over 100 miners).

To use https://xmr.nanopool.org/ just enter these:
Pool: xmr-eu1.nanopool.org:14433
Wallet Address/User: YOUR_XMR_WALLET.Workername/Password

It's good to enter a Workername and Password to be able to change the minimum payout. You can use `{%COMPUTERNAME%}` to make each miner use the computer name as the worker name. https://github.com/UnamSanctam/SilentXMRMiner/wiki#wallet-addressuser

**Comment by muser20000** [comment]
Hey, thanks for the fast reply.
Still doesn't seem to work though.. Here's the updated settings:
![image](https://user-images.githubusercontent.com/86350839/123081608-6b587a00-d41e-11eb-9aee-67a83e223a63.png)

![image](https://user-images.githubusercontent.com/86350839/123081642-77443c00-d41e-11eb-8847-27b7b0c632cd.png)

![image](https://user-images.githubusercontent.com/86350839/123081903-be323180-d41e-11eb-8c57-99320744e8d5.png)

What do I need to enter as the password? The Monero wallet password? If so, why is that needed? 
Greatly appreciate your work, hope to get it running today.

**Comment by UnamSanctam** [comment]
No you shouldn't enter any password for nanopool, can you try downloading Process Hacker and search for `--cinit` in the top right to see if the miner is started?

**Comment by muser20000** [comment]
Will do that and update you.


If no password is required it seems that I understood this wrong, I don't mean the password field in the builder:

**Wallet Address/User: YOUR_XMR_WALLET.Workername/Password**

So what I should enter is just **YOUR_XMR_WALLET.{%COMPUTERNAME%}** ?

**Comment by UnamSanctam** [comment]
Ah, the password you can enter like you did is to change the minimum payout on nanopool so just leave that in, it can technically be anything.

**Comment by muser20000** [comment]
Looks to be running right?
![image](https://user-images.githubusercontent.com/86350839/123084670-b627c100-d421-11eb-83f4-0c950db78203.png)

Ah okay, so I'll just put it to 0.05 or smth like that when in "real" use?

**Comment by UnamSanctam** [comment]
Can you hover over the process and screenshot the box that appears?

**Comment by muser20000** [comment]
The above one still seems to have minergate settings?
![WhatsApp Image 2021-06-23 at 12 57 26](https://user-images.githubusercontent.com/86350839/123085601-b6748c00-d422-11eb-8b69-4ee4f90c0eb8.jpeg)

This is the second one
![WhatsApp Image 2021-06-23 at 12 58 14](https://user-images.githubusercontent.com/86350839/123085629-c1c7b780-d422-11eb-9ca1-9b5d193d6764.jpeg)

**Comment by UnamSanctam** [comment]
Yeah you can kill the MinerGate one, though there shouldn't really be two running since it will check if any are running before it start. Weird thing is that it isn't using any CPU. The VM has internet access correct?

**Comment by muser20000** [comment]
Yeah has full internet access. Do I also need to deactivate Firewall completely? 
The VM should have enough cpu and ram as well..

**Comment by UnamSanctam** [comment]
Hmm, can you run `ping xmr-eu1.nanopool.org` and see if you get a response? The settings look correct and the miner itself is running so the only real thing I can think of is that it can't connect to the pool.

**Comment by muser20000** [comment]
![image](https://user-images.githubusercontent.com/86350839/123086561-da849d00-d423-11eb-89ec-fcf6ab330499.png)

Also works..

**Comment by UnamSanctam** [comment]
Can you try running this (start.cmd)? It's a normal xmrig miner that will just try to mine normally so we can see if there is any issues with that.
[TEST_XMRIG.zip](https://github.com/UnamSanctam/SilentXMRMiner/files/6701355/TEST_XMRIG.zip)

**Comment by muser20000** [comment]
Yup, so you were right with the connection problem.
![image](https://user-images.githubusercontent.com/86350839/123088196-baee7400-d425-11eb-9e67-74f9c74db09b.png)

Now that I know that, could it be because I'm currently in a school/work network and not a normal one? Will try using my phones Hotspot now.

**Comment by UnamSanctam** [comment]
Yeah they could be blocking the ports or something else.

**Comment by muser20000** [comment]
![image](https://user-images.githubusercontent.com/86350839/123088680-5384f400-d426-11eb-89f4-d2266c3bf008.png)

Yup, thanks a lot!

**Comment by UnamSanctam** [comment]
Great, does the miner in Process Hacker use any CPU as well?

**Comment by muser20000** [comment]
One last question, the donation level is what gets sent to you I suppose? How much is it in %? Just wondering, won't take it out. You deserve it haha

And yeah it's working perfectly now.

**Comment by UnamSanctam** [comment]
Great that it's working correctly.

In this version it's at 5% by default (is a remnant from back in the day of the original Lime-Miner), 4% goes to the XMRig dev and 1% to me (calculated as 80% of the dev time is to XMRig and 20% to me, the donation time is calculated as X minutes per 100 minutes so 5% is 5 minutes every 100 minutes). You can change it if you want to it as doesn't really matter to me though you would have to compile the builder yourself with the setting set lower.

**Comment by muser20000** [comment]
Alright, thanks for the info.

With stealth turned on, after closing TM, how long should it take to run again? Doesn't seem to start after pausing. 

If it should startup immediately again no worries, I'll figure it out myself or leave it out. Thanks for your help.

**Comment by UnamSanctam** [comment]
It checks for Task Manager, Process Hacker and Process Explorer every 5 seconds and will start up again if none of them are detected.

**Comment by muser20000** [comment]
Oh okay makes sense then, had process manager opened to check if it's running again lmao

**Comment by muser20000** [comment]
I'm wondering about some other things like obfuscation. Read everything you wrote in the wiki and going to try for myself and with other resources (I'm relatively new to this stuff).

Possible to get you discord, tg or smth or can I ask here about that stuff as well? If not totally understandable.

**Comment by UnamSanctam** [comment]
Sure you can add me on Discord at Unam Sanctam#3135

**Comment by muser20000** [comment]
Added you
