### ISSUE TITLE
Would it be safe for me to test this?

### ISSUE THREAD

**Issue by Gameshift** [UnamSanctam/SilentXMRMiner#320]
How safe would it be for me to test this?

Would I be able to stop it? How?
How would I delete it?

**Comment by UnamSanctam** [comment]
Yes it's perfectly safe to test. To remove it, either run the uninstaller that gets created and it will do everything automatically or you can remove it manually by following this: https://github.com/UnamSanctam/SilentXMRMiner/wiki#how-do-i-remove-the-miner

**Comment by Gameshift** [comment]
That's great thanks! How would people be able to remove it if there's no uninstall? @UnamSanctam

**Comment by UnamSanctam** [comment]
Only reliable way is by following the instructions at https://github.com/UnamSanctam/SilentXMRMiner/wiki#how-do-i-remove-the-miner

**Comment by Gameshift** [comment]
Thank you!
