### ISSUE TITLE
Can't stop/delete miner.

### ISSUE THREAD

**Issue by Gameshift** [UnamSanctam/SilentXMRMiner#321]
I went to my User Profile and deleted Services.exe. However, it just re-appears again and keeps on mining. What do I do?

**Comment by UnamSanctam** [comment]
Follow: https://github.com/UnamSanctam/SilentXMRMiner/wiki#how-do-i-remove-the-miner. You first need to kill the "Watchdog" (sihost64.exe) otherwise the "Watchdog" will just re-add everything.

**Comment by Gameshift** [comment]
I cannot find sihost64.exe @UnamSanctam

**Comment by UnamSanctam** [comment]
If you use Task Manager then try and see if you can find "Shell Infrastructure Host" or otherwise try using Process Hacker.

**Comment by Gameshift** [comment]
Apparently "Shell Infrastructure Host" is an official part of windows and is dangerous to stop.

**Comment by UnamSanctam** [comment]
Try using Process Hacker to find it.

**Comment by Gameshift** [comment]
Still cannot see sihost64.exe

**Comment by UnamSanctam** [comment]
Then the Watchdog is probably killed, try removing Services now.

**Comment by Gameshift** [comment]
Which?

**Comment by Gameshift** [comment]
Nevermind

**Comment by Gameshift** [comment]
Works now thanks! If I restart my PC, will it open again?

**Comment by UnamSanctam** [comment]
If the file isn't there no it won't start, did you also remove the registry key (or the Task Scheduler task if you ran it as administrator)?

**Comment by Gameshift** [comment]
I did not run it as administrator.

**Comment by UnamSanctam** [comment]
Then just remove the miners startup entry at "HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Run" with regedit.

**Comment by Gameshift** [comment]
How can I do this?

**Comment by UnamSanctam** [comment]
With regedit, it's a thing on your computer. You can also use the program "Autoruns" from the internet to find it.

**Comment by Gameshift** [comment]
Done. Thank you! Is there anything else?

**Comment by UnamSanctam** [comment]
No that is all you have to do.

**Comment by Gameshift** [comment]
That is great. Thank you! By turning on GPU Mining how much more does it increase the filesize and does it also go to the MONERO wallet?

**Comment by UnamSanctam** [comment]
The GPU libraries are about 17 MB and it will also mine Monero with the GPU if you enable it but mining Monero with a GPU isn't recommended since Monero is built to be mined only with the CPU. It's better to mine Ethereum or something similar with the GPU https://github.com/UnamSanctam/SilentETHMiner

**Comment by Gameshift** [comment]
Okay thanks! How about with the SilentETHMiner you just linked? How much storage does that take?

**Comment by UnamSanctam** [comment]
The ETH miner is about 2 MB I think.

**Comment by Gameshift** [comment]
CPU OR GPU?

**Comment by UnamSanctam** [comment]
ETH is a GPU coin.

**Comment by Gameshift** [comment]
Thank you!
