### ISSUE TITLE
Need help to launch the builder

### ISSUE THREAD

**Issue by SSLayronn** [UnamSanctam/SilentXMRMiner#323]
Hi I'm a noob and this is what it shows, look ; 
![Screenshot 2021-06-30 213305](https://user-images.githubusercontent.com/86743502/124020641-cffd7100-d9ea-11eb-93de-9a3cd2089d5a.png)
I don't know what to do :))
Thanks !!!

**Comment by UnamSanctam** [comment]
That's the source code, you can find pre-built binaries here: https://github.com/UnamSanctam/SilentXMRMiner/releases

**Comment by SSLayronn** [comment]
Thanks for your fast answer u're amazing sir, I'm downloading the first thing from the link u sent, is that this one ? Look at the screen I'm sending :) 
![Screenshot 2021-06-30 213652](https://user-images.githubusercontent.com/86743502/124021017-5023d680-d9eb-11eb-8757-dc48b4d9040c.png)

**Comment by UnamSanctam** [comment]
Yes that's the one

**Comment by SSLayronn** [comment]
Look, it is empty
![Screenshot 2021-06-30 213906](https://user-images.githubusercontent.com/86743502/124021274-a5f87e80-d9eb-11eb-8dc7-776ad93497aa.png)

**Comment by UnamSanctam** [comment]
Did your antivirus remove it?

**Comment by SSLayronn** [comment]
Huh maybe I think yeah bc it showed a message yeah

**Comment by SSLayronn** [comment]
I'm downloading it again

**Comment by SSLayronn** [comment]
It just showed again a pop up saying they removed the virus but I couldn't download it what should I do

**Comment by UnamSanctam** [comment]
Add an exception to the folder where you download it

**Comment by SSLayronn** [comment]
I'm trying again later brother
![Screenshot 2021-06-30 222123](https://user-images.githubusercontent.com/86743502/124026108-8e23f900-d9f1-11eb-9c25-460b9bb5cb9d.png)
