### ISSUE TITLE
Quick one : xmr-eu1.nanopool.org:14433

### ISSUE THREAD

**Issue by DEXROYHAX** [UnamSanctam/SilentXMRMiner#324]
(delete plz)

**Comment by UnamSanctam** [comment]
All of those ports are for their ETH pool, the ones for XMR are here https://xmr.nanopool.org/

**Comment by DEXROYHAX** [comment]
Thank u,  now i get it,
 i only run this on virtual machine, 
how do i know that the miner is working without testing it on a real machine.
I don't own a second computer.

**Comment by UnamSanctam** [comment]
If you don't enable "Stealth" then you can use something like Process Hacker and search for `--cinit`, if it's using any CPU then it works.

**Comment by DEXROYHAX** [comment]
No how do i know that the wallet is connected to the Nanopool, 
Lets say that i run it on real machine, and it start mining, will i be able to see it up, by searching my address on the nanopool website. thank u again

**Comment by UnamSanctam** [comment]
Yes it will show up. If it's using any CPU then that means it has successfully connected to the pool and is mining which is why that is a good indicator.

**Comment by DEXROYHAX** [comment]
Much appreciated, you can close this issue, you were really helpfull. Next thing is confusion.

**Comment by DEXROYHAX** [comment]
The unistaller works great, i'll give you that.

**Comment by UnamSanctam** [comment]
Great, also if you want to decrease detections then you can read https://github.com/UnamSanctam/SilentXMRMiner/wiki#how-can-i-decrease-detections

**Comment by DEXROYHAX** [comment]
Yeah, i've just read it and went through the obfuscators, tried half of them, none works, it seem all of them got overused. Now none work, i'll figure something out.

**Comment by DEXROYHAX** [comment]
What binder would you recomend i want to pack it with some exe.

**Comment by UnamSanctam** [comment]
You can really use any but usually I use Dream AIO, here is a pre-compiled binary for it https://anonfiles.com/P8T0ce4duf/Dream_AIO_-_Unam_Sanctam_Custom_zip
