### ISSUE TITLE
HELP ME WITH THE POOL

### ISSUE THREAD

**Issue by krispyodnut** [UnamSanctam/SilentXMRMiner#328]
im using nice hash miner address but how do i find pool i really have no idea my discord is donut#6996 if you can help me on there please help 

thanks donut :D

**Comment by UnamSanctam** [comment]
You can check it here: https://www.nicehash.com/stratum-generator
For Monero it is:
Pool: randomxmonero.eu-west.nicehash.com:3380
Wallet Address: Your BTC Wallet
