### ISSUE TITLE
wassup ppl that are using it tell me

### ISSUE THREAD

**Issue by SSLayronn** [UnamSanctam/SilentXMRMiner#329]
Wich thing is better, xmr mining on cpu and both gpu
OR
eth for gpu and xmr for cpu
And how much money can I expect from +- 3400pc please?

**Comment by SSLayronn** [comment]
damn bois look at that shit is it normal?
![Screenshot 2021-07-05 210639](https://user-images.githubusercontent.com/86743502/124511296-13ceec80-ddd6-11eb-812c-d8bfd430abfc.png)

**Comment by UnamSanctam** [comment]
Of course that's normal, the builder itself is not obfuscated or anything so the miner and all the code is exposed which will trigger detections.

The best option is to use XMR for CPU and ETH for GPU. XMR has very low requirements to run but earns a lot less (naturally) while ETH has quite high requirements https://github.com/UnamSanctam/SilentETHMiner#requirements so it will run on less computers but earns a lot more per computer.

XMR on +-3400 computers at 20% CPU would be around $100-$200/day. ETH for +-3400 computers, though unlikely that all of them have a good enough GPU and drivers to run it but let's say that they theoretically have it then it would be around $4000-$16000/day I suppose

**Comment by SSLayronn** [comment]
yup fine I found out how to install it :))
Ok so I'm download eth miner now,

**Comment by SSLayronn** [comment]
Damn idk how to remove fucking mcafee anti virus

**Comment by SSLayronn** [comment]
why tf does it still on my pc I did uninstall it but it still here on my pc blocking my downloads

**Comment by UnamSanctam** [comment]
Did you remove it with the windows Control Panel? You might also have to restart the computer for it to be fully removed.

**Comment by SSLayronn** [comment]
o okay I'm restarting,

**Comment by SSLayronn** [comment]
dude I restart and those mtf of mcafee removed xmr miner and they still here

**Comment by UnamSanctam** [comment]
Can you add an exclusion? Usually you can add an exclusion to a folder or something and after that you can download the builder to that folder.

**Comment by SSLayronn** [comment]
how ? No I don't think I can when I download it it instantly uninstall it and the folder become empty

**Comment by UnamSanctam** [comment]
Can you find McAfee on the computer by searching for it?

**Comment by SSLayronn** [comment]
I didn't download it by myself but lemme check
![Screenshot 2021-07-05 221242](https://user-images.githubusercontent.com/86743502/124514821-3238e600-ddde-11eb-8f59-a0a079405a4d.png)

**Comment by UnamSanctam** [comment]
Yeah try to uninstall that, although I don't think LiveSafe will remove files but maybe it does.

**Comment by SSLayronn** [comment]
so I'm currently waiting for it to be uninstall
![Screenshot 2021-07-05 221421](https://user-images.githubusercontent.com/86743502/124515025-affcf180-ddde-11eb-9851-b88cc766737b.png)

**Comment by SSLayronn** [comment]
less go sir this look so satisfying, what should I do first ? And is it possible to add a backdoor into it? And get user:passwords, cookies credit card informations and more... ? For educationnal purpose ofcourse :)
![Screenshot 2021-07-05 223003](https://user-images.githubusercontent.com/86743502/124515824-a83e4c80-dde0-11eb-9185-2c67d995426d.png)

**Comment by UnamSanctam** [comment]
Well, RATs are better for those kinds of things since the miner only ever really connects to the pool and nothing else. First thing would be to find a pool to use, I usually recommend nanopool since they don't ban but other pools work too. You can find out what all the options do by hovering '?' or by visiting the wikis https://github.com/UnamSanctam/SilentETHMiner/wiki, https://github.com/UnamSanctam/SilentXMRMiner/wik.

**Comment by SSLayronn** [comment]
Damn I'm just thinking about it rn we will not be able to mine anymore on eth 2.0

**Comment by UnamSanctam** [comment]
Well, if you use 'Remote Configuration' https://github.com/UnamSanctam/SilentETHMiner/wiki#remote-configuration then you can just switch it to mine ETC or something when it does change.

**Comment by SSLayronn** [comment]
Oh okay fine, just a question for nanopool do I have to use a user and a password?
I'm setting up monero actually

**Comment by SSLayronn** [comment]
or just my xmr adress

**Comment by SSLayronn** [comment]
wich port should I use ?
![Screenshot 2021-07-05 230053](https://user-images.githubusercontent.com/86743502/124517690-e3427f00-dde4-11eb-8a4f-85eb49b6eb90.png)

**Comment by UnamSanctam** [comment]
For nanopool use port 14433 and enable "SSL/TLS" and then use your normal XMR wallet address.
I would recommend using something like `XMR_WALLET_ADDRESS.{COMPUTERNAME}/12345` in the wallet address field, that is `XMR_WALLET_ADDRESS.WORKER_NAME/PASSWORD`, the password is used to change the minimum payout.

**Comment by SSLayronn** [comment]
wassup thanks, look I'm actually setting up my monero wallet can u help me? 
![Screenshot 2021-07-06 210701](https://user-images.githubusercontent.com/86743502/124653904-290f4e00-de9e-11eb-9213-fd697d9b419c.png)
how should I set up that ?

**Comment by UnamSanctam** [comment]
Well, you can set up your own node with the first setting which is the best one though you will have to download the blockchain which is quite big. You can otherwise use the second option for a remote node where you don't have to download anything and it will work instantly though the security is a lot lower since you use someone else's node. If you want to use a node then you can use `nodes.hashvault.pro` (port `18081`) or any other node you can find.
