### ISSUE TITLE
cant find

### ISSUE THREAD

**Issue by devil1110111** [UnamSanctam/SilentXMRMiner#333]
hi i cant find the donate lvl for this new update in Source code where is it in new update?

**Comment by UnamSanctam** [comment]
I removed it so it should be --donate-level=1 by default now. You can add --donate-level=1 back at the end of the argstr field it you want to.

**Comment by devil1110111** [comment]
and mate i have a problem with miner
its i inject miner into windows explorer but in some pcs it will make a lot of explorer in pc and the pool detect them az miner so it it ruin the pc i use how can we fix that?

**Comment by UnamSanctam** [comment]
Use the latest version,
>Fixed possible critical bug that makes the miner unable to see if a miner is running or not thus opening multiple miners

**Comment by UnamSanctam** [comment]
Do you see it anywhere here: https://github.com/watching?

**Comment by Lordchristy** [comment]
No, thats the problem

**Comment by UnamSanctam** [comment]
Oh, then you're probably subscribed on another GitHub account.

**Comment by Lordchristy** [comment]
Why are you so smart !
