### ISSUE TITLE
Is there any way to make sure i set up my miner correctly with nano pool? 

### ISSUE THREAD

**Issue by zJackk** [UnamSanctam/SilentXMRMiner#336]
I want to make sure that i'll actually be mining xmr but i dont want to put work into it if it's not even working in the first place

**Comment by UnamSanctam** [comment]
If you start it and it's using CPU then it should be working since for it to be able to calculate anything it needs to get jobs from the pool.

**Comment by zJackk** [comment]
> s

Are these settings all good?

pool:  xmr-us-east1.nanopool.org:14444
address: 43w7TzkbW69JVfQQfhr72sNzXENkBZpnKCcATt2hSXiEAwWbWb15g8MLVVksuUMKcZ4BKjPkNDB2DJAUnGQfanh7TpBG7wG

**Comment by zJackk** [comment]
Alright so once i do that how change the minimum?

**Comment by UnamSanctam** [comment]
If you go to your account page (by entering the wallet address in the top right, you have to mine at least one share for it to show) then press the "Settings" button and you should be able to change the minimum payout there, use the password 123456 or whatever you chose.

**Comment by zJackk** [comment]
Alright, thank you
