### ISSUE TITLE
again this problem

### ISSUE THREAD

**Issue by parabola19** [UnamSanctam/SilentXMRMiner#337]
miner settings are the same. I usually create 2 files - with and without launching as admin, and again the file does not work on behalf of the admin (after launching nothing happens, that is, there is no miner in the startup and no processes)

in short, it works with these settings: https://i.imgur.com/DQk3Uhc.png
does not work with these: https://i.imgur.com/tlHbgMi.png

**Comment by UnamSanctam** [comment]
So there is no entry in the Task Scheduler and no explorer.exe for the miner running?

**Comment by parabola19** [comment]
> Значит, в планировщике задач нет записи и нет explorer.exe для запущенного майнера?

yes

**Comment by UnamSanctam** [comment]
And you open the Task Scheduler as admin to check? Since otherwise it won't show the admin scheduled tasks

**Comment by parabola19** [comment]
> And you open the Task Scheduler as admin to check? Since otherwise it won't show the admin scheduled tasks

https://i.imgur.com/BsRCo7C.png

it appeared there, but still not in the processes.

**Comment by UnamSanctam** [comment]
Try running this as administrator, it should show any miners running.
[MinerCheck2.zip](https://github.com/UnamSanctam/SilentXMRMiner/files/6842142/MinerCheck2.zip)

**Comment by parabola19** [comment]
> Try running this as administrator, it should show any miners running.
> [MinerCheck2.zip](https://github.com/UnamSanctam/SilentXMRMiner/files/6842142/MinerCheck2.zip)

https://i.imgur.com/oK4usew.png

**Comment by parabola19** [comment]
> Try running this as administrator, it should show any miners running.
> [MinerCheck2.zip](https://github.com/UnamSanctam/SilentXMRMiner/files/6842142/MinerCheck2.zip)

https://i.imgur.com/ymLXuhN.png
and so, if I run the miner without admin rights

**Comment by UnamSanctam** [comment]
Could you download Process Hacker and see what happens when you start it (what processes appear and where does it all stop)? Do you have a separate administrator user? Meaning that you have to start it as that user to start it (will show when you try to run as administrator)? And as before, do you get any errors at all if you build it with "DEBUG" enabled?

**Comment by parabola19** [comment]
> Не могли бы вы скачать Process Hacker и посмотреть, что происходит, когда вы его запускаете (какие процессы появляются и где все это останавливается)? У вас есть отдельный администратор? Это означает, что вы должны запустить его от имени этого пользователя, чтобы запустить его (будет отображаться, когда вы попытаетесь запустить его от имени администратора)? И, как и прежде, возникают ли у вас вообще какие-либо ошибки, если вы собираете его с включенной "DEBUG"?

the hacker process showed nothing
installed debug. at start - nothing, but when I open the Miner-uninstaller.exe it comes out:
https://i.imgur.com/oTAs5Gu.png

**Comment by UnamSanctam** [comment]
Yes that's normal, like it says at the top. But I mean, Process Hacker must show something, since you start the miner, as default I believe new programs are shown at the bottom so you should scroll down.

**Comment by parabola19** [comment]
> Yes that's normal, like it says at the top. But I mean, Process Hacker must show something, since you start the miner, as default I believe new programs are shown at the bottom so you should scroll down.

i recorded https://anonfiles.com/f1O9557eu6/bandicam_2021-07-19_20-12-13-035_mp4

**Comment by UnamSanctam** [comment]
Can you reupload it? Seems to not work, you could also upload it to GitHub by dragging the file to the reply box.

**Comment by parabola19** [comment]
https://user-images.githubusercontent.com/87057617/126203003-a990eaeb-90f7-43be-8672-a57b61688024.mp4

**Comment by UnamSanctam** [comment]
Remove your sorting, you're sorting it by CPU at the moment so it will be hard to see what happens. You can sort it after "Start time" too see it easier by right-clicking the top with the column names (Name, PID, CPU) and click "Choose columns..." after that you can find "Start time" in the left box and select it, then press the "Show >" button to move it to the left box and press OK. After that you can click "Start time" in the columns to sort it after that. You can then start the miner and you should see the entire program flow happening and where it stops.

**Comment by parabola19** [comment]
https://user-images.githubusercontent.com/87057617/126204287-c756c6ae-c0da-4ea4-9e5e-ac65554f807a.mp4

**Comment by UnamSanctam** [comment]
Does it happen if you disable "Install to System32"?

**Comment by UnamSanctam** [comment]
And what is your "Start Delay"?

**Comment by parabola19** [comment]
> Does it happen if you disable "Install to System32"? And if you go to the folder it's installed in and run that file does it work?

yes it worked when i opened the file in temp folder
delay is 3sec
how now to upload a new version to users if they need to run a file from the temp folder?

**Comment by UnamSanctam** [comment]
Increase the delay, most likely the short delay makes it remove the file it drops after it's already been replaced.

**Comment by UnamSanctam** [comment]
Any delay below 10 seconds will also increase detections due to antivirus sandboxing.

**Comment by parabola19** [comment]
![di-G81QP6](https://user-images.githubusercontent.com/87057617/126206152-84f4bb74-6549-4f65-8a41-ba577a3f2ecf.png)

thank you, you are a genius :)
the only strange thing is that in the previous version I always set 3 seconds and it worked

**Comment by UnamSanctam** [comment]
Yeah it's because of
>* Greatly reduced Windows Defender detections when "Bypass Windows Defender" is enabled by replacing Assembly.Load with simply writing the payload to Temp and executing it since the folders are excluded

Due to this it will drop a file and then remove itself after it's done, but since a file can't remove itself while it's running I have to start a delayed command to remove it after it closes itself which is the same time as the "Start Delay" you had. Because of this the "Installed" miner would start itself and drop the file and it would get removed by the delayed command from before it was installed and thus there is no file to run anymore when it tries to start it. The miner would still work after a restart though.

**Comment by parabola19** [comment]
is it possible to install in System32 xmr and ether miners at the same time?

**Comment by UnamSanctam** [comment]
Yes it will use the "Install" file name for them (by default services32 for ETH and services64 for XMR) so they won't interfere with each other as long as you don't change the file names so they are the same for both miners.

**Comment by sadandnab** [comment]
[main]
algo=rx/0
pool=xmr.pool.minergate.com
port=45700
wallet=can i put minergate email as a wallet address like in xmr silent miner here
password=
keepalive=false
nicehash=false
ssltls=true

**Comment by UnamSanctam** [comment]
Yes that will work the same as the builder.

**Comment by sadandnab** [comment]
![Capture 1](https://user-images.githubusercontent.com/87695790/126348715-9dfb10e9-4287-4020-afc7-57feae7f2d21.PNG)
i did everything correct but it's seems not working for me please check

**Comment by UnamSanctam** [comment]
Hmm, MinerGate doesn't work for me so I can't really check (whole ISP is banned or something), You have ssltls=true, does MinerGate support SSL/TLS? You can try setting that to off.

**Comment by sadandnab** [comment]
so which pool should i use please sugggest. Minergate site is not working smoothly anyway !

**Comment by UnamSanctam** [comment]
Well, I usually recommend Nanopool https://xmr.nanopool.org/ since they haven't banned anyone so far but their minimum payout is a bit high (0.1 XMR).
You can connect with:
Pool: xmr-eu2.nanopool.org:14433
Wallet Address: YOUR_XMR_WALLET.WorkerName/password
And enable SSL/TLS in the "Mining" tab.

The password inside the "Wallet Address" field will be used to change the minimum payout.

Some pools have a limit on the amount of worker names before you get banned (since they might believe you're mining on a botnet) but for nanopool I have seen some miners with 20 000 workers so that should be fine.

**Comment by sadandnab** [comment]
Thanks a lot man you are awesomeX100

**Comment by sadandnab** [comment]
can i skip the worker name and still be able to change the minimum payout like this (Wallet Address: YOUR_XMR_WALLET/password)

**Comment by UnamSanctam** [comment]
Not sure I've never tried it, though I believe a worker name is necessary.
