### ISSUE TITLE
Help with setting up

### ISSUE THREAD

**Issue by CheeseAllegator** [UnamSanctam/SilentXMRMiner#338]
Hello i used 2Miners as pool but it works s bit strange if i open te miner on my virtualmachine than its not always working or smht now i want to switch to nano pool how can i login my dashboard so i can transfer it to my wallet

Edit: Is this good
![screen ](https://user-images.githubusercontent.com/87770217/126517831-7634b29e-51d1-403d-8100-2d636fd92a99.png)

**Comment by UnamSanctam** [comment]
To see the nanopool activity enter your wallet address in the top right corner of the site. Though {%COMPUTERNAME%} doesn't work for 'Remote Configuration' in the current version of the XMR miner. I still have to update it for that but there are a lot more tests to do to ensure that everything works correctly.

**Comment by CheeseAllegator** [comment]
> To see the nanopool activity enter your wallet address in the top right corner of the site. Though {%COMPUTERNAME%} doesn't work for 'Remote Configuration' in the current version of the XMR miner. I still have to update it for that but there are a lot more tests to do to ensure that everything works correctly.

on NanoPool its says "not found
Remember: to add your account to the database you should find at least one share" or does that take some time to get the share?

**Comment by UnamSanctam** [comment]
How long did you mine for? You need to mine a share which since Nanopool has a quite high share difficulty can take like 10-20 minutes, and then the site will have to update as well.

**Comment by CheeseAllegator** [comment]
Okay. I putted te miner on my Virtualmachine now for 5 mins ago and the cpu load is 20-30% so i think its working and if i reach the minium XMR on Nanopool then they automatically transfer it to my wallet?

**Comment by UnamSanctam** [comment]
Yes, and you can change the minimum payout to 0.1 XMR with the password you entered after the / in the wallet address.

**Comment by CheeseAllegator** [comment]
edit its working now only the name is Error because i had %computername% xD

**Comment by UnamSanctam** [comment]
Haha yeah but that should be fine, you can change it in the 'Remote Configuration' at any time.

**Comment by CheeseAllegator** [comment]
![image](https://user-images.githubusercontent.com/87770217/126531114-7c940024-64f3-4897-9cac-a9332aa1d226.png)
can i put here the password i putted after the / in the wallet address

**Comment by CheeseAllegator** [comment]
because its says incorrect

**Comment by UnamSanctam** [comment]
Yes, you need to get at least 10 rating with the worker first, you can see that value in the worker list.

**Comment by CheeseAllegator** [comment]
ah thanks i will try it

**Comment by CheeseAllegator** [comment]
i changed in the remote control the name to worker so new pc wil get name Worker?

**Comment by UnamSanctam** [comment]
Yup, it will get the 'Remote Configuration' when the miner is started.

**Comment by CheeseAllegator** [comment]
ah thanks for now you can close it if i got another question than i will open a new one but i think it will work now
