### ISSUE TITLE
.

### ISSUE THREAD

**Issue by Footsiefat** [UnamSanctam/SilentXMRMiner#34]
.

**Comment by UnamSanctam** [comment]
Probably entered incorrect pool address, wallet address or password.

**Comment by Footsiefat** [comment]
I'm pretty sure it's correct, but to test I'll load up a vanilla version of xmrig and try it ouy

**Comment by UnamSanctam** [comment]
Do that, what pool are you using?

**Comment by Footsiefat** [comment]
SupportXMR

**Comment by UnamSanctam** [comment]
If it doesn't work try using:
Pool address: pool.supportxmr.com:9000
Wallet Address: Your wallet address
Password: WorkerName

Also enable SSL/TLS in the "Mining" settings to use port 9000.

And don't forget that SupportXMR usually bans your account if you have more than 100 miners (without using xmrig-proxy) because they don't allow botnets.

**Comment by Footsiefat** [comment]
alright. also I didn't put in a password because I thought it wasn't needed. also since I don't have an xmrig proxy what should I use if I have or get. more than 100 miners

**Comment by UnamSanctam** [comment]
Yeah all pools have different connection settings required and for SupportXMR a Worker name is required.

But either continue to use SupportXMR but use below 100 miners or use a pool that doesn't ban for having many miners like nanopool or something similar.

**Comment by Footsiefat** [comment]
It seems like it may have a problem injecting into svchost i think becuase it works fine with explorer.exe also are you sure i set the workername in the password feild

**Comment by UnamSanctam** [comment]
Well svchost works for me so I'm not sure about that (could have something to do with permissions or something) but on SupportXMR you should put the worker name in the password field (don't put any spaces though).

**Comment by Footsiefat** [comment]
Well thanks dude. I have two more questions. could I set all the workers to the same name so it appears as it's only one worker? and what free crypter would you recommend and what files would I need to crypt

**Comment by UnamSanctam** [comment]
No even if they use the same name they check the connections and not the worker names to count the amount of miners.

I don't personally use any crypters so I'm not sure which ones are good at the moment, but you only need to crypt the final file you build unless you want to crypt the xmrig.exe in the source code and then compile the builder yourself. That would decrease detection but you'd have to compile it yourself.

**Comment by Footsiefat** [comment]
alright thanks. although if I don't crpyt the xmrig.com won't it be detected once extracted. and if I crypt it will your program still be able to patch it?

**Comment by UnamSanctam** [comment]
Since my miner uses RunPE injection it will bypass most antiviruses like Windows Defender but you can crypt it to avoid even more ones. And it should still work if you crypt it.
