### ISSUE TITLE
Nanopool only showing one worker.

### ISSUE THREAD

**Issue by zJackk** [UnamSanctam/SilentXMRMiner#348]
In the past week i've installed the silent miner on around 10-20 pcs however, nanopool is only showing one worker. Is this normal or is there something that I set up wrong with the miner?

**Comment by UnamSanctam** [comment]
If you use a static worker name like "Worker" then they will all mine under one worker so that is normal. You can use things like {%COMPUTERNAME%} as the worker name for it to use the computers name as the worker name, though this isn't supported in the 'Remote Configuration' currently.

**Comment by Thepowa753** [comment]
> If you use a static worker name like "Worker" then they will all mine under one worker so that is normal. You can use things like {%COMPUTERNAME%} as the worker name for it to use the computers name as the worker name, though this isn't supported in the 'Remote Configuration' currently.

So i need to enable advanced params and add "--rid-id={%COMPUTERNAME%}" at the and of it? 
I'm testing this, but no worker appears 
![immagine](https://user-images.githubusercontent.com/44495483/127134817-29a6d066-238f-4649-bc48-d241d569d6f3.png)

**Comment by UnamSanctam** [comment]
> So i need to enable advanced params and add "--rig-id={%COMPUTERNAME%}" at the and of it?
> I'm testing this, but no worker appears
> ![immagine](https://user-images.githubusercontent.com/44495483/127134817-29a6d066-238f-4649-bc48-d241d569d6f3.png)

No you can just use {%COMPUTERNAME%} as the worker name in the miner like so: `Wallet.{%COMPUTERNAME%}`

**Comment by Thepowa753** [comment]
> > So i need to enable advanced params and add "--rig-id={%COMPUTERNAME%}" at the and of it?
> > I'm testing this, but no worker appears
> > ![immagine](https://user-images.githubusercontent.com/44495483/127134817-29a6d066-238f-4649-bc48-d241d569d6f3.png)
> 
> No you can just use {%COMPUTERNAME%} as the worker name in the miner like so: `Wallet.{%COMPUTERNAME%}`

Sorry for wasting your time :/
You mean in main tab, i write my xmr address dot that var   (like:   94LA...PaG.{%COMPUTERNAME%})

**Comment by UnamSanctam** [comment]
Yes exactly

**Comment by Thepowa753** [comment]
Not working too 🙈

I've tested on linux with pure xmrig and with --rig-id=test it shows up correctly :(

**Comment by UnamSanctam** [comment]
What pool are you using?

**Comment by Thepowa753** [comment]
2miners
I've also tested with debug, but nothing usefull.
Without any custom options it starts

**Comment by UnamSanctam** [comment]
Yeah for 2miners you have to use --rig-id, you should probably try --rig-id="{%COMPUTERNAME%}" at the end of the "Advanced Parameters" and don't enter any worker name into the wallet address.

**Comment by Thepowa753** [comment]
Things i've done to test:
disable install
disable stealth
disable online downloader
enable debug (no errors showing up)
cpu 100% usage

things tested:
--rig-id="{%COMPUTERNAME%}"
--rig-id="%COMPUTERNAME%"
--rig-id=%COMPUTERNAME%
ADDRESS."{%COMPUTERNAME%}"
ADDRESS.{%COMPUTERNAME%}
ADDRESS.%COMPUTERNAME%

what i see:
cpu 100% for the first 2 min and than drops to 25%
no hashrate and no worker showing on 2miners (after waiting fot the first share, around 5/10 mins)


On linux work both --rig-id=worker and ADDR.worker

**Comment by UnamSanctam** [comment]
Hmm, I'm trying to mine to 2miners to test and it's working and I've mined 10 shares now but their site hasn't updated yet so I can't see if it works yes, I have to wait more I guess for their site to update.

**Comment by Thepowa753** [comment]
I let the miner open for 2 our but nothing shows up and cpu is arount 15% all the time. Any idea?

**Comment by UnamSanctam** [comment]
No idea, try something other than 2miners, I've been mining for 32 minutes now (with normal XMRig and my miner, both using different worker names) and submitted a lot of shares and nothing has appeared on 2miners yet, just says
>No miner data available
You need to submit at least a single share to see the stats.

**Comment by UnamSanctam** [comment]
Ah no, when I said that it appeared, --rig-id works correctly for my miner on 2miners.
Could you try downloading this
[MinerCheck2.zip](https://github.com/UnamSanctam/SilentXMRMiner/files/6885275/MinerCheck2.zip)
and copy-paste the miner string here so I can see if anything is wrong?

**Comment by Thepowa753** [comment]
Miners:
C:\Windows\explorer.exe  --cinit-find-x -B --algo=rx/0 --asm=auto --cpu-memory-pool=1 --randomx-mode=auto --randomx-no-rdmsr  --cuda-bfactor-hint=12 --cuda-bsleep-hint=100 --rig-id="CDESKTOPQS" --url=xmr.2miners.com:2222 --user=94LA..Correct_One..PaG --pass= --cpu-max-threads-hint=80

Maybe the --pass= void? In linux i've to put --pass=x
But i know that on previous working exe i leave the pass blank..(1.4.3)

**Comment by UnamSanctam** [comment]
No that should work, what kind of XMR address is that though? Isn't that a testnet address? Shouldn't you use a real one?

**Comment by Thepowa753** [comment]
nono, i just blanked the real one while posting the comment 😅
i'm using my real address like the previous exe that works perfectly (but all grouped with id 0)

**Comment by UnamSanctam** [comment]
So the real address you use starts with a 4 or an 8? Other than that the miner should work, I just mined to 2miners with the same settings and the worker appeared.

**Comment by Thepowa753** [comment]
do you have discord? so i can text you directly there?

**Comment by UnamSanctam** [comment]
Yes you can contact me at Unam Sanctam#3135.

**Comment by Thepowa753** [comment]
Ok, friend request sended. Thank you
