### ISSUE TITLE
SilentXMRMiner + Xmrig-proxy = (

### ISSUE THREAD

**Issue by codexprime** [UnamSanctam/SilentXMRMiner#35]
does not mine through a proxy
tried port and 3333 and 443

workers in proxy logs can be seen
but the mining process itself does not occur to the support and workers do not appear

maybe I did not correctly configure the proxy config itself via tls

in general, I will say that for support mining it is better to use port 3333, since the difficulty itself is lower

**Comment by UnamSanctam** [comment]
Have you enabled Nicehash mining on the miners?

**Comment by codexprime** [comment]
yes i checked
included both nicehash and tls
there are workers in the proxy logs
no supportxmr

**Comment by UnamSanctam** [comment]
Don't use port 3333 with SSL/TLS since that is a stratum port, use port 443 or 9000. Can you post your xmrig-proxy settings here?

**Comment by codexprime** [comment]
{
    "access-log-file": null,
    "access-password": null,
    "algo-ext": true,
    "api": {
        "id": null,
        "worker-id": null
    },
    "http": {
        "enabled": false,
        "host": "127.0.0.1",
        "port": 0,
        "access-token": null,
        "restricted": true
    },
    "background": false,
    "bind": [
        {
            "host": "my ip",
            "port": 9000,
            "tls": false
        },
        {
            "host": "::",
            "port": 3333,
            "tls": false
        }
    ],
    "colors": true,
    "title": true,
    "custom-diff": 0,
    "custom-diff-stats": false,
    "donate-level": 0,
    "log-file": null,
    "mode": "nicehash",
    "pools": [
        {
            "algo": null,
            "coin": "monero",
            "url": "pool.supportxmr.com:9000",
            "user": "my wallet",
            "pass": "x",
            "rig-id": null,
            "keepalive": false,
            "enabled": true,
            "tls": true,
            "tls-fingerprint": null,
            "daemon": false
        }
    ],
    "retries": 2,
    "retry-pause": 1,
    "reuse-timeout": 0,
    "tls": {
        "enabled": true,
        "protocols": null,
        "cert": null,
        "cert_key": null,
        "ciphers": null,
        "ciphersuites": null,
        "dhparam": null
    },
    "user-agent": null,
    "syslog": false,
    "verbose": false,
    "watch": true,
    "workers": true
}

**Comment by UnamSanctam** [comment]
What does it say if you press C in the xmrig-proxy console?

**Comment by UnamSanctam** [comment]
And don't put your IP in the binding host, put 0.0.0.0 to listen on all addresses.

**Comment by codexprime** [comment]
I check on a separately created proxy

there is only one connection in the proxy logs

I will try to check on port 9000 more

maybe deal with tls
I don't understand very well what to do with tls

**Comment by UnamSanctam** [comment]
Under the bind array you can pick whatever port you want, also enable "tls" in the bind array if you have enabled it on your miners. The only place you need to put the pool port (like port 9000) is in the pool array (like "pool.supportxmr.com:9000").

You can also check if your xmrig-proxy port is open by using something like: https://www.yougetsignal.com/tools/open-ports/

Also when you press C what exactly does it say, it should say something like this:
<img width="295" alt="0a67208fe2ded3f2c420" src="https://user-images.githubusercontent.com/10323655/105903100-c462e400-601f-11eb-90b0-1c2a3dca1530.png">

**Comment by codexprime** [comment]
"bind": [
{
"host": "0.0.0.0",
"port": 3333,
"tls": **true**
},
{
"host": "::",
"port": 3333,
"tls": **true**
}
],

I understand something like this? it's about array binding


seems to work)
though other workers who work without tls have fallen off

**Comment by UnamSanctam** [comment]
Yes exactly, although it is possible to add another binding like this for example:
"bind": [
{
"host": "0.0.0.0",
"port": 3333,
"tls": false
},
{
"host": "0.0.0.0",
"port": 4444,
"tls": true
},
{
"host": "::",
"port": 3333,
"tls": false
},
{
"host": "::",
"port": 4444,
"tls": true
}
],
So that mining on port 3333 doesn't use SSL/TLS but port 4444 does.

**Comment by codexprime** [comment]
Thank you!

this is new to me
I would not have thought of

now let's take a look

**Comment by codexprime** [comment]
there is already another nuance

after enabling two ports

hashrate dropped

**Comment by UnamSanctam** [comment]
Hmm there shouldn't be a difference, keep in mind that the hashrate reported in xmrig-proxy is not the same as the one reported in the miners. The xmrig-proxy hashrate is the speed that the miners completes jobs (while miners calculate CPU/GPU speed) so it's best to look at the average over a longer time to get more accurate data.

**Comment by codexprime** [comment]
I will try again
most likely my mistake
it's about spaces

**Comment by rebelsparx** [comment]
codexprime have you tried using a diffent pool for minein i found the best to use hashvault.pro 

also just incase it might be miss leading on sites took me 10 min to work this out (click get started and at bottem ur see some thing like this 

xmrig-proxy --url pool.hashvault.pro:80 --user (YOU WALLET )  --pass x --donate-level 1 --tls --tls-fingerprint 420c7850e09b7c0bdcf748a7da9eb3647daf85985478f36d9ccfdd6b9ff834b14


for the miner builder use

pool.hashvault.pro:80
UR WALLET

**Comment by UnamSanctam** [comment]
No you should use your xmrig-proxy IP in the miner builder, if you use the pool address it will just connect to the pool normally without .

**Comment by codexprime** [comment]
thanks
I am still choosing support
there the payment threshold is less =)

one more question
in array pool
also need to include tls?

**Comment by UnamSanctam** [comment]
Yes enable TLS in the pool array if you use the TLS/SSL pool port (which you do).

Also the minimum payout on nanopool can be changed to 0.1 XMR.

**Comment by UnamSanctam** [comment]
Nice, that's good.
