### ISSUE TITLE
suggestion to make a bitcoin miner if possible

### ISSUE THREAD

**Issue by dsfdsdwcdsfsdf** [UnamSanctam/SilentXMRMiner#352]
i want to purchase things online but some things i want to buy only accept bitcoin
if possible could you make a bitcoin miner?

and is it safe to run the miner on my pc

**Comment by UnamSanctam** [comment]
No you don't mine Bitcoin with normal computers, you only use ASICs to mine Bitcoin so mining on a normal computer would be really slow and unprofitable. Normally you would run the miner and then if you want it in Bitcoin then exchange it to that.

It's safe to run, to remove the miner you can run the uninstaller that gets created.
