### ISSUE TITLE
New file created when obfuscated

### ISSUE THREAD

**Issue by Manwtfjaja1** [UnamSanctam/SilentXMRMiner#354]
I'm using ConfuseEx to obfuscate. However, a new file is created every time I confuse the file, nammed "symbols.map". Do I have to delivery this file joint with the minner? If yes, there is some way to bind this file with the minner and hide then?

When I stop to obfuscate, 3 "symbols.map" are created (one for each file). So how I can joint every file?

Thank you

**Comment by UnamSanctam** [comment]
No I think symbols.map is just for if you even want to disablement the file, it's probably used to link together parts of the code in a disassembler. You can probably just ignore that file.

**Comment by Manwtfjaja1** [comment]
Thank you!
