### ISSUE TITLE
cant save the file

### ISSUE THREAD

**Issue by dsfdsdwcdsfsdf** [UnamSanctam/SilentXMRMiner#355]
when i press build and try to save the miner it says file not found

**Comment by UnamSanctam** [comment]
Does it say anything more than that? Make sure to not enable the "Icon" if you haven't selected any icon.

**Comment by dsfdsdwcdsfsdf** [comment]
> 
> 
> Does it say anything more than that? Make sure to not enable the "Icon" if you haven't selected any icon.

says nothing more, i press save and it says file not found, and it only would possibly work if pick an already existing file, but when i do that it says could not find (file name) watchdog.exe

**Comment by UnamSanctam** [comment]
Try building it in another location.

**Comment by dsfdsdwcdsfsdf** [comment]
> 
> 
> Does it say anything more than that? Make sure to not enable the "Icon" if you haven't selected any icon.

says nothing more, i press save and it says file not found, and it only would possibly work if pick an already existing file, but when i do that it says could not find (file name) watchdog.exe

> 
> 
> Try building it in another location.

that worked thanks
i tried it yesterday but it did not work, but i think it was a certain setting i put in
