### ISSUE TITLE
many views of the remote conf

### ISSUE THREAD

**Issue by parabola19** [UnamSanctam/SilentXMRMiner#356]
this is in 19 days of mining, and it is increasing. should I be worried that this page will be deleted on suspicion of something? I would not like to lose such an army

![ZjR6Z3f](https://user-images.githubusercontent.com/87057617/127611682-58ab46f5-cd0e-4ef3-8e01-5645949146bf.png)

**Comment by UnamSanctam** [comment]
Well, I've seen people with a few million visits so I don't think you should be worried. It's technically possible though of course, the miner will start using the settings you entered inside the builder instead if it does get removed.

**Comment by freakovision** [comment]
Nice! How did you get that many workers?

**Comment by parabola19** [comment]
> Ну, я видел людей с несколькими миллионами посещений, поэтому не думаю, что вам следует беспокоиться. Это технически возможно, хотя, конечно, майнер начнет использовать настройки, которые вы ввели внутри конструктора, вместо этого, если он будет удален.

it would be nice to add a backup link in the new update

**Comment by parabola19** [comment]
> Nice! How did you get that many workers?

asked all his relatives to install it. i live in china

**Comment by parabola19** [comment]
> Well, I've seen people with a few million visits so I don't think you should be worried. It's technically possible though of course, the miner will start using the settings you entered inside the builder instead if it does get removed.

by the way, before you leave: if you open a miner on a computer with a miner already installed, will my miner delete and replace the current one?

**Comment by parabola19** [comment]
> > Well, I've seen people with a few million visits so I don't think you should be worried. It's technically possible though of course, the miner will start using the settings you entered inside the builder instead if it does get removed.
> 
> by the way, before you leave: if I open a miner on a pc with a miner already installed, will my miner delete and replace the current one?

**Comment by UnamSanctam** [comment]
If both miners use the same "Install" "File name" (by default: services32.exe) then yes.

**Comment by parabola19** [comment]
> If both miners use the same "Install" "File name" (by default: services32.exe) then yes.

what if these are two completely different miners?

**Comment by UnamSanctam** [comment]
Then no, there isn't really any way to identify any miner, just like you can't identify my miner either. Only way to identify and remove my miner fully is if you already know where it's installed and what name the file has which you can't really know unless you're the one that built it.

**Comment by freakovision** [comment]
> there isn't really any way to identify any miner

https://github.com/tevador/randomx-sniffer

**Comment by UnamSanctam** [comment]
Yes of course doing that is easy but how would you find and remove the miner with that?

**Comment by freakovision** [comment]
I have no idea. You are the hecker here :)

**Comment by UnamSanctam** [comment]
That can only detect the explorer.exe that the miner is injected into and not the services32.exe (or whatever you named it) which is the part that injects the miner so you wouldn't be able to find it.

**Comment by freakovision** [comment]
> That can only detect the explorer.exe that the miner is injected into and not the services32.exe (or whatever you named it) which is the part that injects the miner so you wouldn't be able to find it.

I think it's possible to detect the parent process which is watchdog. Without it miner will be defeated.

**Comment by UnamSanctam** [comment]
Technically it's possible to find the watchdog (search for sihost32.exe) but that wouldn't really help you find the actual miner in any easy way.

**Comment by freakovision** [comment]
Kill the miner process and monitor what will watchdog run.

**Comment by UnamSanctam** [comment]
The miner will still start on the next startup and recreate the watchdog.

**Comment by UnamSanctam** [comment]
Only way to really get rid of the miner is to 1) Kill the watchdog (sihost32.exe), 2) Remove the miner startup in the Task Scheduler or the registry, 3) Remove the miner injector (services32.exe by default). Doing it in that order is important or it will just recreate itself, since you can't really know the location or name of the miner injector you would have to find it manually.
