### ISSUE TITLE
working name

### ISSUE THREAD

**Issue by jkvint** [UnamSanctam/SilentXMRMiner#357]

**Comment by UnamSanctam** [comment]
Sorry I think your translation is a bit off, what doesn't work? {%COMPUTERNAME%}?

**Comment by jkvint** [comment]
yes. Wallet/{%COMPUTERNAME%}

**Comment by UnamSanctam** [comment]
Which pool are you using? For nanopool it should be `Wallet.{%COMPUTERNAME%}`, the slash (/) is used to enter a password (after the worker name) to change the minimum payout like so `Wallet.{%COMPUTERNAME%}/password`

**Comment by jkvint** [comment]
I use minexmr

**Comment by UnamSanctam** [comment]
For MineXMR you probably use it in the password or rig-id, you can see it here: https://minexmr.com/miningguide
Keep in mind these things on that page though:
>**Botnet / Web Mining Policy**
Sadly it happens that Botnets often run cryptominers on infected PCs. minexmr does not support botnets, web miners or any other illegal activities. Any account suspected of botnet mining or web mining will be banned.
Please contact abuse@minexmr.com to report any incident.

>**Using Many Miners**
If you are running a legal operation with a large number of miners (ie more than 100 miners), please setup and use xmrig-proxy, which allows more efficient management of workers.

So if you're planning on having more than 100 miners and not planning to set up your own xmrig-proxy server then you shouldn't use MineXMR.

**Comment by jkvint** [comment]
I need this to authenticate my farms.
This is only available on Nanopool?

**Comment by UnamSanctam** [comment]
As I said, try inputting the worker name into the password and see if that works or you'll have to add --rig-id="{%COMPUTERNAME%}" into the "Advanced Parameters" which should work.

And also as I said, never use MineXMR if you will have more than 100 miners since then you will most likely get banned.

**Comment by jkvint** [comment]
Understood thanks. In this case, what can you advise to use?

**Comment by UnamSanctam** [comment]
If you mean what pool to use then nanopool is the only one I know that doesn't ban.
