### ISSUE TITLE
If I crypt the source xmrig exe file, will your program still be able to patch it? 

### ISSUE THREAD

**Issue by Footsiefat** [UnamSanctam/SilentXMRMiner#36]
I think I found a good method of crypting the exe, but im not sure if your program will still be able to patch the source exe if I crypt it.

**Comment by UnamSanctam** [comment]
Should be able to depending on the crypter and if it only obfuscates it (doesn't add startup or something).

**Comment by Footsiefat** [comment]
sounds good. it'd just obfuscate it as your does that.

**Comment by Footsiefat** [comment]
actually just to comfirm. this doesn't modify that xmrig binary in any way right? And if so how does it pass it parameters like mining pool

**Comment by UnamSanctam** [comment]
The xmrig binary is encrypted inside the built file and when run it decrypts it and injects it into the chosen process (like explorer.exe) and it runs that process with the command line arguments that contain the pool, address and other settings.

**Comment by Footsiefat** [comment]
ah sweet as, so as long as it can still receive the args it should work fine

**Comment by UnamSanctam** [comment]
Yes exactly.

**Comment by Footsiefat** [comment]
Awesome!

**Comment by umbrella-cyk** [comment]
I crypted xmrig.exe but AV block virus in tmp
how i can bypass

**Comment by UnamSanctam** [comment]
If I understand correctly then temporarily disable your antivirus or add tmp to exceptions, or find a better crypter.

**Comment by dimeks** [comment]
Dont working 
Silent miner useless

**Comment by umbrella-cyk** [comment]
dont working i crypted with lime miner and pe union 
silent miner useless without fud av

**Comment by UnamSanctam** [comment]
First of all this is Silent XMR Miner Builder which is a fork of Lime-Miner so I hope you're using this one and not Lime-Miner since it's outdated and no longer working. Second of all I just tried using PE Union and it works fine so you're doing something wrong.
