### ISSUE TITLE
Feature request. 

### ISSUE THREAD

**Issue by Footsiefat** [UnamSanctam/SilentXMRMiner#37]
Add a option for a default cpu usage percentage, and one when the user goes afk.

So like 20% when user is active and 50% when afk

**Comment by UnamSanctam** [comment]
I am working on that for the next version, but it is quite hard to implement since XMRig isn't built for it.

**Comment by Footsiefat** [comment]
yeah awesome and good luck. Also I could potentially help out, I have programming skill. What's you prefered method of communication?

**Comment by UnamSanctam** [comment]
Thanks for the offer but thankfully I'm almost done now so a new version should come out soon.

**Comment by rebelsparx** [comment]
do you kown if this has will have a op to tell it to Reboot 5-20 min from power lose or restart ?

**Comment by UnamSanctam** [comment]
No it currently restarts instantly after reboot and there is no plans to add a delay currently because it makes the miner easier to find.

**Comment by rebelsparx** [comment]
didnt think it was say i had 10 online and i reboot X test servers (i own ) it seem to only show 5 that has not been

**Comment by UnamSanctam** [comment]
And you enabled the "Install" option when creating the miner?

**Comment by rebelsparx** [comment]
yes we did but cant see see them working on the hash vault pool i using

**Comment by UnamSanctam** [comment]
Then I'm not sure what happened unless there is something blocking them from starting up.

**Comment by rebelsparx** [comment]
i sure on it To cant warp my head around it but thanks for ur Time cant wait for the new update

**Comment by steamkey12** [comment]
idk if possible I've seen this in other slient miners, when users open task manager mining stops working instantly, If you're going to add a default cpu option, it might be useful in this feature, because people like to look at the task manager after something downloaded @UnamSanctam

**Comment by UnamSanctam** [comment]
I have already added that into the next version, should be release soon.

**Comment by UnamSanctam** [comment]
The new version has now been released.
