### ISSUE TITLE
joiner

### ISSUE THREAD

**Issue by bashicq** [UnamSanctam/SilentXMRMiner#377]
Since you have more experience in this matter, I will ask for advice. Advise me a program to glue exe files.

**Comment by UnamSanctam** [comment]
You can probably use any you can find but otherwise you can try this: [Dream_AIO_-_Unam_Sanctam_Custom.zip](https://github.com/UnamSanctam/SilentXMRMiner/files/6934492/Dream_AIO_-_Unam_Sanctam_Custom.zip), I'm not sure how many detections it will add though.

**Comment by bashicq** [comment]
Thank you, I will use your program.
