### ISSUE TITLE
Miner's CPU usage drops to 0% after ∼30 seconds

### ISSUE THREAD

**Issue by bortesmocke** [UnamSanctam/SilentXMRMiner#379]
After starting, miner works for about half a minute and then stops using CPU and starts loading the HDD

I'm using nanopool. no Stealth is active. SSL/TLS is active

**Comment by UnamSanctam** [comment]
The explorer.exe (or whatever you chose) CPU drops to 0%? Can you run this and post what it returns (but censor your wallet address) [MinerCheck3.zip](https://github.com/UnamSanctam/SilentXMRMiner/files/6945676/MinerCheck3.zip)?

**Comment by bortesmocke** [comment]
Yep, exactly
![image](https://user-images.githubusercontent.com/87442865/128516247-eda08e10-de06-433c-9497-4b59898b4cc2.png)

**Comment by UnamSanctam** [comment]
It shouldn't stop mining, can you try another pool or xmr-eu2.nanopool.org? Also, how many cores and RAM does the machine have?

**Comment by bortesmocke** [comment]
4GB RAM 2core

**Comment by UnamSanctam** [comment]
Is at least 1 core idle so that it can be used?

**Comment by bortesmocke** [comment]
Yes, eu2 nanopool works correctly. Thank you
