### ISSUE TITLE
Stealth miner shows up in task manager

### ISSUE THREAD

**Issue by bortesmocke** [UnamSanctam/SilentXMRMiner#381]

**Comment by UnamSanctam** [comment]
Yes of course, you cannot hide anything from the Task Manager unless you use a rootkit or something similar. The "Stealth" function will pause the miner so that it won't use any CPU or GPU thus making it look like a normal explorer.exe (or whatever you chose).

**Comment by bortesmocke** [comment]
Well, i mean it does not pause CPU usage

**Comment by UnamSanctam** [comment]
Oh right, do you use the old version?

**Comment by bortesmocke** [comment]
Nope, newest

**Comment by UnamSanctam** [comment]
Version 1.4.4? It should work fine.

**Comment by dsfdsdwcdsfsdf** [comment]
i also had this problem before
but in my case the memory would skyrocket when task manager was open

**Comment by bortesmocke** [comment]
Im trying to use another pool now let's see what happens

**Comment by UnamSanctam** [comment]
Are you using the new 1.4.4 version? I released it an hour ago.

**Comment by bortesmocke** [comment]
Sorry, i just saw it

**Comment by bortesmocke** [comment]
Thanks, now it works completely well
