### ISSUE TITLE
Remote configuration setings 

### ISSUE THREAD

**Issue by Boria138** [UnamSanctam/SilentXMRMiner#385]
Could you add a more detailed description of the options for remote configuration to the wiki?

**Comment by UnamSanctam** [comment]
The options inside it already exist in the builder itself so you can just check the other wiki entries for what the options do. You can also post your 'Remote Configuration' here and I'll check if it's correct.

**Comment by Boria138** [comment]
https://pastebin.com/raw/prMk0apB

I took an example from the wiki and changed only the keepalive parameter to true, as I understand this parameter is responsible for enabling watchdog?

**Comment by UnamSanctam** [comment]
The keepalive option is an option that if enabled will try to keep the connection to the pool active by sending keepalive packets, it has to be supported by the pool to work. If you use hashvault keep in mind that you can't have too many miners without hosting your own xmrig-proxy and mining through that: 
<img alt="e5cb6f7f8b2a40f77fe8" src="https://user-images.githubusercontent.com/10323655/128673919-e504c3e0-ff20-417b-ad7a-1885991ceb87.png">

**Comment by Boria138** [comment]
Thanks for the clarification
