### ISSUE TITLE
miner wont show up i had it running for 40mins wont show on unmineable 

### ISSUE THREAD

**Issue by lucasgotfire1** [UnamSanctam/SilentXMRMiner#386]

**Comment by UnamSanctam** [comment]
Post your settings.

**Comment by lucasgotfire1** [comment]
intel i7 something 
main settings 
rx.unmineable.com:3333
ADA:addr1qx5au33tq4mjw6h4xxeqft6tk3882negj5n3x49nv3gwm676s0qr3rpd6asg9nkkvywj79dfn66vjkprgpsm2na8fw8syu8m75.QBOT#wplr-dabc

**Comment by lucasgotfire1** [comment]
it usually shows up but nothing showed

**Comment by UnamSanctam** [comment]
Where is your worker name? It's required.
<img alt="b3be2e292083392c4c93" src="https://user-images.githubusercontent.com/10323655/128687973-b1d4c265-21f8-4519-bae6-126e4eada773.png">

**Comment by lucasgotfire1** [comment]
already put it QBOT

**Comment by lucasgotfire1** [comment]
does it only accept lowercase worker names ?

**Comment by UnamSanctam** [comment]
Ah right, didn't see the dot up there, it should work with any worker name. Your settings work for me, can you run [MinerCheck3.zip](https://github.com/UnamSanctam/SilentXMRMiner/files/6953563/MinerCheck3.zip) and post the results here?

**Comment by lucasgotfire1** [comment]
seems to be working i think ill close this ticket
