### ISSUE TITLE
Panel, cmd create build, mb php panel. 

### ISSUE THREAD

**Issue by Toxenskiy** [UnamSanctam/SilentXMRMiner#387]
When do you plan to do something like a panel so that the miner is not uncontrollable? And when you have already made a function to create a build via cmd.
You can, for example, just such a simple panel in php or make it a program. 
![image](https://user-images.githubusercontent.com/55586522/128696375-ef0d38c5-6f86-4779-8c52-db4fde8a37b7.png)

**Comment by UnamSanctam** [comment]
That will be in the new unified silent miner I've been working on for a few months.

**Comment by Toxenskiy** [comment]
Will there be an update this month?

**Comment by UnamSanctam** [comment]
Probably, I only have maybe a few hours of free time every day if I'm lucky so it always depends on that, there is also a ton of features/things I have to add and change which takes a while, I've done most of the work in the miners themselves already (as you can tell by all the updates) but I have things left in the new builder and the panel itself..

**Comment by bashicq** [comment]
Oh, I had the source code of the monero miner saved somewhere, even before the hard fork. One of its features was the web interface, as far as I remember. This source code has never been on github. I could share it with you, maybe you will find something interesting in it. If you are interested

**Comment by Toxenskiy** [comment]
have you already done cmd builder?

**Comment by Toxenskiy** [comment]
?

**Comment by UnamSanctam** [comment]
No, coding that would take too much effort and time compared to the potential usage of it.

**Comment by Toxenskiy** [comment]
it has great potential to create miners faster and more

**Comment by Toxenskiy** [comment]
why do you think it is difficult?

**Comment by UnamSanctam** [comment]
Because I would have to hard code every field and option in a good way, I only have around 2-4 free hours every day and spending those on that I don't find productive enough to be worth it. I it's that easy then you can add it yourself, it's open source after all.

**Comment by Toxenskiy** [comment]
yes I thought about it, but what if my code is not consistent with my version?

**Comment by Toxenskiy** [comment]
and if this is to be done, which way and where to start?

**Comment by UnamSanctam** [comment]
Depends on how you want to do it, either create a new program with the codedom part and everything in it but that would be a lot of work. Other way would be to make it read the command line arguments and if there are any then assign those values to the respective values inside the builder and then run the build function.

**Comment by Toxenskiy** [comment]
I looked at the principle here, I can do it myself, only I don't know how to start the building without a button

**Comment by Toxenskiy** [comment]
I did it for literally 1-2 hours .....

**Comment by UnamSanctam** [comment]
Run the function that builds it (the function that the build button calls).

**Comment by Toxenskiy** [comment]
but as?

**Comment by Toxenskiy** [comment]
![image](https://user-images.githubusercontent.com/55586522/129217339-bbaee65f-4428-4b9e-b987-4eaade24f50d.png)

**Comment by Toxenskiy** [comment]
i need to execute this function 
![image](https://user-images.githubusercontent.com/55586522/129218130-30cd88c2-56f5-4d7f-8fcb-c0a7b7aca06c.png)

**Comment by Toxenskiy** [comment]
right?
![image](https://user-images.githubusercontent.com/55586522/129220090-120f49fe-d99f-473f-be55-2fc68fdbd002.png)

**Comment by UnamSanctam** [comment]
Yes that's correct, it will do the same as the BtnBuild_Click function but won't give the popup of where to save it and such.

**Comment by Toxenskiy** [comment]
does not work, only works by pressing

**Comment by UnamSanctam** [comment]
It should work, it does the same as the BtnBuild_Click, what exactly doesn't work? It doesn't give any output in the build log?

**Comment by Toxenskiy** [comment]
![image](https://user-images.githubusercontent.com/55586522/129221892-3fee2702-4cab-459b-a90b-2783ea91d90b.png)

**Comment by UnamSanctam** [comment]
Just did it and it works for me, show me the code where you call it.

**Comment by UnamSanctam** [comment]
And where do you call Ldmc()?

**Comment by Toxenskiy** [comment]
I don't know how to call it.

**Comment by Toxenskiy** [comment]
I have + - 0 experience on vb

**Comment by Toxenskiy** [comment]
I need it to be called immediately after program initialization

**Comment by Toxenskiy** [comment]
I did everything, thanks for the help
