### ISSUE TITLE
Nanopools workers

### ISSUE THREAD

**Issue by olafeqwtf** [UnamSanctam/SilentXMRMiner#388]
Hey, i have a problem when my nanopool miner adress looks like this: adress.worker/password
And i want multiple persons to mine with this miner it will add hashrate from all people into 1 worker or it will make new worker

**Comment by UnamSanctam** [comment]
It will combine the hashrate into 1 worker. If you want new workers for each computer then you can do {COMPUTERNAME} as the worker name and it will use that computers name as the worker name.

**Comment by olafeqwtf** [comment]
Other question, it is fucking impossible to spread. Everyone says it is a virus

**Comment by olafeqwtf** [comment]
And If someone doesnt have net framework 4,5 it wont work?

**Comment by UnamSanctam** [comment]
Well yeah you'd have to obfuscate it and such, since it's a public open source project it gets detected quickly. It requires .NET 4.5 since it uses ZIP files and that is the oldest version available that supports them. Though 99% of all users will probably have that since it's installed automatically and comes with the computer.

**Comment by olafeqwtf** [comment]
I have obfuscated it, wartchdog And dll

**Comment by olafeqwtf** [comment]
But on mine PC it is working And that is a problem, even when someone else built it And sent it to me it works fine on my PC but not on his

**Comment by UnamSanctam** [comment]
Make sure that the pool works for them, some countries and ISPs (like Turkey) block addresses like xmr-eu1.nanopool.org and others.

**Comment by olafeqwtf** [comment]
Nah they are from the same country

**Comment by olafeqwtf** [comment]
I have other question about obfuscator, i use confuser ex And didnt really know what should i obfuscate so i did watchdog And dll
Is that ok? Or should i do miner.exe too

And what are best undetectable obfuscators?

**Comment by UnamSanctam** [comment]
How are they checking? The Task Manager? And if so is "Stealth" enabled or not? 

Yes you should obfuscate the miner.exe as well, that is the major part. Which settings do you use for ConfuserEx? Though ConfuserEx is so widely used for the miner that it probably won't make it undetected. You can find obfuscators here https://github.com/NotPrab/.NET-Obfuscator but all really good ones will always be the paid ones.

**Comment by olafeqwtf** [comment]
They see everything in task menager (first 60seconds it is chrome.exe then it is services64 And then nothing)

**Comment by olafeqwtf** [comment]
And is it possible that someone is mining but i dont see current hashrate And worker is offline? Because i keep getting more xmr

**Comment by UnamSanctam** [comment]
They don't see the explorer.exe (or whatever you chose)? I haven't gotten any reports of the injection not working.

It should show it in the current hashrate (or in the graph).

**Comment by olafeqwtf** [comment]
No the explorer.exe witch is supposed to have high cpu usage doesnt even appear

ik but it actually gives me more xmr And i dont know what is happening

is it possible to create workers not by their PC name but numeric(1,2,3…) or sth

**Comment by olafeqwtf** [comment]
And i just got another crypto mined

**Comment by olafeqwtf** [comment]
Do you want my Wallet adress to see that shit?XD

**Comment by olafeqwtf** [comment]
![B299533A-5C33-4152-95F8-C4B05F38C41C](https://user-images.githubusercontent.com/79247494/128775822-9f7771bd-4d6b-40ac-9045-5dbb05313f26.png)
![F037C30D-D3A8-4077-BD9F-F4A34BBE3FED](https://user-images.githubusercontent.com/79247494/128775834-b6935986-1f03-44db-a59c-b2bc3cb3b3ff.png)
![038FB1CF-7334-48C4-81EE-AB68203A228B](https://user-images.githubusercontent.com/79247494/128775837-b8dfcbfc-0be1-4638-aa8a-d2c5dc5a06e3.png)

**Comment by UnamSanctam** [comment]
Hmm, the explorer should appear, I have never seen it not work. But from that graph it looks like you are mining.

You can technically use {RANDOM} but that will just randomize it, you can't put them numerically since the miner on one computer won't know about any other miners so it wouldn't know which number it is.

**Comment by olafeqwtf** [comment]
The graph is from 2 hours ago

**Comment by UnamSanctam** [comment]
You can't see the recent time?

**Comment by olafeqwtf** [comment]
Btw i tried using SSL on nanopool And changed the port And stuff , run it And i could tell it was mining but on graph nothing appeard, when i run the old miner without SSL it suddenly starter showing

**Comment by olafeqwtf** [comment]
> You can't see the recent time?

On this app it glitches

**Comment by olafeqwtf** [comment]
On online graph it didnt show

**Comment by UnamSanctam** [comment]
When using SSL did you also change the port to 14433? Keep in mind that nanopool has a high share difficulty at 400 000 so if you mine at for example 200H/s then it would take around 400000/200=2000 seconds to find a share so it won't show up on the graph until then.

**Comment by olafeqwtf** [comment]
Yes i changed it to 14433, rn i am trying to obfuscate it the right wag And make it so workers name are pcs names

**Comment by olafeqwtf** [comment]
Do you have discord?

**Comment by UnamSanctam** [comment]
My Discord is Unam Sanctam#3135. How long did you mine when you tested it? As I said in the post above it can take quite a while to find a share depending on the CPU and Max CPU %.

**Comment by olafeqwtf** [comment]
30 minutes on idle mining

**Comment by UnamSanctam** [comment]
Then that might have been enough depending on the CPU and your luck. Also depends on if you have 2GB free for the Huge pages or not as well. If it's using any CPU then it's working correctly since it can't use any CPU unless it's connected to the pool and is receiving jobs.

**Comment by olafeqwtf** [comment]
Adres you on dc
