### ISSUE TITLE
hangs my computer 

### ISSUE THREAD

**Issue by minnershubs** [UnamSanctam/SilentXMRMiner#389]
hello i have download the silentxmrminer and i followed the instructions on how to build it but after building it and i download it on my own computer just to test , setting are fine , it even gave me some results on minersgate  but the miner starts to drag my computer making it impossible to connect to the internet or do anything with my computer and if its not connected it wont mine , please how can i fix this how can i make it compactible with my computer and mine silently because thats what its supposed to do .. Thanks

**Comment by UnamSanctam** [comment]
Lower the Mac CPU so it uses less CPU.

**Comment by minnershubs** [comment]
specs?

**Comment by UnamSanctam** [comment]
Specifications, what CPU, how many cores and how much RAM does it have?

**Comment by minnershubs** [comment]
4g Ram intelcore i3 64bits

**Comment by minnershubs** [comment]
windows10

**Comment by minnershubs** [comment]
are you saying that when building it i should increase it to %50 ???

**Comment by UnamSanctam** [comment]
No, try another cryptocurrency that doesn't use the RandomX algorithm, there is a list supported by the miner on the main page right beneath the image. The RandomX algorithm requires 2GB of RAM to mine with Huge pages but you only have 4GB of RAM (nearly no one will have that so it's not a worry when spreading the miner),

**Comment by minnershubs** [comment]
i have another computer with intel core of i5  8G Ram 32 bit operation system

**Comment by minnershubs** [comment]
can you give me best specification for this miner and how can i locate the other ones you said could mine with my computer specification on the main page because i cant find it apologies .. do you have a link for it Apologies

**Comment by UnamSanctam** [comment]
Here you can see the algorithms that the miner supports: https://github.com/UnamSanctam/SilentXMRMiner/wiki#algorithms. You could maybe try mining something like TurtleCoin.

**Comment by UnamSanctam** [comment]
In the builder you can select TurtleCoin (argon2d chukwav2) in the "Algorithms" list, don't forget to enter a TurtleCoin pool and wallet address.

**Comment by minnershubs** [comment]
im sorry didnt get this one , are you saying in the xmr builder i could change it to turtlecoin

**Comment by UnamSanctam** [comment]
Yes, the XMR miner supports a lot of different algorithms and cryptocurrencies.

**Comment by minnershubs** [comment]
please im really new here , how can i change it because im looking at the builder right now i dont see where i can switch it to turtlecoins

**Comment by UnamSanctam** [comment]
On the first tab of the builder at the bottom there is an "Algorithm" option, you can select it there. If you don't have an "Algorithm" option then you have an old builder.

**Comment by minnershubs** [comment]
okay but how many bits will be okay for it to mine on successfully

**Comment by UnamSanctam** [comment]
64-bit.

**Comment by minnershubs** [comment]
what about Ram

**Comment by UnamSanctam** [comment]
RandomX requires 2 GB of RAM to mine fast but things like TurtleCoin don't really require anything special in concern to RAM usage from what I can remember.
