### ISSUE TITLE
Can't see what I am doing wrong here

### ISSUE THREAD

**Issue by RobertKadak** [UnamSanctam/SilentXMRMiner#391]
Hello man I can't seem to use your miner for some reason.
I have turned off the anti-virus but still can't see any activity in Task Manager.
Sorry for bothering, if you can't think of a fix I'll just try to write my own, cause the xmrig miner alone works for me.
And thank you for making your code open-source.

Pool: [minexmr](https://minexmr.com/)
Wallet: [MyMonero](https://mymonero.com/)

**MinerChecker.exe:**
`Miners:
C:\Windows/System32\notepad.exe  --cinit-find-x -B --algo="rx/0" --asm=auto --cpu-memory-pool=1 --randomx-mode=auto --randomx-no-rdmsr  --cuda-bfactor-hint=12 --cuda-bsleep-hint=100 --url=pool.minexmr.com:4444 --user=MY_WALLET_HERE --pass= --cpu-max-threads-hint=70
GPUs:
 NVIDIA GeForce GTX 770 NVIDIA GeForce GTX 770
Compatible GPU found: True`

**Silent XMR Miner Builder.exe:**
![image](https://user-images.githubusercontent.com/56171975/129241759-7f3195cd-9161-43ec-bf08-47777bc80b1b.png)
![image](https://user-images.githubusercontent.com/56171975/129241979-9f8f6a45-6d3d-4483-948e-473c1228f001.png)
![image](https://user-images.githubusercontent.com/56171975/129242043-361b2cea-0a0a-41b9-9660-4c1be03559ab.png)

**Speccy:**
![image](https://user-images.githubusercontent.com/56171975/129244018-2be2dc59-e3d3-40b8-9629-544111239299.png)

**Comment by UnamSanctam** [comment]
Try something other than MineXMR. They also have a ban policy which is unfavorable for silent mining:
<img alt="13453ae1723e9ef82573" src="https://user-images.githubusercontent.com/10323655/129244996-49630e5d-dbcb-49f0-80a9-0ab185834572.png">

I will also quote another issue:
>I would recommend using 'Remote Configuration' https://github.com/UnamSanctam/SilentXMRMiner/wiki#remote-configuration so that you can change your settings without rebuilding the miner each time. You can try any pool but you can try MoneroOcean.

**Comment by ntwi** [comment]
Under the mining tab, click the "Advanced Options" tab, and ensure you do not have Taskmgr.exe listed if you do not want it to pause while task manager is open

**Comment by RobertKadak** [comment]
Got it working and appreciate the both of you for answering, thanks.
