### ISSUE TITLE
Not FUD?

### ISSUE THREAD

**Issue by GhauriAyaPher** [UnamSanctam/SilentXMRMiner#393]
It's constantly being detected by Windows defender and being flagged as virus. Do I need to crypt it?

**Comment by UnamSanctam** [comment]
Yes, this is a public and open source project so it gets detected after a while.

**Comment by parabola19** [comment]
> Yes, this is a public and open source project so it gets detected after a while.

have you thought about releasing a private paid version?

**Comment by GhauriAyaPher** [comment]
> Yes, this is a public and open source project so it gets detected after a while.

So, I would have to crypt it? Sorry if I am annoying as I am new to all of this.

**Comment by UnamSanctam** [comment]
Yes, to make it undetected just for Windows Defender you could also try uploading your miner online and then trying my downloader: https://github.com/UnamSanctam/UnamDownloader with "Add Windows Defender exclusions" enabled, it should then add exclusions for Windows Defender before downloading the miner so it won't get detected.
