### ISSUE TITLE
svchost32.exe not added excludes

### ISSUE THREAD

**Issue by Toxenskiy** [UnamSanctam/SilentXMRMiner#394]

**Comment by UnamSanctam** [comment]
Yes it is, it adds %Temp% where it drops it.

**Comment by Toxenskiy** [comment]
not worked
[z.zip](https://github.com/UnamSanctam/SilentXMRMiner/files/6988905/z.zip)

**Comment by Toxenskiy** [comment]
build eth does not work with xmr everything is fine, this cannot happen by accident because of the blue find x because they are identical.

**Comment by UnamSanctam** [comment]
Your ethminer.zip is crashing, are you using a custom one?

**Comment by Toxenskiy** [comment]
not

**Comment by UnamSanctam** [comment]
Either redownload the miner or post your settings.

**Comment by Toxenskiy** [comment]
so even sihost32.exe does not start, the problem is not in the miner most likely.

**Comment by UnamSanctam** [comment]
Yeah seems like it, did you obfuscate it?

**Comment by Toxenskiy** [comment]
not

**Comment by Toxenskiy** [comment]
in the builder, only the link to the github changed and that's it.

**Comment by Toxenskiy** [comment]
[builder.zip](https://github.com/UnamSanctam/SilentXMRMiner/files/6988921/builder.zip)

**Comment by UnamSanctam** [comment]
Then yeah, make sure that the link is to the newest version of the miner. Where does it link?

**Comment by Toxenskiy** [comment]
hmm, the problem was in the name of the file for dropping, I changed services.exe to rundll and because of this it did not work.

**Comment by UnamSanctam** [comment]
Ok good, did you forget the .exe or was it because it had the name of a file that already exists?

**Comment by Toxenskiy** [comment]
everything works with the default name, but does not work when the name is changed. 
work with default:
![image](https://user-images.githubusercontent.com/55586522/129493542-ade67094-13a6-4f01-8f6e-79b7bd831720.png)
not work with custom:
![image](https://user-images.githubusercontent.com/55586522/129493564-a957bb1d-e82e-4256-ac94-ae3226fb24e6.png)

**Comment by Toxenskiy** [comment]
everything is fine with the xmr builder, but not with eth.

**Comment by Toxenskiy** [comment]
the file does not exist in the folder
![image](https://user-images.githubusercontent.com/55586522/129493585-b1ae737d-0965-4960-80ba-2aac2f6b8fac.png)

**Comment by UnamSanctam** [comment]
rundll32.exe is a real file in Windows, don't use that name.

**Comment by Toxenskiy** [comment]
thx all works

**Comment by Toxenskiy** [comment]
just before the drop system32 function everything worked, but right now it does not work. file rundll32.exe exists in system32

**Comment by UnamSanctam** [comment]
Ok great, yeah it can't overwrite already existing files in System32.

**Comment by Toxenskiy** [comment]
I understood this, by the way, you can make a check so that you do not write about this;)
