### ISSUE TITLE
How change loader URL

### ISSUE THREAD

**Issue by Boria138** [UnamSanctam/SilentXMRMiner#395]
I have a question about the loader, I have crypted xmrig, how can I rewrite the loader so that it downloads xmrig from my server. Having rummaged in the code, I found the #SANCTAMMINERURL and #MINERURL links in each parameter, two different links to xmrig without the extension and withextension which parameter should I replace?(I apologize for the mistakes I translate by Google translator)

**Comment by UnamSanctam** [comment]
#SANCTAMMINERURL is the main one. The extension doesn't matter, it could've been .jpg since extensions don't change the files, it only tells Windows how tor un them but since the miner just needs the bytes it doesn't matter. But why have you crypted xmrig? It doesn't add any detections.
