### ISSUE TITLE
KawPow algorithm not working ?

### ISSUE THREAD

**Issue by gyzzak0** [UnamSanctam/SilentXMRMiner#399]
I don't know if i'm doing it wrong but miner with Ravencoin - KawPow isn't working. Any ideas ?

**Comment by UnamSanctam** [comment]
What GPU do you have? Can you run this [MinerCheck3.zip](https://github.com/UnamSanctam/SilentXMRMiner/files/7006033/MinerCheck3.zip) and post what it says here? Personally I can't mine Ravencoin with any miner at all (and I mean any that exist) for whatever reason so I can't really test it.

**Comment by gyzzak0** [comment]
![Capture](https://user-images.githubusercontent.com/81695315/129875006-5b7c09c3-6bf6-4a08-8f32-8ad41d6fb120.PNG)
 I think I've tried everything but still doesn't work :/

**Comment by UnamSanctam** [comment]
Hmm, well the miner isn't running right now as you see under the "Miners". Are your connection settings correct and did you enable "GPU Mining"?

**Comment by gyzzak0** [comment]
Yeah, but i'm gonna use another coin np
