### ISSUE TITLE
How to find the installer

### ISSUE THREAD

**Issue by zoubaba1997** [UnamSanctam/SilentXMRMiner#40]
I ran it on my own computer, and then I could not find him in the temp folder
![无标题](https://user-images.githubusercontent.com/73113267/106577297-2ae48680-6579-11eb-8ba6-c70f535fcc1e.png)

**Comment by UnamSanctam** [comment]
Did you enable the "Hide file" setting? In that case you cannot find it with the Windows Explorer and have to use CMD to remove it, open CMD and "cd" to the folder where the miner is located and then you should be able to find it using "dir /a:h", you can then remove it by running "del /a:h MinerName.exe".
