### ISSUE TITLE
nanopool shows shares, but im not getting any xmr

### ISSUE THREAD

**Issue by dsfdsdwcdsfsdf** [UnamSanctam/SilentXMRMiner#401]
when i put my address in, it says there is shares but it also that there are no workers, and no payments
do i need to put my regular xmr address or my recieve address in the builder?

**Comment by UnamSanctam** [comment]
When you mine, you will be rewarded the XMR when a block is mined, in the case of a pool you will be rewarded with a portion of the block reward decided by your amount of shares compared to all the other shares. It should say your "Balance" and "Unconfirmed Balance" at the top. Nanopool (an all other pools) will only pay out when you reach the minimum threshold which you can see on your "Settings" page on the same page you see the hashrate. You won't see any workers unless you enter a worker name, workers are not the same as miners, workers are just way to group together miners for statistical purposes. If you want to have a worker name and/or change the minimum payout then you need to enter that into the "Wallet Address" field like so: `Wallet.Worker/Password` where the password will be used to change the minimum payout.

**Comment by dsfdsdwcdsfsdf** [comment]
> 
> 
> When you mine, you will be rewarded the XMR when a block is mined, in the case of a pool you will be rewarded with a portion of the block reward decided by your amount of shares compared to all the other shares. It should say your "Balance" and "Unconfirmed Balance" at the top. Nanopool (an all other pools) will only pay out when you reach the minimum threshold which you can see on your "Settings" page on the same page you see the hashrate. You won't see any workers unless you enter a worker name, workers are not the same as miners, workers are just way to group together miners for statistical purposes. If you want to have a worker name and/or change the minimum payout then you need to enter that into the "Wallet Address" field like so: `Wallet.Worker/Password` where the password will be used to change the minimum payout.

so i have to mine 247$ before i can get paid.......

**Comment by UnamSanctam** [comment]
Yes unless you lower it like I said above, you can mine with a worker name and password like so `Wallet.Worker/Password` in the "Wallet Address" field and can then use the password to lower the minimum payout to 0.11 XMR.

**Comment by dsfdsdwcdsfsdf** [comment]
> 
> 
> Yes unless you lower it like I said above, you can mine with a worker name and password like so `Wallet.Worker/Password` in the "Wallet Address" field and can then use the password to lower the minimum payout to 0.11 XMR.

so is this right? https://anonfiles.com/p0XaUaCcu1/Screenshot_103_png     do i just have to replace the examplepassword in both boxes to what i want the password to be and thats it? or do i also have to name the worker
and does it still work if others run it or just 1 person

**Comment by UnamSanctam** [comment]
Only enter it in the "Wallet Address" field, the "Password" field should be left empty. And yes replace it with what you want it to be, it has to be 6 characters long or more. You have to have a worker name but you can name it whatever, as long as all miners (with a worker name) has the same password it will work.

**Comment by dsfdsdwcdsfsdf** [comment]
> 
> 
> Only enter it in the "Wallet Address" field, the "Password" field should be left empty. And yes replace it with what you want it to be, it has to be 6 characters long or more. You have to have a worker name but you can name it whatever, as long as all miners (with a worker name) has the same password it will work.

will i need to keep the password? and if i create another miner will i have to use a diffrent worker name and password?

**Comment by UnamSanctam** [comment]
As long as you want to change the minimum payout all workers need to have the same password. You can have however many miners you want under a worker name, a worker name is just a single miner or a group of miners used for statistical purposes.

**Comment by dsfdsdwcdsfsdf** [comment]
> 
> 
> As long as you want to change the minimum payout all workers need to have the same password. You can have however many miners you want under a worker name, a worker name is just a single miner or a group of miners used for statistical purposes.

so this is all i need? https://anonfiles.com/hcl3W6C3u7/Screenshot_105_LI_jpg
and i can use just that every time i create a miner?

**Comment by UnamSanctam** [comment]
Yes exactly, that will work.
