### ISSUE TITLE
downloader

### ISSUE THREAD

**Issue by bashicq** [UnamSanctam/SilentXMRMiner#402]
Does it make sense to use "pause for obfuscation" at the same time as "online download"? And if I use UnamDownloader on top of that? How can a crypter work at all if the file weight is 100kb?

**Comment by UnamSanctam** [comment]
Yes, the "Online Download" files don't get obfuscated/crypted anyways, if you disable "Online Download" they would just get embedded as encrypted resources anyways. Crypters don't really care how big a file is, they only use certain methods to hide code or other calls from detection.

And the downloader will work fine with anything as long as that file works.

**Comment by bashicq** [comment]
Ok. 
In order not to create a new thread, I will ask here. Can you recommend me file hosting for UnamDownloader?

**Comment by UnamSanctam** [comment]
Any that support direct download links should work. Like Discord (upload your file somewhere and right-click and select "Copy Link"), BitBucket (though you have to use git to upload), Google Driver and Dropbox should work I believe.

**Comment by bashicq** [comment]
Google Driver and Dropbox tried in before asking for advice, direct links to the file it does not give. Or am I doing something wrong. Maybe you can do better and you can provide an example of a link, for example from Google Driver?

**Comment by UnamSanctam** [comment]
Haven't tested those two myself since I use neither. I always use BitBucket but it can be hard to use if you don't know anything about git, you can try creating a new Discord account and a new server and then uploading the file there, you can then copy that link.

**Comment by bashicq** [comment]
Ohh I tried a lot of sites, file sharing... I did not find anything sensible or at least working. Maybe I searched badly, but in my defense I want to say that it took 4 hours of my life. On one forum I found this link: 
https://help.dropbox.com/files-folders/share/force-download
I think you should keep it for your wiki. Here's how users should guess that? (The question is not addressed to you, but to the creators of dropbox) Another working file sharing service was discussed on the forum, but the "direct link" on it is considered a vip service, the price of which is $ 99 / year, I will not give a link to it. In the file sharing of Google, by the way, there was also such an opportunity to receive "direct links". Now there is no such possibility. Or the developers are sadists, specially it was pushed somewhere far away.
