### ISSUE TITLE
one more question

### ISSUE THREAD

**Issue by dsfdsdwcdsfsdf** [UnamSanctam/SilentXMRMiner#405]
how do i get any money if i use a workername/password  if it has no ties to my address, i just ran the miner that i made with the worker name and password and when i type my address in nanopool there are no recent shares or workers even though the miner is running right now

**Comment by UnamSanctam** [comment]
Well, you enter your wallet in the miner no? And you need to mine a share before nanopool will show anything.

**Comment by dsfdsdwcdsfsdf** [comment]
> 
> 
> Well, you entered your wallet address in the miner no? And you need to mine a share before nanopool will show anything.

no, i put miner.myworkername/mypassword  in the address bar like you said
and i did mine shares before doing that one but there were no shares from mining with the worker name

**Comment by UnamSanctam** [comment]
No it's `wallet.myworkername/mypassword` with the `wallet` being your wallet address.

**Comment by dsfdsdwcdsfsdf** [comment]
> 
> 
> No it's `wallet.myworkername/mypassword` with the `wallet` being your wallet address.

k thanks for clarification
