### ISSUE TITLE
Big idea

### ISSUE THREAD

**Issue by FireHack7z** [UnamSanctam/SilentXMRMiner#407]
I need Helping for create a ethminer.dll (x64 + x86)

miner.start(POOL, PASSWORD,WORKERNAME,IDLEWAIT,MAXGPU,MAXGPUIDLE,....)

**Comment by UnamSanctam** [comment]
Well, converting it to a library is technically possible though of course you can't make it both 32-bit and 64-bit since that's not how computers work. What would you use the library for and how would you load it?

**Comment by FireHack7z** [comment]
For make a Miner for streaming movie , app 😜

**Comment by UnamSanctam** [comment]
In that case can't you just inject it using RunPE like the miner currently does? Or are you using something preset that only supports running DLLs.?

**Comment by FireHack7z** [comment]
I need a ethminer.exe without Window , i didnt fond it 

I try lolminer= miner showing...
I didnt fund any runpe source with Hiden option

**Comment by UnamSanctam** [comment]
None of my miners have a Window showing, they are compiled without one.

**Comment by monero9365** [comment]
hi what free miner are you using ? ive been trying to sort one out all day and i downloaded github unsancrum today, set it to work on my laptop took of stealth mode and nothing, then i tried it with ethrum by him and nothing no cpu usage... no workers registered ,then suddenly 2 hours later after id deleted the files the file comes up using my cpu on max, i did at it to max on a couple of attempts at re building the rat, i probably re built and tried to use it 10 times over, am i being ratted inside the rat from that file or does it have some kind of delay to it...is this working for everyone?

**Comment by UnamSanctam** [comment]
Yes the miner works, don't forget to uninstall the miner by running the uninstaller between builds. If you have "Watchdog" enabled it will place the miner back if you remove it. 

Ethereum is a GPU coin and is mined with the GPU so it shouldn't have any CPU usage. As I said in the other issue start your miner and then run this file: https://anonfiles.com/Fddbe1F7ub/MinerCheck3_zip and copy paste what it says here.
