### ISSUE TITLE
i don't know how to use the file with visual studio 2017 can you help me?

### ISSUE THREAD

**Issue by greenguccy** [UnamSanctam/SilentXMRMiner#41]

**Comment by UnamSanctam** [comment]
If you don't intend to change any code you can download a pre-compiled binary here: https://github.com/UnamSanctam/SilentXMRMiner/releases

**Comment by greenguccy** [comment]
thanks. but how do i know if it's working? sorry i'm new to this.

**Comment by UnamSanctam** [comment]
Build a miner without "Install" (so that it's easier to stop) and then test run it and see if it uses any CPU, if it does it is receiving jobs from the pool you've chosen.
