### ISSUE TITLE
where is the update? 

### ISSUE THREAD

**Issue by Toxenskiy** [UnamSanctam/SilentXMRMiner#411]
the month is coming to an end, when will the update be released?

**Comment by UnamSanctam** [comment]
Not sure, haven't been able work on it for two weeks due to work, I don't have a lot of free time at the moment.

**Comment by Toxenskiy** [comment]
ok understood, well, in two weeks it will be right?

**Comment by UnamSanctam** [comment]
Probably, I have to finish remaking it all in C, most is done though I have to make it download and cache the miner. Might also have to find a way to include an icon or assembly data though that might be impossible.

**Comment by EpicBattleStar** [comment]
Hey, what's going to be new in the update?
