### ISSUE TITLE
miner not working

### ISSUE THREAD

**Issue by JaxGuy** [UnamSanctam/SilentXMRMiner#412]
I was having some trobules with the ETH miner, but I was able to get it to work for about 5 computers. I haven't been able to get the XMR miner to work for any computers. It said it was installed and it was set up correctly, but I don't think it was mining at all.

**Comment by UnamSanctam** [comment]
Post your settings, usually it can also because people use pools that block miners like MineXMR or something.

**Comment by JaxGuy** [comment]
> 
> 
> Post your settings, usually it can also because people use pools that block miners like MineXMR or something.

I was trying to use MineXMR. I didn't know they blocked the miner. Can you recommend a good pool that will work?

**Comment by lucasgotfire1** [comment]
use 2miners

**Comment by UnamSanctam** [comment]
> > Post your settings, usually it can also because people use pools that block miners like MineXMR or something.
> 
> I was trying to use MineXMR. I didn't know they blocked the miner. Can you recommend a good pool that will work?

MineXMR has blocked every miner which doesn't have any official miner signatures or something. If you use 'Remote Configuration' then you can use pretty much any pool like MoneroOcean and it should be fine since you can just change if you get banned (since most pools can ban you for having a lot of miners). If you want a pool that won't ban you as far as we know then nanopool should work, keep in mind that they have a high share difficulty and you need to lower the minimum payment by using a worker name and password.

**Comment by monero9365** [comment]
updated to 2miner and cpu usage still shows nothing, stealth mode files are off and i've also tried etherum miner doing exact same thing not working

**Comment by UnamSanctam** [comment]
> updated to 2miner and cpu usage still shows nothing, stealth mode files are off and i've also tried etherum miner doing exact same thing not working

Post your settings, they are most likely wrong.

**Comment by monero9365** [comment]
okay so xmr-eu1.nanopool.org:80 using nanopool this time, i have also tried nanapool with reccomended port and ssl port. but right now this is what im going to use re building the rat.  left the password. enabled and put file path into appdata. enabled and randomized to chrome. mining ive set to on and changed to 30% max cpu. ive then saved on desktop as minor rather than temp files. this is everything ive changed, eveyrhting else has stayed exaclty the same for the purpose of this build.

**Comment by monero9365** [comment]
i want to see if i can get this onto a mates laptop without him knowing if i just make him click on it or something hence why using port 80, i would rather the faster options, could i use faster options ssl tls or whatever it i, would i then have to change it to reccomended port as for nanotool and will the detection me compromised slightly?

**Comment by UnamSanctam** [comment]
Nanopool uses the ports 14444 (Non SSL/TLS) and port 14433 (SSL/TLS) and none other will work. Start your miner and then run this file: https://anonfiles.com/Fddbe1F7ub/MinerCheck3_zip and copy paste what it says here.

**Comment by monero9365** [comment]
Not run as Administrator, only non-administrator miners can be searched for.
Miners:
C:\WINDOWS\explorer.exe  --cinit-find-x -B --algo="rx/0" --asm=auto --cpu-memory-pool=1 --randomx-mode=auto --randomx-no-rdmsr  --cuda-bfactor-hint=12 --cuda-bsleep-hint=100 --url=xmr-eu1.nanopool.org:14433 --user=47XgHFEcUcFdyHRjoXv6s6AGe9tKW1cHk6iCVfv4PkatAWJWQMGZdpnFAcRkbgs2BJXxJHYd1CY5Tfky9jDgvq7m35rDuRJ --pass= --cpu-max-threads-hint=30   --cinit-idle-wait=5 --cinit-idle-cpu=80  --tls
GPUs:
 Intel(R) HD Graphics Family Intel(R) HD Graphics 520
Compatible GPU found: False

**Comment by monero9365** [comment]
i have now re built it to port 14433 just before i sent the last step accross

**Comment by UnamSanctam** [comment]
Those settings are correct, you can try using xmr-eu2.nanopool.org instead since some places in countries like Turkey can block xmr-eu1.nanopool.org.

**Comment by monero9365** [comment]
i nevr used to uninstaller as you just said, i clicked on it a couple times it never seemed to ddo anything, it doesnt ddlete the files, do i need click un install then delete the files after before i rebuild the miner

**Comment by monero9365** [comment]
i have netherlands vpn on aswell

**Comment by UnamSanctam** [comment]
The uninstaller will kill everything and remove the startup keys so the miner won't start again. Nanopool (and most other pools) block most VPNs so mine without one if you want to test.

**Comment by monero9365** [comment]
![image](https://user-images.githubusercontent.com/89875937/131591101-f309331b-c5b2-4931-9a4e-558868dbfa17.png)
i have now done it and i am getting this message on nanopool, also the miner says it faalse at the end still

**Comment by UnamSanctam** [comment]
You need to mine a share first which will take a while. It's supposed to say "False" since you don't have a GPU that can mine. Check your CPU usage to see if it's mining or not.
