### ISSUE TITLE
Virus?

### ISSUE THREAD

**Issue by ttrsemotion** [UnamSanctam/SilentXMRMiner#414]
Windows automatically deletes this bc it has a virus? Worth disabling shields to get this? Confirmation of working?

**Comment by UnamSanctam** [comment]
It's open source so yes it's safe and works. The builder contains miners and everything else which will trigger detections, since it's open source I have not encrypted anything of it or tried to make the builder undetected since there is no reason to.

**Comment by ttrsemotion** [comment]
Thanks a lot, dev!
