### ISSUE TITLE
i am trying to edit the source code so i can encrypt it

### ISSUE THREAD

**Issue by monero9365** [UnamSanctam/SilentXMRMiner#415]
whenever i paste it in notepad++ or visual editer some hyrogliphics show up and suddenly im back to egypt lost.    how to i edit source code or encrpt it and all..ps. very new to all of this

**Comment by UnamSanctam** [comment]
Open "SilentXMRMiner.sln" with Visual Studio.

**Comment by monero9365** [comment]
i have opened it in visual studio i've cloned the link just for sln and i've also tried a million other things and i still cant seem to get the code for it, someone on youtube sid for me to encrypt it i should use mal_enc/b64 = """ text here """then have code here to base64 decdoe it or decrypt it and run using exec(decode(mal_b64) ... that last bit is copy and pasted he said youtube it ive been youtubing for a good 30 hours now lol

**Comment by UnamSanctam** [comment]
None of those are valid functions but what are you trying to encrypt? All the strings and functions in the miner are already encrypted.

**Comment by monero9365** [comment]
oh maybe that  explains a lot then, however i went into the hex of it and there is still full un encrypted words there that can be edited to bypass some avs, didint do much though when i checked it, how can i edit it to get past avs?
