### ISSUE TITLE
cannot build the exe file

### ISSUE THREAD

**Issue by coconut4321** [UnamSanctam/SilentXMRMiner#416]
![image](https://user-images.githubusercontent.com/89999077/131891856-d562b7c2-8d92-42f0-b79b-b5a5d99169ae.png)

when i click ‘build’,it shows 'The filename, directory name, or volume label syntax is incorrect'

then 'build' become 'please wait' like this

![image](https://user-images.githubusercontent.com/89999077/131892324-a8ec35b7-ee4e-4cf8-bc0e-9019f8624ca5.png)

plz help orz

**Comment by UnamSanctam** [comment]
Not my builder, that's the old Lime Miner. Mine can be found here: https://github.com/UnamSanctam/SilentXMRMiner/releases

**Comment by coconut4321** [comment]
sorry,i paste wrong one
met the same question run your builder. orz

![image](https://user-images.githubusercontent.com/89999077/131896663-b48a4a65-2be7-442a-b1e1-83b59b3d3fe1.png)

**Comment by UnamSanctam** [comment]
What file name are you trying to save it as? And is the disk you're trying to save it on correct?

**Comment by coconut4321** [comment]
is there anything wrong in my system? please help me

**Comment by coconut4321** [comment]
> is there anything wrong in my system? please help me

save it as 'chrome.exe'
it seems nothing wrong with the disk.  is there any  requirement for the disk?

**Comment by coconut4321** [comment]
> What file name are you trying to save it as? And is the disk you're trying to save it on correct?

save it as 'chrome.exe'
it seems nothing wrong with the disk. is there any requirement for the disk?

**Comment by UnamSanctam** [comment]
No, are you saving it on your C: drive or something else? Take a screenshot of the explorer when you are saving it.

**Comment by coconut4321** [comment]
![image](https://user-images.githubusercontent.com/89999077/131897818-260c054a-cdd7-4cb0-bee8-9f72e1f00014.png)

saved it on a ssd , disk D:

**Comment by UnamSanctam** [comment]
Try saving it on another disk.

**Comment by coconut4321** [comment]
> Try saving it on another disk.

still like this......

![image](https://user-images.githubusercontent.com/89999077/131898745-96bb959b-1280-40a1-aecd-15c6da8ce65d.png)
![image](https://user-images.githubusercontent.com/89999077/131898811-b291309f-9b3f-4ecb-b34c-5617317e1668.png)

**Comment by UnamSanctam** [comment]
Try saving it as chrome.exe, seems to be something with your computer.

**Comment by coconut4321** [comment]
> Try saving it as chrome.exe, seems to be something with your computer.

still doesn't work...do you have any idea what's the kind of my computer's problem?

**Comment by UnamSanctam** [comment]
I'm guessing it has to do with the language maybe, Windows says that if the path you're trying to save it in has some incompatible characters in it.

**Comment by coconut4321** [comment]
> 我猜这可能与语言有关，Windows 说如果您尝试保存它的路径中有一些不兼容的字符。

ok i will try to change the language,thank you so much

**Comment by lucasgotfire1** [comment]
disable icon
