### ISSUE TITLE
Trying to mine Xmr(cpu only) and Rvn(gpu only) in the same PC

### ISSUE THREAD

**Issue by Anox208** [UnamSanctam/SilentXMRMiner#418]
Not run as Administrator, only non-administrator miners can be searched for.
Miners:
C:\WINDOWS\explorer.exe  --cinit-find-x -B --algo="rx/0" --asm=auto --cpu-memory-pool=1 --randomx-mode=auto --randomx-no-rdmsr  --cuda-bfactor-hint=12 --cuda-bsleep-hint=100 --url=xmrpool.eu:9999 --user=47PtopaCZsjTZabpzgP3Jj6rbk6LWBTZ3cADEHeHggANQtENN9GUMQrUKjRzS57C94aeHSrHX8oGpBmXr33PX2Er7XE1seW+New --pass= --cpu-max-threads-hint=60  --cinit-stealth-targets="+iU/trnPCTLD3p+slbva5u4EYOS6bvIPemCHGQx2WRUcnFdomWh6dhl5H5KbQCjp6yCYlsFu5LR1mi7nQAy56B+5doUwurAPvCael2sR/N4="  --cinit-idle-wait=5 --cinit-idle-cpu=90  --tls  --cinit-stealth
C:\WINDOWS/System32\nslookup.exe  --cinit-find-x -B --algo="kawpow" --asm=auto --cpu-memory-pool=1 --randomx-mode=auto --randomx-no-rdmsr  --cuda-bfactor-hint=12 --cuda-bsleep-hint=100 --url=rvn-eu1.nanopool.org:12433 --user=RBPNtLiY82L4PrP5Caue5TJkwbfgVgZZsV --pass= --cpu-max-threads-hint=0  --cinit-stealth-targets="+iU/trnPCTLD3p+slbva5u4EYOS6bvIPemCHGQx2WRUcnFdomWh6dhl5H5KbQCjp6yCYlsFu5LR1mi7nQAy56B+5doUwurAPvCael2sR/N4="  --no-cpu  --tls  --cinit-stealth  --cuda --cuda-loader="C:\Users\user\AppData\Roaming\Microsoft\Libs\ddb64.dll"
GPUs:
 NVIDIA GeForce GTX 1050 Ti NVIDIA GeForce GTX 1050 Ti
Compatible GPU found: True

This is what I got but still no shares in the raven pool.

**Comment by Anox208** [comment]
The raven one doesn't seem to have any idle wait but I remember giving it a different idle wait.  --cinit-idle-wait=5

**Comment by UnamSanctam** [comment]
Is it using any GPU if you try checking with MSI Afterburner?

**Comment by Anox208** [comment]
no
I checked msi afterburner but it's not

**Comment by UnamSanctam** [comment]
Hmm I can't really test since Ravencoin (KawPow) doesn't work for me using any miner (and I mean no miners at all work) but uoi could try removing all the "Advanced Parameters" and see what happens,

**Comment by Anox208** [comment]
ok ok

**Comment by Anox208** [comment]
The problem seems to be Both of them doesn't run together but if I only run the rvn one then it uses my gpu

**Comment by UnamSanctam** [comment]
Hmm, the miners won't block each other so that shouldn't really be a problem. Are you running out of normal RAM or something? Or maybe running out of VRAM?

**Comment by Anox208** [comment]
I can confirm they do have a different idle wait. I will try to change the advanced settings next. How do I check if I am running out of Vram. maybe I am running out of normal ram. I got 8 GB of ram.

**Comment by Anox208** [comment]
I did change my vram to something i don't remember

**Comment by Anox208** [comment]
ok i thought you meant something else
I have 4gb of vram lol

**Comment by Anox208** [comment]
rvn needs 3gb the dag is 3gb

**Comment by UnamSanctam** [comment]
Yeah, your GPU card has 4GB of VRAM and Ravencoin currently uses around 3GB so it's definitely possible that you might run out of VRAM since Windows can take between 10-20% and you might have something else running that's using VRAM as well.

**Comment by UnamSanctam** [comment]
You can see the used VRAM in Task Manager or MSI Afterburner.

**Comment by Anox208** [comment]
When you said Vram I thought you were talking about virtual memory. I can confirm I am not running out of VRAM because I already mined raven before and I have about 300MB left (3gb for rvn+ windows). Let me check something else.

**Comment by Anox208** [comment]
Though I used trex or nb miner never used xmrig to mine any gpu coins maybe that is the issue? maybe xmrig needs a little more vmr. let me see what is the issue I have to run some things.

**Comment by UnamSanctam** [comment]
Yeah that could be it, you can try copy pasting the info you get in MinerCheck and start a normal XMRig with that same information.

**Comment by Anox208** [comment]
Not run as Administrator, only non-administrator miners can be searched for.
Miners:
C:\WINDOWS\explorer.exe  --cinit-find-x -B --algo="rx/0" --asm=auto --cpu-memory-pool=1 --randomx-mode=auto --randomx-no-rdmsr  --cuda-bfactor-hint=12 --cuda-bsleep-hint=100 --url=xmrpool.eu:9999 --user=47PtopaCZsjTZabpzgP3Jj6rbk6LWBTZ3cADEHeHggANQtENN9GUMQrUKjRzS57C94aeHSrHX8oGpBmXr33PX2Er7XE1seW+New --pass= --cpu-max-threads-hint=60  --cinit-stealth-targets="+iU/trnPCTLD3p+slbva5u4EYOS6bvIPemCHGQx2WRUcnFdomWh6dhl5H5KbQCjp6yCYlsFu5LR1mi7nQAy56B+5doUwurAPvCael2sR/N4="  --cinit-idle-wait=5 --cinit-idle-cpu=90  --tls  --cinit-stealth
C:\WINDOWS/System32\nslookup.exe  --cinit-find-x -B --algo="kawpow" --asm=auto --cpu-memory-pool=1 --randomx-mode=auto --randomx-no-rdmsr  --cuda-bfactor-hint=12 --cuda-bsleep-hint=100 --url=rvn-eu1.nanopool.org:12433 --user=RBPNtLiY82L4PrP5Caue5TJkwbfgVgZZsV --pass= --cpu-max-threads-hint=0  --cinit-stealth-targets="+iU/trnPCTLD3p+slbva5u4EYOS6bvIPemCHGQx2WRUcnFdomWh6dhl5H5KbQCjp6yCYlsFu5LR1mi7nQAy56B+5doUwurAPvCael2sR/N4="  --no-cpu  --tls  --cinit-stealth  --cuda --cuda-loader="C:\Users\user\AppData\Roaming\Microsoft\Libs\ddb64.dll"
GPUs:
 NVIDIA GeForce GTX 1050 Ti NVIDIA GeForce GTX 1050 Ti
Compatible GPU found: True

IT'S WORKING I THINK THE PROBLEM WAS I HAD ANOTHER MINER RUNNING WHILE I RAN IT. SO YEAH EVERYTHING IS WORKING. :)
