### ISSUE TITLE
склейка

### ISSUE THREAD

**Issue by welltom233** [UnamSanctam/SilentXMRMiner#419]
подскажите какой программой можно склеить файл майнера с распространяемым файлом?

**Comment by UnamSanctam** [comment]
You could use any file binder or try my https://github.com/UnamSanctam/UnamDownloader for less detections.

**Comment by welltom233** [comment]
> Вы можете использовать любой связыватель файлов или попробовать мой https://github.com/UnamSanctam/UnamDownloader для меньшего количества
