### ISSUE TITLE
Miner not mining

### ISSUE THREAD

**Issue by BenzoIsHere** [UnamSanctam/SilentXMRMiner#420]
Hello I did a fast build for RAVENcoin with all features enabled including stealth,install, run as admin thingy and all that and managed to create it and I ran it on my own PC so I can make sure it's working, problem is after idle mode passed like 5 minutes I couldn't hear or see any difference on my GPU usage, thus I think it ain't working. Is there an exact way to see if It's actually working or not?

**Comment by UnamSanctam** [comment]
Run [MinerCheck3.zip](https://github.com/UnamSanctam/SilentXMRMiner/files/7116451/MinerCheck3.zip) and post what it returns here (but censor your wallet address) so that I can see if your settings are correct.

**Comment by BenzoIsHere** [comment]
![Untitled](https://user-images.githubusercontent.com/90201064/132236530-959d87e5-4040-459c-8aa5-efe282578dcd.png)

**Comment by UnamSanctam** [comment]
Yeah that should be correct, and when you check with MSI Afterburner it's not using any GPU?

**Comment by BenzoIsHere** [comment]
By the way, Raven is a GPU only algorithm, seems like I got the GPU fans running a bit more than usual after running the executable but don't see any changes in Idle mode after 5 minutes, does the CPU IDLE mode also stand for gpu idle mode? [80%] (left the 20/80 procentile for standard/idle as suggested cuz seems fair as for a non suspicious thing).

**Comment by BenzoIsHere** [comment]
Didn't know that MSI Afterburner gonna show it, let me download it real quick and wait 5 minutes for ,,idle'' mode as well. Gonna reply back immediately after. Thank for the fast support by the way, appreciate it!

**Comment by UnamSanctam** [comment]
The Idle mode doesn't work for the GPU since it uses a lot of different algorithms for the GPU. I have tried to implement it before but that doesn't always work correctly on all algorithms due to how they are implemented. The --cuda-bfactor and --cuda-bsleep arguments in the "Advanced Parameters" are used to control the GPU usage, and that differs on each GPU.

**Comment by BenzoIsHere** [comment]
![image](https://user-images.githubusercontent.com/90201064/132238057-9b245d80-4432-45e7-a70c-cea294a4c115.png)
This is what I got on GPU usage in a timespan of ~7 minutes, a short 40 secs spike at 100% in GPU usage but don't think that's on the miner. What do you suggest, is there anything to be done on controlling GPU usage on standard GPU basis or should I focus on CPU coins?

**Comment by BenzoIsHere** [comment]
> This is what I got on GPU usage in a timespan of ~7 minutes, a short 40 secs spike at 100% in GPU usage but don't think that's on the miner. What do you suggest, is there anything to be done on controlling GPU usage on standard GPU basis or should I focus on CPU coins?
To be precise any kind of real-time Windows protection or third party AV is turned off/blocked at the moment of doing this check, immediately after and before running the miner executable.

**Comment by BenzoIsHere** [comment]
To be precise any kind of real-time Windows protection or third party AV is turned off/blocked at the moment of doing this check, immediately after and before running the miner executable.

**Comment by UnamSanctam** [comment]
Do you have any of the "Stealth Targets" programs such as Task Manager or anything open? Since it will pause the miner if you do. I am planning on implementing (or rather remaking) some sort of GPU usage limits but there are a lot of algorithms to test. I am also planning on implementing KawPow into https://github.com/UnamSanctam/SilentETHMiner but I have to remake most of the miner to support multiple algorithms and then also implement the KawPow algorithms itself.

**Comment by BenzoIsHere** [comment]
No, ain't got any of them open.
So the miner settings are showing that's actually properly configured, I'm gonna try uninstall it and redo it again, I did a PC restart after running the executable for a reason I can't remember, that might have interfered with Windows Defender or anything, as Real-Time protection automatically turns on after every restart for some reason.

**Comment by BenzoIsHere** [comment]
@UnamSanctam Can you recommend a mining pool other than Nanopool? With to user/pass required, like for mass mining :)

**Comment by UnamSanctam** [comment]
There aren't any good ones to be honest. You can try https://ravencoin.flypool.org/ and if you do get banned or anything you can change it using 'Remote Configuration' https://github.com/UnamSanctam/SilentXMRMiner/wiki#remote-configuration

**Comment by BenzoIsHere** [comment]
Do you reckon this mass mining it's gonna end anytime soon? I believe there are certain pools that we can't even know about 🍡

**Comment by UnamSanctam** [comment]
No probably not, you can find pools here: https://miningpoolstats.stream/ravencoin

**Comment by BenzoIsHere** [comment]
So can I use a single link for remote configuration and just change the config text on the link everytime I need to pass the workers to another pool?

**Comment by UnamSanctam** [comment]
Yes exactly, the miners will check the 'Remote Configuration' every 100 minutes (so to not spam the config host) and change their settings if anything has been changed.

**Comment by BenzoIsHere** [comment]
Well, I have to admit that's a good add-on implemented. Thanks for your support again and sorry for asking more questions than the IRS, I got 0 to little knowledge to anything related to mining, especially in this way, as I'm an intermediate web developer and can't seem to figure out everything on my own without your help. So I really appreciate everything. Any way to vouch for you or recommend as an user over here on GIT?

**Comment by UnamSanctam** [comment]
Haha it's no problem, I make the miner for people to use it and helping people setting it is a part of that. You can star the repository in the top-right if you want to.

**Comment by BenzoIsHere** [comment]
Appreciate that, starred all of them. I'll be back as soon as I get my miner working for further questions. xd

**Comment by BenzoIsHere** [comment]
![image](https://user-images.githubusercontent.com/90201064/132244126-07073e18-2d2c-4b7d-84c1-4ee46e810720.png)
This is the new miner config after switching to a different pool, right now I'm still waiting for the GPU Usage to start acting up, should it start like immediately after the miner has been injected? Doesn't seem to change anything. 
If I can't find a solution to this I might have to try switching to a CPU coin, see if anything happens. Maybe my PC is just too well protected, haha.

**Comment by BenzoIsHere** [comment]
There isn't any general GPU string that I could change to like make a general usage term for any kind of GPU, is it? Like to be permanently X %, don't really care about IDLE.

**Comment by BenzoIsHere** [comment]
My RaveCoin Wallet has also not fully synced with the network as it is still Syncing Headers, not totally finished. Could this probably stop me from start mining by any way?

**Comment by UnamSanctam** [comment]
> There isn't any general GPU string that I could change to like make a general usage term for any kind of GPU, is it? Like to be permanently X %, don't really care about IDLE.

No not really, it depends on the GPU



> My RaveCoin Wallet has also not fully synced with the network as it is still Syncing Headers, not totally finished. Could this probably stop me from start mining by any way?

No that won't matter.

> This is the new miner config after switching to a different pool, right now I'm still waiting for the GPU Usage to start acting up, should it start like immediately after the miner has been injected? Doesn't seem to change anything.
> If I can't find a solution to this I might have to try switching to a CPU coin, see if anything happens. Maybe my PC is just too well protected, haha.

Your url there is wrong, you shouldn't include the protocol, just enter `stratum.ravenminer.com:13838` as the pool.

**Comment by BenzoIsHere** [comment]
![image](https://user-images.githubusercontent.com/90201064/132244856-63663696-0fdd-4dd6-a890-fe93a852064e.png)
Saw this on the pool's FAQ, on the previous build based on Nanopool the URL was correct though, i'll change it now.

**Comment by UnamSanctam** [comment]
Yeah that's when using explicit protocols but the miner detects the correct one by itself.

**Comment by BenzoIsHere** [comment]
Oh, working on it rn.

**Comment by BenzoIsHere** [comment]
Couldn't manage to do anything with RavenCoin which was my no1 choice anyway, so I thought I should try an ETC build, and guess what, works like a charm, all features activated. Thing is I indicated in the config a 20/80 procentile ratio for standard/idle GPU mining, although my GPU usage stays at a stable ~60-70% usage during standard mode, and in Idle mode it spikes up and down from 0 to 100%, back and forth, every 5 seconds, so what could be wrong here :(. 
![image](https://user-images.githubusercontent.com/90201064/132250453-768a7cf2-98e2-4d17-9886-8caadbe7fc74.png)

**Comment by UnamSanctam** [comment]
No that's how it works, 50% GPU just means: let's say one kernel call is 50ms then 50% would mean that it mines for that 50ms (at 100%) and then sleeps for 50ms making it an average of 50%, that's how GPUs work.

All GPU usage really changes is the fan speed and temperature so the normal thing to use (for more stealth) is around 50%-60% Max GPU and 90%-100% Idle GPU. The Silent ETH Miner automatically uses less GPU when another program needs it.

**Comment by BenzoIsHere** [comment]
What I'm intending to explain you is that my standard usage is set to 20% and idle set to 80%. And right now in standard mode I actually got 60-70% real usage and in IDLE i got the fluctuating usage 0-85 back and forth. What happens if I set standard to 50-60 and 90-100 idle? I guess it ain't really a maths problem here, at least in my way of thinking. Haha

**Comment by BenzoIsHere** [comment]
![image](https://user-images.githubusercontent.com/90201064/132251096-62c3adaf-3fb5-4a88-b759-b676d6fdba1e.png)
This is what MSI Afterbuner shows although miner standard usage is set to 20%. Is that normal? Didn't really understand 👯

**Comment by UnamSanctam** [comment]
Your Idle GPU is set to 20% as you can see in the image, and your Max GPU is set to 80%. Which graphs both look correct in your screenshot.

**Comment by BenzoIsHere** [comment]
Oh, so i did it the other way round, lol.

**Comment by UnamSanctam** [comment]
Yeah haha.

**Comment by BenzoIsHere** [comment]
I just noticed what the config is trying to telling me xD

**Comment by BenzoIsHere** [comment]
So the stealthiest recommended config would be like ~50% max and ~90% idle, right? What's your opinion over this.

**Comment by UnamSanctam** [comment]
Yes usually, depends on the GPU, temperature in the environment, the airflow of the computer and a lot of other things. I can run it at 100% and not notice that it's running so it depends.

**Comment by BenzoIsHere** [comment]
Yeah, same for me about the performance. Thanks a lot for the info. 
Would binding my miner executable to another executable lower the detection rates or is it a particular way of ,,encrypting'' it that works better before binding it to another .exe?

**Comment by BenzoIsHere** [comment]
![image](https://user-images.githubusercontent.com/90201064/132253582-bb3e6aad-f2ad-4a81-99f1-66d8bec580dc.png)
I recently I got my first accepted share on the pool, says my calculated hashrate would be 17 MH/s but the 2hours SMA would be 2 Mh/s, is that an average hashrate or what? Difference seems fairly big and that kinda worries me, maybe anything to do with like the config of the miner? Or it just takes some time to equilibrate after getting into the pool.

**Comment by UnamSanctam** [comment]
Yes it's the 2 hour average.

**Comment by UnamSanctam** [comment]
Binding files will always increase detections, if you just want to make it undetectable by Windows Defender then you can use my downloader https://github.com/UnamSanctam/UnamDownloader.

**Comment by BenzoIsHere** [comment]
Can I bind two files with your downloader? Or what does it do precisely other than making it undetectable?

**Comment by UnamSanctam** [comment]
Yes you can add any amount of files for it to download, you can enable it to add exclusions into Windows Defender before download and executing any files, meaning that it can exclude any detections the miner would have. https://github.com/UnamSanctam/UnamDownloader/wiki

**Comment by BenzoIsHere** [comment]
![image](https://user-images.githubusercontent.com/90201064/132257160-4a4aee36-7125-4d80-8ddf-7079cbed1a95.png)
Just noticed that Nanopool suggests that minimum payout is 1 ETC, would that be the minimum payout for the particular miner I just managed to launch or is it for all my workers alltogether that mined for that wallet? :(

**Comment by BenzoIsHere** [comment]
![image](https://user-images.githubusercontent.com/90201064/132257248-63e12bdb-e6e2-4cac-8ee4-19a6c1035d2e.png)
Just noticed that Nanopool suggests that minimum payout is 1 ETC, would that be the minimum payout for the particular miner I just managed to launch or is it for all my workers alltogether that mined for that wallet? :(

**Comment by UnamSanctam** [comment]
That's the set minimum payout overall, you can change it in the settings if you mine with an email (though it's a bit buggy on ETC nanopool).

**Comment by BenzoIsHere** [comment]
So if I got the same miner mining for 10 different systems around It's all gonna be 1 ETC overall minimum?

**Comment by UnamSanctam** [comment]
Yes, it's the minimum payout for that wallet address.

**Comment by BenzoIsHere** [comment]
Oh, that saved my breath, 1 ETC on an average gaming rig would have taken like 3 months to break down. Lul

**Comment by BenzoIsHere** [comment]
Can't really find if there's a maximum of workers for a single wallet or this specific pool, Nanopool. Guess it can be suspicious to just have a 3 digit sum of systems mining for one single wallet.

**Comment by UnamSanctam** [comment]
Not really that I know of, I've seen miners with over 20 000 workers.

**Comment by BenzoIsHere** [comment]
On nanopool? That's mad sick. Why wouldn't anyone notice there's something suspicious going on.

**Comment by UnamSanctam** [comment]
Well, they probably do but I don't think nanopool cares.

**Comment by BenzoIsHere** [comment]
Well, as long as they got their fee paid out there's nothing for them to care about, Haha. bless

**Comment by BenzoIsHere** [comment]
Have you got a zipped unnistaler for me? I erased mine completely by accident.

**Comment by UnamSanctam** [comment]
If you build a new miner with the same settings then that one will work.

**Comment by BenzoIsHere** [comment]
Oh thanks :D

**Comment by BenzoIsHere** [comment]
I guess most of my questions on the technic part of the miner's building procedure have been answered. If anything about detection or a bit of advice I'm gonna open another topic on the detector's repository, If that's all right. I'm closing this, highly recommended developer, much respect and appreciation for the quickness in answering every question and the patience involved. Bless!
