### ISSUE TITLE
New Update ?

### ISSUE THREAD

**Issue by DogusCyk** [UnamSanctam/SilentXMRMiner#422]
Will there be a new update, what will come with the update?

**Comment by gamethrower** [comment]
`libuv` dropped support of Windows 7. New versions of xmrig will crash on Windows 7 from now.
Will you update it or keep the old version of xmrig? I hope not, because believe it or not a lot of people are still using Win7!

**Comment by UnamSanctam** [comment]
> Will there be a new update, what will come with the update?

The new update will be a unified miner with a lot of new changes, a bit to numerous for me to remember without checking. But right now I'm working on the code for the installer/injector in C (to reduce detections) but I have to find some good way to support assembly data and icons without requiring users to install Msys2 for windres.

> `libuv` dropped support of Windows 7. New versions of xmrig will crash on Windows 7 from now.
> Will you update it or keep the old version of xmrig? I hope not, because believe it or not a lot of people are still using Win7!

I always try to keep things updated but if some update will break compatibility with older (but still used) systems like Windows 7 then I will not update it. So if it is indeed the case that new versions of libuv will not work with older systems such as Windows 7 then I don't intend to update libuv.

**Comment by gamethrower** [comment]
I remember you were saying the new unified miner will have a control panel. That means port forwarding/VPS is required to use it? 

Don't know how it is in your country, but here many ISP keep users behind NAT, making it impossible to forward a port. They can't even sell white IPs for some types of connection (which is my case).

Don't wanna trust hosting services, so is there any way around it?

**Comment by UnamSanctam** [comment]
The control panel will use a HTTP endpoint since it's not a RAT just a control panel (check the status of miners and control the configuration) for the miner itself. It's also made this way to make it easier to host, you can use any website host if you want to, but if you do want to run the (web)server yourself then you can use VPNs that supports port forwarding.

**Comment by gamethrower** [comment]
Alright, can you recommend any web hosting that will not take down "suspicious sites" then?

**Comment by UnamSanctam** [comment]
Not really that I know of since I never use any hosts, hosting behind a VPN is a lot better for it.

**Comment by gamethrower** [comment]
Never heard that VPN can provide static IP and port forwarding features. What kind of VPN you personally use and is it expensive?

**Comment by UnamSanctam** [comment]
Some VPNs like Ivacy VPN and PureVPN offer dedicated IPs and Port Forwarding but they aren't very good to be honest. Then there are VPNs like Mullvad VPN that only offers Port Forwarding (random port) and it's a lot better but has less features, if you connect to the same server then it should always have the same IP, you could also use a domain and point it to the IP and then change it if ever needed.

**Comment by gamethrower** [comment]
How to point the workers to the correct port if it's random?

**Comment by UnamSanctam** [comment]
You get a random port of the country and city you choose, but that port will stay the same (unless you stop paying for the VPN).

**Comment by gamethrower** [comment]
Ah, it's ok then. Thanks for consultation, issue can be closed now.

**Comment by spaghetti1037** [comment]
Will the update with control panel he available for older versions if remote download is enabled? If so, how will I be able to configure the IP and all for the control panel, will it be with the remote configuration?

**Comment by UnamSanctam** [comment]
No it will be a new miner (the unified miner), technically it would be possible to update the two current miners with it but that still wouldn't make it work with most already installed miners since they cache the miner download and won't redownload it unless the cache disappears.

**Comment by spaghetti1037** [comment]
Aight, will the unified miner be able to mine xmr and eth? Or is It just one of them

**Comment by UnamSanctam** [comment]
Yes it will have both the xmrig and ethminer inside it and you can add multiple miners inside it, so you could add one miner that mines XMR and one that mines ETH or any other cryptocurrencies supported and they will all start.

**Comment by spaghetti1037** [comment]
That sounds cool! Thanks for updating your projects, really appreciate it.
