### ISSUE TITLE
Error Message: MetaData file 

### ISSUE THREAD

**Issue by syedtahasaif** [UnamSanctam/SilentXMRMiner#426]
![Screenshot_1](https://user-images.githubusercontent.com/68808488/133288382-d3755392-d1d7-4286-94bc-1f7b4032e4c2.png)
![Screenshot_2](https://user-images.githubusercontent.com/68808488/133288389-f0041066-bfba-41a3-a96c-a6f02ef9ab3e.png)

I am getting this error while building miner...
Pls Help

**Comment by UnamSanctam** [comment]
Try repairing your .NET Framework, you are missing some DLLs.

**Comment by syedtahasaif** [comment]
Thanks, the software is working completly fine after installing .net 4.8
