### ISSUE TITLE
Possible to mine XMR & ETC

### ISSUE THREAD

**Issue by callMeshelter** [UnamSanctam/SilentXMRMiner#429]
Hi! I was wondering if it was possible to launch the ETC and XMR miner at the same time from a single .exe file

**Comment by UnamSanctam** [comment]
Build both and then use a binder, https://github.com/UnamSanctam/UnamBinder.

**Comment by callMeshelter** [comment]
from the build file with Binder I can have an .exe for both minors?

**Comment by UnamSanctam** [comment]
Build both miners with their respective builders and then use the binder to bind the two exe's together. That's what a binder does, it binds several files into one (and then when run it separates back into the files you bound and executes them).

**Comment by callMeshelter** [comment]
thanks got it, but i can't add an icon with Binder, I got this
![apppear](https://user-images.githubusercontent.com/90361397/133863406-68f95dc1-a7a7-4c09-8b4d-c9501c1abdad.PNG)

**Comment by UnamSanctam** [comment]
Open the log, it will say why.

**Comment by callMeshelter** [comment]
resource.rc:2: unrecognized escape sequence
resource.rc:2: unrecognized escape sequence
resource.rc:2: unrecognized escape sequence
C:\Users\Arthur-PC\Desktop\Mineur\Compiler\MinGW64\bin\windres.exe: can't open icon file `C:\Users\Arthur-PC\Picturesortnite.ico': Invalid argument

**Comment by UnamSanctam** [comment]
Oh yeah, rename your icon, currently it doesn't escape any escape sequences.

**Comment by callMeshelter** [comment]
Thank you it works !
