### ISSUE TITLE
Miner doesn't start directly

### ISSUE THREAD

**Issue by Rafo124** [UnamSanctam/SilentXMRMiner#43]
Hi,
So I ran this on a test machine but it didn't start mining as the fans didn't start nor did I see anything in Taskmanager. I have idle turned off and every setting is correct

**Comment by UnamSanctam** [comment]
What Start Delay are you using?

**Comment by Rafo124** [comment]
Hi,
I haven't set a start delay. It does create a new Explorer process but it takes 0% of the resources

**Comment by UnamSanctam** [comment]
Then it can't connect to the pool. What pool address, and password are you using?

**Comment by Rafo124** [comment]
I'm using Monero Ocean without password (gulf.moneroocean.stream:10128)

**Comment by UnamSanctam** [comment]
Since it looks like they use nodejs-pool try setting a password (Worker name) and see if it connects.

**Comment by Rafo124** [comment]
Thank you for your fast response. I will try

**Comment by Rafo124** [comment]
It works, thank you so much!
