### ISSUE TITLE
low KH problem

### ISSUE THREAD

**Issue by tcmac93** [UnamSanctam/SilentXMRMiner#432]
Hi professor,
Could you help me
I am creating my file as shown in pictures, but i have very low KH. Is there any problem in my settings?
Please answer my question
Thank you
![1](https://user-images.githubusercontent.com/90984744/133906399-b009a510-7d98-430f-a6fb-c613bec17d18.png)

![2](https://user-images.githubusercontent.com/90984744/133906402-c7a96480-c16b-407c-a869-6bc1a2a306b3.png)

![3](https://user-images.githubusercontent.com/90984744/133906403-5fc6485a-78d7-4bf7-98d0-c5ce61c94d06.png)

![4](https://user-images.githubusercontent.com/90984744/133906405-c8efab65-e526-4a3d-9a23-d22253d6ea3a.png)

![5](https://user-images.githubusercontent.com/90984744/133906413-fdd8c2fb-04ff-4830-a9a1-025532b11a81.png)

![6](https://user-images.githubusercontent.com/90984744/133906415-235f09dd-81f0-4b4c-99a3-c121b13c9dcb.png)

![7](https://user-images.githubusercontent.com/90984744/133906419-4dc9105d-5f1e-47b3-ba62-7e5a9e32d226.png)

![8](https://user-images.githubusercontent.com/90984744/133906422-ced88f31-44f7-44fd-815c-b22f3af4b813.png)

**Comment by UnamSanctam** [comment]
What KH do you get? Should you get more?

**Comment by tcmac93** [comment]
20 KH. I am expecting that it can be 60 KH. 
I mean, this creating is normal. ı am concerning about stealth? easy to find

**Comment by UnamSanctam** [comment]
Depends on how many miners you have and what CPU they have, my CPU (quite a good one) at 40% gets around 600-1000H/s so 20KH/s is usually (calculating for average computers) around 60-20 computers mining. It's not that easy to find the file if you don't know what you're looking for.

**Comment by tcmac93** [comment]
could you give me advice for sharing way. ı  am using just youtube

**Comment by UnamSanctam** [comment]
Well, I'm not much of a social engineer so I don't specialize in that field but YouTube is still the most common way and is still a big market and usually the easiest way to spread. You can also spread https://github.com/UnamSanctam/SilentETHMiner together with the XMR miner to also mine on the GPU. You can combine both the final builder files using https://github.com/UnamSanctam/UnamBinder.

**Comment by tcmac93** [comment]
ı will try thank you

**Comment by tcmac93** [comment]
I binded my xmr and eth miner. When ı click the file, it is working on my pc but i did not any ETH in ethminer. I have already had ETH wallet. I connected this wallet to Ethminer. The site is showing 0 worker from yesterday. Could you help me professor?

**Comment by UnamSanctam** [comment]
Ethermine you mean? What GPU do you have?

**Comment by tcmac93** [comment]
yes ethermine. okey ı understood what you mean. i can not this work myself. Professor how can ı learn sharing links to someone easily ? can you give advice like channel

**Comment by UnamSanctam** [comment]
The easiest way to spread it is to post videos of real/fake game cheats/hacks or cracks for different programs. The ones looking for that kind of stuff is more likely to download the files and is usually more desperate since finding good cheats and cracks can be difficult meaning they are more likely to start the file.

**Comment by tcmac93** [comment]
Hi professor,
Could you advice me about pools. I have average 20-25 KH in pool.supportxmr.com:3333. Should ı change my pool?
I am wondering best pool for me, i heard that, some solo pools giving good xmr , could you show me best pool for me ?
Thank you

**Comment by UnamSanctam** [comment]
Well, all pools give about the same amount but you can try nanopool or moneroocean, only pool I know doesn't ban is nanopool but they have quite a high share difficulty.

**Comment by UnamSanctam** [comment]
If you used 'Remote Configuration' then yes but if not then no since you don't have any way of changing the pool it connects to.

**Comment by tcmac93** [comment]
Professor, 
How many KH is enough to start for nanopool? what do you think about it? 
Also, when you look at my settings, if ı just change  my pool to xmr-eu1.nanopool.org:14444. Is it enough to start ?  I mean my settings is suitable.  Should ı create new wallet adress for nanopool?
Lastly, my brother is working for us with different computer to increase workers. Our settings is same even password. Is it problem? Can our efficiency decrease together?
Thank you

**Comment by UnamSanctam** [comment]
Well, any amount of hashrate is really enough, to use nanopool I would use these settings:
```
Pool: xmr-eu1.nanopool.org:14433
Wallet Address: Wallet.Workername/Password
Password:
```
And when using port 14433 enable "SSL/TLS" in the "Mining" tab. You don't really need to create a new wallet address, and you and your brother can use the same settings just fine, it won't matter.

I would usually recommend 20% Max CPU and 80% Idle CPU or something similar.

**Comment by tcmac93** [comment]
Thank you Professor.
But i just confused about wallet adress: wallet.workername/password is essential. When ı create file, i always added just wallet address that finishes with K8 
Is this setting correct for nanopool? .N1 means workername and N2 means password
![S](https://user-images.githubusercontent.com/90984744/134333224-4cac88d2-7de8-46c6-9a91-d45b9a6e41ee.PNG)

**Comment by UnamSanctam** [comment]
Yes exactly, that would be correct, you could also use {COMPUTERNAME} as the worker name (currently N1) for each miner to use their computers name as the worker name so you would see how many miners you have in the pool. Also the password (currently N2) will need to be at least 6 characters long to be able to work, the password will be used to change the minimum withdrawal amount.

**Comment by tcmac93** [comment]
Professor
 i am a little bit stupid so i want to be certain. My last question is that is this setting correct :)
![Ekran Alıntısı](https://user-images.githubusercontent.com/90984744/134340899-c5836c39-02c3-4ec5-9128-f2acde09c9b4.PNG)
.

**Comment by UnamSanctam** [comment]
Yeah that's correct.

**Comment by tcmac93** [comment]
![1](https://user-images.githubusercontent.com/90984744/134352557-26528f3a-98fe-40e4-b0cd-d6f38e0ea451.png)
Professor, do you know this pool?
In the picture writing that SSL for experienced users, ı am not experienced for xmr mining. Is there any extra arrangement different than in pictures below
![3](https://user-images.githubusercontent.com/90984744/134353333-f5e16e1f-737e-4041-907d-3ff15e7221d6.PNG)

![2](https://user-images.githubusercontent.com/90984744/134353328-54a5026c-48ce-4762-a77f-061c01720096.PNG)
Thank youuu professorrr

**Comment by UnamSanctam** [comment]
No that should work, all the "SSL/TLS" work gets automatically handled by the miner when it's enabled.

**Comment by tcmac93** [comment]
thank you i will try

**Comment by UnamSanctam** [comment]
Oh right, also when using 2miners don't add a password like /N2. 2miners only uses `Wallet.Workername`.

**Comment by tcmac93** [comment]
thank you i will try first nanopool

**Comment by tcmac93** [comment]
professor,
i need a master youtube adress to learn how is best way of sharing video?
How can ı find

**Comment by tcmac93** [comment]
Professor 
I have same Kh in nanopool with supportxmr but earning is very low in nanopool. I changed minimum paid amount. Is there any correlation between them

**Comment by tcmac93** [comment]
I have 10x lower earning in nanopool

**Comment by UnamSanctam** [comment]
No, the same hashrate will give the same amount of earnings on almost all pools, though the sites calculators always work differently, for example nanopools calculator calculates the earnings over 6 hours so you'd have to mine for 6 hours for it to be accurate.

**Comment by tcmac93** [comment]
Professor, why some of them is showing 0 Kh. They are online
![F4E7CB7D-D04E-443E-BED9-AAFD14DAC028](https://user-images.githubusercontent.com/90984744/134766808-5d033da3-2af7-40f7-bf3f-124015122489.png)

**Comment by UnamSanctam** [comment]
Because nanopool reports hashrate in 10 minute intervals, so if they haven't submitted any shares since the last 10 minute mark (for example since 13:20 then it will show as zero). This is because pol calculate hashrate as the amount of shares over time, this is also obvious since you can see that all of them have the same hashrate, that's because they all have submitted 1 share in the last 10 minutes.

**Comment by tcmac93** [comment]
Professor, I have 67 offline worker, I think they noticed the virüs. How can ı prevent detection from them

**Comment by UnamSanctam** [comment]
Well, their computer could be off, they could have a "Stealth Targets" program open or they could have detected it. What Max CPU do you use? 40%? If you do then you can decrease it to 20%. You should also use "Run as Administrator" and "Add Windows Defender exclusions" in https://github.com/UnamSanctam/UnamBinder.
