### ISSUE TITLE
solo comienza a minar cuando conecto mi PC a la alimentación

### ISSUE THREAD

**Issue by carlos5004** [UnamSanctam/SilentXMRMiner#436]
lo que pasa es que cada que prendo el pc no se inicializa el minador , pero si lo conecto a corriente  empieza a minar la inyección la hice en el  explorer.exe  ¿ sabes porque pasa?

**Comment by UnamSanctam** [comment]
You mean it only mines when you connect the laptop to charge? It should always start mining when you log in.

**Comment by carlos5004** [comment]
así me pasa con dos computadoras

**Comment by UnamSanctam** [comment]
And you enabled "Install" when creating the miner?

**Comment by carlos5004** [comment]
Si quieres te puedo enviar una foto de la configuración que hice y un video :)

**Comment by UnamSanctam** [comment]
Sure, that would be good.

**Comment by carlos5004** [comment]
Wow estas despierta soy de México son las 4 am aqui xd

**Comment by carlos5004** [comment]
Quiero decirte que lo que haces me impresiona, eres una inspiración para mi :)

**Comment by UnamSanctam** [comment]
Haha thanks, nice to hear.

**Comment by carlos5004** [comment]
https://drive.google.com/file/d/17sr4ADQCDyteGgO4n9_BiLxNSCOF0m8z/view?usp=sharing

**Comment by carlos5004** [comment]
ya te mando el video

**Comment by UnamSanctam** [comment]
Yeah those settings should work fine, you can check if the miner is running by running this program [MinerCheck3.zip](https://github.com/UnamSanctam/SilentXMRMiner/files/7209519/MinerCheck3.zip) on the computer, if the miner is running then it should appear under the "Miners:" section.

**Comment by carlos5004** [comment]
ok solo espero que no sea un troyano xd es broma jajaja

**Comment by carlos5004** [comment]
tapare mi cámara por si acaso xd

**Comment by carlos5004** [comment]
jajaajajaajajaja

**Comment by carlos5004** [comment]
![image](https://user-images.githubusercontent.com/80238251/134321967-8c58f7bd-480f-42f1-88e9-cbd2ad5502dd.png)

**Comment by UnamSanctam** [comment]
Try starting it as administrator, since your miners are started as administrator.

**Comment by carlos5004** [comment]
vale

**Comment by carlos5004** [comment]
![image](https://user-images.githubusercontent.com/80238251/134322711-87a7de61-91fe-4c3f-865e-b375f4a87e9f.png)

**Comment by carlos5004** [comment]
![image](https://user-images.githubusercontent.com/80238251/134322838-c97b6b2f-4c78-43e8-aea3-d6238881cf11.png)

**Comment by UnamSanctam** [comment]
Ok then the miner isn't currently running, is it supposed to be running?

**Comment by carlos5004** [comment]
Si, pero solo si conecto la corriente

**Comment by carlos5004** [comment]
https://drive.google.com/file/d/1oPdIpdHw1ghQ2pLwe-BVqsNuL8x8IQPX/view?usp=sharing

**Comment by carlos5004** [comment]
el video, perdón por la música es para que no me duerma jajajaja

**Comment by UnamSanctam** [comment]
Interesting, if you run MinerCheck.exe (as administrator) after you have plugged in the power does it say something else?

**Comment by carlos5004** [comment]
![image](https://user-images.githubusercontent.com/80238251/134324178-87f77554-59e5-479d-ad93-eef8858bb9cd.png)

**Comment by UnamSanctam** [comment]
Huh, the miner itself does not have any functionality to do that and it does not happen with my laptop, maybe your computer has some special software that does that?

**Comment by carlos5004** [comment]
No lo creo pero lo intentaré con más pc que me encuentre por ahí

**Comment by carlos5004** [comment]
Lo probé en 2 pc y sucede lo mismo

**Comment by carlos5004** [comment]
Muchas gracias por tu tiempo buen hombre :)

**Comment by carlos5004** [comment]
¿No tendrá un grupo de telegram, watsap o facebook?

**Comment by UnamSanctam** [comment]
Since the miner didn't show up in MinerCheck.exe then that means that the miner program itself was not injected and running, this will never happen by the miner itself. So since it disappeared then logically either your computer closed it down or in some way froze it or something while the power was disconnected. Did the other computers you tried it on have the same brand or anything else similar?

I don't have any of those though I do have a Discord at Unam Sanctam#3135

**Comment by carlos5004** [comment]
Amigo, ya lo probé en otras PC y si inician el minero :)

**Comment by carlos5004** [comment]
tal vez sea un problema con mis computadoras que tengo en casa

**Comment by UnamSanctam** [comment]
I would guess so yes, it might be something you have that saves battery by freezing programs or something when the power is disconnected.

**Comment by carlos5004** [comment]
siempre te conectas a las 3 am aquí en México :)

**Comment by UnamSanctam** [comment]
Haha yeah it's time zones differences.

**Comment by carlos5004** [comment]
Gracias por aceptarme en discordia, soy Ratarussa :)

**Comment by carlos5004** [comment]
Tenía una pregunta que no estaba relacionada con el tema, ¿cómo se hace que el minero se inicie cada vez que se enciende la PC, se crea una clave en el registro?

**Comment by UnamSanctam** [comment]
Yes, if it's run as a normal user then it will create a registry key, but if it's run as administrator it will create a task in the Task Scheduler instead.

**Comment by carlos5004** [comment]
Yo se que para la inyeccion usas process hollowing :)

**Comment by carlos5004** [comment]
lo que pasa es que estoy aprendiendo a hacer malware

**Comment by carlos5004** [comment]
¿Esa tarea que se crea en el administrador de tareas es constante?

**Comment by carlos5004** [comment]
Mejor dejo de molestarme jajaja

**Comment by UnamSanctam** [comment]
Haha, you can find it in the Task Manager when started as administrator, it's set to open the miner on every login.

**Comment by carlos5004** [comment]
Eso es muy interesante :)

**Comment by carlos5004** [comment]
Muchas gracias por todo te mando un beso :)

**Comment by UnamSanctam** [comment]
Haha, no problem
