### ISSUE TITLE
New Update?

### ISSUE THREAD

**Issue by lilkolasi** [UnamSanctam/SilentXMRMiner#439]
new update soon? pls

**Comment by UnamSanctam** [comment]
I have to build most of the things I need myself which is why it takes time. Currently I'm modifying a C ZIP library to support memory to memory decompression, I made it work but it seems to not do it correctly every time which means I have to debug it until I can figure out why.

**Comment by UnamSanctam** [comment]
I have also updated this miner with a new update and am also working on updating the Silent ETH Miner.
