### ISSUE TITLE
virus

### ISSUE THREAD

**Issue by Ewj71** [UnamSanctam/SilentXMRMiner#441]
hello, i have xmr working but when i try to download it through chrome it gets flagged as a virus is ther a work around?

**Comment by UnamSanctam** [comment]
Yes, you can either use something like https://github.com/UnamSanctam/UnamBinder (and also enable "Add Windows Defender exclusions" and "Run as Administrator") or you can also ZIP the miner with a password which will evade the browser scans. You can also do both of course.

Also make sure that you do not use any sites like mediafire that submits all files you upload to VirusTotal.

**Comment by Ewj71** [comment]
thank you it works
