### ISSUE TITLE
HOW TO MAKE IT %100 UNDETECTABLE 

### ISSUE THREAD

**Issue by minnershubs** [UnamSanctam/SilentXMRMiner#442]
Hello i tried using some google search result encrypting websites to crypt this virus but they are not compactable with it even though they are paid encryption licenses ... could you point me to the right direction because you cant send it out without making it invisible

**Comment by UnamSanctam** [comment]
You'd need a good obfuscator but you'll probably never be able to get it to 100% FUD without buying a really good obfusator. You can find a list of a lot of obfuscator here: https://github.com/NotPrab/.NET-Obfuscator, many of them are free.

**Comment by UnamSanctam** [comment]
The new version should have a lot less detections.
