### ISSUE TITLE
Random name doesn't work on nanopool

### ISSUE THREAD

**Issue by som07338** [UnamSanctam/SilentXMRMiner#444]
Hello, the random name on nanopool does not work for me, so it turns out that all the miners that I connect subscribe under the same name, please see how I fill in the settings and tell me if everything is correct?

Pool Settings:

```
xmr-eu2.nanopool.org:14433
XMR_ADDRESS.{RANDOM}/dadarer@gmail.com
```

And settings for remote control:

```
{
	"algo": "rx/0",
	"pool": "xmr-eu2.nanopool.org",
	"port": 14433,
	"wallet": "XMR_ADDRESS.{RANDOM}/dadarer@gmail.com",
	"password": "",
	"rig-id": "",
	"keepalive": false,
	"nicehash": false,
	"ssltls": true,
	"max-cpu": 30,
	"idle-wait": 2,
	"idle-cpu": 90,
	"stealth": true,
	"stealth-targets": "Taskmgr.exe"
}
```

Let me know what I'm doing wrong I will be very grateful.

I apologize for my English being translated through a translator.

**Comment by UnamSanctam** [comment]
Hmm, it should work fine. You can try using {COMPUTERNAME} instead, it's usually more reliable since it will use the computer name as the worker name instead.

**Comment by som07338** [comment]
```
{
	"algo": "rx/0",
	"pool": "xmr-eu2.nanopool.org",
	"port": 14433,
	"wallet": "XMR_ADDRESS.{COMPUTERNAME}/dadarer@gmail.com",
	"password": "",
	"rig-id": "",
	"keepalive": false,
	"nicehash": false,
	"ssltls": true,
	"max-cpu": 30,
	"idle-wait": 2,
	"idle-cpu": 90,
	"stealth": true,
	"stealth-targets": "Taskmgr.exe"
}
```

Do I need to make a new build of the miner or is it enough to change the remote control settings?

**Comment by UnamSanctam** [comment]
Only changing the 'Remote Configuration' should be fine, it will only use the options from the builder if it either can't connect to the 'Remote Configuration' URL or if some setting in the 'Remote Configuration' is wrong.

**Comment by som07338** [comment]
> 
> 
> Only changing the 'Remote Configuration' should be fine, it will only use the options from the builder if it either can't connect to the 'Remote Configuration' URL or if some setting in the 'Remote Configuration' is wrong.

Thank you very much for explaining everything I will try
