### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by therotte795** [UnamSanctam/SilentXMRMiner#445]
It would be pretty cool if you add a feature where you connect each miner to panel which counts active miner and if a miner dies it should be removed from the total numbers. 
and making a panel work on onion site would be pretty awesome just saying

**Comment by therotte795** [comment]
and if a miner can grab settings directly from panel it would be awesome (2)

**Comment by UnamSanctam** [comment]
In the next unified miner I've been working on for a few months there will be support for a HTTP panel.

**Comment by therotte795** [comment]
it will support onion right?

**Comment by UnamSanctam** [comment]
No there aren't any easy ways to run Tor to get .onion domains in C++. You'd have to run a Tor SOCKS5 proxy or something and connect through that but I don't think there are any simple or automatic ways to do that.

**Comment by therotte795** [comment]
Well thanks for the information! will be waiting for http panel support
