### ISSUE TITLE
How to setup for Nicehash?

### ISSUE THREAD

**Issue by Baseult** [UnamSanctam/SilentXMRMiner#446]
Hey I struggle a little to create the miner for my Nicehash Wallet.
Am I doing something wrong here?
Tried it with different builds, my CPU increases but somehow my Nicehash doesn't receive any income.

Pool - tried it with:
1. randomxmonero.eu.nicehash.com:3380
2. randomxmonero.eu-west.nicehash.com:3380
3. stratum+tcp://randomxmonero.eu-west.nicehash.com:3380

Wallet Address/User: - tried it with:
1. Myminingwalletaddress/myemail@gmail.com
2. Myminingwalletaddress/RandomWorkerName
3. Myminingwalletaddress.RandomWorkerName
4. Myminingwalletaddress.RandomWorkerName/myemail@gmail.com

Password:
1. (nothing)
2. x

Algorithm:
Monero (rx/0 - RandomX)

Mining -> Nicehash Mining: (toggled on)

Would be great if you could help me out here.

----------------------------------------------------------------------------

After reading previous issues I think it should actually work with the following settings, but it does not somehow.
![image](https://user-images.githubusercontent.com/45830921/135317276-6c5661c9-0304-4084-8be3-e8c91a99380e.png)
![image](https://user-images.githubusercontent.com/45830921/135317333-7f5e47b5-8134-4772-a2ca-6388f4007615.png)

**Comment by UnamSanctam** [comment]
Is that the correct Nicehash BTC wallet address for your account? How long did you mine for? You need to mine at least one share for something to show up at any pool, the time it takes to mine a share depends on the hashrate, pool share difficulty and luck. Also wouldn't recommend "GPU Mining" with Monero since it's a CPU coin.

**Comment by Baseult** [comment]
I had it running for an hour now, neither an active rig, nor any income was shown on nicehash. 
If i use the nicehash quick miner as an example, it is shown as a "quickminer - UNMANAGED" on the nicehash monitoring page after 30 seconds so that shouldn't be an issue ig?

I have checked the wallet ID several times and it should be the right one if thats the one I have to use:
![image](https://user-images.githubusercontent.com/45830921/135328805-06024a20-ad19-4c62-bfff-7c926f16ae90.png)

I will try it without GPU Mining now. Do I have to use "x" as password too?
Also would it be possible to mine anything else using this Builder together with the GPU Mining for Nicehash purposes?

**Comment by UnamSanctam** [comment]
That is the correct wallet address but the one in your screenshot is wrong. And yes you should probably use "x" as the password.

For GPU mining the most profitable would be Ethereum https://github.com/UnamSanctam/SilentETHMiner but you can mine any algorithm that the miner supports. You could also use KawPow algorithm in the Silent XMR Miner for GPU mining though the ETH Miner is better at managing the GPU.

**Comment by Baseult** [comment]
Jeez your right, thats strange, everytime I press the "copy" button it gives me a different address than the one which is shown in the mining address field. I couldn't even manually copy paste that one so I had to type it char by char. It actually works now. Idk whats wrong with the copy feature lol.

Thanks for your help, will try the Eth Miner then :)

**Comment by Baseult** [comment]
One short follow up question for the ETHMiner.
Which prefered pool do I have to use for this one If I want to use it with Nicehash?

Also instead of WalletAddress.Workername I just do WalletAddress and WorkerName Separate from each other?
Anything else I have to note for working with nicehash?

**Comment by UnamSanctam** [comment]
Use the Nicehash URL for Ethash (DaggerHashimoto) `daggerhashimoto.eu.nicehash.com:3353`

For the worker name you can do either, both should work I believe but using the "Worker Name" is the "official" way. It should work fine with those settings.
