### ISSUE TITLE
nanopool

### ISSUE THREAD

**Issue by bashicq** [UnamSanctam/SilentXMRMiner#448]
Please tell me how to configure the remote configuration file for nanopool?
Just now I noticed that it requires some mail. Should it be valid or just random?
The configuration file with your instructions for the nanopool is working, but after a while I began to notice strange things.
- I have the password/name of the worker specified, and it works. although you said (only recently noticed it) that a password is not needed for a nanopool
- I don't have a worker displayed, at all 0. But at the same time, the mining process is underway.

**Comment by UnamSanctam** [comment]
The "password" in the "wallet" field is the "email", so use the "password" you entered in the "wallet" as the password/email on nanopool, it can be anything like password123.

Can you post the "wallet" string here (but censor your wallet address)?

**Comment by UnamSanctam** [comment]
To change the minimum payout you need to add a worker name and password/email into the "wallet" field like so:
```
{
"algo": "rx/0",
"pool": "xmr-eu1.nanopool.org",
"port": 14444,
"wallet": "jfkasdjkfsdkfjaidjf8ur9uur94eut0u438tjdfkajdkfjoweir843t8py348yteyufudoijsdf.Worker/Password",
"password": "",
"rig-id": "",
"keepalive": false,
"nicehash": false,
"ssltls": false
}
```
And leave the "password" field empty since nanopool doesn't use it.

**Comment by bashicq** [comment]
Oh, thank you :)
