### ISSUE TITLE
[COMMENT NOT ISSUE] wow bro

### ISSUE THREAD

**Issue by shainodev** [UnamSanctam/SilentXMRMiner#45]
I've left miner stuff like 2 months ago, and I was curious that have u updated it and wow damn, these updates. continue your work your insane

**Comment by shainodev** [comment]
also the stealth seems not to be working

**Comment by UnamSanctam** [comment]
In what way?

**Comment by shainodev** [comment]
i opened the app and it just stays on 20% cpu with task manager open

**Comment by shainodev** [comment]
i have idle mining on

**Comment by UnamSanctam** [comment]
Windows 10? Using the normal Task Manager?

**Comment by shainodev** [comment]
yes, on my main pc

**Comment by shainodev** [comment]
im not wanting to make another thread so ima say it here, feature request: fake error, site blocker, (maybe) disable task manager

**Comment by shainodev** [comment]
site blocker info: glasswire website, wireshark website, virustotal, anyrun.

**Comment by UnamSanctam** [comment]
Fake Error should be added with a file binder, site blocker and disabling task manager would require admin permissions for the program which of course it doesn't have in most cases.

**Comment by shainodev** [comment]
what file binder? i think it makes it more detected if u use binder or im not sure, if u directly just do (idk in VB but in c#) MessageBox.Show(error, title), its tbh easy to do

**Comment by shainodev** [comment]
disabling task manager i think is not requiring admin if u use registry

**Comment by UnamSanctam** [comment]
Adding a fake error would bloat the builder too much at the moment, you could add the message box directly into the code yourself and compile it if you really need it. It might possible to block the Task Manager from the current user (not all users) so I might add that.

I haven't been able to get the stealth to not work, no matter what I try it works. Do you have some kind of custom Task Manager or something that uses another window class?

**Comment by shainodev** [comment]
na, idk why it does that i have 60 seconds sleep on and idle mining try with those settings

**Comment by UnamSanctam** [comment]
Yeah I've tried with all settings, it wouldn't matter anyways since it checks for the Task Manager every mining tick.

**Comment by shainodev** [comment]
ok then its just something bout my computer, doesnt really matter either

**Comment by shainodev** [comment]
userinit startup would be dope

**Comment by shainodev** [comment]
but i think it detects it, idk try u know more than i do

**Comment by shainodev** [comment]
ight, thanks for the help bro! ur a legend
