### ISSUE TITLE
compilers directory

### ISSUE THREAD

**Issue by bashicq** [UnamSanctam/SilentXMRMiner#450]
In the new version of the builder, after the creation of the miner, the "compilers" directory is created, so is its presence mandatory for the miner to work? Or I can use myminer.exe without him?

**Comment by UnamSanctam** [comment]
No the compilers directory just contains the programs necessary to compile the native code and everything so you could even delete it if you want to.

**Comment by bashicq** [comment]
Understood thanks for the answer.
