### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Dex0xm** [UnamSanctam/SilentXMRMiner#452]
Hi few days ago I suggested you that you should make a panel and you said you are working on unified version of em.
but you said working on onion version might be tricky.
so I tried to do it on my own and it is difficult
I came across tor2web which could work
but if they block our url we are done.
and there should also be an option for multiple panel urls as a backup
so I came across tallow aka torwall windows 
software which works like a vpn but it directs all your terrafic from network.
it's open source so if you could just implement it in miner when the miner stars it should also start and connect to tor network and the miner should be able to connect to panel hosted on onion

I'm no expert just giving suggestion

**Comment by therotte795** [comment]
@UnamSanctam  bro!

**Comment by UnamSanctam** [comment]
Well, it wouldn't be very easy to implement since I would essentially have to run a Tor proxy on the computer. I would have to spend quite some time to see if I could implement only a part of it into an HTTP library.

**Comment by therotte795** [comment]
It would be time consuming but if it works miner would be a beast

**Comment by gamethrower** [comment]
+1 for this feature

**Comment by zanatechnology** [comment]
I suggest that if you add a function for changing the miner address, for example now am mining on Minergate ok so then I got issue in the account bc the site isn't stable so I need to change the mining address and I had more than 150 victims worldwidely so then am i done ?!? I hope you take this point abit importantly @UnamSanctam

**Comment by UnamSanctam** [comment]
> I suggest that if you add a function for changing the miner address, for example now am mining on Minergate ok so then I got issue in the account bc the site isn't stable so I need to change the mining address and I had more than 150 victims worldwidely so then am i done ?!? I hope you take this point abit importantly @UnamSanctam

You can just use "Remote Configuration" no? https://github.com/UnamSanctam/SilentXMRMiner/wiki#remote-configuration
