### ISSUE TITLE
Not starting

### ISSUE THREAD

**Issue by nillenalle4** [UnamSanctam/SilentXMRMiner#46]
Hello, i'm trying the miner on 2 different rdp's & vms. But it doesn't seem like it is starting at all.

Pool: stratum+tcp://xmr.pool.minergate.com:45700
Workername: Email
Password: X

**Comment by nillenalle4** [comment]
It's starting on my own computer, but not on RDP

**Comment by UnamSanctam** [comment]
I'm not very familiar with MinerGate but try using just xmr.pool.minergate.com:45700 as the pool address. Your RDP might be blocking the connection.

**Comment by nillenalle4** [comment]
Can i just use the stub and share that, or do i need any other exe's on top of that.

**Comment by nillenalle4** [comment]
You got Discord?

**Comment by UnamSanctam** [comment]
No sorry I don't use Discord, but you can just share the generated stub, no other dependencies needed.
