### ISSUE TITLE
monero ocean

### ISSUE THREAD

**Issue by parabola19** [UnamSanctam/SilentXMRMiner#460]
sorry if i'm writing in the wrong place, does this mean that my address has been blocked? there is no information about crashes in the discord

![164362](https://user-images.githubusercontent.com/87057617/136157108-8156110e-b1fb-4165-a43c-eee830230f2f.png)

**Comment by parabola19** [comment]
> It's possible, do you use "Remote Configuration"? Then you can try changing the pool to see if it shows any hashrate.

yes i am using. will it take a long time to transfer all users to a new address? and what pool do you recommend not to be blocked?

**Comment by UnamSanctam** [comment]
The miner checks the "Remote Configuration" every 100 minutes. Only pool I know that doesn't ban is nanopool.

**Comment by parabola19** [comment]
> The miner checks the "Remote Configuration" every 100 minutes. Only pool I know that doesn't ban is nanopool.

hm, thanks. should i use ssl/tls for nanopool?

**Comment by UnamSanctam** [comment]
Yes it's best to do that. Nanopool has quite a high share difficulty (always 400 000) but is the only (big or well known) pool I know that hasn't banned yet.

**Comment by parabola19** [comment]
![uZDI2LH](https://user-images.githubusercontent.com/87057617/136198045-e093b2fd-0937-4ae7-95ec-ed809046d5fe.png)

that's the name of the worker, right?

**Comment by UnamSanctam** [comment]
Either that or enter it in the "wallet" field in the format `Wallet.Workerr`
