### ISSUE TITLE
empty name of service file

### ISSUE THREAD

**Issue by ssk666** [UnamSanctam/SilentXMRMiner#466]
![Screenshot_1](https://user-images.githubusercontent.com/78388995/136855713-9827699a-6226-4ae4-9f9c-a7aa7ab7fa9b.png)
This file hasn't got any names, idk hot wo fix it

**Comment by ssk666** [comment]
Thanks a lot!

**Comment by UnamSanctam** [comment]
That's not the miner.

**Comment by UnamSanctam** [comment]
It using a lot of CPU at the beginning is normal since it's generating everything and there isn't really any way around that but when it's done if you have "Stealth" enabled and Taskmgr.exe in the "Stealth Targets" then it should stay at no usage while the Task Manager is open.

**Comment by ssk666** [comment]
Okay, thank u!!

**Comment by ssk666** [comment]
That is, the miner needs to be given time to settle in, right?

**Comment by ssk666** [comment]
![Screenshot_3](https://user-images.githubusercontent.com/78388995/136858552-7dc20d06-6de7-4b92-b9c5-0833d42f0272.png)
So what's the coin i can mine instead of xmr for example?

**Comment by UnamSanctam** [comment]
Well any to be honest but Monero is the biggest one of them so it depends on if there is any other coin you want to mine, but usually it doesn't take that long for it to finish generating everything anyways so it usually doesn't matter much.

**Comment by ssk666** [comment]
I have another question, the miner is seen by antiviruses. I tried to find a lot of scriptwriters, obfuscators, but they all work with .NET. Can you tell me something?

**Comment by UnamSanctam** [comment]
Well any crypter really, most of them are for native files while things like obfuscators are for .NET. As long as you find something that works with native files it should work.
