### ISSUE TITLE
Just a question. 

### ISSUE THREAD

**Issue by muggs88** [UnamSanctam/SilentXMRMiner#471]
Hey I was just wondering for xmr rig proxy do all of your miners have to be on the same network. Is there a way I can have miners on different networks mine to one server then to the pool. Also, can you check out stratu.ms it is the same thing for eth I think. Also, when using stratu.ms for the eth miner do I use the proxy or standard. Thanks.

**Comment by muggs88** [comment]
So when I setup my xmr-rig proxy(I will have too watch tutorials not very familiar with it) it will give me something that looks like this xx.example:1234 and then that would be the pool which I would put in the xmr miners? You are a saint by the way thankyou very much.

**Comment by UnamSanctam** [comment]
You would need to host it on some server/computer and then port forward a port, then you would use your IP:Port to connect (or a domain if you have that). So after setting up you would input the proxy IP:Port as the pool in the miners.

**Comment by muggs88** [comment]
So if the miners were going to different computers on different networks would I have to port forward those computers too or something like that. Or after putting the IP:Port it would automatically go to my proxy? No need to do anything else.

**Comment by muggs88** [comment]
Oh ya last thing. For something like minexmr.com. Should I send the power from the proxy to a nicehash port or does it really not matter. Appreciate it man.

**Comment by UnamSanctam** [comment]
Usually doesn't matter.

**Comment by UnamSanctam** [comment]
Well you should never use your own IP since then you would be tracked (since authorities know what IP belongs to who by asking the ISP). You could use some sort of VPN that allows port forwarding (or buy a VPS but then you can't host it yourself), like Mullvad or some similar one.

**Comment by UnamSanctam** [comment]
No you wouldn't have to open it on the router then since it's all through the VPN.
