### ISSUE TITLE
32bit not working?!

### ISSUE THREAD

**Issue by zanatechnology** [UnamSanctam/SilentXMRMiner#477]
Hello bro , first before anything thank you soo much for this awesome project, but i do had a problem which the excutable file not run on 32bit !!, what is the solution?

**Comment by zanatechnology** [comment]
Did you added the features of the newest version or it's just simple as it is? And does it work on 32bit?!

**Comment by zanatechnology** [comment]
> > Yes, it won't have all the features of course since it's a really old version, and there is no prebuilt 32-bit xmrig there from what I can see so you'd probably have to compile one yourself.
> 
> 
> 
> I'm recompilled latest beta version (6.15.3), please, accept friend request in Discord (marat2509)

Did you added the features of the newest version or it's just simple as it is? And does it work on 32bit?!

**Comment by marat-2509** [comment]
> > > Yes, it won't have all the features of course since it's a really old version, and there is no prebuilt 32-bit xmrig there from what I can see so you'd probably have to compile one yourself.
> > 
> > 
> > I'm recompilled latest beta version (6.15.3), please, accept friend request in Discord (marat2509)
> 
> Did you added the features of the newest version or it's just simple as it is? And does it work on 32bit?!

If we are very willing, maybe developer @UnamSanctam will add this feature. Like this post and the developer will notice us
