### ISSUE TITLE
Builder gives error

### ISSUE THREAD

**Issue by Zreaoz** [UnamSanctam/SilentXMRMiner#489]
Hi when I try building the exe It gives me an error saying the system cant find the file specified

here is the screenshot
https://paste.pics/ba8a9206a6f69430357e9b717b8cde1d

**Comment by UnamSanctam** [comment]
Are you trying to add an icon or something? If you are then make sure that the location is correct.

**Comment by ghost** [comment]
even thought I am not even adding a logo it is giving me a error I tried this on the Monero miner and The Etherium miner I get the same errors I am not adding a logo
For building it says.
Starting...
Replacing strings...
Creating resources...
Embedding resources...
Compiled Miner payload!
Creating Uninstaller...
Error compiling Uninstaller loader!
Error compiling Miner loader!

**Comment by UnamSanctam** [comment]
There is probably something wrong with the folder you are building it in, I would build it in another folder. I would also use my new miner instead: https://github.com/UnamSanctam/SilentCryptoMiner.

**Comment by ghost** [comment]
yep! your new miner works very well! Thank you for your help!

**Comment by UnamSanctam** [comment]
Great to hear.
