### ISSUE TITLE
Detection

### ISSUE THREAD

**Issue by barracudakrakatoa** [UnamSanctam/SilentXMRMiner#491]
Hi I was using your miner a while ago with success and no detection. Then I stopped and now I wanted to try it again and after a couple of builds I am getting frustrated because something keeps getting detected by the Windows Defender. Everything obfuscated with ConfuserEx the same way I did a while ago.

![Zrzut ekranu 2021-11-03 225955](https://user-images.githubusercontent.com/84273281/140199110-339c4a0a-5331-403f-8dc5-e08fb76b7aef.png)

**Comment by UnamSanctam** [comment]
Yes it's a new detection that Windows Defender added 2 or 3 days ago.

**Comment by barracudakrakatoa** [comment]
Oh that sucks, is there anything that can be done in the settings of the miner? Or maybe do you have any ideas to implement to get around this? Thanks for response.

**Comment by UnamSanctam** [comment]
You can most likely use powershell obfuscations to get around it, currently I'm working on the unified miner (an improved miner that is my XMR and ETH miners combined) so that won't get added into this miner, though it's not much left on the unified miner now.

**Comment by GoldenSkyRunner** [comment]
Any idea as to what the timeframe will be until this comes out?

**Comment by UnamSanctam** [comment]
Already out, check my GitHub.

**Comment by GoldenSkyRunner** [comment]
thank you i just found it!
