### ISSUE TITLE
Changing the mining address remotely!!!

### ISSUE THREAD

**Issue by zanatechnology** [UnamSanctam/SilentXMRMiner#492]
I suggest that if you add a function for changing the miner address, for example now am mining on Minergate ok so then I got issue in the account bc the site isn't stable so I need to change the mining address and I had more than 150 victims worldwidely so then am i done ?!? I hope you take this point abit importantly @**UnamSanctam **

**Comment by UnamSanctam** [comment]
Reposting from other thread.

You can just use "Remote Configuration" no? https://github.com/UnamSanctam/SilentXMRMiner/wiki#remote-configuration
