### ISSUE TITLE
Help me!

### ISSUE THREAD

**Issue by SamYPay** [UnamSanctam/SilentXMRMiner#494]
What is better to enter in "Kill Targets" ?

**Comment by UnamSanctam** [comment]
Any program that you want the miner to kill, someone has sent `mbam.exe,mbamtray.exe,avp.exe,avpui.exe,AVGSvc.exe,afwServ.exe,avgnt.exe,ProductAgentUI.exe,MMSSHOST.exe,McShield.exe,mcafee.exe` (kills some antivirus parts) before but I have not test it all.
