### ISSUE TITLE
i need a advice

### ISSUE THREAD

**Issue by sadandnab** [UnamSanctam/SilentXMRMiner#497]
First thanks for your hard work

i am getting around (2,304,280.0 H/s) on cpu right now. mining XMR 
which coin should i mine or stay on XMR please advice me Thanks !

i will close this issues immediately once you reply.

**Comment by UnamSanctam** [comment]
I would try different coins (algorithms) and see what hashrate I get, then I would enter that hashrate in a mining calculator for that coin and see what is more profitable for you. The most profitable is always to mine small coins that you believe will go up in price and then hold those coins for as long as you want or need to.

I will repost a post about a few coins that I like:
>Depends on how long you want to hold the coins, ArQmA will soon release staking nodes I think (so they will become both a PoW (mining) and PoS (staking) coin). Kevacoin is a really small cryptocurrency and their marketing is kind of bad but it does have a lot of potential. Kryptokrona is also a kind of small cryptocurrency but it already has a working "product" (privacy messenger) that works and the coin is promising, I haven't mined any myself but I have heard good things about it from others. Haven is also a good alternative which crashed before (think there was some hack?) but has recovered. So choosing any of those for mining is probably what I would do.
