### ISSUE TITLE
Miner not showing up on Minergate when opened

### ISSUE THREAD

**Issue by ilgabbibo** [UnamSanctam/SilentXMRMiner#5]
Hey, I tried to build a miner with your builder, though it's not showing up on minergate.
More info:

![image](https://user-images.githubusercontent.com/61429285/80962126-b4113600-8e0c-11ea-83fb-e0a30a9ceaed.png)
![image](https://user-images.githubusercontent.com/61429285/80962134-ba9fad80-8e0c-11ea-8b6b-5ded19c6b85c.png)
![image](https://user-images.githubusercontent.com/61429285/80962192-d86d1280-8e0c-11ea-8f45-1714b4fc99cc.png)

Thanks for the eventual help!!

**Comment by UnamSanctam** [comment]
Try turning off Idle Mining for testing. When you have Idle Mining on it will only mine when you haven't touched the mouse or keyboard for 15 minutes.

**Comment by ilgabbibo** [comment]
@UnamSanctam I turned it off and still nothing happens on minergate, although i got this error after a while:
![image](https://user-images.githubusercontent.com/61429285/81046684-36573400-8eb9-11ea-8d42-29b41f837ebe.png)

**Comment by UnamSanctam** [comment]
Hmm, I've been looking around and trying things and everything seems to work for me. Can you try mining to a different pool than minergate and see if it works? Also a thought, I am pretty sure minergate was/is a scam and it's the only thing I get when I search about it, it is even listed on lists like this: [https://www.reddit.com/r/monero/wiki/avoid/](url)

**Comment by ilgabbibo** [comment]
> Hmm, I've been looking around and trying things and everything seems to work for me. Can you try mining to a different pool than minergate and see if it works? Also a thought, I am pretty sure minergate was/is a scam and it's the only thing I get when I search about it, it is even listed on lists like this: https://www.reddit.com/r/monero/wiki/avoid/

All right, I'll try a different one.
Also yes I am aware that Minergate is notorious for being shady, but it is the only low-difficulty pool that allows sharing so that I can mine with my low-performance PCs.

**Comment by ilgabbibo** [comment]
@UnamSanctam Tried again with a different pool, xmr-eu.luxor.tech:8888, same result, miner is not showing up on the website. Idle mining is off.

**Comment by UnamSanctam** [comment]
@ilgabbibo 

Hmm, just tried and it works for me using these settings.
`Pool: xmr-eu.luxor.tech:8888
Wallet/User: MoneroAddress/Username
Password: x`
Are you using the same? Especially the password (x).
If it still doesn't work it might be something with your computer and we can work from there.

**Comment by ilgabbibo** [comment]
> @ilgabbibo
> 
> Hmm, just tried and it works for me using these settings.
> 
> Pool: xmr-eu.luxor.tech:8888
> Wallet/User: MoneroAddress/Username
> Password: x
> 
> Are you using the same? Especially the password (x).
> If it still doesn't work it might be something with your computer and we can work from there.

huh will try with "x" as password. otherwise if you want you can contact me on telegram @rab00t so we can try and fix this 1 on 1.
will try with the password and I'll let you know :)

**Comment by ilgabbibo** [comment]
@UnamSanctam 
![image](https://user-images.githubusercontent.com/61429285/81219275-dc9d5980-8fdf-11ea-9f84-25ad45f8ba09.png)

It works!! Many thanks :)
Will consider donating when I'll have something :D
