### ISSUE TITLE
Issues connecting to pool

### ISSUE THREAD

**Issue by RealKolasi** [UnamSanctam/SilentXMRMiner#50]
So i open the latest exe,

pool: pool.supportxmr.com:443
W.A/User: xxxxxx
Password: xxxxx

SSL/TLS = True 
CPU Mining = True
GPU Mining = True 
Idle Mining = False
Max CPU = 50%
Stealth = True

The exe builds, when run it opens and uses cpu/gpu but runs 80% ish for about 30 seconds and then goes down to 1% and never mined anything on the pool.

**Comment by UnamSanctam** [comment]
What are you using to check the CPU amount? If you have Stealth on it will pause the miner when you have Task Manager open.

**Comment by RealKolasi** [comment]
> What are you using to check the CPU amount? If you have Stealth on it will pause the miner when you have Task Manager open.

just made a new exe with stealth disabled, it keeps using 40% ish cpu constantly but isn’t showing workers or hashes on supportxmr

**Comment by UnamSanctam** [comment]
If it's using any CPU it means that it has connected to the pool and has received a job to work on. Either the Wallet address is wrong or maybe the password. If both are right you might have to wait for either the miner to mine a valid share or for the pool to report the valid shares.

**Comment by RealKolasi** [comment]
> If it's using any CPU it means that it has connected to the pool and has received a job to work on. Either the Wallet address is wrong or maybe the password. If both are right you might have to wait for either the miner to mine a valid share or for the pool to report the valid shares.

ok so it took about 6 minutes for the miner to show on the site. thanks for the help and fast responses. take care
