### ISSUE TITLE
Miner not Showing in Pool

### ISSUE THREAD

**Issue by WaveyyBeFresh** [UnamSanctam/SilentXMRMiner#500]
When I run the payload, it executes and starts mining (cpu usage 100%). But when I check my pool it shows no active workers, or any hashrate. Yes I did give it some time and still nothing. How can I fix this?

**Comment by UnamSanctam** [comment]
[Wait longer](https://github.com/UnamSanctam/SilentCryptoMiner/wiki#why-is-my-miner-not-showing-up-on-the-pool-even-though-its-mining), but you should probably use my new miner as well https://github.com/UnamSanctam/SilentCryptoMiner.
