### ISSUE TITLE
64 bit or 32 bit?

### ISSUE THREAD

**Issue by wanz3ru** [UnamSanctam/SilentXMRMiner#502]
Is it a 64 bit program or 32 bit? If 64, then is it possible to somehow make it so that it was 32 bits, maybe there are any versions, or suggestions how this could be done?

**Comment by UnamSanctam** [comment]
It is 64-bit, and to make it 32-bit you would have to change a lot in XMRig and change the RunPE functions to be able to inject 32-bit into 64-bit or 32-bit programs.
