### ISSUE TITLE
raptoreum

### ISSUE THREAD

**Issue by MR81726** [UnamSanctam/SilentXMRMiner#503]
could you add it to the miner as a algo to mine to

**Comment by UnamSanctam** [comment]
No not at this moment, this miner isn't in development either, it's https://github.com/UnamSanctam/SilentCryptoMiner

**Comment by begirenkcah** [comment]
When?Raptoreum is open sourced(https://github.com/Raptor3um/raptoreum/releases/tag/1.2.15.2).It would be nice if mining Raptorium was added this week

**Comment by UnamSanctam** [comment]
Adding an algorithm and everything associated takes a ton of work, at least a few hundred hours with development and asking others to test it and then benchmark it with other miners to find improvements.

**Comment by UnamSanctam** [comment]
Raptoreum is supported in the latest version of https://github.com/UnamSanctam/SilentCryptoMiner.
