### ISSUE TITLE
I Cant open program.

### ISSUE THREAD

**Issue by Lubuluk** [UnamSanctam/SilentXMRMiner#505]
Hello. I Have just one question. How do ı open this thing ? İt is on the visual studio. What should ı download to open it ?
![Screenshot_24](https://user-images.githubusercontent.com/95049683/143690920-a99cf398-3807-4808-804d-2d13859fd848.png)

**Comment by UnamSanctam** [comment]
You can just download the pre-compiled version, though I would use my new unified miner instead: https://github.com/UnamSanctam/SilentCryptoMiner/releases.

**Comment by Lubuluk** [comment]
İt is the same thing. How am ı going to open this ? Can you pls guide me.
![Screenshot_25](https://user-images.githubusercontent.com/95049683/143691486-ab1b139f-27a4-4679-93ff-12c659523ec0.png)
.

**Comment by UnamSanctam** [comment]
Stop downloading the source, download the pre-compiled version on the page I linked.

**Comment by Lubuluk** [comment]
Okey ı got it. I Have just one more question. No one do such thing without taking a payment. Are you taking fee from the machines that we infected ?

**Comment by UnamSanctam** [comment]
There's a 0.1%-1% fee in the XMR miner and none in the ETH miner. This project is just a hobby project, just like the binder and downloader as well.
