### ISSUE TITLE
methods?

### ISSUE THREAD

**Issue by MR81726** [UnamSanctam/SilentXMRMiner#508]
any good methods on getting more bots ive done the whole FREE MODMENU DOWNLOAD yt video thing but isnt as effective is there a way i can get like a hashrate higher then 50kh/s ? efficently

**Comment by ducksucker** [comment]
i just do vids I got 30kh/s after 2 days (161 miners) also if u wanna get higher hashrate just change their CPU usage to like 10% higher through panel and it'll be higher
