### ISSUE TITLE
Just a Question (Not a issue)

### ISSUE THREAD

**Issue by Tirkovic22** [UnamSanctam/SilentXMRMiner#509]
I wanna ask about chrome detecting it as virus and also the Windows Defender Bypass is  not working when i ticked it to bypass if u can reach out to me fast i would consider donating to you ;)

**Comment by UnamSanctam** [comment]
Well this is the old (and deprecated miner), the new unified miner is here: https://github.com/UnamSanctam/SilentCryptoMiner though I haven't had time to update it lately due to a lot of real life work. A program (especially when public and open source) usually gets detected within a week (if no crypting is done).

**Comment by Tirkovic22** [comment]
hmm thanks for help tho so if i still run it on the unified version its still going to show as virus ?

**Comment by UnamSanctam** [comment]
Probably at this time before a new update yes, though you usually circumvent it (Chrome detection) by zipping the file with a password.

**Comment by Tirkovic22** [comment]
oh so i should just zip it with the password on ?

**Comment by UnamSanctam** [comment]
Yes that usually bypasses Chrome antivirus detection.

**Comment by Tirkovic22** [comment]
ahh thank you

**Comment by Tirkovic22** [comment]
yep it bypassed it but im kinda sad about the Windows Defender thing now

**Comment by Tirkovic22** [comment]
@UnamSanctam  btw how does GPU Mining works i seem to get less kH/s with gpu enabled and i get a increase when the option is disabled

**Comment by UnamSanctam** [comment]
Don't mine Monero with the GPU, it's a CPU coin.

**Comment by Tirkovic22** [comment]
do you have discord and if u do can you drop it i wanna ask you some more stuff and i have ideas too
