### ISSUE TITLE
Question about the executable

### ISSUE THREAD

**Issue by RealKolasi** [UnamSanctam/SilentXMRMiner#51]
If im using supportxmr. And lets say someone opens the executable and their user name is set to something like "Miner1" if multiple people open the same exe designated to "Miner1" will it combine power or not work. Would i need to change the pass for every different desktop.

**Comment by UnamSanctam** [comment]
They will just all mine under the same worker name, you don't need to change the worker name for each one.

**Comment by RealKolasi** [comment]
> They will just all mine under the same worker name, you don't need to change the worker name for each one.

so i could technically have one worker running 1MH/s combining a ton of different desktops?
would supportxmr suspect that as botnetting???

**Comment by UnamSanctam** [comment]
Yes and the supportxmr admin bans everyone he thinks is mining with a botnet which is usually everyone that has over 100 miners/connections to the pool. The only real way to get around it is to set up a xmrig-proxy server but then you would need to host it somewhere. Most pools ban accounts they think have any malicious miners, only one I'm pretty sure don't is nanopool, some say that MinerGate also don't but I've had reports of people getting banned.

**Comment by RealKolasi** [comment]
> Yes and the supportxmr admin bans everyone he thinks is mining with a botnet which is usually everyone that has over 100 miners/connections to the pool. The only real way to get around it is to set up a xmrig-proxy server but then you would need to host it somewhere. Most pools ban accounts they think have any malicious miners, only one I'm pretty sure don't is nanopool, some say that MinerGate also don't but I've had reports of people getting banned.

so if i ran an xmrig-proxy server on an offshore vps for a "botnet" i have much lower chance of getting banned?
