### ISSUE TITLE
Wallet issue

### ISSUE THREAD

**Issue by Programmer1603** [UnamSanctam/SilentXMRMiner#512]
If i run it, it does use computing resources, but there is no monero in my wallet.

**Comment by UnamSanctam** [comment]
Yeah of course, check your pool instead, you have to reach a minimum threshold (depends on the pool) for them to pay it out so that you won't lose everything in transfer fees.

**Comment by Programmer1603** [comment]
Oh ok ty 
How can i check my pool balance?

**Comment by UnamSanctam** [comment]
Depends on the pool, go to the pool you use and usually you enter your wallet address somewhere.

**Comment by Programmer1603** [comment]
Ok i will try that asap ty for ur fast responses and have a nice day!

Holen Sie sich Outlook für iOS<https://aka.ms/o0ukef>
________________________________
Von: UnamSanctam ***@***.***>
Gesendet: Thursday, January 6, 2022 10:20:45 PM
An: UnamSanctam/SilentXMRMiner ***@***.***>
Cc: Programmer1603 ***@***.***>; Author ***@***.***>
Betreff: Re: [UnamSanctam/SilentXMRMiner] Wallet issue (Issue #512)


Depends on the pool, go to the pool you use and usually you enter your wallet address somewhere.

**Comment by Programmer1603** [comment]
How much am i gonna make if i run it on 10 computers on 25%?

**Comment by UnamSanctam** [comment]
Depends on the hashrate of the CPUs, but since Monero is a CPU coin meaning barely any requirements to run it and nearly undetectable at 25% it earns a lot less compared to GPU coins like ETH/ETC.

**Comment by Programmer1603** [comment]
Would it be possible to mine ETH silent and put it in an exchange service to transfer it to a monero wallet? So it would be anonym and more profitable.

**Comment by UnamSanctam** [comment]
Yes either mine ETH and then just exchange it to XMR manually or you can mine ETH to something like MoneroOcean where they automatically pay it out in XMR.

**Comment by Programmer1603** [comment]
Ok ty

**Comment by Programmer1603** [comment]
> Yes either mine ETH and then just exchange it to XMR manually or you can mine ETH to something like MoneroOcean where they automatically pay it out in XMR.

Can i mine on moneroocean if i use ur software? Like change the pool and stuff or isnt this possible?

**Comment by UnamSanctam** [comment]
Yes you can you any pool, if you have a "Remote Configuration" or web panel you can change the pool after you've built it if that's what you mean.

**Comment by Programmer1603** [comment]
No em its kinda hard to explain i meant if i put in a eth pool from moneroocean will it still work?

**Comment by UnamSanctam** [comment]
You still use the same pool in MoneroOcean for any of the cryptocurrencies they support, what you do to mine another cryptocurrency is to add `~algorithm` at the end of the "Password" field (worker name on MoneroOcean) so for ETH it would be `workername~ethash` in the "Password" field.

**Comment by Programmer1603** [comment]
No i knew that before
Ehat i meant is to mine Eth on moneroocean with ur silent miner

**Comment by UnamSanctam** [comment]
Yes MoneroOceans ETH pool is just like any other ETH pool so you can mine that just fine, but use my new unified miner instead https://github.com/UnamSanctam/SilentCryptoMiner to mine both.

**Comment by Programmer1603** [comment]
Ok tysm

**Comment by Programmer1603** [comment]
How much am i gonna make if i run it on 10 computers on 25%?

**Comment by UnamSanctam** [comment]
Depends fully on the CPU/GPU of the computer, for GPU profitability you can find that here: https://whattomine.com/coins while for Monero (or Raptoreum) profitability you would have to test it and see.
