### ISSUE TITLE
sometimes it doesen't start

### ISSUE THREAD

**Issue by valekatoz** [UnamSanctam/SilentXMRMiner#514]
hello, i noticed sometimes it doesen't start on few devices with pretty good cpu and gpu, on my tests works clean perfect but on my friend pc (he knows that it is a miner) it dosen't connect to the pool or the panel, nothing... could you please help me?

**Comment by UnamSanctam** [comment]
Try changing the "Startup" tabs "Filename" to something else, like `Chrome\updater.exe` some anti-cheats blocks access to certain folders.

**Comment by valekatoz** [comment]
okay i will! thank you for your quick answer!
