### ISSUE TITLE
XRM Miner does not work on 32 bit Windows 7...

### ISSUE THREAD

**Issue by domik2008** [UnamSanctam/SilentXMRMiner#53]
Hello everyone!

I just used the builder on a Windows 7 32 bit, and I managed to generate an exe file. However when I try to run it an error shows up... is this normal? is this miner only compatible with 64 bit systems?
Im looking forward to hear your expertise fellow users! Thanks in advance!

Also... Will this work on MAC OS or is it Windows only?

![error text](https://user-images.githubusercontent.com/79109497/107983616-0e573e00-6fbe-11eb-9af3-ac67093f9134.jpg)

**Comment by UnamSanctam** [comment]
Yes XMRig is only supported on 64-bit systems. My builder and injector is only for Windows since it uses a lot of Windows APIs.
