### ISSUE TITLE
The generated. exe file cannot work on other computers

### ISSUE THREAD

**Issue by kenneth1225** [UnamSanctam/SilentXMRMiner#530]
Hello, sir! I used the latest version of the builder to generate three files, and transferred the first exe program to other computers, but it did not run and did not occupy the CPU. Do I need to transfer all three files, or do I need to manually click the first exe file that has been transferred before other computers can mine for me? Look forward to your reply!
<img width="410" alt="截屏2022-10-10 18 46 31" src="https://user-images.githubusercontent.com/114070951/194850605-ba736e3c-1303-4453-81f3-33fd383f53d2.png">

**Comment by UnamSanctam** [comment]
No you only have to send the first .exe and run it for it to work, make sure that your settings are correct. You can find some example settings https://github.com/UnamSanctam/SilentCryptoMiner/wiki#lite.

**Comment by kenneth1225** [comment]
Thanks for your reply, that is, you must click it on other computers, right? What i dig is xmr. I can run normally on the computer where I created it, but I set the CPU to account for 70% when I built it. It accounts for 20% - 30% most of the time when I work, even if I don't use the computer for other work?

**Comment by UnamSanctam** [comment]
Most likely only 20-30% of the CPU cores are available for mining then, could be that the other cores aren't idle (just because you aren't directly using the computer for anything else doesn't mean that the CPU isn't being used). Also, do you have "Stealth" enabled? Since then it will pause while you have the Task Manager open so it won't use any CPU then.

**Comment by kenneth1225** [comment]
我大概明白了，十分感谢👍！最后一个问题是，我是用爆破抓取的方法获得了其他计算机，如果开启了管理员权限，我不主动点击它，对方重启了他的计算机，矿工会自动开始工作吗？还是每次都需要我来手动运行它呢？

**Comment by UnamSanctam** [comment]
You need to run it at least once on the other computer and then if you have "Startup" enabled in the miner then the miner will automatically start every time they start the computer.

**Comment by kenneth1225** [comment]
OK, thank you for your patient reply, and thank you for creating this generator. I wish you happy every day, and I will donate to you in the future when there is profit!🤘
