### ISSUE TITLE
nano pool.

### ISSUE THREAD

**Issue by RealKolasi** [UnamSanctam/SilentXMRMiner#54]
nano pool doesnt show hash rate or worker. it is using my cpu. any ideas?

Pool: xmr-eu1.nanopool.org:14433

Pass: x

SSL/TLS = True 

Idle mining = Flase

Stealth = False

Nicehash Mining = False

Advanced Parameters = False

**Comment by UnamSanctam** [comment]
Leave the password blank

**Comment by ExeRhythm** [comment]
Hello, I have the same issue, but the password field is blank. How do I fix this? Thanks

**Comment by UnamSanctam** [comment]
Are you using the same settings? How long have you waited for?

**Comment by ExeRhythm** [comment]
Yes. I mined for about 15 minutes for testing and waited 30 minutes, so 45 minutes in total.

**Comment by UnamSanctam** [comment]
Was it using any CPU in the Task Manager (if you have "Stealth" disabled)?

**Comment by ExeRhythm** [comment]
I use Process Hacker, and from what I see it is using 40% of cpu

**Comment by UnamSanctam** [comment]
Then it's working, it can't use any CPU if it doesn't receive any work from the pool. Either the wallet address is wrong or 15 minutes wasn't enough for your CPU to generate many shares.

**Comment by ExeRhythm** [comment]
Alright, thanks. I am going to try to run it longer. Also, could it be related to the fact that I am using a virtual machine?

**Comment by UnamSanctam** [comment]
Yes definitely could be, it depends on your VM settings,

**Comment by ExeRhythm** [comment]
I didn't change anything, just booted up Windows 10 VM and ran executable. Also, still nothing - no account found.

**Comment by UnamSanctam** [comment]
Did you enter the wallet address correctly? If you did and it's using CPU, just keep mining and it should show up.

**Comment by ExeRhythm** [comment]
Ok, thank you for helping me! I'll message again if it won't work.

**Comment by ExeRhythm** [comment]
No, still does not work. I let it run for 15-30 more minutes more, but the account is still being not created. Maybe it is something related to the pool? Maybe I did not create an account there?

**Comment by UnamSanctam** [comment]
What pool are you using?

**Comment by ExeRhythm** [comment]
Nanopool

**Comment by UnamSanctam** [comment]
And you use the pool address xmr-eu1.nanopool.org:14433 with SSL/TLS enabled?

**Comment by ExeRhythm** [comment]
Yes, I am

**Comment by UnamSanctam** [comment]
What CPU do you have?

**Comment by ExeRhythm** [comment]
Intel one, but I am using a VM

**Comment by UnamSanctam** [comment]
And how much CPU and RAM have you allocated to the VM?

**Comment by ExeRhythm** [comment]
4 cores and 6000 MB of RAM, here are my settings:
<img width="537" alt="Screenshot 2021-02-27 at 17 40 31" src="https://user-images.githubusercontent.com/52459150/109391240-2cf6f680-7927-11eb-9df6-005db1d275cb.png">
<img width="540" alt="Screenshot 2021-02-27 at 17 40 54" src="https://user-images.githubusercontent.com/52459150/109391241-2e282380-7927-11eb-8e82-f0b14f3db57f.png">
<img width="537" alt="Screenshot 2021-02-27 at 17 41 06" src="https://user-images.githubusercontent.com/52459150/109391242-2ec0ba00-7927-11eb-94a1-a58aa9687572.png">
<img width="539" alt="Screenshot 2021-02-27 at 17 41 12" src="https://user-images.githubusercontent.com/52459150/109391244-2f595080-7927-11eb-8356-081ef8a330bf.png">
<img width="538" alt="Screenshot 2021-02-27 at 17 41 40" src="https://user-images.githubusercontent.com/52459150/109391251-2ff1e700-7927-11eb-8b55-89b1159052e3.png">
<img width="424" alt="Screenshot 2021-02-27 at 18 10 25" src="https://user-images.githubusercontent.com/52459150/109391257-2ff1e700-7927-11eb-90d7-75e75779a927.png">

**Comment by UnamSanctam** [comment]
Hmm, well the settings look correct and that CPU should maybe be enough. You are only mining with 1 core though (since 20% of 4 cores is 1 core), but that should be enough to complete at least some jobs unless you have something like a 2 GHz processor.

**Comment by ExeRhythm** [comment]
I have a 4Ghz processor, so that should be enough?

**Comment by ExeRhythm** [comment]
Wow, it works now. Just needed to let it run for a while. Guess I was just really unlucky. Thanks for helping me :)

**Comment by UnamSanctam** [comment]
Ahh great, glad it worked out, I guess since mining is technically also luck based it can take longer when mining at slower speeds.
