### ISSUE TITLE
can we make new worker per victim on nanopool ? +1 question

### ISSUE THREAD

**Issue by corsair550** [UnamSanctam/SilentXMRMiner#55]
and how we can adjust an e mail for nano pool because minimum payout 1 is too high

**Comment by corsair550** [comment]
also i cant pass 5k  H/s any ideas? great app btw you should add a donate percentage adjust feature btw

**Comment by UnamSanctam** [comment]
You can make new workers if you create new miners for every user, you used to be able to input {%COMPUTERNAME%} or {%RANDOM%} as worker name in the builder so would only need one mining build but I accidentally misplaced the code in the latest version.

If you mine with the wallet address as YOUR_XMR_ADDRESS.YOUR_WORKER/YOUR_EMAIL, for example 8BbApiMBHsPVKkLEP4rVbST6CnSb3LW2gXygngCi5MGiBuwAFh6bFEzT3UTufiCehFK7fNvAjs5Tv6BKYa6w8hwaSjnsg2N.TestWorker/passmail@test.com and get at least 10 shares with it you can use the email (passmail@test.com) to change it. You only really need to mine those 10 shares with one miner and then you can turn it off.

If you want higher hashrates you need more miners or better equipment, not much else to do. Currently if someone wants to donate they can do it directly instead.

**Comment by corsair550** [comment]
should i open advanced parameters and nicehash for nanopool ? and when i injeckt miner to svchost.exe its always blank in task manager but i cant terminate it as it's supposed to be
