### ISSUE TITLE
Random worker name problem

### ISSUE THREAD

**Issue by boff64** [UnamSanctam/SilentXMRMiner#56]
Hi, I have an issue, miner submits same job because of same worker name on proxy.

**Comment by UnamSanctam** [comment]
No, worker names have nothing to do with the actual mining they are just there to measure performance per worker. You could have 100 miners on the same worker name and everything would work fine. it would just display the performance with all miners combined.

**Comment by corsair550** [comment]
my miner also cant pass through 10k and i tried to open miner in my pc with worker1 name it didnt even change after 10 minutes and i change worker name to worker2 and after 10 minutes my hashrate increase to 14k but im not sure all of that maybe it was about victims or nanopool system

**Comment by UnamSanctam** [comment]
Using a worker name is not required on nanopool though.

**Comment by corsair550** [comment]
> 
> 
> Using a worker name is not required on nanopool though.

yeah but you need to use worker name if you want to change user settings also can you help me should i open advanced parameters and nicehash for highest hashrate on nanopool ?

**Comment by UnamSanctam** [comment]
No changing the advanced parameters should almost never be required. Nicehash is only for when you mine on Nicehash or use xmrig-proxy, doesn't really have to do with hashrate. 

Using a worker and email only really have to be done once, you only have to mine 10 shares on a worker to change the settings. I usually never use a worker name on the other miners and then just start a single miner on my own computer and wait about 10-15 minutes, I can then use the email I put in that to change the settings and then turn off the miner.

**Comment by corsair550** [comment]
okay i get that thank you, one last thing is there any fix for this issue when i injekt to svchost.exe process name going blank
![mlware PNG 431953c19f44dbd99fc9f80712932398](https://user-images.githubusercontent.com/66438050/108281577-db838600-7134-11eb-9ef6-aa929aee3241.PNG)

**Comment by UnamSanctam** [comment]
It seems to do that on some Windows versions, you could try to add some Assembly information in the builder and it might take that.

**Comment by corsair550** [comment]
i tried that but it didnt help anyway i ll use conhost thank you for your help

**Comment by bigdans3000** [comment]
> Using a worker name is not required on nanopool though.

Please Sir, I need this to work for me. I have tried different pools but there's nothing showing up. Please help me
