### ISSUE TITLE
Can i disable program in my or someones PC ?

### ISSUE THREAD

**Issue by adamix123** [UnamSanctam/SilentXMRMiner#58]
title says all

**Comment by UnamSanctam** [comment]
Disable which program, the miner?

**Comment by adamix123** [comment]
> 
> 
> Disable which program, the miner?

yes miner

**Comment by UnamSanctam** [comment]
Depending on the settings, if you want to turn off an already running instance of the miner that didn't have "Install" enabled you can open Task Manager and Restart the explorer.exe process (if that is what you injected into).

**Comment by adamix123** [comment]
I just want to test it but i am afraid of it :D if i run it and cant disable it after...

**Comment by UnamSanctam** [comment]
If you don't enable "Install" and choose to inject it (on first tab) into something like nslookup.exe that's easy to find you can just turn off that process in the Task Manager and it will be gone.
