### ISSUE TITLE
No output file! 

### ISSUE THREAD

**Issue by boff64** [UnamSanctam/SilentXMRMiner#6]
When I click on build, there is no file. 
Program shows this:
Starting...
Adding injection explorer.exe (%WINDIR%)
Creating a DLL...
Embedded Resource...
Done!...
BUT NO OUTPUT FILE!

**Comment by UnamSanctam** [comment]
Have you checked whether your antivirus removed it?

**Comment by UnamSanctam** [comment]
Closing due to lack of response.
