### ISSUE TITLE
Is there any way to mine another cryptocurrency with this builder?

### ISSUE THREAD

**Issue by corsair550** [UnamSanctam/SilentXMRMiner#61]
i have 50 workers more or less but i still have 25k hashrate max and its still too low, i think its because of monero so is there any way to use this builder with any other cryptocurrency or do you think to add a feature like that if its possible

**Comment by UnamSanctam** [comment]
You won't really find any better cryptocurrency at mining CPU and 25k Hashrate for 50 workers (depending on your Max CPU) is already good for silent mining.

All other big cryptocurrencies are only good with GPU and requires the worker to have the required drivers and a good GPU of course. In the future I might make a silent miner for Ethereum GPU mining but first I have to finish all the modifications for the current loader and I'm not sure actually how profitable it would be.

**Comment by corsair550** [comment]
maybe combined miner in the future like worker can mine monero with cpu etherum with gpu will be much more profitable instead mining monero with gpu

**Comment by UnamSanctam** [comment]
Maybe but that would also increase the detection rate and probably be quite hard for users to understand since you would have to enter multiple pools and people are already having trouble with just one. Might consider it though and make GPU mining into it's own tab with pools and all there. Name is currently also silent XMR miner so not sure how that branding would work but I will think about any possible implementations.

**Comment by LAD1** [comment]
theoretically could this be used for eth?

**Comment by UnamSanctam** [comment]
> theoretically could this be used for eth?

> All other big cryptocurrencies are only good with GPU and requires the worker to have the required drivers and a good GPU of course. In the future I might make a silent miner for Ethereum GPU mining but first I have to finish all the modifications for the current loader and I'm not sure actually how profitable it would be.

**Comment by LAD1** [comment]
Ahh no worries, well ill be looking out for the eth miner if you release it

**Comment by Anox208** [comment]
> i have 50 workers more or less but i still have 25k hashrate max and its still too low, i think its because of monero so is there any way to use this builder with any other cryptocurrency or do you think to add a feature like that if its possible

add me on discord sir i think i need to talk to u personally. my discord: SNova#2408

**Comment by corsair550** [comment]
> 
> 
> > i have 50 workers more or less but i still have 25k hashrate max and its still too low, i think its because of monero so is there any way to use this builder with any other cryptocurrency or do you think to add a feature like that if its possible
> 
> add me on discord sir i think i need to talk to u personally. my discord: SNova#2408

i cannot it says Snova doesnt accept friend requests you can add me here The TheroX#2938

**Comment by Anox208** [comment]
> > > i have 50 workers more or less but i still have 25k hashrate max and its still too low, i think its because of monero so is there any way to use this builder with any other cryptocurrency or do you think to add a feature like that if its possible
> > 
> > 
> > add me on discord sir i think i need to talk to u personally. my discord: SNova#2408
> 
> i cannot it says Snova doesnt accept friend requests you can add me here The TheroX#2938

DONE

**Comment by danielkp1234** [comment]
Yeah it would also like to see a Silent Ethereum miner since there is very low actual profit or a loss when mining XMR after the RandomX change

**Comment by UnamSanctam** [comment]
Planning on releasing an Ethereum miner based on the new version released when I get the Ethminer modifications done.
