### ISSUE TITLE
Can't compile in Visual Studio

### ISSUE THREAD

**Issue by roast247** [UnamSanctam/SilentXMRMiner#64]
when trying to load up form1.vb it doesn't show it and says a bunch of things don't exist. I believe this is because you didn't upload ALL project files to github, please do so!

**Comment by shainodev** [comment]
no, its not cause he hasnt uploaded all project files. you need to build it in release, then reopen form1.vb.

**Comment by roast247** [comment]
thanks bro

**Comment by shainodev** [comment]
always. also close this if u dont need any help anymore

**Comment by bigdans3000** [comment]
> thanks bro

Can you build an .exe file for me? I will give you the source codes. HMU at telegram @Dart_Vadar
