### ISSUE TITLE
Have u heard of unmineable.com?? Can this not work the same way??

### ISSUE THREAD

**Issue by Anox208** [UnamSanctam/SilentXMRMiner#65]

**Comment by UnamSanctam** [comment]
Well, you can mine to unminable with this miner...

**Comment by Anox208** [comment]
> Well, you can mine to unminable with this miner...

How do I do that? I couldn't really find any pool address or port for unmineable.

**Comment by Anox208** [comment]
ok i found it

**Comment by Anox208** [comment]
rx.unmineable.com:3333
Alternative Port: 13333
this is it?

**Comment by Anox208** [comment]
but what kind of address should i put in? should it be my xmr address or the address i want to withdraw in ( ex. doge/btt)

**Comment by Anox208** [comment]
Also I had another question how do i decrypt the miner and what is the best way to spread? I need ur advice I am not a coder or programmer.

**Comment by Anox208** [comment]
> Well, you can mine to unminable with this miner...

help me out with all of this. Also i use web.xmrpool.eu coz it has 0.1 xmr as minimum withdraw limit
