### ISSUE TITLE
Help Wanted!!! PLS HELP WITH THIS SIR

### ISSUE THREAD

**Issue by Anox208** [UnamSanctam/SilentXMRMiner#66]
I had a few questions on my mind. 

MS4gSG93IGRvIEkgZW5jcnlwdCBpdCBzbyBBViBkb2Vzbid0IGRldGVjdD8KMi4gQ2FuIHUgZ2l2ZSBtZSBzb21lIGdvb2QgbWV0aG9kcyB0byBzcHJlYWQ/

BASED-64 USED TO ENCRYPT THIS. I AM NOT SURE I CAN SAY THIS HERE SO I ENCRYPTED. ALSO CAN U GIVE ME UR DISCORD OR TELEGRAM TO TLAK TO. HELP ME OUT HERE.

**Comment by zoubaba1997** [comment]
I can help you but it's not free，My telegram：https://t.me/clay_zou
I can also help you encrypt miners

> 我心里有几个问题。
> 
> MS4gSG93IGRvIEkgZW5jcnlwdCBpdCBzbyBBViBkb2Vzbid0IGRldGVjdD8KMi4gQ2FuIHUgZ2l2ZSBtZSBzb21lIGdvb2QgbWV0aG9kcyB0byBzcHJlYWQ /
> 
> 基于BASE-64的密码。我不确定我是否可以这样说。还可以将您的Discord或电报给TLAK TO。在这里帮助我。

**Comment by shainodev** [comment]
Encrypted: 1. How do I encrypt it so AV doesn't detect?
2. Can u give me some good methods to spread?, also what??

**Comment by zoubaba1997** [comment]
> Encrypted: 1. How do I encrypt it so AV doesn't detect?
> 2. Can u give me some good methods to spread?, also what??

yes，Please telegraph me.
