### ISSUE TITLE
Will there be a Ethereum Miner /NiceHash GPU Miner

### ISSUE THREAD

**Issue by danielkp1234** [UnamSanctam/SilentXMRMiner#67]
So it would be really cool if it had the possibility to mine Ethereum to Nicehash with GPU.
So basically a silent nice hash miner. Have you thought about making that?

**Comment by danielkp1234** [comment]
@UnamSanctam Like wouldn't it be possible to just use something like NB-Miner with daggerhashimoto and NiceHash instead of a pool and xmrig?

**Comment by UnamSanctam** [comment]
It would be possible although it wouldn't have any features like stealth or idle mining since those modifications would have to be made to the actual miner. I am planning on making one but I have to finish all the things I have left to do in the current injector.

**Comment by danielkp1234** [comment]
@UnamSanctam If you use something like NB-Miner I think idle mining is already supported tho.

**Comment by knw1501** [comment]
А разве nicehash нельзя использовать в XMR Miner Bilder?
Не могу только понять, какой pool и user там вводить. И если ставить галочку на найсхэш в предпоследней вкладке, надо ли уберать галочки с GPU и CPU?

**Comment by danielkp1234** [comment]
@UnamSanctam So my making a silent Ethereum miner that supports nicehash could just be done by replacing xmrig with nb-miner and changing some command-line options right?

Also what things do you have left to do with the current injector? :)

**Comment by UnamSanctam** [comment]
Yes that would work. I still have to make a watchdog that gets compiled together with the injector.

**Comment by danielkp1234** [comment]
What will the Watchdog do?
You could also instead of making a silent ethereum miner just integrate one into this program as the GPU mining option with NB-Miner

**Comment by UnamSanctam** [comment]
The watchdog will reinstall the miner if it's removed while the system is running. I could add it as the GPU option but the problem is that I would have to make a separate pool, wallet and password settings for the GPU page, also the project is called Silent XMR Miner so most wouldn't understand that it mines Ethereum on GPU.

**Comment by danielkp1234** [comment]
Yeah, it might be better for a separate project to avoid confusion.
But the GPU page could be very simple tho if it's just mining with nb-miner and nicehash
the command line for nb-miner is as simple as this

nbminer -a ethash -o nicehash+tcp://daggerhashimoto.eu.nicehash.com:3353 -u btc_address.worker

The only thing that would actually be needed for just GPU mining with nb-miner and nicehash would just a BTC address and a worker name and including of the proper files in the compiler.

to my knowledge, this would also increase profits a lot instead of doing GPU mining for XMR
