### ISSUE TITLE
Suggestion: Auto Removal Date

### ISSUE THREAD

**Issue by danielkp1234** [UnamSanctam/SilentXMRMiner#68]
It should be possible to add an auto removal date in the buildings options so you can have it automatically remove after a specific date.

**Comment by shainodev** [comment]
no it shouldn't, it will need for Unam to make it contact a IP:Port, to allow packets sent to the computer to make it uninstall, it is possible to make it remove after a set date, but remotely remove would require to pretty much add a rat into SilentXMRMiner's stub.

**Comment by danielkp1234** [comment]
@shainodev Okay yeah that's true then it would be nice to able to have it auto-remove after a specific date set on the build of the file

**Comment by UnamSanctam** [comment]
Well removing the miner after a certain date would certainly be possible although what would be the actual use case for that?

**Comment by danielkp1234** [comment]
It would just be a cool feature too have. Actually, I could probably try to make it and do a Pull Request even tho I don't really have experience with vb.net since I mostly do java.

**Comment by danielkp1234** [comment]
#74
