### ISSUE TITLE
What is install?

### ISSUE THREAD

**Issue by Rafo124** [UnamSanctam/SilentXMRMiner#7]
What does the functions in the install tab do? Like app data, temp, user profile? I chose App data, and when I binded it with another program I chose user profile in that program. does the file still work?

**Comment by UnamSanctam** [comment]
The Install function places the program in appdata/temp/user and adds the program to the run on startup registry. If you bind it to another program don't enable the run on startup function in the binder program if it exists. 

So only use either the Install function in my program or the run on startup in another program, never use both.
