### ISSUE TITLE
HOW TO DELETE PLZ

### ISSUE THREAD

**Issue by protataetuk** [UnamSanctam/SilentXMRMiner#70]

**Comment by UnamSanctam** [comment]
Read earlier issue: https://github.com/UnamSanctam/SilentXMRMiner/issues/62

**Comment by protataetuk** [comment]
Im sorry i just panicked.Do you know how to delete it?

**Comment by protataetuk** [comment]
THank you

**Comment by protataetuk** [comment]
Sorry!I saw the regedit,but what must be the key name?Thanks!

**Comment by UnamSanctam** [comment]
The entry name will be whatever you chose as a file name in the "Install" tab.

**Comment by protataetuk** [comment]
Thanks!But before i tried this solution i restarted the explorer and the miner stopped!And now i cant see the key.Is it deleted?

**Comment by UnamSanctam** [comment]
Yes, if you can't find the key in regedit it is removed.

**Comment by protataetuk** [comment]
Thank you for everything!

**Comment by Anox208** [comment]
just use malwarebyte to remove lol

**Comment by rebelsparx** [comment]
or hitman pro and kills any thing on ur pc lap etc
