### ISSUE TITLE
Xmrig fork support

### ISSUE THREAD

**Issue by ghost** [UnamSanctam/SilentXMRMiner#71]
Moneroocean has their own fork of Xmrig that is more efficient since it mines other cryptos as well if they are more profitable. Could you please port their xmrig fork over, or release source code of the changes you made to your xmrig version to allow IDLE CPU and stealth etc.

**Comment by UnamSanctam** [comment]
Doesn't that only work on the MoneroOcean pool though?

**Comment by YouUnderscoreded** [comment]
Yes but it is more profitable. The MoneroOcean pool is also very user-friendly. The owner is available on discord and so is his server.
