### ISSUE TITLE
Is there the latest encryption method? 

### ISSUE THREAD

**Issue by zoubaba1997** [UnamSanctam/SilentXMRMiner#73]
Is there the latest encryption method? The previous one has expired. The Windows Security Center found it this morning.

**Comment by zoubaba1997** [comment]
Use this SilentXMRMiner.crproj, is it necessary to add other .exe files in addition to adding miners?

**Comment by UnamSanctam** [comment]
If you are using ConfuserEx try using this project file https://anonfiles.com/54Jcmap1q6/SilentXMRMiner3_crproj.

**Comment by zoubaba1997** [comment]
I use this SilentXMRMiner3.crproj, and a miner was found in the windows security center this morning

**Comment by UnamSanctam** [comment]
Then either you did it wrong or it has indeed "expired" and some other obfuscator/settings has to be used. I will also soon release the new version which would probably update the code signatures.

**Comment by UnamSanctam** [comment]
Also what did it detect it as? "wacatac.D5!ml" or something similar?

**Comment by zoubaba1997** [comment]
Detected: Trojan:Script/Wacatac.c!ml and win32/CoinMiner.AC!bit

**Comment by zoubaba1997** [comment]
Is it possible to use powershell to add windefender exclusions, such as .exe and .zip .rar to add to the miner, first run powershell and then run the miner

**Comment by zoubaba1997** [comment]
I have been using this method before, but the .bat file I used to call .ps is too troublesome, if not, you can add this process directly to the miner

**Comment by UnamSanctam** [comment]
Yes there are multiple ways but all of them require administrator permission to do. Normally the miner won't have administrator permissions so this can't really be done by the miner.

**Comment by zoubaba1997** [comment]
Has SilentXMRMiner4.crproj been developed?
