### ISSUE TITLE
It's not working anymore

### ISSUE THREAD

**Issue by MrZ-UI** [UnamSanctam/SilentXMRMiner#78]
2 days ago the miner (the executable file) was working just as it should and now i am pressing on it, nothing happens also **the** **antivirus is off** and the miner still not working.

**Comment by UnamSanctam** [comment]
By not working do you mean that it's not using any CPU?

**Comment by MrZ-UI** [comment]
Yes it's not using any cpu
 i checked everything, even i reinstalled windows system and tried on my all PCs

**Comment by UnamSanctam** [comment]
What settings did you use when creating the miner?

**Comment by MrZ-UI** [comment]
Inject to : explorer.exe (%WINDIR%)
Install enabled : Temp
Hide File: on
**Mining:**



- CPU mining: on >>>  Max CPU: 30%

- Idle mining : on>>> Idle CPU 50%

- Idle wait: on >>> 10 Minutes

- GPU mining: off

- SSL-TLS : off

- Nicehash mining : off

- **Stealth: off**

- Advanced Parameters: Disabled

**Comment by UnamSanctam** [comment]
Try creating it with "Hide File" off, also make sure that the pool address is correct. If it still doesn't work try to ping the pool to see if it connects. Also check that you're not banned from the pool or anything.

**Comment by MrZ-UI** [comment]
Ok

**Comment by MrZ-UI** [comment]
Well the miner is back to work , it's working now thanx man, I just changed the Pool and the port
