### ISSUE TITLE
Custom path edit issue

### ISSUE THREAD

**Issue by fsx891** [UnamSanctam/SilentXMRMiner#8]
if you could tell me how to add a custom installation path that would be nice

**Comment by UnamSanctam** [comment]
Currently only the paths under the Install path are available, if you wish to use a custom one you can edit the source and recompile it otherwise you'll have to make do with the ones currently available.

**Comment by fsx891** [comment]
this is exactly what im trying to do but when I add/change path it wont work anymore thats my issue or im editing something wrong or else hm

**Comment by fsx891** [comment]
the issue is on visual studio seems that I cant find every reference for path ;c

**Comment by UnamSanctam** [comment]
If you go into Form1.vb you can edit the PayloadPath on line 91 (Edit "Path.Combine(Micro...).
