### ISSUE TITLE
No Results On Mining Pools

### ISSUE THREAD

**Issue by bigdans3000** [UnamSanctam/SilentXMRMiner#82]
Hey Guys, please which pool is best for this miner. I have tried a lot of pool but nothing works. Please any help will be appreciated. Thanks

**Comment by LAD1** [comment]
perhaps minexmr.com its what i've used, it does take some time to stats to show

**Comment by UnamSanctam** [comment]
Any pool will work but make sure that you use a pool that won't ban you unless you use xmrig-proxy. I usually recommend nanopool since from what I know they don't ban.

For nanopool you can find the addresses here: https://help.nanopool.org/article/59-pool-information
For example:
Pool address: xmr-eu1.nanopool.org:14433
Wallet address: You Monero wallet address
And enable SSL/TLS in the "Mining" tab.

**Comment by bigdans3000** [comment]
> Any pool will work but make sure that you use a pool that won't ban you unless you use xmrig-proxy. I usually recommend nanopool since from what I know they don't ban.
> 
> For nanopool you can find the addresses here: https://help.nanopool.org/article/59-pool-information
> For example:
> Pool address: xmr-eu1.nanopool.org:14433
> Wallet address: You Monero wallet address
> And enable SSL/TLS in the "Mining" tab.

Please give me your telegram or Wickr, I have tried everything  correctly but to no avail

**Comment by UnamSanctam** [comment]
Well I don't have any of those but try disabling "Stealth" and then check in Task Manager to see if it's using any CPU. If it is then it is correctly mining to the pool.

**Comment by bigdans3000** [comment]
> Well I don't have any of those but try disabling "Stealth" and then check in Task Manager to see if it's using any CPU. If it is then it is correctly mining to the pool.
Still not working Sir, please can you send a demo video to computerapps@yahoo.com . Thanks

**Comment by bigdans3000** [comment]
Still not working Sir, please can you send a short demo video to computerapps@yahoo.com

**Comment by UnamSanctam** [comment]
Just take a screenshot of your settings and attach them here or write them down. There isn't really much that can go wrong.

**Comment by bigdans3000** [comment]
https://anonymousfiles.io/kneAQAZU/

I disabled the settings for assembly, icon and mining, please check out the pictures and tell me what am doing wrong. Thanks

**Comment by UnamSanctam** [comment]
You use the SSL port 14433 so you should enable SSL/TLS in the settings.
