### ISSUE TITLE
How do I add worker names?

### ISSUE THREAD

**Issue by oneinam1llion** [UnamSanctam/SilentXMRMiner#83]
I am using nanopool but it is a little vague on how to exactly add worker names, where does it go?
does it go with the email? but how do I separate it? Or does it go in the wallet bar, I do not want to mess anything up but I would like to see my worker statistics on nanopool. How exactly do I configure worker names properly w/ nanopool?

**Comment by UnamSanctam** [comment]
You enter it into the Wallet address section of my builder. As you said you should enter it like so YOUR_XMR_ADDRESS.YOUR_WORKER/YOUR_EMAIL.
For example: 8BbApiMBHsPVKkLEP4rVbST6CnSb3LW2gXygngCi5MGiBuwAFh6bFEzT3UTufiCehFK7fNvAjs5Tv6BKYa6w8hwaSjnsg2N.WorkerName/password@fakemail.com

The email doesn't have to be real since it is only used as a password to change the minimum payout of XMR. I'm pretty sure you can also skip adding the email (don't add the / and everything after it) and just add .WorkerName after the wallet address.

**Comment by oneinam1llion** [comment]
Thank you for your insightful reply, on nanopool when I enter the email it always says incorrect password.

**Comment by UnamSanctam** [comment]
No problem, if you mine with the email in the wallet address and mine at least 10 shares (with no other workers mining with a different email) then it will work.

**Comment by oneinam1llion** [comment]
Oh, thank you for the clear up.  I suggest adding a nifty little arrow on your next update containing all the examples you showed me and anymore insightful information about your program in a dropdown or a new window. I couldn't find that information anywhere but I had a hunch when it said to configure nicehash you would use the example.example layout. It just wasn't directly stated, a nice little window would help keep you from answering stuff like this in the future. Thank you, great piece of software.

**Comment by UnamSanctam** [comment]
Since there already exists small '?' that display what the options do I might add a more extensive wiki here on GitHub later.

**Comment by ZakyanGrish** [comment]
How can you make it unique for each miner?  For example, assign the current user's IP address, or incrementing numbers from 1 to up, or literally, any other way just to detect how many active workers you got? Thanks.

**Comment by UnamSanctam** [comment]
I will quote and earlier issue I responded to
>I have also added an undocumented feature (not fully tested) that you can enter as a worker name and it will replace it at runtime, you can enter {%COMPUTERNAME%} to get the computers name as a worker address or use {%RANDOM%} to get a random string every time the miner starts up. You could try this if you really want to see how many computers are mining.

But keep in mind that pool won't like if you have too many different workers (I believe).
