### ISSUE TITLE
How exactly does GPU mining work?

### ISSUE THREAD

**Issue by oneinam1llion** [UnamSanctam/SilentXMRMiner#84]
Nanopool states it is not worth it due to RandomX, how exactly does it work? Does it follow the idle times and max CPU? Or is it 100% GPU all the time.

**Comment by oneinam1llion** [comment]
And does it even benefit you if you're mining with nanopool

**Comment by UnamSanctam** [comment]
Mining with GPU isn't very profitable with the "new" RandomX, doesn't really matter which pool you use. GPU Mining doesn't really have a percentage it uses since that isn't really how the GPU works but it should use around 1-5% GPU load and about 50-100% GPU VRAM entirely depending on the GPU.
