### ISSUE TITLE
CPU Usage is high

### ISSUE THREAD

**Issue by iml1929** [UnamSanctam/SilentXMRMiner#85]
Hello sir and thank you for this project.... even though i have the CPU usage at 10% when the miner starts when i open task manager it shows around 20% then it jumps to around 60%.. any ideas?

**Comment by UnamSanctam** [comment]
How many cores do you have? If you set it to 10% and have 8 cores it will use 1 core which is 12,5% but if you have 2 cores then 10% would be 1 core thus using 50%.

**Comment by iml1929** [comment]
I have 4 cores

**Comment by UnamSanctam** [comment]
Hmm then it should use 25%, try checking the usage with Process Explorer or Process Hacker instead, the Task Manager is really inaccurate.

**Comment by iml1929** [comment]
it doesnt add up

**Comment by iml1929** [comment]
Yeah

**Comment by iml1929** [comment]
One last thing, What is --donate-level=5 ?

**Comment by UnamSanctam** [comment]
It's the XMRig devs mining fee, it can be lowered to 1 but I have set it to 5 to support his work. Donate level 5 means that it will mine to the XMRig dev 5 minutes every 100 minutes.
