### ISSUE TITLE
Miner files starting and injecting but doing nothing.

### ISSUE THREAD

**Issue by oneinam1llion** [UnamSanctam/SilentXMRMiner#87]
Title says it all, my files are creating new "explorer.exe" & nslookup procs but cpu usage is not being used and I do not have stealth checked.

**Comment by UnamSanctam** [comment]
What settings are you using? Specifically the pool, wallet and password settings.

**Comment by oneinam1llion** [comment]
xmr-us-east1.nanopool.org:14433
2TVijsngCaMYB3yYizBsLS1Mx5f6YGd1ZsDykQRCcRGGj1fm9rW2BFGLU3xNim694eer7zPbcepfDqQh7MBpjwK1q42R19.Test
no password
![image](https://user-images.githubusercontent.com/80195847/110303503-4f37e680-7faf-11eb-8cc5-f2f778ac1ad0.png)
![image](https://user-images.githubusercontent.com/80195847/110303578-64ad1080-7faf-11eb-94ab-d771c88adec8.png)
![image](https://user-images.githubusercontent.com/80195847/110303603-6aa2f180-7faf-11eb-8b4d-da8bc305c387.png)

**Comment by UnamSanctam** [comment]
And if you start it then it uses no CPU? All those settings work from me, could you try and open CMD and run "ping xmr-us-east1.nanopool.org"?
