### ISSUE TITLE
Malicious text in the hosts file after launch

### ISSUE THREAD

**Issue by X3NOOO** [UnamSanctam/SilentXMRMiner#88]
can you tell me why this shit is disabling vt and other scanners after launch?
![Zrzut ekranu 2021-03-08 085753](https://user-images.githubusercontent.com/48159366/110293013-55998300-7fee-11eb-9c7a-490e2a195a98.png)

**Comment by UnamSanctam** [comment]
Nyan cat added that a long time ago and you can find it in https://github.com/UnamSanctam/SilentXMRMiner/blob/master/SilentXMRMiner/Form1.vb and I haven't removed it since people are still dumb enough to try to scan with them.

**Comment by thebigjoe** [comment]
> Nyan cat added that a long time ago and you can find it in https://github.com/UnamSanctam/SilentXMRMiner/blob/master/SilentXMRMiner/Form1.vb and I haven't removed it since people are still dumb enough to try to scan with them.

Please dont remove as it will get detected by most av within hours
