### ISSUE TITLE
Cpu 50 percent, but no results showing in pool

### ISSUE THREAD

**Issue by thebigjoe** [UnamSanctam/SilentXMRMiner#89]
Hello, I have opened the miner, it has succefully injected into explorer, its at 50% but no results showin after 10 minutes? Explorer injected data:
C:\Windows\explorer.exe  -B --coin=monero --asm=auto --cpu-memory-pool=-1 --randomx-mode=auto --randomx-no-rdmsr  --cuda-bfactor-hint=12 --cuda-bsleep-hint=100 --url=xmr-eu1.nanopool.org:14433 --user=Myadress --pass= --cpu-max-threads-hint=40 --donate-level=5  --unam-idle-wait=5 --unam-idle-cpu=100  --tls  --unam-stealth 

Any idea?

**Comment by UnamSanctam** [comment]
Well it can take longer than 10 minutes for it to refresh on nanopool but it also depends on what CPU you mine on, if you use something like a VM with like 1 core and no cache it could take a long time since it won't be able to complete any work.

**Comment by thebigjoe** [comment]
Its been like 20 minutes since i left it and with most miners it takes like 3 minutes in that particular pool, i injected another process so ill see if it works

**Comment by UnamSanctam** [comment]
It doesn't usually take 3 minutes on nanopool, if I mine at about 5 kH/s on my computer and it usually takes around 10-30 minutes for it to show up. But the most important factor is what CPU you have.

**Comment by thebigjoe** [comment]
I created the miner at 16:18 and left it up until now and still nothing im going to let it for another 20 minutes
The cpu i have is an i5-2400

**Comment by thebigjoe** [comment]
Do i probably need to put a name in it or else it wont work?
