### ISSUE TITLE
Please Read This Comment Mr.Unamsanctam

### ISSUE THREAD

**Issue by timurka7484** [UnamSanctam/SilentXMRMiner#9]
Hi.

I want to talk to you something special.

Is it acceptable?

Is it OK? Then give a platform where I can talk to you.

Thank u..

**Comment by UnamSanctam** [comment]
You can PM me on Hackforums where I have the same name.

**Comment by timurka7484** [comment]
Hack Forums
--
We are sorry but we require 25 quality posts to send a PM. Any LQP (Low Quality Post) spamming will result in a closed account. If you upgrade to L33t membership this requirement is removed.

**Comment by UnamSanctam** [comment]
Try to use the Conversation feature to the left of Private Messages, I don't think that requires 25 posts.

**Comment by timurka7484** [comment]
I did what you said but I could not find you here ..

**Comment by UnamSanctam** [comment]
Whats your HF username? Alternatively link it here.

**Comment by timurka7484** [comment]
MohammadHasanov
