### ISSUE TITLE
Injecting, but not using CPU.

### ISSUE THREAD

**Issue by oneinam1llion** [UnamSanctam/SilentXMRMiner#91]
I keep on having this issue, and having to remake my stubs.
I use a batch file to execute the stub file I know that has nothing to do with why it is not working as when executed manually I encounter the same issue. I test my stubs personally before releasing them. Everytime I have had an issue, even tried running only one. I configure everything correctly but it merely is not using any CPU. A proc is made, such as a new explorer.exe but nothing is happening. Do you have a Discord, can we get in contact please? 
I also make 3 stubs and all 3 are opened, so far only ONE stub has shown up on nanopool. One person out of the 300 views on the video. I should have a heapload more clients than I do. I would really like some one on one help. Am I lacking the required files to compile the stub correctly?? I make a stealth stub that will never get found by the user, another stub called "NS" Non stealth, always running @ 20% cpu and so far that is the only one ironically to show up on nanopool. I also make an entirely separate GPU stub.

**Comment by UnamSanctam** [comment]
Well the two basic reasons for the miner to be injected but not using any CPU is either that you have "Stealth" enabled so that it pauses when you have Task Manager open or it can't connect to the pool either by wrong settings or the connection being blocked.
