### ISSUE TITLE
Which pool to connect to i have tried antpool and btc pool

### ISSUE THREAD

**Issue by zuespc** [UnamSanctam/SilentXMRMiner#92]
i have used antpool and btc pool but non is working pls can you pls direct me, i guess i am not doing it right. you you direct me on the pool to use

**Comment by UnamSanctam** [comment]
This is a Monero (XMR) miner so you should use a Monero pool. I normally use nanopool and you can connect with these addresses: https://help.nanopool.org/article/59-pool-information

For example: xmr-eu1.nanopool.org:14433 and then enable SSL/TLS in the "Mining" tab.

**Comment by zuespc** [comment]
thank you for your quick responds i have built as instructed and tested how do i know it is working now?

**Comment by UnamSanctam** [comment]
If it's using any CPU in the Task Manager it should be working. If you enabled "Stealth" then use something else than Task Manager like Process Explorer or Process Hacker since then it will hide from the Task Manager.

**Comment by zuespc** [comment]
i dont really understand your last mail, go through the img and see the settings if they are all good 
https://prnt.sc/10j1dhs
https://prnt.sc/10j1o04
https://prnt.sc/10j1p48
https://prnt.sc/10j1roo

**Comment by UnamSanctam** [comment]
That looks like a BTC address and not a Monero address, are you sure that's the right one?

**Comment by zuespc** [comment]
it is a btc address how do i get the monero address

**Comment by UnamSanctam** [comment]
Get a Monero wallet. You can find some on this page https://www.getmonero.org/downloads/

**Comment by zuespc** [comment]
https://prnt.sc/10ja2bv

check out the img, i guess i have doe it right, one more thing how can this funds be convert to btc so it can be used.

**Comment by UnamSanctam** [comment]
That looks correct, you can use any exchange like Binance or something to exchange between most cryptocurrencies.

**Comment by zuespc** [comment]
Good day bro 
i tested the build miner on a 6gig rdp, i did not see any interest on my monero wallet.

**Comment by UnamSanctam** [comment]
Is it using any CPU on the RPD?

**Comment by zuespc** [comment]
how do i check that pls

**Comment by UnamSanctam** [comment]
Use Task Manager, but if you have "Stealth" enabled use Process Explorer or Process Hacker. If you haven't changed the "Inject into" then explorer.exe should be using the CPU.
