### ISSUE TITLE
DLL

### ISSUE THREAD

**Issue by RealKolasi** [UnamSanctam/SilentXMRMiner#93]
any chance you will release a DLL version of this builder to be implemented into RATs like Lime RAT had?

**Comment by UnamSanctam** [comment]
Uhh well Lime RAT just had a normal cpu.exe and injector or something if I remember correctly. But you can just execute the final build onto RATs anyway, no real need for a DLL.

**Comment by RealKolasi** [comment]
> Uhh well Lime RAT just had a normal cpu.exe and injector or something if I remember correctly. But you can just execute the final build onto RATs anyway, no real need for a DLL.

fair, take care
