### ISSUE TITLE
Miner drops to 0% on VPN connection.

### ISSUE THREAD

**Issue by oneinam1llion** [UnamSanctam/SilentXMRMiner#95]
The miner seems to completely halt mining when connected on a VPN, my best guess is because It's already sending encrypted ssl data or something like that through the tunnel.

I've also got 100+ downloads, verified the miner is working myself but I have no users. Either this is a connection issue, or it has something to do with --donatelevel?
I'm genuinely confused here, I should have over 10,000H/S but have none. I have devised a method where once the stub is launched it pings my server. I know they're being launched. I get computer specifications sent as a .txt file, these are able computers and connections.
I've even added exclusions with batch commands etc to ensure it stays.

**Comment by UnamSanctam** [comment]
The pool could be blocking the VPN IP or the other way around. --donate-level will only mine to the dev 5 minutes after 95 minutes  has been mined normally so that shouldn't matter. If you have "Install" enabled then try disabling "Hide File", some users have reported issues with permissions but that shouldn't stop all of them from working.

I am planning on releasing a new update today so you could try using that one.

**Comment by oneinam1llion** [comment]
Will you be releasing the new pre compiled version? I do not have a problem compiling with the .sln. Unlike 50% of the users whom use this software I am at least somewhat technically adept. 
And what is new in the new .sln file?

**Comment by UnamSanctam** [comment]
I have already released one, you can find it here: https://github.com/UnamSanctam/SilentXMRMiner/releases

**Comment by oneinam1llion** [comment]
What exactly has changed in this version?
Is the MD5 different? Are AV detections lowered, because it seems as of your new release windows defender rolled out a new definition update and the miner is now almost fully detected. Even the injected string of code is being detected in "svchost" and cmd by windows security center (windows 7 defender). Even a simple UPX compression would lower AV detection by a little bit. 
I do praise you for adding these two tidbits, as beforehand I was using a batch script to assure the computer never slept & even made my own watchdog proc that watched the miner and made sure it was active every 5 minutes.

**Comment by oneinam1llion** [comment]
Not to mention the pesky startup window when launched, I am not sure how you took care of that but I run windows silently with .vbs scripts.

One genuine question I do have is, is this a keylogger in one shape or form? - How else would it detect key input & mouse movement to enable idle mode.

**Comment by UnamSanctam** [comment]
You can see all the non-xmrig changes here: https://github.com/UnamSanctam/SilentXMRMiner/commit/301dac23a75be53522d92e40d3b277e4a2c68bf6, the antiviruses only detect the code signatures in the miner so using a .NET Obfuscator should make it as undetected as it probably could be.

To remove the command windows I changed the subsystem from console to windows and added an entry point. I don't use a keylogged to detect the idle time but simply use the Windows API LASTINPUTINFO function.
