### ISSUE TITLE
[suggestion]

### ISSUE THREAD

**Issue by oneinam1llion** [UnamSanctam/SilentXMRMiner#96]
I have seen a lot of Nyancat products with .exe downloaders that download and execute an executable from a remote server, having this option in the build section of the miner would greatly help updating stubs remotely, as when the computer starts it would check and download the new stub.exe from www.website.com/stub.exe and execute it. This way users can change their xmr address to mine to if they wish to mine for a friend etc. & this would also benefit a lot of users in minor ways but be an overall useful tool. This way I could compile builds without ever having to recompile new builds with the new version of the software. 
Adding onto this, you could also add a ping function that pings a remote server with a specified dump file or just a standalone ping so you know when a new users executes your program. I have been taking care of this via batch scripting but having it all built in saves time and potential accidental detection.

**Comment by oneinam1llion** [comment]
Futhermore, the ability to save a .cfg file would be lovely so I don't have to fill it out every launch. Would come in handy because I keep the file on a flash drive so I can easily build a stub wherever I am and deploy it.

**Comment by Toxenskiy** [comment]
hmm, I suggested something similar, but you suggested it in a more simplified form.

**Comment by Khizhniak** [comment]
> 
> 
> hmm, I suggested something similar, but you suggested it in a more simplified form.

I think you should already close issue. ;/
