### ISSUE TITLE
1.0 Watchdog failure 

### ISSUE THREAD

**Issue by bengalm** [UnamSanctam/SilentXMRMiner#98]
The Watchdog function of the program I generated does not take effect
If the second path is the same as the program name, it won’t run

**Comment by UnamSanctam** [comment]
What?

**Comment by oneinam1llion** [comment]
He is saying if the watchdog name is the same as the program name it wont run.

**Comment by UnamSanctam** [comment]
Oh, the watchdog is separate and in another folder so the name of the program nor the name of the watchdog can affect it at all.

**Comment by bengalm** [comment]
Sorry, I mean Watchdog is not running. I stopped xmrig and didn’t restart it.
I will try your update first, thank you for your open source

**Comment by UnamSanctam** [comment]
Yeah, it should restart XMRig after 15 seconds. You can check if the process sihost64.exe is running.

**Comment by bengalm** [comment]
ty xD
