### ISSUE TITLE
Miner is working but clients 90% never appear

### ISSUE THREAD

**Issue by oneinam1llion** [UnamSanctam/SilentXMRMiner#99]
30 downloads and one computer, it obviously works but I am unsure what is hindering it? I’ve even disabled firewall using batch when it’s run but I’m not sure if it’s helping. Is it being detected and deleted before users can use it? I’m just completely at awe here because it clearly functions as it is suppose to, but half the time? I’ve got one named alpha I released for like 3 minutes and it is still coming back but it’s a single person and that specific link got 6 downloads, 1 out of 6, not accurate odds but. Cause for wonder ? Is it antivirus? Firewall? Or maybe just bad computers that can’t hash fast enough to keep up with blocks being found?

**Comment by UnamSanctam** [comment]
Well could be any of those to be honest, how are you checking how many are actually mining?

**Comment by oneinam1llion** [comment]
Nanopool tells me when they’re mining, I can do an educated guess that 600-1.3kh/s is one computer, then continue to add onto that the more it displays under the grouped sub sector. Media fire tells me how many people download the installer, the installer pings my server when it executes it under elevated permissions. I know the program won’t start unless all of the embedded files are present either. So I’m genuinely confused.

**Comment by UnamSanctam** [comment]
One computer usually mines at about 100-300 H/s per core highly depending on the CPU it has. So 6 miners would mine anywhere between 600-1800 H/s (with only one core) or higher depending on the CPU. 

I have also added an undocumented feature (not fully tested) that you can enter as a worker name and it will replace it at runtime, you can enter {%COMPUTERNAME%} to get the computers name as a worker address or use {%RANDOM%} to get a random string every time the miner starts up. You could try this if you really want to see how many computers are mining.

**Comment by oneinam1llion** [comment]
I’ll give it a shot next time I’m free, this consumes a lot of my time as I have to make sure they’re working before I release them. I want this to go big because profits are highly possible.
